### ISSUE TITLE
SingleConsumerQueue::size can return over-flowed int size

### ISSUE THREAD

**Issue by nitsanw** [ben-manes/caffeine#10]
This is unlikely, but there's nothing to stop the unbounded queue to grow beyond MAX_INT length and so:

    @Override
    public int size() {
      Node<E> h = head;
      Node<E> cursor = h.getNextRelaxed();
      int size = 0;
      while (cursor != null) { // should be while (cursor != null && size < MAX_INT)
        cursor = cursor.getNextRelaxed();
        size++;
      }
      return size;
    }

**Comment by ben-manes** [comment]
All JDK queues, and in general throughout the collections framework, do not handle sizes larger than `Integer.MAX_VALUE`. Two examples are `LinkedList` and `LinkedBlockingQueue`. And of course array-based versions will crash due to the length limit of an array. Because this has not been an issue in practice, it is generally acceptable to not follow the contract strictly and leave it unhandled until deemed necessary.

The only JDK collection that I'm aware of that does handle the size threshold is `ConcurrentHashMap`.

I think this is unlikely enough to not be covered.

**Comment by ben-manes** [comment]
Actually I might as well fix this, so I'll add it with #9's changes.
