### ISSUE TITLE
jakarta.inject support

### ISSUE THREAD

**Issue by kdombeck** [ben-manes/caffeine#1009]
The `javax` to `Jakarta` headache never ends. :)

I see that this project is using `javax.inject.Inject` in [TypesafeConfigurator](https://github.com/ben-manes/caffeine/blob/0f582e94ad8aafb0c98a5d351d9a0e944d249347/jcache/src/main/java/com/github/benmanes/caffeine/jcache/configuration/TypesafeConfigurator.java#L42). 

This is causing issues when I upgraded to [Guice 7.0](https://github.com/google/guice/wiki/Guice700) as my `FactoryCreator` is not being injected into TypesafeConfigurator.

I see that you are aware of the headaches this is causing by your comments in https://github.com/google/guice/issues/1383 so I am wondering on what your thoughts are on being able to support `jakarta.inject.Inject`?

**Comment by ben-manes** [comment]
yeah, I was wondering about what to do here.

An easy fix is to write an adapter rather than directly wire up `requestStaticInjection(TypesafeConfigurator.class)`. Guice doesn't use classpath scanning so the old inject would be ignored. Or is something else amiss?

An issue that is not easy to work around is if you use `org.jsr107.ri:cache-annotations-ri-guice`? Since jcache is abandonware this uses the javax annotations and won't migrate. Thus the annotation support is broken. The only way to resolve that is bytecode rewriting, e.g. using [gradle-jakartaee-migration-plugin](https://github.com/nebula-plugins/gradle-jakartaee-migration-plugin).

I'd be fine updating to use the newer annotation, but I don't know if that would resolve your woes.

**Comment by kdombeck** [comment]
You are spot on for both points!!!

1. We currently are using `requestStaticInjection(TypesafeConfigurator.class)` and that is how I was able to find that `FactoryCreator` was not being "injected".
2. We were using `org.jsr107.ri:cache-annotations-ri-guice` prior to us migrating to jakarta, but I then realized it was abandoned like you mentioned and was able to remove it without issue.

I copied the source of `TypesafeConfigurator` and replaced the package name of `javax.inject.Inject` with `jakarta.inject.Inject` and everything worked. So I "think" that is the only change needed right now.

Or I can do like you mentioned and manually set the FactoryCreator on TypesafeConfigurator.

**Comment by ben-manes** [comment]
Released in 3.1.7

**Comment by froque** [comment]
This should not have been a patch version

**Comment by ben-manes** [comment]
This change should only require that Guice users upgrade to 6.0, which has support for both namespaces. That is a backwards compatible release and usages of the RI annotations will work until Guice 7.0 which drops support for javax.
