### ISSUE TITLE
Custom copy strategy

### ISSUE THREAD

**Issue by GuillermoBlasco** [ben-manes/caffeine#101]
Hello folks,

I moved a project from Ehcache to Caffeine and testing I've found some concurrent access exception on some lists. Then I realised that these lists where cached. So what happened is that the list is cached by reference and when the value is retrieved the same list is returned instead of a copy of such list.

Put and get by reference is great if all your values are immutable, but at least for us that's not the case. For example we retrieve a cached list and then we sort it in place.

I think it would be good to provide an access to configure the policy of how to process the returned value in case of hit. Similarly to http://www.ehcache.org/documentation/2.8/configuration/configuration.html#copyonread-and-copyonwrite-cache-configuration

**Comment by ben-manes** [comment]
Since most caches are used in 1-3 places within a component, which guards access and masks the implementation details, this seems pretty easy to do in the calling code. This isn't too commonly needed, won't be a great simplification to be performed implicitly within the cache, and is fairly obvious logic. I'm hesitant to add it explicitly to the `Caffeine` builder because the power-to-weight ratio doesn't seem to be in its favor.

Do you think your code would be greatly simplified by having this implicitly done, vs at the call sites? Being explicit has the benefit of only paying the cost when you need it, e.g. internal cache calls may not care while handing out the cached value might have an explicit copy. I believe Ehcache 2.x copied by Java serialization, making it a pretty expensive.

An alternative is to use the JSR-107 adapter which includes a pluggable `Copier`. The specification has a `store-by-value` requirement, primarily for serialization for distributed caches. If you're using Spring Cache then its changing the configuration from its native Caffeine support to its JCache support.

**Comment by GuillermoBlasco** [comment]
Since we are using the application cache just to cache read only entities the issue is just limited to caching collections of those entities that is the modifiable stuff. Our problem is solved, because it was limited to 10 lines more or less. Easy to solve. So it is not a need, just a "I think it would be good".
But, sincerely, I feel more confortable reading a copy of the value rather than getting the reference to the original object. And yes, deep copy by serialisation is costly, but it depends on the objects you know you are caching if they require deep copy or not (for example, not in my case).
If I found further problems I'll move to JCache backed by Caffeine, yes, that was the idea.
Thanks for the support Ben ;)

**Comment by ben-manes** [comment]
Unless there is additional feedback, I am planning on closing this issue. I don't think this would introduced into the API. But happy to leave open if there is opposition favoring a reconsideration.

**Comment by jmiguelsamper** [comment]
Hello,

I'm trying to achieve what the original reported described, particularly getting **a new instance** of the stored object on every retrieval. However, I'm getting always the same stored instance.

I've added a debug message with a dummy Copier and it seems that the Copier object is not invoked **on every read**.

This is my test configuration:

        CaffeineConfiguration<String, Object> config = new CaffeineConfiguration<>();
        config.setStoreByValue(true);
        Factory<Copier> copierFactory = (Factory) new FactoryBuilder.SingletonFactory<>(new Copier() {
            @Override
            public <T> T copy(T t, ClassLoader classLoader) {
                LOG.debug("Copier invoked for {}", t.getClass().getName());
                return t;
            }
        });
        config.setCopierFactory(copierFactory);

Of course, this copier does not copy anything, its purpose is just debugging.

Could you confirm if the Copier should be invoked on every read or if I understood that wrong?

Thanks in advance and thanks for this great project.

**Comment by ben-manes** [comment]
If you are using the JCache module then it should be on every read. I think the original ask was for a similar feature in Caffeine's core, which isn't planned.

The read value should be passed through the `Copier` before being returned. Can you set a breakpoint in `CacheProxy` at, 

https://github.com/ben-manes/caffeine/blob/f107fbc8b93883ec5513916c6c7fb5a819e6b498/jcache/src/main/java/com/github/benmanes/caffeine/jcache/CacheProxy.java#L179

If you provide a full test case then I can help debug.

**Comment by jmiguelsamper** [comment]
Hello Ben,

Thank you very much for your response, that has pointed me on the right direction.

You're completely correct, Caffeine is "copying on read" as expected. My problem seems to be related to the Spring configuration (Spring 5 + JCache) because the objects are not copied when Caffeine is used through Spring. But it works perfectly when Caffeine caches are invoked directly.

I'll post the solution when/if I got it.

**Comment by jmiguelsamper** [comment]
I don't know the underlying cause but it seems that Spring cache synchronization (https://docs.spring.io/spring/docs/current/spring-framework-reference/integration.html#cache-annotations-cacheable-synchronized) prevents cache elements to be copied on read.

Disabling synchronization makes it work as expected.

So, when I remove the *sync=true* on

    @Cacheable(cacheNames="foos", sync=true)

values are copied on read.

**Comment by ben-manes** [comment]
That probably uses the invoke() api and perhaps there is a missing copy call in the caffeine jcache adapter.

**Comment by jmiguelsamper** [comment]
I tried to follow the source code to provide a better explanation but I got lost (Spring is all about proxies and decorators), sorry about that and thank you very much again for your help.

**Comment by ben-manes** [comment]
I think it’s a missing copy on my side. See invoke’s return,

https://github.com/ben-manes/caffeine/blob/f107fbc8b93883ec5513916c6c7fb5a819e6b498/jcache/src/main/java/com/github/benmanes/caffeine/jcache/CacheProxy.java#L794

**Comment by jmiguelsamper** [comment]
Ok, thank you very much for the additional information.

Removing sync works for us but if that missing copy is added in future versions we will be able to enable it again.

**Comment by ben-manes** [comment]
It looks like the reason is because the return of `Cache#invoke` is user-defined, rather than the entry's value. So it isn't clear if a copy should be expected, since it might be a user-defined return of some computation rather than the entry's current value. I think its probably okay to add the copy here, but also a bit confusing.

```
/**
  * Invokes an {@link EntryProcessor} against the {@link Entry} specified by
  * the provided key. 
  *
  * @param <T>            the type of the return value
  * @param key            the key to the entry
  * @param entryProcessor the {@link EntryProcessor} to invoke
  * @param arguments      additional arguments to pass to the
  *                       {@link EntryProcessor}
  * @return the result of the processing, if any, defined by the
  *         {@link EntryProcessor} implementation
  */
```

The entry processor mutates the given entry directly, so it is an in/out parameter.

```java
public interface EntryProcessor<K, V, T> {

  /**
   * Process an entry.
   *
   * @param entry     the entry
   * @param arguments a number of arguments to the process.
   * @return the user-defined result of the processing, if any.
   * @throws EntryProcessorException if there is a failure in entry processing.
   */
  T process(MutableEntry<K, V> entry, Object... arguments)
      throws EntryProcessorException;
}
```

Would you expect the `the user-defined result of the processing, if any.` to be copied? Or perhaps the copy needs to be the given to the `EntryProcessor` and that is the mistake. I'd have to dig in a little deeper into how Spring uses it.

**Comment by luckywzy** [comment]
Now, I have the same problem. I need a deep copy from cache，because It will be modify, subsequently. 
I don't know which one is high performance and elegant

**Comment by ben-manes** [comment]
@luckywzy Note that the `Copier` is only applicable for JCache, since it is a requirement of the JSR. If you are not using it, e.g. instead using Spring Cache or Caffeine's native apis, then there is no built-in copying.

There are many object serializers, e.g. [Jackson](https://github.com/FasterXML/jackson) and [Kryo](https://github.com/EsotericSoftware/kryo/). It is too complicated of a subject to advise on. An alternative is to use immutable values and a builder which can be auto-generated (e.g. [Immutables](https://immutables.github.io/), [AutoValue](https://github.com/google/auto/blob/master/value/userguide/index.md)). Then you can populate a builder from an existing value, mutate it, etc. This is what I do, as it is fast and useful for other record-style use-cases.

**Comment by yarosman** [comment]
> @luckywzy Note that the `Copier` is only applicable for JCache, since it is a requirement of the JSR. If you are not using it, e.g. instead using Spring Cache or Caffeine's native apis, then there is no built-in copying.
> 
> There are many object serializers, e.g. [Jackson](https://github.com/FasterXML/jackson) and [Kryo](https://github.com/EsotericSoftware/kryo/). It is too complicated of a subject to advise on. An alternative is to use immutable values and a builder which can be auto-generated (e.g. [Immutables](https://immutables.github.io/), [AutoValue](https://github.com/google/auto/blob/master/value/userguide/index.md)). Then you can populate a builder from an existing value, mutate it, etc. This is what I do, as it is fast and useful for other record-style use-cases.

What is the best strategy to add serialization such us kryo or others to caffeine? Or it will be better to leave objects in cache without serialization ?

**Comment by ben-manes** [comment]
@yarosman What is the best way to add serialization to `ConcurrentHashMap`?

That is to say, a cache is just a fancier hash table, so the answer is the same. That could be done during load (e.g. `Map.computeIfAbsent`) or by the consumers (e.g. after a `Map.get`). The best fit is use-case specific.

**Comment by navratan-ch** [comment]
I am also stuck on this issue, is there any caffine config present, which can return copyOnRead objects...
