### ISSUE TITLE
QUERY: How best to shut down cache safely

### ISSUE THREAD

**Issue by nheitz** [ben-manes/caffeine#104]
I've been a big advocate of Caffeine in the past couple of years, and have seen many benefits from the non-blocking approaches used.  However, recently, a colleague and I have wanted to use Caffeine to cache instances of JMSContext, and have been forced to consider alternate caching strategies due to problems around completing shutdown.  In short, it doesn't appear that I can reliably ensure that all items are presented to the removalListener (on shutdown) unless two things are true:

1) I set the executor explicitly....I assume this is because the fallback to ForkJoinPool uses daemon threads

2) The cache is bounded.  This one puzzles me slightly.

Is this the intended behaviour?  Do I need to use a nondaemon thread executor and bound the cache if I want confidence that every item in the cache will be disposed of according to my best efforts?

UPDATE:
After having stepped through the code a bit, I am concerned that my perceived success using bounded queues might be more luck than success...Bounded executors go through more stages of removal (eden, probation, protected) than unbounded, so perhaps there is slight more time for threads to complete.  I have also attached my small test case.
[testcase.txt](https://github.com/ben-manes/caffeine/files/404501/testcase.txt)

**Comment by ben-manes** [comment]
Caffeine's cache is effectively a `ConcurrentMap` with fancy features so, as long as you are mindful of the concurrency scenarios, it should be easy to build your own shutdown logic on top.

The removal listener will be executed asynchronously on any removal. I'd expect that on shutdown you reject subsequent additions, clear the cache, and wait for the listener to process all of the removals. I don't think either (1) or (2) are constraints. I'd expect your shutdown request to block (with a timeout) waiting for all of its internal services to have halted for a clean shutdown (e.g. see Guava's `ServiceManager`).

It would definitely be easiest if using the executor's `shutdown` and `awaitTermination` methods. That unfortunately is ignored by `ForkJoinPool#commonPool()` due to being shared JVM-wide, so in that strategy a custom executor would be required (daemon allowed). Alternatively you could coordinate it using other `java.util.concurrent` utilities, such as a `Semaphore` or `Phaser`. If you use a `CacheWriter` instead, then `delete` is synchronous to the calling thread, so that all entries removed by `invalidateAll` would have notified the writer before returning.

**Comment by ben-manes** [comment]
You wouldn't print completed shutdown until the executor has terminated. I won't get a chance to play with your code until after work, but will take a look this evening to provide an example.

**Comment by ben-manes** [comment]
See this [small update](https://github.com/ben-manes/caffeine/files/404820/testcase.txt) to your test case which prints the following and exits.

```
Removed 9 and cleaned up.
Removed 1 and cleaned up.
Removed 0 and cleaned up.
Removed 3 and cleaned up.
Removed 2 and cleaned up.
Removed 6 and cleaned up.
Removed 7 and cleaned up.
Removed 5 and cleaned up.
Removed 4 and cleaned up.
Removed 8 and cleaned up.
Clean shutdown
```

**Comment by ben-manes** [comment]
Here's another slight [variation](https://github.com/ben-manes/caffeine/files/405353/testcase.txt) that removes the need for a dedicated executor. It tracks the number of submitted and completed tasks, and allows for waiting until there are no more in-flight. The decorating `ExecutorService` could be flushed out more if needing to implement the full contract, but its purpose here is just to remove the need for extra threads.

**Comment by nheitz** [comment]
Thanks, Ben, for your insightful and complete answer.  If I am reading successfully, then, the onus for managing complete termination is effectively left external to the cache itself, specifically to the semantics of the executor service.  This is fine, and I understand this pathway well enough.

I suppose it was unfortunate that Guava by comparison seems to offer a blocking "shutdown", though I imagine that is a performance negative in other scenarios.  Would you ever consider wrapping the executor shutdown and and await with timeout into the Caffeine API?

**Comment by ben-manes** [comment]
I think you are taking advantage of Guava's implementation details rather than an intended API. Guava performs all work on calling threads, populating a notification queue that callers can simultaneously drain. Guava's behavior can be emulated with a same-thread executor, though we don't have a notification queue since the executor tends to take care of that. The design difference stems from `commonPool` now being available and a no-brainer to take advantage of it.

The executor is a convenient way to achieve your results, but not the only approach. You could use a `CacheWriter` to perform the close() synchronously with removal. Perhaps the simplest scheme is to iterate (via `cache.asMap()`) the entries to explicitly close() them when shutting down.

The cache doesn't have a lifecycle concept and I don't think introducing one is necessarily beneficial for you use-case. It is a data structure that is malleable by the application, rather than a framework to bridge life-cycles with.

**Comment by nheitz** [comment]
Ok.  :+1:  .  Perhaps I have been conflating the notion of "cache" with a "service that provides data backed by a cache". Thanks again.

**Comment by pugupta-linkedin** [comment]
@ben-manes does this approach (forwarding executor) work when we put TTLs for evictions?

What we notice is that during application shutdow - we stop reads/writes to the cache, but TTL maintainence can kick off removal task at any time. I think we will need a dedicated executor for such cases

**Comment by ben-manes** [comment]
The TTL would only cause the removal listener to be notified if (a) activity on the cache triggers maintenance, (b) a scheduler is configured. So perhaps you need to similarly shutdown the scheduler? Or you could change the shutdown executor to be a caller-runs policy instead of throwing the exception to avoid the log warning. Since you are shutting down, I would think clearing the cache at that point would negate TTL issues. I use Guava's [ServiceManager](https://github.com/google/guava/wiki/ServiceExplained) for application lifecycle management, if that helps.

**Comment by pugupta-linkedin** [comment]
Interesting. I thought ttl cleanup can happen outside of (a) and (b). If there are no cache reads/writes - ttl would still be enforced by something like a sleep/wait or infinite polling. 
We don't have a scheduler - so it seems we are still doing read/writes on the cache

**Comment by ben-manes** [comment]
yeah, the cache does not create any of its own threads. The scheduler is a provided thread that would be scheduled based on the next TTL event. Otherwise we rely on some activity to trigger a maintenance cycle, e.g. a write or an accumulation of reads. If the cache is idle and the entry expires it is left there, hidden as a miss if queried for and cleaned up in response to that activity.

**Comment by pugupta-linkedin** [comment]
Thanks for the details. Followup question on the same: 
Is Cache#cleanup a blocking call? https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/2.0.3/com/github/benmanes/caffeine/cache/Cache.html#cleanUp--

(We stop reads/writes before calling Cache#cleanup - but notice removal listener still gets called somehow)

**Comment by ben-manes** [comment]
Yes, an explicit cleanUp is blocking as the caller performs the maintenance work. For example to evict expired entries, which are then submitted to the executor for the removal notification. However, the caller wouldn't want for those listener notifications to complete and only the maintenance work.

**Comment by pugupta-linkedin** [comment]
Ahh, I think in our case we will have to somehow block on those listener notifications to complete 
Thanks!

**Comment by ben-manes** [comment]
If the listener is fast then it may have no harmful effects if you use an eviction listener, which is called under the entry's lock so it penalizes the operation but is then serial / predictable.

**Comment by pugupta-linkedin** [comment]
Thanks for the details. We have been trying to debug a synchronization issue on our end.

The listener writes to a database.
Database is closed after cache#cleanup as part of shutdown.
Leaky listener notifications after the db is closed are causing crashes during shutdown.

**Comment by pugupta-linkedin** [comment]
Actually thinking more about this.

We don't need to invoke Cache#cleanup, and can instead just do Cache#invalidateAll.
Does invalidateAll trigger listener notifications? (assuming there are no reads/writes and no scheduler)

**Comment by ben-manes** [comment]
It would with `RemovalCause.EXPLICIT`. It sounds like you might just want a lifecycle flag to simply no-op the listener once shutdown has started?

**Comment by ben-manes** [comment]
To clarify, it would notify the removal listener but not the eviction listener.

**Comment by pugupta-linkedin** [comment]
> It would with `RemovalCause.EXPLICIT`. It sounds like you might just want a lifecycle flag to simply no-op the listener once shutdown has started?

👍 yup plan is to "switch off" the listener

**Comment by manrajgrover** [comment]
Hi @ben-manes, thanks for this great library. I'm trying to resolve the same issue as above i.e. gracefully shutting down cache. This means writing cache data to an external store before closing the connection to the store.

Here's a solution I came up with but have doubts that it is able to handle the TTL triggering the eviction listener.
I also wish to prevent processing the key twice (once during expiration and another during eviction).

```java
var cacheMapCopy = new ConcurrentHashMap<>(cache.asMap());
cache.invalidateAll();
cache.cleanUp();

cacheMapCopy.forEach((key, value) -> {
   evictionHandler.onRemoval(key, value, RemovalCause.EXPLICIT);
});
```

Challenges:
1. I'm unable to use `removalListener` and have to resort to `evictionListener` as it is synchronous. But since `evictionListener` does not get triggered for explicit removal i.e., when `invalidateAll` is called, I have to flush the data myself. Had `removalListener` been a synchronous call, things would have been simple.
2. With the above code, post-creation of map copy, a TTL can get called before invalidateAll. This means the data can get processed more than once. 

I'm looking for a clean way to achieve the same. Also, adding a grace period before shutdown doesn't seem clean.

**Comment by manrajgrover** [comment]
@ben-manes, thanks for the quick reply.

Not sure if my understanding is correct. Please correct me if I'm wrong. In the case of removal listener, if we set `Caffeine.executor(Runnable::run)` and it runs on the calling thread, it will run the logic on the application thread both in case of TTL as well as `invalidateAll` (I'm assuming application thread as I read somewhere that caffeine does not create its own thread). If true, the process will be blocking in nature and inefficient.

```java
for (var entry : cache.asMap().entrySet()) {
  if (cache.asMap().remove(entry.getKey(), entry.getValue()) {
    evictionHandler.onRemoval(entry.getKey(), entry.getValue(), RemovalCause.EXPLICIT);
  }
}
```

This feels atomic, as `evictionHandler` will be called only if we can remove it.

Given its asynchronous nature, I sense `removalListener` is more efficient than `evictionListener`. In such a case, will the above snippet work atomically?
