### ISSUE TITLE
Weigher accepts Int which is unecessary

### ISSUE THREAD

**Issue by fzakaria** [ben-manes/caffeine#1044]
You wouldn't believe it but we try to put in cache entries that are larger than 4GiB.

We are using caffeine through JRuby and therefore the calculation of the _size_ for the Weigher is calculated at runtime.
It tries to convert the size which is larger than an Int to an Int and then fails during the bounded byte Weigher.

Can we bump it to Long for more future facing support?

**Comment by ben-manes** [comment]
In this case you can normalize to a different base unit as the weigher doesn't care if its bytes or otherwise. For example using Guava: `Math.toIntExact(IntMath.divide(weight, 4, RoundingMode.UP))`. Does that work for you?

**Comment by fzakaria** [comment]
As a workaround sure -- I can scale everything by 1024  or higher but seems like a weird limitation to impose int anyways.

Thank you for the suggestion.

**Comment by ben-manes** [comment]
The field is stored on the entry, so using a `long` doubles the per-entry memory cost. It is rare to have humongous objects on the heap, which tends to not be GC friendly. The usages that store it off-heap or persisting are often databases which allocate rows to blocks, so they break up into chunks anyway. That leaves the need for a `long` per-entry weight pretty rare. 

We code generate the entries so a `LongWeigher` is possible though doubles the number of entry classes. There is also a problem that the total weight could overflow, so now either that has to be accounted for or a `BigInteger` is required which is not ideal. So far scaling is just a simple, easy, and less error prone answer.

Glad it's working well for you otherwise! 🙂
