### ISSUE TITLE
Question: what is the actual difference between `.asMap().compute()` and `get()`?

### ISSUE THREAD

**Issue by SHxKM** [ben-manes/caffeine#1069]
Thanks for an awesome library.

I'm wondering what is the practical different between the following `cache.get()` and `cache.asMap().compute()`? It seems like both would compute a result based on a function, save it in the cache, and return it to the caller?

**Comment by ben-manes** [comment]
`Cache.get(key, mappingFunction)` delegates to the Map’s `computeIfAbsent`. It has an identical contract. I’m sure that’s what you meant, as of course that’s different from `compute` which can update or remove an existing entry.

**Comment by SHxKM** [comment]
Thanks @ben-manes, let me understand if I got you correctly:

`Cache.get(key, mappingFunction)` will "at most" either put a new entry into the map, or, or if the computed value returned is `null`, not insert it. It doesn't really have an "update" mechanism, since if the value is already in the map, the `mappingFunction` isn't run at all.

`compute` however, gets a reference to the current value in the map, therefore it decides how it wants to proceed with the internals of the map (for example, if for a certain key we have > `n` entries, ship them somewhere else, and then return `null`, effectively clearing an existing key.

**Comment by ben-manes** [comment]
You're correct. The remapping function can modify the entry, but it cannot make a call directly into the map. In your example the usage is correct, if you do not operate on `existingList` outside of the computation because `LinkedList` itself is not thread-safe. If you only read/write within the compute then it is safely synchronized. If outside like an iterator, it might see observe a partial object and crash or return wrong data non-deterministically. In this particular example, a `CopyOnWriteArrayList` or a `ConcurrentLinkedQueue` could be safe to use the list outside of the computation.

The warning is meant for mutations to the map, such as if the `compute` performed a `put` operation. These nested or recursive writes can cause corruption, such as in `HashMap` the addition might resize the underlying table and cause the entry to be lost as corrupted ([JDK-8071667](https://bugs.openjdk.org/browse/JDK-8071667)). The locking protocol in `ConcurrentHashMap` could lead to live locks (Java 8), so when possible these cases are detected and fail fast.

**Comment by SHxKM** [comment]
@ben-manes Thank you so much for your eloquent answers (here and at SO) and wonderful library.
