### ISSUE TITLE
Entries are not cleaned when using weakValues

### ISSUE THREAD

**Issue by tepitebson** [ben-manes/caffeine#111]
We faced a memory leak after upgrading caffeine from 2.2.7 to 2.3.1. It seems that cache entries are not evicted when using weak values. Following test is working on 2.2.7 but eats all memory with 2.3.1:

    @Test
    public void testWeakValuesEviction() throws InterruptedException {

        Cache<Long, Object> cache = Caffeine.newBuilder().executor(e -> e.run()).weakValues().recordStats().build();
        ScheduledThreadPoolExecutor exec = new ScheduledThreadPoolExecutor(1);
        AtomicLong versionCounter = new AtomicLong(1L);
        exec.scheduleAtFixedRate(() -> {
            int idCounter = 1;
            while (idCounter++ < 200_000) {
                cache.put(versionCounter.getAndIncrement(), new Object());
            }

        } , 0L, 500L, TimeUnit.MILLISECONDS);
        for (;;) {
            Thread.sleep(10000);
            CacheStats stats = cache.stats();
            System.out.println(stats.toString());
            // cache.cleanUp();
            System.gc();

        }
    }

Eviction count stays at zero on 2.3.1 while growing fast on 2.2.7. If cache is cleaned up explicitly from outside, entries are evicted.

**Comment by ben-manes** [comment]
Sorry, I accidentally debugged the counts with the Guava provider which of course worked. The Caffeine provider passed because the assertion's count isn't restrictive enough, despite the cache not having evicted any entries. As you said, if I manually `cleanUp` then it discards.

**Comment by ben-manes** [comment]
I found the problem in `BoundedLocalCache#afterWrite()`.

This was incorrectly modified to not call `scheduleAfterWrite()` if `buffersWrites()` is false. The surrounding logic was changed to use a bounded write-buffer when investigating what turned out to be the JVM bug [Missed submissions in ForkJoinPool](https://bugs.openjdk.java.net/browse/JDK-8078490). The `afterWrite()` method had to then handle back-pressure due to a full queue, which typically only happens in synthetic tests. Accidentally the `scheduleAfterWrite()` was moved into the if-block, whereas in 2.2.7 it is called [regardless](https://github.com/ben-manes/caffeine/blob/d690f5cd85f15cd0f00af4a1397f1489854a5f37/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L847).

The maintenance work should still occur after a number of reads exceeds a threshold. I'd like to shore up the `ReferenceTest` assertions prior to releasing this fix.

**Comment by tepitebson** [comment]
Hi. Good to see that the problem has been located, we will revert to 2.3.0 meanwhile since that version does not seem to be affected by this issue. Thank you for your swift response for the issue.

**Comment by ben-manes** [comment]
Yes, it looks like I introduced it in 2.3.1 only. I'm working on improvements to the unit tests and hope to release this evening, but it is already getting late. I might do so tomorrow.

**Comment by ben-manes** [comment]
Released. Sorry about any trouble this caused and thanks for understanding.
