### ISSUE TITLE
Loading Cache loads values only on get operation

### ISSUE THREAD

**Issue by desoliture** [ben-manes/caffeine#1112]
I'm using Spring Boot v3 with Caffeine v3.1.2
I'm trying to use loading cache, so my beans for this looks like this:

`@Bean("defaultCaffeineConfig")
    public Caffeine<Object, Object> defaultCaffeineConfig(@Qualifier("cacheTasksExecutor") Executor executor) {
        return Caffeine.newBuilder()
                .executor(executor)
                .recordStats();
    }

    @Bean
    public CaffeineCacheManager cacheManager(@Qualifier("defaultCaffeineConfig") Caffeine<Object, Object> defaultCaffeineConfig,
                                             List<CaffeineCache> customCaches) {
        var manager = new CaffeineCacheManager();
        manager.setCaffeine(defaultCaffeineConfig);
        customCaches.forEach(c -> manager.registerCustomCache(c.getName(), c.getNativeCache()));
        return manager;
    }
    
    @Bean
    public CaffeineCache accountCache(AccountRepository accountRepository,
                                      @Qualifier("cacheTasksExecutor") Executor executor) {
        var cacheLoader = buildCacheLoader(accountRepository);
        Cache cache = Caffeine.newBuilder()
                .refreshAfterWrite(5, TimeUnit.MINUTES)
                .recordStats()
                .executor(executor)
                .build(cacheLoader);
        cache.putAll(loadAll(accountRepository));
        return new CaffeineCache(ACCOUNT_CACHE, cache);
    }
`

So, I've created some entities and put them into the cache via spring's `@Cacheable`
Also I've put some breakpoints inside mapping function (newBulkMappingFunction)

The thing is that after the set timeout for refreshAfterWrite nothing happens, unless I do request to retrieve cached entity and only then the breakpoint is being reached and entity loads into the cache.

Maybe I misunderstood something, but isn't cacheLoader should be invoked automatically at the background?

Thanks!

**Comment by ben-manes** [comment]
The [javadoc](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/com.github.benmanes.caffeine/com/github/benmanes/caffeine/cache/Caffeine.html) and the [wiki page](https://github.com/ben-manes/caffeine/wiki/Refresh) pages might help explain this.

This feature is intended to be used with expiration so that inactive entries will be expired, while active ones are optimistically reloaded. This way popular entries, like an api auth token used on every request, can be kept up to date whereas if it expired then all callers would periodically block waiting for it to load anew. If the entry was not used then it would fade away, making space available for new data.

A proactive refresh is best done using a scheduled task, such as `cache.refreshAll(cache.asMap().keySet())`. A full reload of all of the in-memory content is more like a read replica rather than a cache, as it is unbounded and lacks policy constraints. That might have various logic for different conditions or queries, so there is not much for this cache to offer that wouldn't be best handled by a scheduled task in your code. Anything we could offer would be trivial enough to not provide any real value, so rather than make it more confusing we simply don't offer that capability.

**Comment by desoliture** [comment]
Thanks for the response!

So, if I'm not mistaken, It will not load automatically in the background and I should use some kind of scheduled task?

**Comment by ben-manes** [comment]
Correct. It will only initiate the reload for an entry on the first request after the `refreshAfterWrite` duration.

**Comment by desoliture** [comment]
Thanks a lot for the explanation!

**Comment by ravaelamanov** [comment]
@ben-manes, hi. Just faced a use case where caches needs to be automatically refreshed and thought Caffeine 100% had this feature. `refreshAfterWrite` seemed to be a perfect solution if not this slight caveat: 

> Correct. It will only initiate the reload for an entry on the first request after the `refreshAfterWrite` duration.

For now, I settled down with a scheduler. Yet having the ability to tell Caffeine cache to reload entries immediately instead of marking them as eligible for refreshing after duration specified by `refreshAfterWrite` elapses would save many of us from creating these simple schedulers. At first glance an overloaded version of `refreshAfterWrite` with an additional flag (like `reloadImmediately`) would suffice. Is there any chance you would consider adding this feature?

> so there is not much for this cache to offer that wouldn't be best handled by a scheduled task in your code

Well, no code is better then some code 😉

**Comment by ben-manes** [comment]
It's just a really weird feature ask that feels wrong when I imagine it as a native feature. It is effectively asking for an unbounded cache, or else one would want rules to scope in just some entries but not others for a scheduled refresh. The more conditional rules makes it seem like either a rich callback is needed for evaluation. The more customizable logic you may want then the more it feels like a scheduled task is clearer code than trying to understand a framework's callbacks and lifecycle quirks.

For an implementation side, we'd also need to change it to track when to trigger that refresh operation when no user activity occurs. That would mirror eager expiration which uses a sorted order (via timer wheel) and scheduler to kick off promptly (a ~1s fuzz factor). But most / all of the cache is being regularly refreshed, do individual refreshes help? One might instead perform a bulk reload periodically instead of trying to track it per-entry.

So yeah.. I still cannot wrap my head around how a feature is better than a scheduled task. I very much understand the desire and why it comes up so often, but it also seems like an XY problem where the obvious solution is not actually what the user wants to acheive.
