### ISSUE TITLE
Question on the Support Life Cycle

### ISSUE THREAD

**Issue by KasperDeng** [ben-manes/caffeine#1126]
Just want to know any life cycle of Caffeine. As I do see there are two main versions, 2.x for JDK8 and 3.x for JDK11 plus.
Does any exact EoS (End of Support) date defined?
My concern is about 2.x version since our software currently is still based on JDK8.
I see that the release of 3.x is more frequently than 2.x. Is there any feature missing in 2.x? Will the fix of vulnerability issues back port to 2.x?

Looking forward on your answer. Thanks so much.

**Comment by ben-manes** [comment]
That's a great question. In tldr; critical issues will be addressed when discovered but other fixes will only be backported upon request.

The 2.x release will be supported minimally to fix a vulnerability or if blocking a user. Otherwise it won't be proactively updated with backports from the mainline. When user issues or questions do come up, the first response will be asking about if upgrading is viable or seeing if there is an acceptable workaround. A feature enhancement, optimization, or other purely QoL changes won't be backported (which I think if a fair penalty for being on older, EOL'd JDKs).

Since upgrade cycles can be very slow, I don't see any major version being completely unsupported. I still try to help on Guava's Cache or would respond on the even older CLHM, though users would be nudged to migrate. In the end though, consuming projects should try to keep relatively up to date across their software stack as a general rule of health.

**Comment by KasperDeng** [comment]
Thank you Ben's answer. It is very clear to me now.
