### ISSUE TITLE
OSGi Provide-Capability

### ISSUE THREAD

**Issue by lburgazzoli** [ben-manes/caffeine#113]
The caffeine-jcache bundle define the following Provide-Capability 

```
Provide-Capability = 
	osgi.serviceloader;osgi.serviceloader=com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider
```

Sholdn't it be javax.cache.spi.CachingProvider insteaad of com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider ?

**Comment by ben-manes** [comment]
You're right and I'll remove that line. I was trying to fix [OSGiTest](https://github.com/ben-manes/caffeine/blob/master/jcache/src/test/java/com/github/benmanes/caffeine/jcache/OSGiTest.java) and experimenting with different variations. It fails with the exception,
```
com.github.benmanes.caffeine.jcache.OSGiTest > sanity FAILED
    java.lang.ClassNotFoundException: com.github.benmanes.caffeine.jcache.spi.CaffeineCachingProvider not found by PAXEXAM-PROBE-9081d622-0b8c-4ce3-b9da-2e04a1f4949b [20]
        at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1574)
        at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
        at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at javax.cache.Caching$CachingProviderRegistry.loadCachingProvider(Caching.java:485)
        at javax.cache.Caching$CachingProviderRegistry.getCachingProvider(Caching.java:526)
        at javax.cache.Caching.getCachingProvider(Caching.java:238)
        at com.github.benmanes.caffeine.jcache.OSGiTest.sanity(OSGiTest.java:56)
```

The problem was due to JCache not supporting OSGi ([issues #326](https://github.com/jsr107/jsr107spec/issues/326)). This jar doesn't require or provide service loader functionality, so those manifest entries are unnecessary.

**Comment by lburgazzoli** [comment]
Woul it be instead possible to fix it and mark the  capabilities as optional ? so if you get an osgi aware api your bundle would work but capability won't be mandatory

**Comment by ben-manes** [comment]
I'm not experienced with OSGi, so a PR would be greatly appreciated =)

My understanding is that the underlying problem is that JCache doesn't properly export the required packages. The detailed failure from the test is,
```
org.osgi.framework.BundleException: Unable to resolve com.github.ben-manes.caffeine.jcache 
[17](R 17.0): missing requirement [com.github.ben-manes.caffeine.jcache [17](R 17.0)] 
osgi.wiring.package; (osgi.wiring.package=javax.cache.configuration) Unresolved requirements: 
[[com.github.ben-manes.caffeine.jcache [17](R 17.0)] osgi.wiring.package; (osgi.wiring.package=javax.cache.configuration)]
```

Where the JCache provider needs `javax.cache.configuration` which isn't available. I don't know enough OSGi to correct for that and thought it had to be done at the application-level.

**Comment by lburgazzoli** [comment]
I'll try to experiment a little bit then a PR if results are good

**Comment by anhldbk** [comment]
@lburgazzoli Any progress?

**Comment by lburgazzoli** [comment]
damn I forgot this issue, I may resume working on it in a couple of weeks.

**Comment by anhldbk** [comment]
@lburgazzoli Let's me share this burden with you then :D

**Comment by ben-manes** [comment]
JCache 1.1 is in preview and should contain this fix. They said end of the preview is the 18th so hopefully the artifact will be out shortly after. Caffeine 2.6 passes the maintenance update's TCK except for backwards incompatible tests, where I'll update to 1.1's behavior when its official.

**Comment by ben-manes** [comment]
JCache 1.1 was released and it has a proper OSGi manifest. The [unit test](https://github.com/ben-manes/caffeine/blob/master/jcache/src/test/java/com/github/benmanes/caffeine/jcache/OSGiTest.java) passes, too!

However, I have to use `test-cache-2` which does not use a `CacheLoader`. The error reported was that `TestCacheLoader` cannot be casted to `CacheLoader`, which could indicate a bundling problem. Since JCache's `ClassFactory` uses the thread's classloader to resolve, perhaps the dynamic lookup is the issue. Unfortunately my limited knowledge of OSGi prevented me from finding a fix, e.g. by using `DynamicImport-Package: *`

The build should be in the snapshot repository shortly, if you would like to verify.
