### ISSUE TITLE
[FeatureRequest] add the cache itself into RemovalListener.onRemoval as parameter

### ISSUE THREAD

**Issue by jiming** [ben-manes/caffeine#116]
Hi Ben,

In case the entry is removed by expire cause, I'd like to check the timestamp of the entry, which is quite light operation than load the whole object. If it is not modified so far, I would like to re-put the entry into cache instead of simple remove it, and load it later. What do you think about it?

Best regards,
Jiming

**Comment by ben-manes** [comment]
Hi Jiming,

You might consider this in terms of `refreshAfterWrite`. That is triggered when an entry is accessed and not yet expired, but stale enough that it should be asynchronously reloaded. The `CacheLoader#reload` accepts the old value and returns the new value. You could put your quick check and return the old value if unmodified, which would reset the write time to give it another full duration.

The benefit of that approach is it ensures that you don't resurrect inactive entries. That is of course error prone if no maximum size is set by leading to memory leaks. The size policy is pretty intelligent so it should correctly identify that the inactive entries are preferable to evict, so perhaps it doesn't matter too much.

I think needing the cache in the listener isn't the common case and is an API breaking change. The workaround of setting the cache instance on the listener after construction is simple, so I don't think an API change is necessary.

Also note that the removal listener is called after the entry was removed. This means there is a slight race condition of removal -> get -> re-put. That's probably okay, though there are workarounds using `CacheWriter`.

I think using `refreshAfterWrite` is probably the cleanest approach. What do you think?

Cheers,
Ben

**Comment by jiming** [comment]
Dear Ben,

My concern was there has time window between expire and refresh duration. I guess I should set refresh duration shorter than expire duration, but how many? What is the number? It is not easy.

BTW, I wrote unit test to verify refreshAfterWrite, it doesn't work, and I found refreshAfterWrite even affect the expire duration of expireAfterWrite, no idea why:(


```
    @Test
    public void test_reload_about_to_expired_entry() throws InterruptedException {
        AtomicInteger counter = new AtomicInteger(0);
        AtomicInteger reloadCounter = new AtomicInteger(0);
        LoadingCache<String, String> graphs = Caffeine.newBuilder()
                .maximumSize(1000)
                .expireAfterWrite(50, TimeUnit.MILLISECONDS)
                .refreshAfterWrite(30, TimeUnit.MILLISECONDS)
                .recordStats()
                .build(new CacheLoader<String, String>() {
                    @Override
                    public String load(@Nonnull String key) throws Exception {
                        return key + ":"  + counter.incrementAndGet();
                    }

                    @Override
                    public String reload(@Nonnull String key, @Nonnull String oldValue) throws Exception {
                        reloadCounter.incrementAndGet();
//                        System.out.println("old value = " + oldValue);
                        return oldValue;
                    }
                });
        Assert.assertEquals("jiming:1", graphs.get("jiming"));
        Thread.sleep(30);
        System.out.println(reloadCounter.get());
        Assert.assertEquals("jiming:1", graphs.get("jiming"));
        Assert.assertEquals(1, reloadCounter.get());

        Thread.sleep(20);
        Assert.assertEquals("jiming:1", graphs.get("jiming"));
        Assert.assertEquals(1, reloadCounter.get());


        System.out.println("1." + graphs.get("jiming"));
        Thread.sleep(20);
        System.out.println("2." + graphs.get("jiming"));
        Thread.sleep(20);
        System.out.println("3." + graphs.get("jiming"));
        Thread.sleep(20);
        System.out.println("4."+ graphs.get("jiming"));
        Thread.sleep(20);
        System.out.println("5." + graphs.get("jiming"));
        Thread.sleep(1000);
    }

```
Am I write the code not correct?

Please kindly help me check the code!

Thanks
Jiming

**Comment by jiming** [comment]
Dear Ben, 

I agree that, breaking API is not good idea. What about adding a new hook api, `checkPreExpire(new Prediccate(key, oldValue, Node theExpiredNode){})`, 

If the Predicate return true, remove the entry. Otherwise, keep it and extend its life.

Best regards
Jiming

**Comment by ben-manes** [comment]
Hi Jiming,

The refresh time should be shorter than the expiration time. Knowing a good number for either is guess work, unfortunately, because it is very domain specific. In both cases you have to judge when an entry is too stale and the system-of-record should be queried. If you have an expiration time set, then you have some hypothesis that could be extended to a refresh duration.

I appreciate your API suggestion, but it feels very special case. I think there are adequate ways to achieve your desired effect without making library changes. Your original idea could be done by providing the cache instance to the listener after construction. Or you could use a second-level victim cache set with a longer expiration time. Regardless, whether you observe performance gains is questionable and I suspect that if you measured its not problematic to expire and let the next request load it.

Your test passes for me, but by sheer luck. The problem is a race conditions by using the system clock and that refresh is performed asynchronously. You can control time using a custom ticker, e.g. Guava's `FakeTicker`, and disable asynchronous execution using a same-thread executor.

Below is your test using that style. Note the minor tweak of an off-by-one (30 -> 31) is necessary due to the comparison logic.

```java
@Test
public void test_reload_about_to_expired_entry() throws InterruptedException {
  FakeTicker ticker = new FakeTicker();
  AtomicInteger counter = new AtomicInteger(0);
  AtomicInteger reloadCounter = new AtomicInteger(0);
  LoadingCache<String, String> graphs = Caffeine.newBuilder()
      .maximumSize(1000)
      .ticker(ticker::read)
      .executor(Runnable::run)
      .expireAfterWrite(50, TimeUnit.MILLISECONDS)
      .refreshAfterWrite(30, TimeUnit.MILLISECONDS)
      .recordStats().build(new CacheLoader<String, String>() {
        @Override
        public String load(@Nonnull String key) throws Exception {
          return key + ":" + counter.incrementAndGet();
        }

        @Override
        public String reload(@Nonnull String key, @Nonnull String oldValue) throws Exception {
          reloadCounter.incrementAndGet();
          // System.out.println("old value = " + oldValue);
          return oldValue;
        }
      });
  Assert.assertEquals("jiming:1", graphs.get("jiming"));
  ticker.advance(31, TimeUnit.MILLISECONDS);
  System.out.println(reloadCounter.get());
  Assert.assertEquals("jiming:1", graphs.get("jiming"));
  Assert.assertEquals(1, reloadCounter.get());

  ticker.advance(20, TimeUnit.MILLISECONDS);
  Assert.assertEquals("jiming:1", graphs.get("jiming"));
  Assert.assertEquals(1, reloadCounter.get());


  System.out.println("1." + graphs.get("jiming"));
  ticker.advance(20, TimeUnit.MILLISECONDS);
  System.out.println("2." + graphs.get("jiming"));
  ticker.advance(20, TimeUnit.MILLISECONDS);
  System.out.println("3." + graphs.get("jiming"));
  ticker.advance(20, TimeUnit.MILLISECONDS);
  System.out.println("4." + graphs.get("jiming"));
  ticker.advance(20, TimeUnit.MILLISECONDS);
  System.out.println("5." + graphs.get("jiming"));
  ticker.advance(1000, TimeUnit.MILLISECONDS);
}
```

**Comment by jiming** [comment]
Dear Ben,

Using refresh and expire together is easy to be confused, so I prefer to not use it.

I think add the checkPreExpire hook is a clean method. You said it is a special case, and which I think it is a very useful feature.

Most data put in cache are not modified often, that's why we can put it into cache. I believe most data  are not modified when they are evicted from cache. When this happened, we need re-query the WHOLE data from database and serialize it into object again. However, with the checkPreExpire hook, we can simply check id/updated_time, which is indexed, ten of hundreds times faster than reload the whole object. Which is very valuable to a heavy system. And which is why we use cache.

What do you say?

Best regards,
Jiming

**Comment by jiming** [comment]
Dear Ben,

This feature also can easy developers' pain on setting duration of expiration. 

From performance side, we want it the longer the better. Therefore, from functionality side, we want it shorter. With this feature's help, we can simply set the expired time shorter. 

Thanks
Jiming

**Comment by ben-manes** [comment]
Hi Jiming,

I agree that in isolation your idea is very reasonable. But I think there are a few details you haven't considered yet.

__Concurrency__
A read like `getIfPresent` and iterators should be non-blocking. If they observe an expired entry then it is treated as not present, e.g. returning `null` or skipping over it. If a expired entry can be resurrected then these calls have side-effects of needing to call the expiration hook. To avoid stampedes this would require double-checked locking of the entry. As the expiry check is a foreign function it could be slow, so it might be surprising behavior that a simple read results in an expensive operation.

There would be a similarly large ripple effect across all methods, e.g. `remove` and `replace`, as all would have to take into account the entry may be recovered. Even though you want to remove a key, to give the correct removal cause we'd have to perform the check. That might be viewed as unnecessarily wasteful in some scenarios.

__Network__
Your proposal optimizes for a single server, but in a large network you'll have many with possibly different entries in their cache. That means if the call to query the data is prohibitively expensive, it will be encountered fairly frequently in either case. Instead you would want to optimize at the system level, e.g. using a secondary cache like memcached/redis, a materialized view, etc. If that was in place to reduce the worst-case latencies, then a few extra calls of an expired cache entry would have a marginal effect.

That means that most cases for a local cache is to avoid "death by a thousand cuts" due to the high volume of cheap queries. Examples might be DNS resolution or loading a schema to validate a json request.

---

The simpler approach of expiring and reloading the data seems like it should be adequate. It is easy to understand, predictable, and focuses the problem on optimizing the whole system rather than a single machine.

I also believe you get most of the benefit if you use `refreshAfterWrite` to reload active entries that will expire soon. Your approach defers until after it has expired, which primarily helps when there has been no system activity. For example if your product is only used within a single region, so at night there is no usage and all entries expire. That leads more to a case of potentially wanting to periodically warm the cache for morning traffic. But once you have activity around the clock, which often happens at scale, then your idea doesn't seem overly beneficial.

That's why I feel this is a special case which optimizes for handling low volume scenarios and has high implementation complexity. At which point there seem to be very easy workarounds to get the desired effect in user code rather than needing to change the library.

**Comment by jiming** [comment]
Dear Ben,

I agree there have some other way to resolve this, including your advice. It's just it is not clean in my view:)

If the main difficult it about concurrency, I think I did not describe myself clear. Here you only need to consider RemovalClause.EXPIRED, the hook method is **only** called before expire(expireAfterWrite, **NOT** expireAfterAccess), and if the Hook method return true, you just never need to do the real job of remove the entry. You simply extend its life in cache is fine. Which I suppose will not cause concurrency problem.

I already used redis, but even redis, I guess it is at least 1000 times slower than load from cache. I just wanted some extreme performance. In order to avoid creating a complex notify cache clean system, I set some cache entries' TTL only seconds, I really do not like the entry to be reloaded againg and again.

BTW, could you please consider add a RemovalCause.EXPIRED_AFTER_WRIETE and RemovalCause.EXPIRED_AFTER_ACCESS.

Thank you for your time!
Jiming

**Comment by ben-manes** [comment]
`expireAfterWrite` means that the entry should be removed after a duration past its last modification. That means for a setting of 10 minutes and the next cache access is an hour later, the expired entry will be present, hidden from the user, and automatically removed. There isn't a timer thread that performs an immediate removal, but rather the work is triggered by application usage. Therefore I think the hook would need to be called to determine whether the entry is visible to a query.

Sorry, but splitting the expired removal cause would be an API break. An access policy is usually for cases like authentication tokens and similar. That's not as common, so most users probably want a write policy. Off hand I can't think of a use-case for enabling both and needing to distinguish in the listener.

I agree your hook, if properly implemented, is optimal for your scenario. It is cleaner client code than the optimal workarounds, e.g. a victim cache to loop back through. But shaving off a few requests won't have an observable performance improvement for application. When I construct a case that would, the application would benefit from a secondary cache regardless making it moot. If you use Caffeine+Redis and `refreshAfterWrite` then you'll have good performance, the system behavior you want, and a lot of flexibility. If you remove Redis from that equation, you'd still want to optimize the database query to minimize worse-case latencies of the entry not being cached.

I'm sorry, but I see a lot of complexity and struggle to see the upside. I really appreciate your thoughts, and please keep offering them, but I am doubtful that we're going to agree on this one.

**Comment by jiming** [comment]
Dear Ben,

Thanks for your kindness and  patiance! I will try some other hack.

Have a nice day!
Jiming
