### ISSUE TITLE
Blocking Issues with AsyncCache

### ISSUE THREAD

**Issue by anuragagarwal561994** [ben-manes/caffeine#1171]
<img width="1689" alt="Screenshot 2023-09-07 at 6 58 52 AM" src="https://github.com/ben-manes/caffeine/assets/6075379/05f0d212-d5f6-422d-965a-8f91a3fe2fd1">

Hello @ben-manes can you help me figure out what is going on here, I am not able to wrap my around with this.

```java
var loadingCache = Caffeine
            .newBuilder()
            .maximumSize(100_000)
            .recordStats()
            .buildAsync(ipServiceLoader);
```

This is my cache definition

Now in the IPServiceLoader we make an http call and return the completable future for the same. 

The entry is fetched as

```
asyncLoadingCache.asMap().containsKey(ip);

and also

asyncLoadingCache.get(ip).orTimeout(duration, TimeUnit.MILLISECONDS).handle(IPServiceFutureHandler(startTime, fromJvm))
```

**Comment by ben-manes** [comment]
The stack trace shows that the future completed and its `whenComplete` handler updated the cache with the results. In that case it was unsuccessful, so the cache has to remove the entry.

https://github.com/ben-manes/caffeine/blob/fef5e2d06e4e4f6f7a400571456ab092dc0776a2/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncCache.java#L208-L214

The blocking may be if the cache size stays small and there is a high churn rate of entries being added and removed. You might consider decoupling the cache load from the caller's timeout, so ConcurrentHashMap has allocated too few locks and there is a high collision rate. As the FAQ [suggests](https://github.com/ben-manes/caffeine/wiki/Faq#write-contention), you can set `initialCapacity` to allocate a larger hash table and therefore more internal locks.

Unlike dependant actions that create a new future, the `orTimeout` affects the current one. This means you are canceling the future held by the cache, which might not be your intent. If it was, then clearer code would be to add the timeout in your cache loader. You can use `copy()` to decouple the cache's future and the caller's, e.g. so that the cache load can exceed the timeout while the caller is bound to it.

**Comment by anuragagarwal561994** [comment]
Thanks @ben-manes for your quick help.

We found bottle neck in our application and resolved it. Didn't get time to update and also because the contention has for sure reduced but I am still seeing some contention in concurrent map complete method at the same line.

As you mentioned about initialCapacity isn't 0.1 M enough large cache. I am still trying to understand your link on this topic.

**Comment by ben-manes** [comment]
Sound good, let me know if I can help clarify anything.

**Comment by ben-manes** [comment]
> As you mentioned about initialCapacity isn't 0.1 M enough large cache. I am still trying to understand your link on this topic.

re-reading, and I think you are assuming that the `maximumSize(100_000)` is the same as the initial capacity? It is actually distinct, that maximum is what the hash table can grow up to before we start evicting. The initial capacity is how many entries the table can hold, which starts at 16, doubles as needed, and is triggered by the load factor. We don't default `initialCapacity` to `maximumSize` since that preallocates space, e.g. `maximumSize(Integer.MAX_SIZE)` is valid even if unwise. Typically the hash table quick grows to the maximum so these resizes are inexpensive and part of the warmup. However if the table stays tiny then since  `ConcurrentHashMap` piggybacks on the table size to determine the number of locks (rather than per-entry locks), you might see more unnecessary contention. By preallocating a larger hash table, via `Caffeine.initialCapacity`, you ensure that there are enough locks if lock collisions are causing you problems.

**Comment by anuragagarwal561994** [comment]
Oh!! I am seriously sorry that I have overlook this part of the documentation, I seriously didn't know until now there is an initial capacity option. I used to think that the maximum size is the size the cache is initialised with, since that is how a ConcurrentHashMap would work when I do `new ConcurrentHashMap<>(size)`.

But now when I write it I understand, it is the initial capacity and not the maximum capacity, maximum size is Caffiene specific property because that would be the mark of eviction. Now the whole thing makes a lot of sense to me.

There are in general 2 use-cases, one where we know the size is too much because the keys are sparse and we would want to be able to cache only the hot keys here, where we can make initialSize = maximumSize.

Second where we don't know what the actual cache size would be but we know that it should not go beyond this capacity there I believe it is okay to either not mention the initial size or we can be a little conservative about it, because such cache might not be that aggressive in nature and we would want to instead save some space here.

Thanks again for helping me understand this.

**Comment by anuragagarwal561994** [comment]
<img width="1728" alt="Screenshot 2023-09-10 at 6 47 09 PM" src="https://github.com/ben-manes/caffeine/assets/6075379/12649e73-f5e1-44d5-adc7-5f87964870fd">

So I noticed that the contention is significantly reduced, still some left over traces.

```
Caffeine
            .newBuilder()
            .maximumSize(100_000)
            .initialCapacity(100_000)
            .recordStats()
            .buildAsync(ipServiceLoader);
```

**Comment by ben-manes** [comment]
hmm... I can think of two possible paths to explore.

The `compute` is blocking but should be extremely short as it merely creates the `CompletableFuture` to assign it and similarly on eviction it just removes the mapping. In the best case then there would be no blocking as the lock uncontended and held for a few dozen nanoseconds to do this atomic work. If your `ipServiceLoader` is doing more work to produce that future then it would lengthen the hold time and that might explain things?

The other case is much trickier which is when the [profiler is lying to you](http://psy-lob-saw.blogspot.com/2016/02/why-most-sampling-java-profilers-are.html). A sampling profiler will try to guess where to assign the blame by taking a stacktrace, which forces all threads to wait at a safepoint, and then looks for the dominators. This can lead to bias where the wrong section of code is blamed, such as cheap but frequently code that is forced to wait on the global safepoint like a mutex. That forces the threads to block unnecessarily, does not sample all points at equal probability, introduces blocking that won't happen in non-profiled runs, and blames the wrong sections code. There are some excellent articles and talks about the safepoint bias problem, where [async-profiler](https://github.com/async-profiler/async-profiler) is the preferred tool for micro-optimizations.

My rule of thumb is to use a classic profiler like yourkit or jfr for finding why users are reporting a sluggish application, e.g. response times measured in seconds. Those tools quickly identify the long-running I/O (slow sql query), inefficient algorithms (big-O large computation), excessive allocations causing gc pauses (string concat), or for analyzing a heap dump for an out-of-memory error (memory leak). I'll use async-profiler for tiny optimizations like a few milliseconds or less where it will more accurately identify the problem in a compute-bound workload driven by a micro-benchmark. That's great for infrastructure projects like this one, where performance is already good enough but it's an excuse to learn more and inflate my ego by making it even faster. For most day-to-day work on end-user facing application performance I'll just pull out an easy to use tool like yourkit / jprofiler / jfr to quickly find the problem, fix it, and move onto the next customer issue or feature work.
