### ISSUE TITLE
computeIfAbsent on BoundedLocalCache overwrites existing keys

### ISSUE THREAD

**Issue by GFriedrich** [ben-manes/caffeine#1207]
Hey,

I'm not sure if this is a bug here or in the ConcurrentHashMap implementation (or it could also be me getting things wrong on the `computeIfAbsent` contract). But as I would imagine that the JRE implementation is somewhat more used than this library here, I figured I would post it here first.

So my problem is that the call to `computeIfAbsent` on a Caffeine cache overwrites the values once in a while.

I've written a test case for this:
```java
public class ComputeIfAbsentOverwrite {
    private final Map<String, Lock> cache = Caffeine.newBuilder().expireAfterAccess(100, MILLISECONDS).<String, Lock>build().asMap();

    public void acquireLock(String key) {
        cache.computeIfAbsent(key, (ignored) -> new ReentrantLock(true)).lock();
    }

    public void releaseLock(String key) {
        var lock = cache.get(key);
        if (lock != null) {
            lock.unlock();
        }
    }

    public static void main(final String[] args) throws Exception {
        final var instance = new ComputeIfAbsentOverwrite();
        final var barrier = new CyclicBarrier(2);
        final var latch = new CountDownLatch(2);
        final Runnable handler = () -> {
            try {
                for (int i = 0; i < 1000; i++) {
                    barrier.await();
                    instance.acquireLock("1");
                    instance.releaseLock("1");
                    Thread.sleep(200);
                }
                latch.countDown();
            } catch (final Exception e) {
                e.printStackTrace();
                System.exit(1);
            }
        };
        var thread1 = new Thread(handler);
        var thread2 = new Thread(handler);
        thread1.start();
        thread2.start();

        latch.await();
    }
}
```

When I run the main method, I get the following exception (sometimes right away, sometimes after waiting for a few moments):
```
java.lang.IllegalMonitorStateException
	at java.base/java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:175)
	at java.base/java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1007)
	at java.base/java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:494)
	at example.ComputeIfAbsentOverwrite.releaseLock(ComputeIfAbsentOverwrite.java:23)
	at example.ComputeIfAbsentOverwrite.lambda$main$1(ComputeIfAbsentOverwrite.java:36)
	at java.base/java.lang.Thread.run(Thread.java:833)
```

I'm a bit unusure whether this is me getting things wrong on the `computeIfAbsent` method contract on a ConcurrentMap, but I was under the impression that this method would only set the value to the map if the value is missing. But in this case it seems that one thread is overwriting the value of the other thread. 🤔

Would be already great if you can at least tell me, whether I'm having wrong expectations or whether this is really some bugged behaviour.

Thanks in advance in any case.

**Comment by ben-manes** [comment]
Thanks for providing a test case! When I run it locally it does not fail, but I understand it is a timing issue. The 100 ms expiration time looks error prone because it assumes that the system will respond immediately, e.g. there is no delay that causes the thread to be inactive and exceed that threshold. In a non-realtime system you cannot make those type of assumptions and need to assume best effort scheduling. `Thread.sleep` states that the duration is _"subject to the precision and accuracy of system timers and schedulers"_ and `ScheduledThreadPoolExecutor` makes a similar promise of a minimum delay but _"without any real-time guarantees"_.

In your specific case, I would instead use a weak reference to allow the garbage collector to discard an unused lock. That would be to replace `expireAfterAccess` with `weakValues`. This way only when there are no strong references to that lock instance is it eligible for garbage collection and may be swept away. If the gc doesn't kick in promptly, then another thread may be able to obtain and reuse the cached instance to avoid an extra allocation.

If your actual logic is more complex than what you want is called [pinning](https://github.com/ben-manes/caffeine/wiki/Faq#pinning-entries) in the FAQ. You could supply a `expireAfter(Expiry)` that makes the entry eligible for expiration only when unlocked. In your sample of blocking on the lock external to the computation in order to avoid blocking within the hash map's lock, this requires adding a wrapper to manually reference count. The pinning and unpinning would happen with a computation and the acquisition of the lock outside of it.


<details>
<summary>Lock pinning</summary>

```java
public class ComputeIfAbsentOverwrite {
  private final Cache<String, LockHolder> cache = Caffeine.newBuilder()
      //.evictionListener((k, v, c) -> System.out.println(c + ": " + k))
      .expireAfter(new Expiry<String, LockHolder>() {
        @Override public long expireAfterCreate(String key, LockHolder lock, long currentTime) {
          return (lock.queued() > 0) ? Long.MAX_VALUE : TimeUnit.MILLISECONDS.toNanos(100);
        }
        @Override public long expireAfterUpdate(String key, LockHolder lock,
            long currentTime, long currentDuration) {
          return (lock.queued() > 0) ? Long.MAX_VALUE : TimeUnit.MILLISECONDS.toNanos(100);
        }
        @Override public long expireAfterRead(String key, LockHolder lock,
            long currentTime, long currentDuration) {
          return currentDuration;
        }
      })
      .build();

  @Test
  public void test() throws Exception {
    final var instance = new ComputeIfAbsentOverwrite();
    final var barrier = new CyclicBarrier(2);
    final var latch = new CountDownLatch(2);
    final Runnable handler = () -> {
      try {
        for (int i = 0; i < 1000; i++) {
          barrier.await();
          instance.acquireLock("1");
          instance.releaseLock("1");
          Thread.sleep(200);
        }
        latch.countDown();
      } catch (final Exception e) {
        e.printStackTrace();
        System.exit(1);
      }
    };
    var thread1 = new Thread(handler);
    var thread2 = new Thread(handler);
    thread1.start();
    thread2.start();

    latch.await();
  }

  public void acquireLock(String key) {
    var holder = cache.asMap().compute(key, (k, value) -> {
      return (value == null)
          ? new LockHolder(new ReentrantLock(true), 1)
          : new LockHolder(value.lock(), value.queued() + 1);
    });
    holder.lock().lock();
  }

  public void releaseLock(String key) {
    cache.asMap().computeIfPresent(key, (k, holder) -> {
      holder.lock().unlock();
      return new LockHolder(holder.lock(), holder.queued() - 1);
    });
  }

  record LockHolder(Lock lock, int queued) {}
}
```
</details>

**Comment by GFriedrich** [comment]
Thanks for getting back at this - it is much appreciated.

So what should be mentioned: This test case is just a heavily stripped down version of how it is used. E.g. the eviction time is a lot longer (5 minutes) and also there is no `Thread.sleep` at all, but rather different threads trying to call a `computeIfAbsent` on "random" times. But there are situations where two threads may run this at the very same time after the previous entry was evicted. And so this test case tries to emulate this situation.

If I would create a test case with the original situation, it could run for several days without falling apart and thats of course not really useful anymore.

So my question is: Is there something wrong with `computeIfAbsent`? Because I would expect that it never overwrites a previously existing value.

**Comment by ben-manes** [comment]
From your example there was nothing wrong because the entry expired, so it is not usable and therefore considered absent. The cache discarded the entry and created a new one. Since this is determined by the timing rather than logical state, this means you might introduce race conditions like your failure case. The pinning / ref count approach instead rely on the logical state of the entry so that it cannot be evicted while in use. That would be less error prone and, if it failed, might be easier to argue as a library bug. From what I can see so far, there is not enough for me to narrow in on an implementation issue rather than a mistaken assumption about how expiration and computes can interact.

**Comment by GFriedrich** [comment]
I'm not sure if I understand this, because the two threads will in parallel run the `computeIfAbsent` method, so why would both set the value into the map where one overwrites the other? I thought the whole point of this method is to run this as an atomic operation on the `ConcurrentMap`. How can this be a race condition on an implementation that is considered thread safe. 🤔

**Comment by ben-manes** [comment]
In the test case, the entry expires after 100 ms since the last read or write. The threads sleep for 200 ms between iterations. This means that they could be in lockstep (0,1; 200,201; ...) or offset (0,120; 200,320, ...). If in lockstep then thread T1 always encounters an expired entry that is evicted and created atomically, while T2 always sees it present and available to use.

This is all in the ideal case where the scheduler fairly gives the threads system time, but a most OS schedulers are not fair and will penalize a thread. There can be executions where T2 is penalized longer than 100ms so it acquired the lock, T1 slept so that the entry expired and cycled through, and T2 resumed in at the wrong state. This does not have to be due to your sleeps, the OS scheduler can preempt a thread at any time. There are many variations of this type of race condition, like the ABA problems, where rare races will happen even in practice. The safer approach is to make decisions based on the logical state instead of the system clock, which is why I recommend pinning or weak references.

**Comment by GFriedrich** [comment]
Ok, thanks for the explanation of your thoughts.
But how do you explain that this is also happening for situations where the expiration time is a lot larger (e.g. 5 minutes) and the computation between the lock/unlock is just a few seconds (at the very worst case - and normally just less than a second). Because I hardly believe that the OS scheduler would block one of the threads for such a long period.
That's why I was trying to express that this test case is a stripped down version to enforce the behaviour I've seen in rare cases and to enforce this unexpected behaviour.

I've also played a bit with my test scenario and am even able to reproduce the behaviour in an acceptable time range when I increase the eviction to 1 second and the sleep to 2 seconds.

**Comment by ben-manes** [comment]
All I can explain is that there is not enough yet for me to pinpoint a library bug, as time thresholds are too fuzzy to be reliable. A real system can have all sorts of quirks so that at scale, the mean time between failure is not that high. If there is a race condition then it will probably happen, so the first step is to resolve them. In the sample code it is easy to identify that as a problem, even if that is not what is actually the root problem in your production system. It is hard to eyeball from this where a library problem would be, so a corrected test that fails might offer more insights.

The cache performs a `computeIfAbsent` under a `ConcurrentHashMap.compute` to give it exclusivity during the creation. If present and not yet expired, it will instead use a `Map.get` to avoid locking. You are welcome to review that [logic](https://github.com/ben-manes/caffeine/blob/375af1b76530591d29b9b308e546057b5284969c/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L2646). The access timestamp is set in a racy manner, so it would be possible for a state overwrite to cause an early expiration. Since a cache is a transient data store and expiration is best-effort. A cache should have recomputable state, e.g. any entry should be eligible for eviction unless opted out (pinned). Expiration is the maximum potential lifetime of an entry, but it could be evicted earlier, e.g. if size evicted. In a maximum size, for instance, we don't promise LRU ordering either as newer arrivals might be evicted if deemed low value one-hit wonders. If not instructed that an entry is ineligible, an early eviction is valid to maximize some goal like hit rates or concurrency. Often times optimizations implemented by taking advantage of the known constraints so that performance can be obtained by exploiting the "don't care" gray area.

**Comment by GFriedrich** [comment]
Ok, understood. Sadly I don't know how to reliably reproduce this issue without these shorter timings when this is a race condition which happens once in a week on a productive system.
What I can tell is that the locking and the unlocking, which caused the exception happened within just a few milliseconds on two different threads on the production system as stated by some logs, so this can't be related to any OS scheduler mechanism.

I already saw the logic around the updating of the access timestamp and was already wondering whether this could be the culprit of my problem. Basically so that the first thread returns the old value but before this can update the access time, the second thread finds the value expired and replaces the value with a new one.

But I also do understand your reasoning about saying that the cache should have a recomputable state. It is just that this is some unexpected behaviour when just looking at the `computeIfAbsent` method, as I would never expect an existing value to be replaced in a racing manner.

In any case: Thanks again for your opinion. If I have a better idea how to reproduce the issue I'll let you know, but feel free to close the issue.

**Comment by ben-manes** [comment]
Best of luck! I truly think you should incorporate pinning into your production logic, either as shown above or use weak references. I don't think expiration is a good fit for a resource that might be evicted prematurely. If you can inform the cache that it should be excluded from eviction then that should resolve your problem.

**Comment by GFriedrich** [comment]
For the record in case somebody else is struggeling with this in the future:
I've replaced my `computeIfPresent` call with a `compute` call instead which in turn just returns the existing value if one is available.
As this updates the `accessTimestamp` in a synchronous way, it stopped the test case from falling apart.
Even when using the lowest configuration (100/200ms) mentioned above.

**Comment by ben-manes** [comment]
Do you mean you replaced the `get` in `releaseLock` so that the access timestamp is performed within the write?

It makes sense that at the expiration edge a read obtains the value just before it expires, the thread is context out, another thread observes the expiration so it evicts and replaces it, and the original thread updates the timestamp on the discard entry and returns it. This certainly can happen as the timestamp update on read is not synchronous with the action as that would limit the concurrency. By making it a pseudo write it becomes synchronous so you avoid that problem. That limits concurrency, but in the benchmarks that [write throughput](https://github.com/ben-manes/caffeine/wiki/Benchmarks#write-100) was higher than the read throughput of popular alternatives

**Comment by GFriedrich** [comment]
No I've just replaced the `computeIfAbsent` in `acquireLock`. It doesn't matter to me if the `get` does an asynchronous update of the timestamp and by that basically "losing" the previous lock as I already have the correct lock at hand when the updating of the timestamp via `get` happens.
But I now at least keep the right lock if both threads run `computeIfAbsent` at the same time, but one is returning a different lock as the other and by that even replacing the lock in the cache (which is, as said, pretty confusing when just readin the `computeIfAbsent` contract).

And as said: I'm not really worried on throughput in any way, because I'm luckily far away from the numbers you have in your benchmarks.
