### ISSUE TITLE
Support a Map#compute like method

### ISSUE THREAD

**Issue by rdifalco** [ben-manes/caffeine#121]
I have a use case where I cache time-interval criteria for a given key. The interval is just a half-open range. When the key is present I atomically expand the old range with the new range (if necessary), otherwise I just add the new range. Something like this:
```
void addCollectionCriteria(CollectionCriteria criteria) {
        cache.compute(criteria.getInstanceId(), (instance, prevCriteria) -> {
            if (prevCritera == null) {
                return criteria;
            } else {
                CollectionCriteria extended = prevCriteria.extendRange(criteria.getTimeRange());
                if (extended.getTimeRange().toDays() > 14) {
                    queue(prevCriteria);
                    return criteria;  //  effectively removes the previous criteria 
                } else {
                    return expanded;
                }
            }
        });
}
```
I additionally want to evict the oldest criteria when there are too many items in the cache.

Maybe there is a better way achieve this?  Or maybe I shouldn't be using a cache like Caffeine at all for this kind of thing. Currently I just use a `ConcurrentMap` but it would be nice to be able to remove oldest items when a size or time threshold is exceeded.

**Comment by ben-manes** [comment]
`Cache#asMap()` has full support for atomic computations. Your usage looks similar to `merge` which would let you reuse the lambda (currently a new one is required to capture the `criteria`).

The size policy is based on likelihood of reuse rather than age, so that might not be what you want. You might also want to consider whether a `Weigher` would be helpful, which lets you state how much room in the cache the entry consumes. If a criteria can become very large (e.g. a collection of dates), staying within the entry count might not be good enough

**Comment by ben-manes** [comment]
Please re-open if there is more to discuss or that I can assist with.
