### ISSUE TITLE
Nested ".get()" method calls

### ISSUE THREAD

**Issue by wglanzer** [ben-manes/caffeine#1237]
If I try using the cache in combination with "nested cache value loaders", the cache throws an `java.lang.IllegalStateException: Recursive update` exception.
I think it gets clearer, if I show you my example:

```java
  @Test
  void test() throws Exception
  {
    //com.google.common.cache.Cache<Object, Object> c = CacheBuilder.newBuilder()
    //    .initialCapacity(1)
    //    .build();

    com.github.benmanes.caffeine.cache.Cache<Object, Object> c = Caffeine.newBuilder()
        //.initialCapacity(1)
        .build();

    test2(c, 100);
  }

  private Object test2(@NonNull com.github.benmanes.caffeine.cache.Cache<Object, Object> pCache, int pNumber)
  {
    return pCache.get(pNumber, pN -> {
      if(Objects.equals(pNumber, 0))
        return "found";
      return test2(pCache, pNumber - 1);
    });
  }
```

I compared the caffeine cache against the guava cache too; it seems, that the guava cache handles it without any problems.
I tried to increase/decrease the `initialCapacity` of the cache - less initial capacity leads to an earlier exception.

Is this something, that the cache should be aware of? I think yes, because the guava cache can handle those use cases too.

**Comment by ben-manes** [comment]
Correct, unfortunately this isn't supported by `ConcurrentHashMap` in its Java 8 rewrite. You can read the two threads, [2011](https://web.archive.org/web/20210115202646/http://jsr166-concurrency.10961.n7.nabble.com/ConcurrentHashMapV8-td7312.html) and [2014](https://web.archive.org/web/20210115210305/http://jsr166-concurrency.10961.n7.nabble.com/Re-ConcurrentHashMap-computeIfAbsent-td11687.html). The best we could get is a fast failure instead of a livelock.

The FAQ entry on [recursive computations](https://github.com/ben-manes/caffeine/wiki/Faq#recursive-computations) shows how to do this manually. This is similar to Guava's approach which treats every map entry as a future value, whereas CHMv8 uses a coarser hashbin lock (determined by the table capacity). In the example, you insert a pending computation into the map and perform the computation outside of it. This requires that you handle error cases, etc. so it requires more care.

**Comment by wglanzer** [comment]
Oh, sorry, I din't see your really well written FAQ.. My fault, thanks for clarification!
