### ISSUE TITLE
How to Cache a Hierarchy of Objects?

### ISSUE THREAD

**Issue by adamretter** [ben-manes/caffeine#125]
@ben-manes I was wondering if you had any suggestions or advice on how to cache a hierarchy of objects with Caffeine in a concurrent but safe update manner?

For example, the values in my `Cache<Id, Node>` look like:

```java
class Node {
   Set<Id> childNodes;
}
```

The thing I am struggling with here is how to link a new Node into my hierarchy, which requires updating the parent Node's subNodes.

```java
Node node = cache.getIfPresent(id);
if(node != node) {
  return node;
}

node = new Node(someId);
//TODO: How to Atomically add to cache AND update the `childNodes` of the parent Node in the cache?
```

I looked at the `ConcurrentMap#compute` methods, but they say:
>must not attempt to update any other mappings of this Map

**Comment by adamretter** [comment]
I guess that I could use a `Cache<Id, Cache<Id, Node>>`, however my gut feeling is that this could be quite expensive?

**Comment by ben-manes** [comment]
Since a cache is transient, recomputable data its usually okay to update the system-of-record and invalidate. Then your database is updating all of the effected rows in a transaction so that it is performed atomically. Then removing all of the affected records from the cache causes subsequent calls to observe the correct state. So if possible, that's a simple and common solution usually performs well and keeps consistency.

I agree recursive, hierarchical concurrent operations can be really messy and best to be avoided. If you can defer that to a transaction it would be much simpler.

**Comment by adamretter** [comment]
@ben-manes I am not sure if I am quite following what you are saying.

Well... I had an attempt today to try and create something, it's pretty wild but I would be interested to get your opinion: https://gist.github.com/adamretter/11ccca59cebd07b4612b2b1f4e7bfb4f

The function of interest which plays with Caffeine is [getOrCreateNodeExplicit](https://gist.github.com/adamretter/11ccca59cebd07b4612b2b1f4e7bfb4f#file-nodemanager-java-L26)

One of the helpful properties I have is that an id for one of my nodes is really the path to the node, which allows me to make some simple calculations. I managed to encase most of the updates inside a `compute` block, I allow different threads to collaborate in linking a child node into the tree, basically each node has an `AtomicBoolean` which indicates whether the node is active (i.e. inserted into the tree yet).

I am not sure what the concurrency is like, but I take a bottom-up approach to adding nodes, so hopefully I only call `compute` on the closest existing ancestor of the tree node.

There are also some basic tests: https://gist.github.com/adamretter/0b58dffa9ab7476cc96ed5b0d0f526b9

With some naive testing it seems to show that it works, but I might be missing something obvious that further testing would reveal. Also I have no real idea of the concurrency (or not).

**Comment by ben-manes** [comment]
You have a `persistNode` method to store the results to some kind of database. That means you plan on eventually loading the nodes from the database, e.g. because the cache previously evicted them due to the size constraint.

My thinking was that you perform all this work inside of a database transaction. This makes sense because it has stronger locking support, e.g. if two machines try to create overlapping paths it won't result in potential corruption. A transaction handles row-level locking, with deadlock detection, so you have much less to worry about regarding concurrency control. Instead you start a transaction, perform all of the tree manipulation logic, persist, and invalidate all nodes in the tree that were mutated. The cache is remains a simple way to query nodes quickly, but the database still does the heavy lifting.

Joe Celko's [book](https://www.amazon.com/Hierarchies-Smarties-Kaufmann-Management-Systems/dp/0123877334) is an excellent descriptions of how trees can be modeled in SQL. If you're using a NoSQL database instead then it might be harder to model.

**Comment by adamretter** [comment]
@ben-manes Thanks for the explanation, that helps me to understand your previous comment. However in this instance I am using a NoSQL database and it does not provide Transactions so I need to manage my own concurrency here.

**Comment by ben-manes** [comment]
In that case I'd still start from the data model and work up towards the cache, rather than the other way around. I think its probably simpler that way, but I could be wrong. It might be a good exercise regardless.

If its key-value then you might consider making the tree structure one value, with the leaves as separate key/value lookups. Then walk downwards instead of upwards.

If your on a column-family store, like Cassandra, you might be able to use composite columns or similar. You'd want to talk with developers experienced in that domain.

But if you plan on doing this yourself you might need to use node-level locks and manage deadlocks. You might move locking outside of the `Map` and either on the `Node` or use lock striping. Guava's `CycleDetectingLockFactory` could prove to be useful. Something along these lines would be similar to what a database does internally. However, they get to assume ownership of the data access whereas you may have multiple machines mutating in parallel, which could cause more problems. In that case you might have periodic process that scans, detects corruption, and correct it if possible.

Alternatively, if you use a distributed commit log (e.g. Kafka) you might be able to simplify this. Store the changes and make them viewable immediately. Then replay on a single writer into NoSQL database. This removes the writer needing to worry about concurrency and you can try to give an immediate view of the changes in the cache, if needed.

I guess my argument is to focus on the database side first, then propagate to the cache. You're taking the other route, which usually is more problematic but you might get to work nicely here. I think all I can recommend is to look for edge cases and explore what both approaches offer. But if it works nicely for you now, then great job.

**Comment by ben-manes** [comment]
Closing, but re-open if there is more to discuss.
