### ISSUE TITLE
java.lang.NoClassDefFoundError: Could not initialize class com.github.benmanes.caffeine.cache.LocalCacheFactory$SSSMSW

### ISSUE THREAD

**Issue by wclaeys** [ben-manes/caffeine#128]
When using com.github.ben-manes.caffeine;version=2.3 in an OSGi container, we got the following error:
`
java.lang.NoClassDefFoundError: Could not initialize class com.github.benmanes.caffeine.cache.LocalCacheFactory$SSSMSW
`
Looks like this inner class 'SSSMSW' could not be found. We're not using any extensions.

**Comment by ben-manes** [comment]
For clarity that is an abbreviation for,
 - S(trong) keys
 - S(trong) values
 - S(stats)
 - M(aximum) W(eight)

When I configure [OSGiTest](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/test/java/com/github/benmanes/caffeine/OSGiTest.java) with that configuration it passes. I'm not very familiar with OSGi, so I'd guess its a container bug or an issue with your build. 

Are you performing any type of minification, e.g. Proguard, or constructing a fatjar? The latter because they can use special classloaders, have class conflicts, etc. that cause quirks.

**Comment by johnou** [comment]
http://stackoverflow.com/questions/34413/why-am-i-getting-a-noclassdeffounderror-in-java

java.lang.NoClassDefFoundError This exception indicates that the JVM looked in its internal class definition data structure for the definition of a class and did not find it. This is different than saying that it could not be loaded from the classpath. Usually this indicates that we previously attempted to load a class from the classpath, but it failed for some reason - now we're trying to use the class again (and thus need to load it, since it failed last time), but we're not even going to try to load it, because we failed loading it earlier (and reasonably suspect that we would fail again). The earlier failure could be a ClassNotFoundException or an ExceptionInInitializerError (indicating a failure in the static initialization block) or any number of other problems. The point is, a NoClassDefFoundError is not necessarily a classpath problem.

@wclaeys can you see any exceptions _before_ the NoClassDefFoundError?

**Comment by ben-manes** [comment]
Oops, I decoded the abbreviation wrong (SSSMSW)

- S(trong) keys
- S(trong) values
- S(stats)
- M(aximum) S(ize)
- Expire after W(rite)

But no difference on that test case passing.

The only case I can think of is if `sun.misc.*` cannot be imported (for Unsafe). Due to quirks in OSGi, when adding I remember reading that I had to set it to `resolution:=optional`. Perhaps there's a better configuration that makes it required but doesn't cause container issues.

**Comment by ben-manes** [comment]
@nedtwigg any advise on if I'm misusing OSGi? From https://github.com/diffplug/osgiX it sounds like I should use an extension bundle, though I'd prefer not adding a dependency if possible.

**Comment by nedtwigg** [comment]
1) what OSGi container are you using
2) we need the full stacktrace

It might be that the exception looks like this:

```
java.lang.NoClassDefFoundError: Could not initialize class com.github.benmanes.caffeine.cache.LocalCacheFactory$SSSMSW

because could not load sun.misc.Unsafe
```

In which case the @wclaeys could fix this by adding an extension bundle from osgiX.  But it depends on the rest of the exception and the runtime, so @ben-manes there's no need for you to add this as a dependency for everybody.

**Comment by wclaeys** [comment]
I'm using org.apache.felix.framework;version='[5.4.0,5.4.0]' together with Bndtools (3.3.0). 

Full stacktrace:
Caused by: java.lang.ClassNotFoundException: sun.misc.Unsafe not found by com.github.ben-manes.caffeine [15]
at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1574)
at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:79)
at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:2018)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

I was able to solve this issue by adding the following in my bndrun file:
`
-runsystempackages: sun.misc
`

Thx guys for the pointers to solve this issue!
