### ISSUE TITLE
`computeIfAbsent` in BoundedLocalCache uses `recordStats` instead of `recordMiss`

### ISSUE THREAD

**Issue by Valloric** [ben-manes/caffeine#129]
I was just stepping through Caffeine cache code in my codebase when I noticed the following:

From `LocalCache.java`:

```java
  @Override
  default V computeIfAbsent(K key, Function<? super K, ? extends V> mappingFunction) {
    return computeIfAbsent(key, mappingFunction, /* recordMiss */ true, /* recordLoad */ true);
  }

  /**
   * See {@link ConcurrentMap#computeIfAbsent}. This method differs by accepting parameters
   * indicating whether the operation was called by an asynchronous cache.
   */
  V computeIfAbsent(K key, Function<? super K, ? extends V> mappingFunction,
      boolean recordMiss, boolean recordLoad);

```

Notice that the second param is named `recordMiss` and seems to indicate that misses should be recorded.

Now the overload for that method in `BoundedLocalCache.java`:

```java
  @Override
  public V computeIfAbsent(K key, Function<? super K, ? extends V> mappingFunction,
      boolean recordStats, boolean recordLoad) {
    requireNonNull(key);
    requireNonNull(mappingFunction);
    long now = expirationTicker().read();

    // An optimistic fast path to avoid unnecessary locking
    Node<K, V> node = data.get(nodeFactory.newLookupKey(key));
    if (node != null) {
      V value = node.getValue();
      if ((value != null) && !hasExpired(node, now)) {
        afterRead(node, now, /* recordHit */ true);
        return value;
      }
    }
    if (recordStats) {
      mappingFunction = statsAware(mappingFunction, recordLoad);
    }
    Object keyRef = nodeFactory.newReferenceKey(key, keyReferenceQueue());
    return doComputeIfAbsent(key, keyRef, mappingFunction, now);
  }
```

The param name is `recordStats` and is used to turn stats collection on/off. So something is very wrong here.

**Comment by ben-manes** [comment]
Since there are unit tests that should verify the stats, probably an incorrect comment when annotating all of the flags / consistent naming. In some places `recordMiss` is the parameter name, so I might have intended to rename `recordStats` due to being unclear. Unfortunately the code gets due to all the different features, races, etc. so double checking which name is appropriate is a good idea.

**Comment by Valloric** [comment]
I was looking at this because I was trying to answer does Caffeine cache misses as well as hits for a LoadingCache. I'm trying to avoid 50 gets for key X that's not in the cache or in the backing store resulting in 50 gets to the backing store (which is on disk). If Caffeine cached misses (with the standard timeout it uses for records), I'm done. If it doesn't, I need to implement it on top of Caffeine (with another Caffeine cache for misses). 

When I saw the `recordMiss` part it made me think that yes, misses will be recorded but the implementation uses `recordStats`.

So I'm still not sure are you saying `recordMiss` means "record a miss in the stats" and the param names are not in sync (but the code is), OR `recordMiss` means "record a miss in the cache" and the code has a bug.

**Comment by ben-manes** [comment]
There may be a bug, but my gut feeling is poor naming when refactoring. I put a lot of effort into the unit tests, so hopefully this would fall into one of those easy cases that are covered. For the limited set of Guava tests available (e.g. `LocalLoadingCacheTest`), Caffeine passes that port so that adds a bit of confidence.

Regardless, the name `recordMiss` is meant as "record a miss in the stats". Caffeine does not perform negative caching ("record a miss in the cache") and leaves that to the user. A common pattern is to use an `Optional<V>` so that an entry does exist from the cache's perspective. I think deferring negative caching to client code is less confusing for everyone involved.

**Comment by Valloric** [comment]
> I think deferring negative caching to client code is less confusing for everyone involved.

Possibly, though I don't see how adding another `cacheMisses` config method to the Caffeine builder would be confusing. It would have great docs like any other method on the builder. :)

But like you said, it's easy to emulate. Instead of returning null for misses from my CacheLoader, I'm just going to return some sort of sentinel empty object. Caffeine will cache that just fine. My logic will need to be a bit funkier in that I'll have to recognize the sentinel object, but I can live with that.

Thanks for the quick responses! (Feel free to close this issue if needed.)

**Comment by ben-manes** [comment]
The `Optional<V>` is the sentinel I was thinking of. Then you can do `cache.get(key).orElse(null)` which isn't too bad.

Negative caching adds a lot of subtle complexity. Do stats distinguish a miss from a negative hit? How does Map behave (size, iteration)? Is it okay to retain the user's key? What "weight" does a negative entry have? How does `computeIfAbsent` behave? Its just messy, the library tackled a lot of complexity, and it could be more of a burden than a gain. Hence my feeling of deferring to your code.

**Comment by Valloric** [comment]
> The Optional<V> is the sentinel I was thinking of. Then you can do cache.get(key).orElse(null) which isn't too bad.

Yeah but that's another pointer dereference in the happy path, no? `Optional.get()` isn't free and I'm writing perf-critical code. Storing a sentinel V means happy path just has the V right away.

> Negative caching adds a lot of subtle complexity. 

Agreed, which is kinda the reason why it might be better to have it in the library so that it only needs to be written and tested once instead of in all the clients that are doing this. For instance, I'll now have to stop using the nice stats provided by Caffeine (thanks for that BTW) so I can easily track miss rate. I'll need to write custom stats code in my CacheLoader so that I have the "real" miss rate.

Not saying that any of this is obvious or that my suggestion is correct; this is very much in the trade-off space where both approaches strike me as reasonable. Punting on this to the caller is an understandable choice; complexity comes with non-trivial costs.

**Comment by ben-manes** [comment]
Both `BoundedLocalCache` and `UnboundedLocalCache` honor a `recordStats` behavior. The only direct call is `LocalAsyncLoadingCache#get(key, executor, mappingFunc, recordStats)`. It appears that the comment & param name in `LocalCache` is wrong, but has no negative effect on internal expectations. These are the types of bugs I like :)

I definitely see where you're coming from. I think that I've nearly exhausted the complexity budget from the implementation perspective, further leading to my hesitation. If the pattern was repeatably needed then writing a decorator that adds that capability is my current preference. As a library it should be easy to extend to provide richer capabilities and be encapsulated in other caching frameworks (e.g. Infinispan, imcache). And I might be proven wrong, so I'll keep revisiting the idea.

Btw, you might have a middle ground for stats by using a custom `StatsCounter` so that you don't feel the need to give up on all of them. See the `stats-metrics` example for Dropwizard Metrics. Then you can have more control on publishing the default types (and names), in addition to your custom ones, in the metrics reporter. Might make it easier to wrap this all up into a reusable package to add negative caching.
