### ISSUE TITLE
add support for native image - GRAALVM

### ISSUE THREAD

**Issue by Ricard-Kollcaku** [ben-manes/caffeine#1293]
Currently if we use caffeine and we want to build a native image (spring boot app)
it will not work because reflected classes are not declared for graalvm to include them in compile time
Would be nice that this configuration would be included in the library

**Comment by ben-manes** [comment]
There is an [example](https://github.com/ben-manes/caffeine/tree/master/examples/graal-native) of using graalvm and how to discover the configuration by an agent.

Graal provides the [reachability metadata](https://github.com/oracle/graalvm-reachability-metadata) for caffeine.

Previous discussions with graal users, like quarkus, have said we should not include it due to them wanting only a subset. The framework authors consider it their responsibility to maintain the metadata.

Since it’s murky, I think that example project is the most we can do until an authoritative source can advise us on something better.
