### ISSUE TITLE
Distributed cache

### ISSUE THREAD

**Issue by sheldon-sminq** [ben-manes/caffeine#134]
This is a question, can caffeine be used as a distributed cache?

**Comment by ben-manes** [comment]
Not by itself. Caffeine is only a local cache, so it could be a building block.

For example, Infinispan 9.0 swapped out its internal cache for Caffeine. That's a good indicator that others could do the same, build new ones using this library, or adapt Caffeine's ideas. There are a lot of options out there and I don't have any recommendations.

Hope that helped.

**Comment by haikalpribadi** [comment]
Sorry for revisiting an old issue, but would you be so kind as to share the available options that you know out there, without making any specific recommendation, @ben-manes ? Thanks!

PS: Truly amazing work, btw. I'll be using Caffeine in the Grakn rewrite (2.0) @graknlabs. Thank you so much!

**Comment by ben-manes** [comment]
Typically distributed caching means that data is replicated and consistent across multiple nodes. So memcached and redis would be a remote cache, but not distributed. Redis clustering (sentinel, ElastiCache) might fit that, though. It is ill defined term and data consistency levels vary.

Unfortunately there isn't a jespen.io analysis for this area, with only one product below being evaluated and failing badly. These would be distributed with local, remote, replication of caches managed by the vendor.

- Apache Geode
- Apache Ignite
- Apache JCS
- Infinispan
- Redisson
- Hazelcast
- Terracotta
- Oracle Coherence
- NCache

I cannot make a recommendation due to a lack of familiarity. I would just advise that this choice is like that of a database, hype or brand doesn't mean it is high engienering quality.

**Comment by haikalpribadi** [comment]
Thanks, @ben-manes !

**Comment by ben-manes** [comment]
Redis 6 added some client-side caching, which could be interesting too.
https://redis.io/topics/client-side-caching

**Comment by ohadeytan** [comment]
Hi @haikalpribadi,
Out of curiosity, can you describe a little what is your use case?

(I'm a Ph.D. student working occasionally with @ben-manes and my research topic is caching)

**Comment by haikalpribadi** [comment]
Hey @ohadeytan,

We're building a logical database (aka. [knowledgebase](knowledge base software)) at @graknlabs (people call these days also call it "knoweldge graph"). It has a formal [knowledge representation system](https://en.wikipedia.org/wiki/Knowledge_representation_and_reasoning) and it performs logical reasoning. One of the characteristics of the formal KR system is that the attribute values in the knowledge base are "unique" and [immutable](https://en.wikipedia.org/wiki/Immutable_object). To implement attributes being immutable, we need an in-memory cache as part of the strategy. And we're currently heavily refactoring and rewriting the underlying architecture for scalability so we need a performant in-memory caching system. :)

That's kind of the gist of it - in a nutshell. Hope that helps!

**Comment by ohadeytan** [comment]
Sounds interesting! Thanks
