### ISSUE TITLE
Support for primitive keys?

### ISSUE THREAD

**Issue by markelliot** [ben-manes/caffeine#135]
I have some performance sensitive code where I'd like to cache expensive index-based fetches and presently have `long` indexes. I think I'm hitting a boxing penalty for a `LoadingCache<Long, T>` and wonder if you have any plans to support something like a `LongLoadingCache<T>` any time in the near future. 

If not, I would be interested in something that allowed me to say that a key should be copied when a cache entry is loaded, since that would allow me to use, say, a MutableLong in this case. 

Thoughts?

**Comment by ben-manes** [comment]
Unfortunately the burden is too high. This would require rewriting `ConcurrentHashMap` to use long keys and, I presume, templatize the entire project for code reuse. Project Valhalla is a long ways away, but it does most of the heavy lifting. From there it would require some hopefully minor rework, e.g. a per-entry state machine that uses sentinel keys.

The key escapes the cache due to the underlying `computeIfAbsent` which loading relies on. So the copying would require forking `ConcurrentHashMap` and might introduce subtle races with the hash lookup.

I don't think there's a good option until JDK10.

**Comment by ben-manes** [comment]
Rather than copying keys, you could discard the `MutableLong` once the instance is assigned to an entry. At that point it should be effectively immutable to avoid map corruption and race conditions. Assuming you are using Apache Commons' `MutableLong` you'd write code as,

```java
private static final ThreadLocal<MutableLong> mutable =
    ThreadLocal.withInitial(MutableLong::new);

private final LoadingCache<MutableLong, Object> cache = 
    Caffeine.newBuilder().build(key -> {
      mutable.set(null);
      return new Object();
    });

public Object get(long key) {
  MutableLong mutableKey = mutable.get();
  mutableKey.setValue(key);
  return cache.get(mutableKey);
}
```

Any `put`, `load`, or `compute` must discard the key once its been shared and may never modify it afterwards. But a `get` that doesn't invoke the loader, a lookup key, can be reused if isolated to the thread.

**Comment by markelliot** [comment]
Cool, thanks, that should work here.
