### ISSUE TITLE
com.github.benmanes.caffeine.cache.SSLSMWA consuming very high memory.

### ISSUE THREAD

**Issue by jomishr** [ben-manes/caffeine#1356]
I have initialized my cache in the following way:

```
Cache<Key, Entry> sharedCache =Caffeine.newBuilder()
                          .ticker (ticker::read)
                          .expireAfter(new ExpirySetting())
                          .weigher( a weigher logic that calculates the bytes consumed by each entry value)
                          .maximumWeight(maxBytesInMemory) //maxBytesInMemory =242 MB
                          .executor(executor)
                         .scheduler(scheduler)
                         .build();
```

There is a **weightedSize** variable that keeps track of the total weight consumed at any point of time. When the value of this reaches the **maxWeightedSize** (242 MB as set in the caffeine initialization), eviction start to happen as expected.

but the object com.github.benmanes.caffeine.cache.SSLSMWA consumes a lot of memory (way higher than the maxWeightedSize i.e 242 MB), example of such instances are provided below:

_Unique requests were sent at the rate of 25 per second for 40 mins so that all the requests are getting writen to cache and heap dumps were taken every 3 min. Below are the observations:_

```
com.github.benmanes.caffeine.cache.SSLSMWA: 262.4 MB | maxWeightedSize: 242.194645 MB | weightedSize: 198.201916 MB | time elapsed: 18 min
{Retained size of SSLSMWA (262.4 MB) already exceeded the max weight (242 MB) but the weighted size is still below max weight.}

com.github.benmanes.caffeine.cache.SSLSMWA:289.2 MB | maxWeightedSize: 242.194645 MB | weightedSize: 218.480108 MB | time elapsed: 21 min

com.github.benmanes.caffeine.cache.SSLSMWA:314.3 MB] maxWeightedSize: 242.194645 MB | weightedSize: 237.563964 MB | time elapsed: 24 min

com.github.benmanes.caffeine.cache.SSLSMWA:320.5 MB | maxWeightedSize: MB | weightedSize: 242.193292 MB | time elapsed : 27 min
{weighted size approaches maxweight}

com.github.benmanes.caffeine.cache.SSLSMWA: 299.1 MB | maxWeightedSize: 242.194645 MB | weightedSize: 226.00419 MB | time elapsed: 30 min {weighted size starts to reduce, retained size of SSLSMWA also starts to reduce}

com.github.benmanes.caffeine.cache.SSLSMWA: 258.8 MB | maxWeightedSize: 242.194645 MB | weightedSize: 195.53424 MB | time elapsed: 33 min

com.github.benmanes.caffeine.cache.SSLSMWA: 231.9 MB | maxWeightedSize: 242.194645 MB | weightedSize: 175.148864 MB | time elapsed: 36 min
```

Can you please answer the following questions ?

1.) What is the use of SSLSMWA class?

2.) Why is the com.github.benmanes.caffeine.cache.SSLSMWA consuming so much memory (causing my application to use 99% of the heap)? Why is it not contained within the maxWeightedSize (i.e. 242 MB)

**Comment by ben-manes** [comment]
The library code generates specialized implementation classes to minimize the memory overhead to only include the fields necessary for the given configuration. The `SSLSMWA` class is the cache instance, and likely the per-entry class is `PSAMW`. Calculating the object size is not straightforward (see [JEP draft: Low-level Object layout introspection methods
](https://openjdk.org/jeps/8249196)) and using Java Object Layout we can make a best-effort estimate of the footprint,

```console
***** Hotspot Layout Simulation (JDK 15, 64-bit model, compressed references, compressed classes, 8-byte aligned)
com.github.benmanes.caffeine.cache.PSAMW object internals:
OFF  SZ                                      TYPE DESCRIPTION                 VALUE
  0   8                                           (object header: mark)       N/A
  8   4                                           (object header: class)      N/A
 12   4                          java.lang.Object PS.key                      N/A
 16   4                          java.lang.Object PS.value                    N/A
 20   4   com.github.benmanes.caffeine.cache.Node PSA.previousInAccessOrder   N/A
 24   8                                      long PSA.accessTime              N/A
 32   4   com.github.benmanes.caffeine.cache.Node PSA.nextInAccessOrder       N/A
 36   4                                       int PSAMW.queueType             N/A
 40   4                                       int PSAMW.weight                N/A
 44   4                                       int PSAMW.policyWeight          N/A
Instance size: 48 bytes
Space losses: 0 bytes internal + 0 bytes external = 0 bytes total
```

When you set a maximum based on memory, you have to take into account the overhead of the cache entry (value wrapper), `ConcurrentHashMap` entry, etc. You also have to provide the JVM a reasonable amount of slack as memory is not reclaimed immediately. Similarly, the cache will temporarily exceed its maximum under a write load as it tries to avoid eviction from limiting concurrency. Unfortunately since managing memory is tricky in Java all of the advice is a best guess.

**Comment by jomishr** [comment]
Hi Ben, 
Thanks for the quick response.
The values that I provided was that of a test simulation that I did to replicate the issue.

In reality, the scale of the values are much higher.

One such instance is :-

maxWeightedSize is set to  → 4.79 GB
 weightedSize shows up as → 3.59GB

but the object,
com.github.benmanes.caffeine.cache.SSLSMMA is consuming → 7.46 GB

Do you think this amount of the overhead is possible or is there some kind of underlying issue in caffeine do to which it consumes so much amount of memory?

Please let me know your thoughts on this.

**Comment by ben-manes** [comment]
There are a lot of unknowns given the details provided. A few questions,

**Who is reporting the current size?** Is this from the cache using the `Cache.policy()` api, or is this by an independent calculation such as a heap dump or iterating over the cache to summarize it? Is this reporting on a single cache instance or across multiple of them?

**Is the entry's weight modified over its lifetime?** If the entry's weight may change, e.g. adding to a list held by the value, then this must be reported to the cache to avoid them becoming askew.

**How is the weight being calculated?** As the JEP discusses, calculating the runtime size of an object is error prone and often wrong. If then comparing that against different way this is measured then it's likely that the calculations give different results. Generally the runtime inspection is a best guess that is considered close enough, but is not trusted as accurate.

**Is the cache reporting evictions at a healthy rate?** If evictions was halted or taking a very long time to perform, this could cause the cache to temporarily exceed the maximum. A very long running user computation may hold the underlying ConcurrentHashMap lock, and since that spans across multiple entries it can block siblings in the same hash bin. That might be do to the executor being exhausted (defaults to the commonPool) or a long entry computation (load, compute, eviction listener).

**What are the sizes of the parts that sum up to a large cache instance?** If the entry weights are in bound but the cache instance is excessive, then it may be other structures that became bloated. For example, the FrequencySketch provides a compact histogram for the entry popularities and adjusts its size based on the number of observed entries. If the key's equality method is broken then the cache would fail to evict fully evict the entry and the underlying map would continue to grow, causing a memory leak and forcing the sketch to be resized along with the hash table.

**What version of the library is being used?** If an older version, please review the release notes for anything that sounds related and and consider upgrading.

**Comment by ben-manes** [comment]
let me know when you have answers to some of those questions. A memory leak due to a broken key equality would explain your observations, so getting the number of entries would be useful. In the latest 3.x there is a log message when that problem is detected.

fyi, after a few days of no response I tend to close tickets if not a library bug or a planned feature. Of course you are always welcome to reopen, reply after closed, or open another ticket.

**Comment by jomishr** [comment]
Hey Ben,
It would take me some time to get the answers to the questions that you asked. I will get back to you once I get them .
Feel free to close the ticket for now. If needed , I will reopen it later.
Before closing the ticket can you please describe a bit more about  the " memory leak due to a broken key equality" which you mentioned in the previous comment?
What is meant by broken key equality ?
And is there any issue or bug which talks more about this issue and it's fix? Can you please point me to that ticket ( if there is any) ?

**Comment by ben-manes** [comment]
A mistake that could lead to a memory leak is if the key is modified while the entry resides in the map, such that its `equals` and `hashCode` change. This would break a `HashMap` trying to remove an entry because it hashes to the wrong location and cannot find it, causing the map to become corrupted. Similarly this would happen for the cache, except that in the latest versions we will log a warning if detected. That was introduced to assist [SOLR-16489](https://github.com/apache/solr/pull/1118) where the corruption led to a live lock, but I see that IntelliJ has an bug, [Improve Smart PSI pointer "equals" implementation](https://youtrack.jetbrains.com/issue/IDEA-320644/Improve-Smart-PSI-pointer-equals-implementation), that cause this message to be reported.

When the cache evicts it polls the victim off of an LRU list and removes it from a `ConcurrentHashMap`. If the removal fails and the internal state machine says it shouldn't have, then the message below is logged. If over time these zombie entries accumulate then you would have a problematic memory leak. That usually happens because someone forgot or didn't know that the object was a cache key and mutated it, potentially across threads. The simple solution is to try to use immutable keys when possible. 

I don't know if you are experiencing that problem or something else, but it is a good one to quickly check for.

<details><summary>BrokenEqualsTest</summary>

```java
import static org.junit.jupiter.api.Assertions.assertEquals;

import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

import org.junit.jupiter.api.Test;

import com.github.benmanes.caffeine.cache.Cache;
import com.github.benmanes.caffeine.cache.Caffeine;

public class BrokenEqualsTest {
  static {
    Logger.getLogger("").setLevel(Level.WARNING);
  }

  @Test
  public void equality_cache() {
    Cache<Key, String> cache = Caffeine.newBuilder()
        .maximumSize(1)
        .build();
    var key = new Key();
    cache.put(key, "");

    // Break equals contract
    key.i++;

    // force all items to be evicted
    cache.policy().eviction().orElseThrow().setMaximum(0);

    // Fails as not empty
    assertEquals(cache.estimatedSize(), 0);
  }
  
  @Test
  public void equality_map() {
    var map = new HashMap<Key, String>();
    var key = new Key();
    map.put(key, "");

    // Break equals contract
    key.i++;

    // force all items to be evicted
    map.remove(key);

    // Fails as not empty
    assertEquals(map.size(), 0);
  }
  
  
  static final class Key {
    int i;
    
    @Override public boolean equals(Object o) {
      return (o instanceof Key) && (((Key) o).i == this.i);
    }
    @Override public int hashCode() {
      return i;
    }
  }
}
```
</details>

<details><summary>Cache Warning</summary>

>Dec 11, 2023 10:35:57 AM org.slf4j.jdk.platform.logging.SLF4JPlatformLogger performLog
SEVERE: An invalid state was detected, occurring when the key's equals or hashCode was modified while residing in the cache. This violation of the Map contract can lead to non-deterministic behavior (key: BrokenEqualsTest$Key@1, key type: BrokenEqualsTest$Key, node type: PSMS, cache type: SSMS).
java.lang.IllegalStateException
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.logIfAlive(BoundedLocalCache.java:304)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.evictEntry(BoundedLocalCache.java:1104)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.evictFromMain(BoundedLocalCache.java:818)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.evictEntries(BoundedLocalCache.java:710)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.maintenance(BoundedLocalCache.java:1722)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedPolicy$BoundedEviction.setMaximum(BoundedLocalCache.java:4114)
	at BrokenEqualsTest.equality_cache(BrokenEqualsTest.java:29)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:728)
	...
size? 1

</details>

**Comment by ben-manes** [comment]
Closing until you have feedback or questions that can continue the discussion.
