### ISSUE TITLE
Eviction function does not performed

### ISSUE THREAD

**Issue by Dingln** [ben-manes/caffeine#1357]
Hi, I am encountering an issue for eviction is not happened after the cache meets its max size and try to insert new value. Following is the class:

I created this class:
```java
public class LocalCache<K, V> {

    public Cache<K, V> cache;

    public LocalCache(int maxSize) {
        cache = Caffeine.newBuilder().maximumSize(maxSize).recordStats().build();
    }

    public LocalCache() {
        cache = Caffeine.newBuilder().recordStats().build();
    }

    public V get(K key, Function<? super K, ? extends V> mappingFunction) {
        cache.cleanUp();
        return cache.get(key, mappingFunction);
    }

    public V getIfPresent(K key) {
        cache.cleanUp();
        return cache.getIfPresent(key);
    }

    public void putAll(Map<K, V> map) {
        cache.putAll(map);
        cache.cleanUp();
    }

    public boolean containsKey(K key) {
        return this.cache.asMap().containsKey(key);
    }

    public long size() {
        return cache.estimatedSize();
    }
}
````

And the test
```java
    @Test
    public void testGetMultipleItems() {

        LocalCache<Integer, String> cache = new LocalCache<>(5);

        assertEquals(0, cache.size());
        String v1 = cache.get(1, v -> createValue("1"));
        String v2 = cache.get(2, v -> createValue("2"));
        String v3 = cache.get(3, v -> createValue("3"));
        String v4 = cache.get(4, v -> createValue("4"));
        String v5 = cache.get(5, v -> createValue("5"));
        cache.getIfPresent(3);
        assertEquals(5, cache.size());

        for (int k = 6; k < 30; k++) {
            int finalK = k;
            cache.get(k, v -> createValue(finalK));
        }
        CacheStats cacheStats = cache.cache.stats();
        System.out.println(cacheStats.hitRate());

        assertEquals(5, cache.size());
        assertEquals("3_", cache.getIfPresent(3));
    }
```

As you could see, the key 3 still has the value after the for loop, and actually, during the for loop which should add new entries for key 6 to 30, but they are never reflected in the cahce.

Could you help to review this and guide me if I need to change some implementation?

Thanks for your help!

**Comment by ben-manes** [comment]
Caffeine's eviction policy takes into account the recency and frequency of an item. In your case, `3` has a higher frequency so it is preferred to keep. The cache may evict new arrivals in favor of frequently used ones to maximize the hit rate based on what is has observed in the recent past. Your test is similar to the [glimpse](https://github.com/ben-manes/caffeine/wiki/Efficiency#glimpse) workload which scans over a data set, which pollutes and flushes LRU. Caffeine's policy is probabilistic and may be modified across releases, so you should avoid tests that make strong assumptions as to what it decides to retain.

As an aside, you should prefer to use `Caffeine.executor(Runnable::run)` to disable async eviction or use Awaitility assertions instead of ample usage of `cache.cleanUp()`, which performs a locking operation so it may serialize your calls. The cache's logic is very quick but we don't how expensive a callback to user code, like listeners, might be so we default towards minimizing the response latency by making work asynchronous when possible.

**Comment by Dingln** [comment]
Thanks!

I also found that in some cases when going to this line
`        assertEquals(5, cache.size());
        assertEquals("3_", cache.getIfPresent(3));`
the cache size became 6 and failed the test.
I am wondering if this is expected and how I can avoid this?

**Comment by ben-manes** [comment]
The `executor(Runnable::run)` should resolve that. Otherwise you have a race condition as the new item was added, eviction scheduled, but its execution has not yet started by the time you test asserts. By disabling async eviction there are no other threads in-flight, so you won't see it temporarily exceed the maximum in your unit test.

**Comment by Dingln** [comment]
Thanks ben!
