### ISSUE TITLE
Adding expiration dates different from #expireAfterWrite; saving memory (in developer situations)

### ISSUE THREAD

**Issue by coderFlameyosFlow** [ben-manes/caffeine#1378]
Hello, Thanks for checking this out.

I have an issue where sometimes I must do:
Map<String, Map<String, Long>>

Now I've switched to guava/caffeine to try eliminate this by having 'ticked' keys.
Although I still need to use Cache<..., Cache<..., ?>> (where ? doesn't matter because of expiration of keys)

and making a method to put(K, V, ? extends TemporalAmount) where TemporalAmount (such as Duration) would tick the key and override the default expiration after write of Caffeine#expireAfterWrite to save unnecessary allocations to memory and improve readability of handwritten code.

I've come here to see if there's another way to get around this or do I have to create a PR?
Thanks.

**Comment by ben-manes** [comment]
I'm not sure that I understand, but are you asking for variable expiration?

```java
cache.policy().expireVariably().orElseThrow()
    .put(key, value, duration);
```

There are a few other [feature-specific methods](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/com.github.benmanes.caffeine/com/github/benmanes/caffeine/cache/Policy.VarExpiration.html) you might review as well. This requires using `expireAfter(Expiry)`, where that `put` overrides to pass in your duration instead of querying the `Expiry` for it.

**Comment by coderFlameyosFlow** [comment]
> I'm not sure that I understand, but are you asking for variable expiration?
> 
> ```java
> cache.policy().expireVariably().orElseThrow()
>     .put(key, value, duration);
> ```
> 
> There are a few other [feature-specific methods](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/com.github.benmanes.caffeine/com/github/benmanes/caffeine/cache/Policy.VarExpiration.html) you might review as well. This requires using `expireAfter(Expiry)`, where that `put` overrides to pass in your duration instead of querying the `Expiry` for it.

Yes this is actually what I'm looking for. Thanks :D
