### ISSUE TITLE
Caffeine + jcache - multiple threads on cache create cause CompletionException: javax.cache.CacheException: Cache cache-forever already exists

### ISSUE THREAD

**Issue by enigma1510** [ben-manes/caffeine#142]
Noticed an issue in one of our stress environments, where multiple requests being made to a method annotated with @CacheResult(cacheName = 'xxx') results in the CompletionException: javax.cache.CacheException: Cache cache-forever already exists.  

The following Groovy Junit Test reproduces 100% for me.

`
@CompileStatic
class CacheExampleTest {

    @Test
    void testCacheCreateDeluge() {

        Injector injector = Guice.createInjector(new AbstractModule() {
            @Override
            protected void configure() {
                install(new CacheAnnotationsModule())
            }
        })
        CacheExample cacheExample = injector.getInstance(CacheExample)

        List<CompletableFuture> futures = []

        ExecutorService executorService = Executors.newFixedThreadPool(5)

        (1..5).each {
            futures << CompletableFuture.runAsync({ cacheExample.getDirectCached() }, executorService)
        }

        CompletableFuture.allOf(futures.toArray(new CompletableFuture[futures.size()])).join()
    }

    @Singleton
    private static class CacheExample {

        int invocations = 0

        //'cache-forever' is not defined so caffeine will create a default, non-expiry cache
        @CacheResult(cacheName = 'cache-forever')
        int getDirectCached() {
            ++invocations
        }
    }
}

`

Complete output:

Feb 10, 2017 3:44:14 PM org.jsr107.ri.annotations.DefaultCacheResolverFactory getCacheResolver
WARNING: No Cache named 'cache-forever' was found in the CacheManager, a default cache will be created.
Feb 10, 2017 3:44:14 PM org.jsr107.ri.annotations.DefaultCacheResolverFactory getCacheResolver
WARNING: No Cache named 'cache-forever' was found in the CacheManager, a default cache will be created.
Feb 10, 2017 3:44:14 PM org.jsr107.ri.annotations.DefaultCacheResolverFactory getCacheResolver
WARNING: No Cache named 'cache-forever' was found in the CacheManager, a default cache will be created.
Feb 10, 2017 3:44:14 PM org.jsr107.ri.annotations.DefaultCacheResolverFactory getCacheResolver
WARNING: No Cache named 'cache-forever' was found in the CacheManager, a default cache will be created.
Feb 10, 2017 3:44:14 PM org.jsr107.ri.annotations.DefaultCacheResolverFactory getCacheResolver
WARNING: No Cache named 'cache-forever' was found in the CacheManager, a default cache will be created.

java.util.concurrent.CompletionException: javax.cache.CacheException: Cache cache-forever already exists

	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1629)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: javax.cache.CacheException: Cache cache-forever already exists
	at com.github.benmanes.caffeine.jcache.CacheManagerImpl.lambda$createCache$0(CacheManagerImpl.java:96)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1877)
	at com.github.benmanes.caffeine.jcache.CacheManagerImpl.createCache(CacheManagerImpl.java:94)
	at org.jsr107.ri.annotations.DefaultCacheResolverFactory.getCacheResolver(DefaultCacheResolverFactory.java:73)
	at org.jsr107.ri.annotations.AbstractCacheLookupUtil.createCacheResultMethodDetails(AbstractCacheLookupUtil.java:281)
	at org.jsr107.ri.annotations.AbstractCacheLookupUtil.getMethodDetails(AbstractCacheLookupUtil.java:190)
	at org.jsr107.ri.annotations.AbstractCacheLookupUtil.getCacheKeyInvocationContext(AbstractCacheLookupUtil.java:72)
	at org.jsr107.ri.annotations.AbstractCacheResultInterceptor.cacheResult(AbstractCacheResultInterceptor.java:49)
	at org.jsr107.ri.annotations.guice.CacheResultInterceptor.invoke(CacheResultInterceptor.java:49)
	at CacheExampleTest$_testCacheCreateDeluge_closure1$_closure2.doCall(CacheExampleTest.groovy:33)
	at CacheExampleTest$_testCacheCreateDeluge_closure1$_closure2.call(CacheExampleTest.groovy)
	at groovy.lang.Closure.run(Closure.java:507)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1626)
	... 3 more

**Comment by enigma1510** [comment]
Meant to include... tested with 2.3.1 and 2.3.5.

A few more tests runs, and sometimes it does pass... but most of the time if fails with the above.

**Comment by ben-manes** [comment]
Unfortunately this is a limitation of JCache and the RI's annotation providers. `CacheManager` does not provide a `getOrCreate` cache method. 

The `createCache` method is documented as,
```java
* @throws CacheException if there was an error configuring the {@link Cache},
* which includes trying to create a cache that already exists.
```

The `DefaultCacheResolverFactory` uses a racy `getCache` then if null then `createCache`. If multiple threads call into it they will result in an exception thrown. The proper solution would be for the factory to synchronize on its own lock in a double-checked locking fashion.

I had noticed this myself, but a provider is not supposed to implement the annotations. It is a bug in the RI that affects Guice and CDI (as Spring has their own) for framework integration. Unfortunately the annotations are also racy by not supporting a blocking memoization, so multiple threads could compute for the same key.

@jerrinot has been the biggest advocate in pushing for fixes to these issues. I think @vbekiaris is now trying to work through some of these issues. Perhaps one of them can help resolve this.

**Comment by cruftex** [comment]
> I had noticed this myself, but a provider is not supposed to implement the annotations. It is a bug in the RI that affects Guice and CDI (as Spring has their own) for framework integration.

The RI, as it is designed by the JCache spec leads, isn't meant to be production ready or thread safe.

> CacheManager does not provide a getOrCreate cache method.

The JCache standard is vague about a cache's life cycle. In case of distributed or persistent caches, caches would be created only once, probably by the administrator or some initialization routine. The `createCache` method is meaningless in this context. I suspect that the actual routine in the RI is just for the matter that things work OOTB for the TCK test cases, which need to run without prior configuration, but actually shouldn't be a real implementation reference per se.

A `getOrCreate` method, IMHO, isn't the solution, because it gets even more unclear who actually is controlling the cache life cycle. Would a `getOrCreate` method need to check that the requested configuration fits?

> The proper solution would be for the factory to synchronize on its own lock in a double-checked locking fashion.

Exactly. Alternatively all caches could be created first, instead of being initialized lazily.

This bug affects every JCache implementation and should be reported against guice.

**Comment by ben-manes** [comment]
The RI cache is not production quality, but the annotation RI is meant to be used. This has been stated by the Greg in multiple contexts. The bug is not Guice's, but the annotation processors.

**Comment by enigma1510** [comment]
After reviewing the annotation RI code, I realized this race condition only happens for caches unknown to the CacheManager (or unspecified in the config for Caffeine).  I had one such cache that was relying on the cache forever defaults.

As a workaround, I was able to declare "caffeine.jcache.cache-forever: {}" in the config and this race condition no longer happens.

Thanks for the quick response Ben.

**Comment by cen1** [comment]
Sorry for necro, just some more info for the sake of the debate. This is indeed a bug in `cache-annotations-ri-cdi` (not in the actual reference impl) for caches that have no config and need to be created on the fly. I'd say you shouldn't have such a cache in any serious code but anyway..

On the nose solution is to make
```
public CacheResolver getCacheResolver(CacheMethodDetails<? extends Annotation> cacheMethodDetails)
```
synchronized since this is the method that creates a cache on miss. Without even delving too deep into the call stack this is probably an unwanted performance hit.

The **proper** fix for this issue is _probably_ to do annotation scan on CDI context init and create all unknown caches before context is fully set up. Whether this is the responsibility of `ri-cdi` or the integrator is another matter. I might take a look at this upstream when I have nothing better to do.
