### ISSUE TITLE
Why BoundedLocalCache:doComputeIfAbsent allocates unnecessary single element arrays?

### ISSUE THREAD

**Issue by jandam** [ben-manes/caffeine#146]
Is there any reason to allocate single element arrays? They can be replaced with local variable.

@SuppressWarnings("unchecked")
    V[] oldValue = (V[]) new Object[1];
    @SuppressWarnings("unchecked")
    V[] newValue = (V[]) new Object[1];
    @SuppressWarnings("unchecked")
    K[] nodeKey = (K[]) new Object[1];
    @SuppressWarnings({"unchecked", "rawtypes"})
    Node<K, V>[] removed = new Node[1];

RemovalCause[] cause = new RemovalCause[1];

**Comment by ben-manes** [comment]
The reason is because the array is populated inside of the lambda and evaluated outside. Due to the implicit final restriction, a variable would not be allowed by the compiler. Therefore we need a final variable that we can mutate to work around this language limitation.

Most often you'll see people use an `AtomicReference` in that case, then though it doesn't cross a thread boundary. That's more expensive as it adds memory barriers and object overhead that may be harder for the JIT to eliminate. By using an array we can hope its more likely to be stack allocated by escape analysis.

Technically these arrays could be combined with careful indexing. I'm not sure how beneficial that would be if (a) the arrays are escaped to the stack, (b) computations are rare due to the optimistic lookup. So for simpler code in a complex method, I've kept them individual for now.

**Comment by jandam** [comment]
Thank you for fast reply. I missed lambda expression.

**Comment by Maaartinus** [comment]
You could allocate a single bean instead of the many arrays. Assuming, you declare a single class for all usage places, some fields would be left unused somewhere, but the total number of allocated bytes could still be lower than when using arrays. The code would be shorter, maybe even nicer, but that's a matter of taste.
