### ISSUE TITLE
Question: Is it possible to force refresh before answering it (with refreshAfterWrite)?

### ISSUE THREAD

**Issue by rkluszczynski** [ben-manes/caffeine#147]
Hello,
I have started to use CaffeineCache which integrates with spring really nice. After reading the documentation I have got use case, that I do not found nice way to handle.

What I want to achieve:

- set two-leyered cache for endpoint response,
- first, short-lived cache (from 10 seconds up to several minutes max) should always contain up-to-date value wrt cache time,
- second, I called it "fallback cache", should works only after expiration of short-lived cache and in problems with obtaining data from external database (expiration duration is counted in hours),
- additionally it would be nice to populate "fallback cache" just before it expires.

It is really rarely that endpoint response is longer then 3s. 

The closest solution I have came up using CaffeineCache would be with specification: *refreshAfterWrite=15s,expireAfterWrite=3h*. It is almost good, but the problem is that *refreshAfterWrite* first response with old data and then refreshes it.

In this example, assuming request is called again 2h later, endpoint will answer with 2 hour old value before refreshing it, even when database is working correctly. This one request is unfortunately no go for us. 

Is there some way to force refresh before response?

Maybe you have some suggestions how to handle that differently? At the moment I've ended up with two cache instances and implementation of Spring's value loader.

If that is not the place for such questions, sorry for that.

Kind regards,
Rafal Kluszczynski

**Comment by ben-manes** [comment]
If you use a `CacheWriter` then I think you can achieve your goals. Lets assume you're using the API directly, as I am less familiar with Spring.

Cache 1
 - Configured with `expireAfterWrite` of 1 minute
 - `CacheWriter#delete` pushes the entry into cache 2 if `RemovalCause` is expired.
 - `CacheLoader#load` fetches from the db. If an error occurs, it fetches from cache 2 and verifies that the timestamp is in an acceptable range. If not, returns null or throws exception.

Cache 2
 - Configured with `expireAfterWrite` of 3 hours

The only flaw is the extra expiration check in the loader. This is because expiration a fixed time period and not handled by a dedicated thread, so it may be delayed until the next access or maintenance cycle. The algorithmic design for variable expiration is flushed out ([slide 10](https://docs.google.com/presentation/d/1NlDxyXsUG1qlVHMl4vsUUBQfAJ2c2NsFPNPr2qymIBs)) but I haven't gotten around to implementing it yet. (Alternatively, you might prefer to use an external fallback cache like Redis so that responses across servers is cached)

Do you think this solution would work for you?

**Comment by rkluszczynski** [comment]
@ben-manes Hello, thanks a lot for your suggestion. I think I will try your way:) I'm also thinking about getting rid of spring abstraction. Today, I have managed to do some performance tests between version with only cache 1 and first attempt with second cache implementation (based on Spring's value loader). 

Definitely have still something to work on, because request times have increased based on Apache Bench percentiles.

I will let you know about results next week. Thanks a lot for your help!

Kind regards,
Rafal Kluszczynski

**Comment by ben-manes** [comment]
Closing as this is a month old and I hope you've found a nice solution. Please re-open if there were issues or you have suggestions. Thanks!

**Comment by VytautasSer** [comment]
Hi, 

Would you share your solution?

 I'm also trying to figure out same thing. Sad that there is no out of the box feature like this. I also saw another post that it should be possible to do with CacheWriter somehow. Thanks
