### ISSUE TITLE
Array keys don't work

### ISSUE THREAD

**Issue by Valloric** [ben-manes/caffeine#149]
Testcase:

```java
@Test
public void testByteArray() throws Exception {
  Cache<byte[], String> cache = Caffeine.newBuilder().build();

  byte[] key1 = new byte[] {5, 10};
  byte[] key2 = new byte[] {5, 10};

  cache.put(key1, "foo");
  assertThat(cache.getIfPresent(key2)).isNotNull();
}
```

This is of course because of a design mistake in Java where `equals()` on arrays is the same as `==` (identity comparison). Java has `Arrays.equals(array1, array2)` to work around this, but generic code has to special-case arrays.

Could Caffeine be changed to special-case arrays as well? Otherwise array keys plain don't work.

**Comment by ben-manes** [comment]
It would require either a wrapper or forking `ConcurrentHashMap` to support custom equivalences. I'm not keen on forking, as that leads to a desire to do further optimizations. Then it will be harder to support value types and track other fixes.

I think the best option is a wrapper in user code. When value types land that might make it very low overhead option.

**Comment by Valloric** [comment]
A wrapper around the raw array would indeed work, but it comes with big drawbacks: first, it's an extra layer of indirection. Instead of derefing a pointer, the CPU now needs to deref a pointer to the object and then deref the array pointer within it. This two-layer indirection screws up memory prefetching because while modern CPUs are good at prefetching data behind a one-layer indirection, two layers doesn't work nearly as well.

And on top of this, there's the extra space overhead of another pointer. We're moving away from String keys to `byte[]` compressed keys precisely to reduce RAM usage, and the extra 8 bytes for the pointer are painful when the average compressed byte array is 9 bytes. It doubles the size.

Whether you special-case arrays to work or not is up to you of course, but even if you don't, you might want to at least throw an exception from `build()` if the key is an array to prevent people from blowing their foot off (we almost did).

**Comment by ben-manes** [comment]
I think the cache should feel like a natural extension to the Java Collections Framework and inline with Effective Java. That of course means to prefer collections over arrays, etc. It does put the onus on the developer to follow best practices, such as using static analyzers to catch these types of mistakes.

Due to erasures we can't detect the type, so failing isn't an option. If the builder required a type literal then we'd know at the cost of a new class per usage. But I don't think that it carries its weight.

The byte[] key/value starts getting into the territory of offheap caches, e.g. [ohc](https://github.com/snazy/ohc), and [Apache Mnemonic](https://github.com/apache/incubator-mnemonic).

The [Compact String JEP](http://openjdk.java.net/jeps/254) might help your particular case.

I understand the performance penalty, but its a platform problem that will hopefully be solved in jdk10. I know that isn't a satisfying answer. Its just there is no good generic solution until then.

**Comment by Valloric** [comment]
We'll just go with the wrapper approach; hopefully it should be enough.

Thank you for your time and for considering this though!

**Comment by Maaartinus** [comment]
@Valloric 

> This is of course because of a design mistake in Java where `equals()` on arrays is the same as `==`

I wouldn't call it a mistake. Arrays are mutable and for mutable objects, identity equals makes more sense. Though I agree that content-based equals would be handy quite often.

> you might want to at least throw an exception from build() if the key is an array

There are legitimate uses for arrays compared by identity. I can't recall a real use case, nor can I construct a realistic example, but some heavily optimized code can need them.

**Comment by ben-manes** [comment]
One could argue `weak keys` would make sense for that case, since they use identity. Retaining a array key that has no other references makes little sense, as it would require walking the keySet to rediscover. But, similarly, some want weak keys with normal equivalence to create an interner.

Perhaps lobbying Doug Lea (via `concurrency-interest`) would be your best bet. The Collections Framework probably disfavored the complexity for non-concurrent cases, as custom maps abundant. For the concurrent case, especially for `ConcurrentHashMap`, a custom or fork are discouraged. While I don't think he'd go for it, I do think that's where the feature should reside and Caffeine would expose it.
