### ISSUE TITLE
Possibly convert AsyncLoadingCache to use CompletionStage instead of CompletableFuture

### ISSUE THREAD

**Issue by dpratt** [ben-manes/caffeine#15]
It would seem to logically and architecturally make the loading part of an AsyncCache populate itself from a CompletionStage instead of a CompletableFuture. CompletionStages are designed to be the 'read' side of a logical promise. There are a few concurrency bridging libraries (the most prominent of which is the Scala Java 8 compatibility layer) that map this properly - and in fact you cannot convert a Scala Future to a CompletableFuture, rather only a CompletionStage. 

Of course, you can always bypass this by creating a new, unfulfilled CompletableFuture and completing it with the result of the scala future, but this just seems like a lot of overhead.

**Comment by ben-manes** [comment]
Let me first say that I am open to API changes, as getting the right API that uses new language features is hard. I have a minor fixes planned for v2 and had hoped to hear more concerns like this one before I bit the bullet and made API updates.

If CompletionStages had all of the read side properties I would have used it. It is actually only the fluent chaining capabilities and lacks the ability to inspect the result (isDone, getNow, etc). At first this seems fine from an interface-impl theology by viewing the toCompletableFuture() bridge as an escape hatch. Unfortunately that cannot be relied upon due to being optional (`@throws UnsupportedOperationException if this implementation does not interoperate with CompletableFuture`).

This is not just annoying for users who want to bridge frameworks. Its also a problem for the LoadingCache view, which provides the convenience of a synchronous api and avoids duplicating various methods (size, invalidation, etc). It did not seem to be a better API choice to have the view break if a stage couldn't be converted to a future. If that was allowed, it may also be surprising for users who are combining libraries and don't realize the incompatibility choice they made.

The concurrency-interest threads on [why CompletionStage was introduced](http://mail.openjdk.java.net/pipermail/core-libs-dev/2013-July/018859.html) does not provide a lot of guidance. Prior to its introduction, CompletableFuture was said to be a low-level class that others should build abstractions above that match their policies. A subclass is allowed to disable features and JDK9 introduces a copy() method for safe publication to avoid obtruding the original's value. There is very little said about how to use CF/CS from in api design.

The interop approach you mentioned is ugly, but an explicit bypass in user code so they know that obtruding the result (e.g. cancel) won't work. It doesn't break the principle of least astonishment and lets the APIs work as expected. The bridge code is short and isolated, and the cache itself can be hidden behind a custom facade to avoid leaking CompletableFuture if desired. An alternative is to accept CompletionStage, produce CompletableFuture, and try to perform the bridge code internally. That would have some surprising side effects too, so I don't think it would be an ideal API either.

Given that rational, what do you think would be the best choice going forward?

**Comment by ben-manes** [comment]
@dpratt 

I'm ready to focus on revamping the APIs for v2 and fix any mistakes or gaps. Please advise on this specific issue and any other commentary on the other APIs.

**Comment by dpratt** [comment]
This is very much on my radar - I don't want to delay you, but would a discussion early next week derail you?

**Comment by ben-manes** [comment]
That would be great, thanks!

I'm slowly flushing out the simulator to explore alternative eviction policies. That will take some time and, other than api improvements, nothing else is currently planned for v2.

**Comment by ben-manes** [comment]
I am going to begin the code phase for v2 this week. I spent a lot of time researching eviction policies, eventually designing a new one that has an optimal hit rate, low footprint, is O(1), and is fairly simple. The integration work should be relatively straightforward. At that point I'll be pretty excited to get it out the door, so having a checklist of what else needs improvements would help round out that release.

**Comment by cruftex** [comment]
Hey, just got a ping by bens' post. I missed that here are some decent thoughts on async cache APIs....

Here is what I currently have in mind:

From a "light, simple and high performance" perspective I consider the CompletableFuture/CompletionStage as an impedance mismatch. The CompletionStage interface is intended for chaining tasks that are time consuming. OTOH it is the nature of the cache, that the task should not be time consuming (remark: some caches are always time consuming, too....). 

In the hope that the cache is doing its job, is it possible to implement the critical hit path efficiently? Idea: In the hit case return a CompletionStage that executes non-async methods within the calling thread. Only if the async methods are used the heavy CompletableFuture "engine" is needed. If this is feasible (by defined semantics), then the CompletionStage with a custom implementation for the cache use case would be preferable.

If the cache API guarantees that there is always a Future, then declaring only CompletionStage would be not perfect in terms of API design. What actually is missing (any discussion pointers here?) is an interface that implements both, the CompletionStage and the Future. But no one stops a cache API to do this. As a gut feeling I would stay away from returning CompletableFuture in a cache API, since it is an implementation, not an interface.

More progressive thoughts:

All interfaces I have seen yet, always have one operation and one result or one result interface. What about:

````java
interface CacheOp<K,V> {

  CacheOp<K, V> get(K key);
  CacheOp<K, V> getIfPresent(K key);
  CacheOp<K, V> put(K key, V value);
  ...
  CacheOp<K, V> atomic(boolean f);
 

  CompletionStage<Map<K, V>> executeAsync();
  Map<K, V> execute();
  
}
````

Usage:

````java
    Cache.operation()
      .get(47)
      .get(11)
      .put(12, 34)
      .atomic(true)
      .executeAsync()
      .thenApply(....);
````

**Comment by ben-manes** [comment]
Thanks for the thoughts Jens.

While its unfortunate that CF is not an interface, the impact is thankfully not high. For testing, such as mocks, its very easy to control a CF by either supplying an executor or using the constructor and obtruding the value. 

I think that issue between CF, CS, etc. are about integration between different async operators. A proliferation of CS variants requiring integration between each type might be more cumbersome than standardizing on CF, which all have to integrate with regardless. The slow adoption of Java 8, wide number of ad hoc async operators (Rx, Guava, Twitter's, etc), CS compatible futures (Scala's), and lack of a hint by the JSR makes this all very confusing.

By itself CS is not enough for the cache, because it might accept a future rather than wrap synchronous code. For example the value might be the result of composing a chain of async operators across different web services. If the cache was only accepting synchronous computations and exposing a Future, then your idea of a custom CS might work out well. However I think computing futures is a valuable use case as more frameworks adopt reactive APIs. At that point CF appears to be the best common future all need to interact with, hence the current AsyncLoadingCache interface.

I don't think composing multiple cache operations like your example shows will be a common pattern. I think that case might begin to lead into transactions, which becomes a messy discussion. I suspect the usage of being part of an [Observable](http://reactivex.io/RxJava/javadoc/rx/Observable.html) style chain might be more prevalent.

I should note that the compute time of a future is not incurrent by the cache, like it is for a synchronous compute. The value in the cache is a future, potentially in-flight on an Executor, so the cache operations themselves are low overhead. The details comes into handling errors, disabling size/expiration for in-flight futures, weighted size, removal listeners (discarding while in-flight), statistics, and bulk computation. The interface provides a convenient and correct abstraction rather than doing this ad hoc by caching futures manually.

**Comment by ben-manes** [comment]
The scala-java8-compat project [recently](https://github.com/scala/scala-java8-compat/pull/49) added support for `toCompletableFuture()`. The [future-converter](https://github.com/lukas-krecan/future-converter/) project supports Spring, Guava, and RxJava conversion. This removes the integration concern for the most popular alternative future libraries.

I think the remaining issue is how can the API be improved? What functionality is missing?

**Comment by ben-manes** [comment]
The scala-java8-compat project [recently](https://github.com/scala/scala-java8-compat/pull/49) added support for `toCompletableFuture()`. The [future-converter](https://github.com/lukas-krecan/future-converter/) project supports Spring, Guava, and RxJava conversion. This removes the integration concern for the most popular alternative future libraries.

I think the remaining issue is how can the API be improved? What functionality is missing?

**Comment by ben-manes** [comment]
The scala-java8-compat project [recently](https://github.com/scala/scala-java8-compat/pull/49) added support for `toCompletableFuture()`. The [future-converter](https://github.com/lukas-krecan/future-converter/) project supports Spring, Guava, and RxJava conversion. This removes the integration concern for the most popular alternative future libraries.

I think the remaining issue is how can the API be improved? What functionality is missing?

**Comment by ben-manes** [comment]
Closing due to lack of actionable feedback. Please reopen, or open a new issue, if you'd like to continue the discussion.
