### ISSUE TITLE
refreshAll feature for CacheLoader

### ISSUE THREAD

**Issue by tomaskolda** [ben-manes/caffeine#1536]
Is it possible to refresh keys also in a bulk way? Our scenario:

1. We are using getAll to fetch many keys at once. It is much faster, because the latency to our backend is high so loadAll is bringing us huge performance improvement.
2. We would like to avoid any slowdown when we need to expire all keys every N minutes. The only way to not block getAll is to use refreshAfterWrite. 
3. When we use refreshAfterWrite then getAll creates "reload" jobs one by one. That means getAll notices 1000keys are needed to be reloaded on background, but these are reloaded as single units thus bringing back our latency impact.

Is it possible to introduce something like reloadAll similar to loadAll?

**Comment by ben-manes** [comment]
The recommended approach is to use [refresh coalescing](https://github.com/ben-manes/caffeine/tree/master/examples/coalescing-bulkloader-reactor). What do you think?

The idea is to collect reload requests over a short time/size window and perform a batch request. This turns out to be very short and simple code if using a reactive stream library. The above example shows how to combine the libraries so that you can control the time window, the batch size, and the parallelism. The readme describes how you can do this for synchronous or asynchronous caches. Then in your application you would change to something like,

```java
var cache = Caffeine.newBuilder()
    .maximumSize(10_000)
    .expireAfterWrite(Duration.ofMinutes(30))
    .refreshAfterWrite(Duration.ofMinutes(10))
    .build(new CoalescingBulkLoader.Builder<Integer, Integer>()
        .mappingFunction(keys -> { ... })
        .maxTime(Duration.ofMillis(250))
        .maxSize(1_000)
        .parallelism(3)
        .build());
```

This works pretty well because the refreshes are optimistic reloads and user requests are not waiting on them. It is also common for applications to trigger it by one-offs lookups, rather than making an explicit batch load like `getAll`. From an implementation-side, it seemed a little messy and unintuitive to coordinate the batch calls correctly. For example, we would call `reloadAll` if defined, else individual `reload` if defined, else `loadAll`, else individual `load`. That means if `reload` was defined on the `CacheLoader`, we'd have to use the oldValue in order to honor that behavior but then opt out of bulk reloading if `loadAll` was present. I don't think users would find that very obvious and it leads overly complex code trying to wrangle these flows. So our conclusion in #7 is that refresh coalescing nicely side-stepped these issues, was more clear, and could lead to better performance by batching individual calls as well.

**Comment by koldat** [comment]
I was looking on that coalescing example before as well, but I think it will break totalLoadDuration statistics completely which I see very useful so we will need to redo metering in loader.

That reloadAll can have default function similar to loadAll,  but I understand your point. In my case I am always implementing only bulk api where single ones are just a call of bulk with one entry.

Anyway thank you for your explanation. Caffeine is my most favorite library. Especially async features of it! I will manage it in application code.

**Comment by ben-manes** [comment]
Definitely `reloadAll` could be a default function, it is just a bit of routing quirkiness if both `reload` and `loadAll` are user defined but not `reloadAll`. Then I think we'd have to honor the user's `reload` by individual keys and they'd be surprised to have lost out on the bulk behavior.

You can always add more statistics, e.g. have an actual total load duration versus a perceived. The ones we have are the minimal common ones, but others augment them with their own like the number of puts. I agree, its more work, but I think less then batching at the application level.

I'm going to close because, at least for now, I still feel like coalescing is the best solution. Thanks for asking, though, and I'm open to being proven wrong.

unrelated fyi if helpful, `CacheLoader.bulk(func)` is a convenience utility you might have seen but is easy to overlook.

and thanks for the kind words! 🙂
