### ISSUE TITLE
Caching large files

### ISSUE THREAD

**Issue by anhldbk** [ben-manes/caffeine#155]
Hi guys! 

I'm sorry if opening an issues is not a proper way to ask questions. But would you please tell me can I use Caffeine to cache large files? If yes, please let me know how Caffeine handle the files or I have to implement the logic behind. 

Thanks in advance!

**Comment by ben-manes** [comment]
Can you explain what you mean?

**Comment by anhldbk** [comment]
@ben-manes I'm sorry to ask the wrong question. 

> Caffeine provides an **in-memory cache** using a Google Guava inspired API.

My question is related to some kind of disk caches. Just wonder how to enhance `caffeine` with disk persistence.

**Comment by ben-manes** [comment]
There are persistent caches like DiskLruCache, MapDB, RocksDB. You could use Caffeine as an in-memory tier with disk as a second level. Alternatively, you could use Caffeine as the eviction policy with persistent keys and values. The loader and writer make it very flexible.

Other than fast warmup on a restart, disk caches have a history of being slow. Usually a remote cache like Redis provides a more efficient scheme. It's not a goal of this project and often isn't the best choice anyway.

**Comment by anhldbk** [comment]
@ben-manes Perfect! Gonna have a look at your suggestions. Thank you!

**Comment by anhldbk** [comment]
@ben-manes I'm sorry to bother you once again. But I'm reading about [RocksDB's Block Cache](https://github.com/facebook/rocksdb/wiki/Block-Cache). So RocksDB would be a good caching solution which supports in-memory & persistent caching, right?

**Comment by ben-manes** [comment]
I have not used RocksDB, but it sounds to be highly respected. Their [homepage](http://rocksdb.org/) highlights an article on using it for application data caching, but the policy work may be left to users who treat it as a key-value store. 

There were a few dedicated caching projects (Flashcache, EnhanceIO) but they seem to have been abandoned. Ideally there would be a project dedicated to that use-case, as often jack of all trade projects do them all poorly.

If you need something simple to deploy and embed, MapDB has a good reputation. I'm sure a little Googling would uncover a few other possible candidates.

I haven't used a persistent cache for a long time since usually other approaches are better for the type of applications Java lends itself to.
