### ISSUE TITLE
Rapidoid is missing in the benchmark

### ISSUE THREAD

**Issue by nmihajlovski** [ben-manes/caffeine#157]
Hi, it's been a while since we added Rapidoid to the benchmark suite, but I can't find it anywhere in the results.

**Comment by ben-manes** [comment]
Sorry, I haven't updated the benchmarks page since version 2.0. It takes time to setup in order to avoid other processes from stealing cpu time and skewing results. There hasn't been any major changes in Caffeine to warrant a new evaluation and, since it is a manual process that I pay for, it hasn't been a priority to rerun. Usually running on a local machine is good enough for spitball testing to find bottlenecks.

The main advantage is getting your cache into a set of JMH benchmarks which could aid you for in tuning. From there you can fork it off into your own set of benchmarks (e.g. as done by cache2k, collisions, kudu) so as not to be tied to my project. It is more of a starting point than an annual shoot-out like the [TechEmpower Benchmarks](https://www.techempower.com/benchmarks). If annual, you'd also want someone unbiased with authors providing recommendations, but otherwise unassociated.

**Comment by nmihajlovski** [comment]
OK, thanks for the quick response and for the clarification.
