### ISSUE TITLE
Is the version that supports JDK8 no longer updated?

### ISSUE THREAD

**Issue by beibeiGeng** [ben-manes/caffeine#1570]
Hi, we are still using JDK8 for business development, but the caffeine software that supports JDK version has not been updated for 3 years. Will there be any update for JDK8 in the future?

**Comment by ben-manes** [comment]
If there are critical bugs then we'll make a JDK8 release. Otherwise small bug fixes, features, or other improvements are not being actively backported. Thankfully Caffeine is just a fancy `ConcurrentHashMap` so it has very low surface area for compatibility or security issues. Using the older release is pretty safe (you can review the change log).

Note though that JDK8 reached end of public and premier support, so you won't receive security fixes unless you are an Oracle Extended Support customer or similar by another vendor. I believe usually those are kept private to paid customers, but some like RedHat or Corretto may be public but limited to supporting usages with their products. It's a little unclear, just know that it's a business risk.
