### ISSUE TITLE
Blocked when access one key inside another key's loader in same cache

### ISSUE THREAD

**Issue by jiming** [ben-manes/caffeine#160]
Hi Ben,

When I execute the following code, it just blocked. Is that designed for purpose, or a bug?

```
public class CaffeineTest {
    static Cache<String, String> cache;

    static {
        cache = Caffeine.newBuilder().expireAfterWrite(10, TimeUnit.DAYS)
                .maximumSize(100)
                .executor(Executors.newFixedThreadPool(5))
                .build();
    }


    public static String getString1() {
        return cache.get("getString1", s -> {
//                    return "string1" ;
                    return "string1" + getString2();
                }
        );
    }
    public static String getString2() {
        return cache.get("getString2", s -> {
                    return "string2";
                }
        );
    }


    @Test
    public void testCaffeineDeepAccess() throws Exception {
            System.out.println(getString1());
    }

}

```

**Comment by ben-manes** [comment]
Yes, recursive computations are not supported. In the JavaDoc it states,
> <b>Warning:</b> as with {@link CacheLoader#load}, {@code mappingFunction} <b>must not</b> attempt to update any other mappings of this cache.
...
@throws IllegalStateException if the computation detectably attempts a recursive update to this cache that would otherwise never complete

Internally, ConcurrentHashMap is stuck in a live-lock by spinning forever. In 2011 I advocated for this to fail fast and, while the fix was lost, the JavaDoc was changed to include a throws message. In 2014, I helped to more reliably detect it but that was not backported from Java 9 to an 8 release. See this StackOverflow [answer](https://stackoverflow.com/a/28845674) for a few links.

Interestingly, HashMap was deemed acceptable to perform recursive computations due to a lack of thread safety. However that fails due to internal resizing of the map caused corruption. I'm not sure if their fix was to restrict that or make the computeIfAbsent call handle it.

**Comment by ben-manes** [comment]
ahh, the HashMap corruption issue was only [fixed](https://github.com/netroby/jdk9-dev/blob/master/jdk/src/java.base/share/classes/java/util/HashMap.java#L1096) in JDK9 too.

For Caffeine, you can resolve this by using an async cache, the synchronous view, and the default (unbounded) executor. That breaks the recursion by inserting a future, executing it on another thread, and blocking.

**Comment by jiming** [comment]
Thanks!

**Comment by breandan** [comment]
In case anyone else encounters the error with `IllegalStateException`, I used this pattern and it seemed to fix the issue: 

```var cache = Caffeine.newBuilder()[...].buildAsync().synchronous()```

**Comment by ben-manes** [comment]
@breandan another, more complicated, approach is in the [FAQ](https://github.com/ben-manes/caffeine/wiki/Faq#recursive-computations) which can avoid using extra threads. It similarly performs the computation outside of the cache while adding a proxy value, but does the work on the calling thread rather than on a threadpool.
