### ISSUE TITLE
Striped ring buffer

### ISSUE THREAD

**Issue by anhldbk** [ben-manes/caffeine#161]
@ben-manes Would you please tell me what a striped ring buffer is? I've googled a lot but could not find any related definition.

**Comment by ben-manes** [comment]
A striped data structure means that it is replicated N times with a strategy at the top level to select the instance (usually hashing). For example Java 5's `ConcurrentHashMap` was striped into multiple hash maps (called segments) that each had a lock for writes. This allowed for concurrent writes if two threads were mutating different segments.

Similarly a striped lock (e.g. Guava's `Striped`) would be used to simulate a lock per key by hashing into an array of locks. There could be some loss due to hash collisions, but rarely and avoids other complexities.

Memcached can be thought of as a stripe of cache nodes using hashing to determine which to query from. When adding or removing nodes, a consistent hash can be used to find the right node regardless.

A striped ring buffer is merely an array of ring buffers with a hash to select which to insert into. Just like the above cases the write is an expensive operation if contended on so the stripe reduces this penalty. Unlike the above cases, we don't need to deterministically find the value again and can resize at will. This is done based on contention by using the strategy in Java's `LongAdder`, which extends `Striped64` - a stripe of counters. See [StripedBuffer](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/StripedBuffer.java) and [BoundedBuffer](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedBuffer.java) for implementation details.

**Comment by anhldbk** [comment]
@ben-manes Thank you.
