### ISSUE TITLE
Too many simple repetition of "multi put, multi get" results in immediate item eviction

### ISSUE THREAD

**Issue by masashi-sato-flect** [ben-manes/caffeine#1611]
Hi. When I executed the following code with Caffeine v3.8.1, I always encountered the situation where the secondary item put result in immediate eviction of the first item.

```JAVA
        Cache<Integer, String> cache = Caffeine.newBuilder()
        .maximumSize(1000)
        .evictionListener((Integer key, String value, RemovalCause cause) -> {
            System.out.println("Evicted " + key + " " + cause);
        })
        .build();

        int BATCH = 2;

        for (int i = 0; i < 10000; i = i + BATCH) {
            for (int j = i; j < i + BATCH; j++) {
                try {
                    System.out.println("Putting " + j);
                    cache.put(j, String.format("v%d", j));
                }
                catch (Exception e) {
                    System.out.println("Exception " + e);
                    break;
                }    
            } // end of for (j)
            for (int j = i; j < i + BATCH; j++) {
                try {
                    System.out.println("Geting " + j);
                    String s = cache.asMap().get(j);
                    if (s == null) {
                        throw new RuntimeException("Got null");
                    }
                    System.out.println("Got " + s);
                }
                catch (Exception e) {
                    System.out.println("Exception " + e);
                    break;
                }    
            } // end of for (j)
        } // end of for (i)
```

Example output:

```
Putting 5606
Putting 5607
Evicted 5596 SIZE
Evicted 5606 SIZE
Geting 5606
Exception java.lang.RuntimeException: Got null
```

I like to know how to mitigate this behavior.
Thanks.

**Comment by ben-manes** [comment]
The items don’t really differ in popularity so to the cache a newer arrival is as good as any other, if judging by the hit rate. In a scan like walking a db table it often has MRU characteristics. If the workload shows higher LRU behavior than the cache will learn and adapt, favoring to evict the least recently used entry. Since your test looks fairly equal there isn’t much insight for it to draw from, and the configuration defaults to start more aggressively rejecting new arrivals as more commonly desired in practice. Does that make sense?

**Comment by masashi-sato-flect** [comment]
Ah, yes. I really respect your opinion (and your deeply intricate consideration for Caffeine!). 
But please listen to a story of mine.

1. I'm deploying a Keycloak cluster, which includes Infinispan, which includes Caffeine (as a JVM heap memory storage).
2. At a customer's test, it requires to complete success of huge repetition of simple login. (I understand it is never realistic.)
3. It results in the access pattern as in this sample code.

I don't know you may have any interest for my situation. But I will grad to know any trick which avoids quick eviction after (reasonably) tedious access pattern.

**Comment by ben-manes** [comment]
The first half of this [article](https://highscalability.com/design-of-a-modern-cachepart-deux/) should explain in a bit more depth. You’ll see how it adapts to the pattern, where we adjust every ~10x max size accesses.

In your case that’s hard to help because it’s an artificial expectation by your client to assert certain cache behavior. They could just as well loop over users to pollute an Lru cache for a ddos attack.

Can you warm up with a workload that is very recency biased? The Corda trace we use is, for example. We don’t expose a knob to tune this since the cache figures it out, so user tests usually only assert usage behavior not hit rate expectations. I don’t think your client should have an assumption about the hit rate in a short test.

**Comment by masashi-sato-flect** [comment]
Anyway, I really appreciate your quick response. Reply from the original author was quite helpful for me.

**Comment by masashi-sato-flect** [comment]
I understand this behavior was by design.
