### ISSUE TITLE
Oldest Eviction option

### ISSUE THREAD

**Issue by ee-usgs** [ben-manes/caffeine#1627]
For size limited caches, it would be nice to be able to specify 'oldest' as an eviction option.  This is really the simplest type of cache, but sometimes that is the strategy that is needed and w/o that option, I need to bring in some other cache (Guava) to use for that situation.

Use Case:  From my server, I provide download 'receipts' after a download is completed w/ basic metadata of how many rows of data should be in the download so a user can verify they have the complete download.  So the user downloads a file, and they get a unique ID in the header and the downloaded file, then they can request /download-receipt/UNIQUE_ID to get how many rows should have been in the file.

I can't keep the receipts in memory forever, so I use Caffeine as in memory storage.  I want to limit the total number of receipts in memory so I don't use up memory, but when I have too many, I want to ensure I delete the oldest one, since user's should not have need to grab an old receipt or grab it more than once.  I don't want a user to be able to force a receipt to stay in memory by continually requesting it.

I could easily use a different cache, but I have other needs for which Caffeine is a good fit, so I already have it in my code base.

**Comment by ben-manes** [comment]
The oldest would be a FIFO cache (insertion time). In that case you could use a bounded, synchronized `LinkedHashMap` to maintain the size bounding and on eviction make a callback to the concurrent map so that reads stay fast. I believe this would be a small amount of glue code and avoids feature creep in this library for special cases.

The size-based eviction tries to maximize the hit rate, so it adjusts by the frequency / recency characteristics. That often means early eviction because many new arrivals are pollutants (aka one-hit wonders). In a weighted cache where entries vary in their size, e.g. by byte size, then inserting an entry that exceeds the total capacity can just be evicted immediately instead of clearing it entirely. A constraint like FIFO might reasonably disable that, or not, depending on one's opinion of how authoritative the cache is. Similar challenges come up when others want to disable eviction of certain entries or inspect their entry for a domain-specific "priority score", etc to instruct the decision making process. It gets messier and rigid in order to avoid breaking someone's business logic whereas today it is simpler policy bounding where we try to make good optimization choices.

In your particular case, you might run into problems if you have multiple servers without sticky sessions. The next request could be load balanced to a different instance with other cached content. I can't tell if that would be problematic or not, so just fyi.

**Comment by ben-manes** [comment]
Closing due to lack of feedback and that I think the workaround is preferable.
