### ISSUE TITLE
Disable stats recording for a single get() request

### ISSUE THREAD

**Issue by wkuranowski** [ben-manes/caffeine#164]
Hi!

I am using Caffeine with async cache in the following scenario:

1. optionalValue = cache.synchronous().getIfPresent(url);
2. result = doSomething(param, param, optionalValue);
3. if (result ==true && optionalValue == null) cache.get(url);

I would like to disable stats for step 3, because I just want to asynchronously populate cache without incrementing miss counter. I also tried a refresh() method, but it is not atomic...

Is there any way to atomically and asynchronously populate cache without incrementing miss counter? I don't need the result of that operation.

Regards!

**Comment by ben-manes** [comment]
I'd prefer not exposing low-level details like that as it confuses the API. I think there are workarounds, but you may feel they are hacky.

The `asMap()` view does not record stats for non-computing methods (@yrfselrahc might remember the reasons why / rules for Guava). Caffeine does record them for computing methods to capture loads, and whether that was the correct choice depends on @yrfselrahc's view. Guava's recent addition of these methods doesn't provide insight since they sporadically record stats, so it wasn't a consideration when implemented.

That means you should be able to use `cache.synchronous().asMap().get(url)` without stats recorded, If you supply the `StatsCounter` and retain a reference, you could update it on the `else` condition. That way (1) does not record and (3) always does,

Another solution might be to use a custom `StatsCounter` with a thread local flag to disable it temporarily. That's a more awkward solution, imho.

**Comment by wkuranowski** [comment]
What do you think about adding similar method to getQuiet from Ehcache 2?

**Comment by ben-manes** [comment]
I think that approach has a poor power-to-weight ratio. A simpler solution is to supply a custom `ConcurrentStatsCounter` and decrement the miss counter in step three. The counters are merely `LongAdder` instances, so fairly simple. If you are proxying the stats (e.g. to yammer metrics) you might just have a compensating counter that is decremented and report the sum.
