### ISSUE TITLE
Use caffeine to swap objects to disk

### ISSUE THREAD

**Issue by piegamesde** [ben-manes/caffeine#168]
Last year, I had [this](https://stackoverflow.com/questions/40705185/java-cache-objects-to-disk) problem where I was searching a way to swap certain objects to disk. Now I have a similar situation, only that the objects in question are mostly images (measured by size).

Can you please have a look at it and tell me if this is possible with your library, and perhaps even how to do it? I started reading the wiki but I'm new to caching and such and thus can't judge this by myself.

**Comment by ben-manes** [comment]
Yes and no.

This library is strictly an in-memory cache. It can be integrated with another tier easily, but does not try to solve those. If you have a disk cache (e.g. [DiskLruCache](https://github.com/JakeWharton/DiskLruCache)) then you can use a `CacheWriter` to evict into that cache, a `CacheLoader` to fetch through it, and a `Weigher` to provide an entry size.

If you want an all-in-one solution then the convenience will require using libraries that offer much less performance (but that might be acceptable). [MapDB](http://www.mapdb.org/) is a disk cache with on-heap cache. Ehcache supports multiple tiers, though v2 still sounds more robust than v3. I think some of the distributed caches (infinispan, ignite, etc) offer a disk tier, but that might be too invasive for your needs.

Disk caches used to have a negative performance impact (spinning disks) and everyone switched to network attached caches (memcached). Flash has reduced that penalty, but mostly to reduce costs of memcached instead of reintroducing local disk caches. So that capability is not in much demand these days, which is why you won't find to many active projects with support. I'd probably try MapDB first, later pairing it with Caffeine if its on-heap performance wasn't good enough.

**Comment by piegamesde** [comment]
Thank you. With its [overflow mechanics](https://jankotek.gitbooks.io/mapdb/content/htreemap/), it seems to match my needs. If you care about StackOverflow, you can get 25 easy credits by answering my question with a MWE (otherwise I'll do it once I know the library).

**Comment by ben-manes** [comment]
You might consider rocksdb in lru mode and it’s [Java bindings](https://github.com/facebook/rocksdb/wiki/rocksjava-basics). I don’t think any of the pure Java disk caches are actively maintained anymore but the distributed caches with them might minimally support if bugs were found.

Some users let Caffeine act as the cache while storing the values on disk. VMWwre’s Robusto would dynamically move the value to the right tier by inspecting our metadata. I’ve just used it for a disk scratchpad to optimize network data sync through async caching, pinning, weights, etc. There’s different considerations for optimizing each tier so this can work but is not always ideal.
