### ISSUE TITLE
Can I use Caffeine as a Key level lock?

### ISSUE THREAD

**Issue by jiming** [ben-manes/caffeine#174]
Dear Ben,

Here is the code

```
Cache<Object, Object> cache = Caffeine.newBuilder()
        .expireAfterWrite(0, TimeUnit.NANOSECONDS)
        .build();
cache.get("key1", o -> "do some work synchronized for key1");

// now, the lock for key1 released, because the expiredAfterWrite is 0
```

does this work?

Thanks!
Jiming

**Comment by ben-manes** [comment]
Yes, but this would not be advisable. It would be equivalent to using `ConcurrentHashMap` with `computeIfAbsent` and always returning `null`.

The problem is that the hash table locks the bin, which can be coarser than a single entry though it is often one-to-one. The table won't increase the number of bins until it is populated, so the amount of concurrency is limited by the initial count. This will also have more overhead than a simpler scheme.

What you want is called `lock striping` and can be done using a simple array of locks:
```java
Lock[] locks = new Lock[1024];
Arrays.setAll(lock, i -> new ReentrantLock());
Lock lock = locks[key.hashCode() % 1024]; // or & (locks.length - 1) if power-of-two sized
lock.lock(); ... lock.unlock();
```

One can use a dynamic stripe if using a weakValued `Cache<Key, Lock>` with no other constraints. In that case the entry won't be eligible for collection until the lock is no longer used. This avoids unnecessary blocking due to hash collisions, but I've never seen it worthwhile in practice.

Of course these patterns are available in Guava as `Striped`. So you could use that instead of rolling your own.

**Comment by Maaartinus** [comment]
> This avoids unnecessary blocking due to hash collisions,

I'd add that with striping, you may get a deadlock easily, ever for completely unrelated objects as they may get hashed onto conflicting locks. Good luck debugging. ;)

> but I've never seen it worthwhile in practice.

I wonder when the cost matters? The code is even simpler than yours, there's one cache lookup and a `Lock` waiting for the GC...

**Comment by ben-manes** [comment]
> I'd add that with striping, you may get a deadlock easily, ever for completely unrelated objects as they may get hashed onto conflicting locks. Good luck debugging. ;)

If the locks are reentrant then usually its not a big deal. But then anytime you use multiple locks without an ordering guarantee its deadlock prone. But I think that goes to the point that lock striping is good to know but should very rarely be used. There is usually a more elegant design that performs better and only makes sense in low-level code.

> I wonder when the cost matters? The code is even simpler than yours, there's one cache lookup and a Lock waiting for the GC...

Yeah, the cost probably doesn't matter. I think having a tested abstraction or implement it thoughtfully is more important than performance. I've seen too many incorrect versions on StackOverflow that it worries me :)

**Comment by Maaartinus** [comment]
> If the locks are reentrant then usually its not a big deal.

It's improbable, but easily possible. Let thread 1 lock A, thread 2 B, 1 C and 2 D, possibly with completely unrelated locks and let both A and D map to x while B and C map to y. The bad thing is that you have zero control. With 16 stripes, the probability is about 1/256.

With Guava `Striped`, you can't do anything about it as the mapping isn't  exposed. So even if you knew upfront what locks are needed, you can not order them properly.

I needed locking for whole HTTP requests (where the cost really does not matter) and I went for `LoadingCache` with weak values (as you wrote above). There are multiple locks, I know in advance which ones are needed and sort them before acquiring. Very simple.

**Comment by ben-manes** [comment]
`Striped.lazyWeakLock` does the caching trick, although its confusing by having a sizing parameter that may use a custom hash table. I think he over did it and made it not predictable enough, so I'd have done the same as you.

Sometimes striping is used for work distribution, e.g. see this StackOverflow [thread](https://stackoverflow.com/q/29889885/19450). I feel like many people use it as a hammer that's often good enough, but there is a better abstraction out there.

But some, like you, do it right :)

I'm starting soon on a row-level locking scheme that will have the deadlocking problem. Unfortunately I don't always know the rows in advance so I have to detect deadlocks, handle retries, and rollback. I've effectively modeled the application as a glorified document database, where usually each row is independent and goes through some complex processing. But sometimes there are side effects of creating or mutating other rows by a trigger, which requires them to be scheduled for processing. If two rows have side effects of needing to update each other synchronously, then its a deadlock. I can't see how to get around that with Sagas, so either one of them is rolledback completely or an asynchronous trigger must be used. I think that is good enough, but feels dirty by not solving it entirely. Its something I need to start implementing this week and have been spinning on hoping to see a better way.

**Comment by Maaartinus** [comment]
> Sometimes striping is used for work distribution, e.g. see this StackOverflow [thread](https://stackoverflow.com/questions/29889885/java-divide-incoming-work-uniformly-via-hashing-in-multithreaded-evnironments).

I really like your answer. This separation of concern is perfectly obvious, once someone mentions it. And the Java 8 (nearly) one-liner shown me that there are still quite a few Java 8 I haven't learned yet.

> But some, like you, do it right :)

:) I was thinking about an optimization which I may need in a few years :D When `A`, `B`, `C` should be locked, I'd (really) lock `A`, try-lock `B` and on success try-lock `C`. On failure, I'd release all locks, so that other threads won't be blocked needlessly. Then I'd (really) lock the failed one and release it again, so that I know when to retry. Now, I'd retry the whole sequence again.

> I have to detect deadlocks

Once I wondered [why Java does not provide it](https://stackoverflow.com/q/20035366/581205), but I haven't got a satisfactory answer. I guess, with using `tryLock` in places where the deadlock may occur, you can get away without much overhead. Only when the `tryLock` fails, you need to start worrying about what's going on. I can't see how to get the whole lock graph from `ReentrantLock`, but I guess, I'm missing something (and you could always add your own tracking).

Are you going to do proper lock detection? Maybe you could just rollback and retry when it looks like a deadlock? Maybe you could use the information what rows were needed and lock them upfront?

**Comment by ben-manes** [comment]
> Are you going to do proper lock detection? Maybe you could just rollback and retry when it looks like a deadlock? Maybe you could use the information what rows were needed and lock them upfront?

I'm still brainstorming at the moment. I'm not really settled with the design as it feels like error prone to quietly give up on a deadlock. That would be fine, but I don't think the programming models as imagined communicates that to a developer (often being.. me). See this [brief proposal](https://docs.google.com/document/d/1pJ3-7vagIg-LD8jj8Oa-utU6OZlfKTCwzF63x-x8Lz8/edit#heading=h.1rmuf1l8d309), though note that there is a lot of assumed context.

I assumed that I would need to maintain a lease table (lock tracking) to retry with, e.g. when the task restarts due to a server shutdown. That would tell me what I already owned, hint at what I wanted, and who else was active in the system. The problem isn't in the technical details of deadlock detection, but the resulting programming model.

In the model an entity is a bag of data + metadata with a common CRUD api. For saving it does some light work on the caller's request, marks it as locked, and schedules async for heavy work which finally unlocks it. The metadata is used to dynamically construct an execution pipeline for what logic to run against the entity. This works great when entities are independent, but complex workflows require an entity to update other entities. Those updated entities would then be processed, where their business logic does some intelligent thing based on that state change. Then you abstract that up a level with UI tools based on your metadata and rules to easily support custom entities and workflows.

I'm digressing from the original question, so ping me over email if you're interested.

**Comment by jiming** [comment]
Thanks Ben,

I read document about Striped in guava, and found that your advice is very much valuable and helpful.

Have a nice day!

Jiming
