### ISSUE TITLE
Why weak or soft keys/values can not be combined with Async[Loading]Cache?

### ISSUE THREAD

**Issue by notify-bibi** [ben-manes/caffeine#1766]
![image](https://github.com/user-attachments/assets/140a1746-059a-4f46-a0c9-62dcc6ff328e)

**Comment by ben-manes** [comment]
AsyncCache is actually a `Cache<K, CompletableFuture<V>>` instance that handles minor differences given the mapping is established before the future has materialized. For example you wouldn't expect it to evict the in-flight future to expire and for it to be evaluated by that, its weight, etc. when the future completes and to be removed if the future fails. Therefore the weak/soft mapping is actually to the future, not the value it wraps, and this really doesn't make very much sense.

This works fine with `weakKeys` in most cases, except with `evictionListener` which is called when the cache removes an entry by the policy (collected, size, expiration) and is part of the Map's `computeIfAbsent` call so that it is atomic. This way if there is stateful resource that depends on key ordering, it can be cleaned up before the mapping can be re-established (e.g. a file at a deterministic path). Since the entry could be eligible for weak key collection before the future completes, this would require that the callback, `(key, value, cause) -> ???`, blocks on the `future.join()` which is very much undesirable. Otherwise the mapping would have to pollute the cache waiting for the future to complete in order to then be discarded, which is less bad but perhaps awkward. So far no one has complained about this limitation (a minor over restriction), which does not exist for `removalListener` since that is performed after the Map's compute operation completes and can just chain the listener call to the value future for notification.
