### ISSUE TITLE
Allow transferring eviction metadata

### ISSUE THREAD

**Issue by viveksjain** [ben-manes/caffeine#1774]
Hi, to improve cache hit rates across process restarts, we would like to serialize the cache state and deserialize & insert it somewhere else. For our use case this will happen across different servers, but I believe much of this applies even for a single server if you want to preserve the cache across a restart. We can iterate through the cache and serialize it in the application on the sender side, and deserialize and `put` on the receiver side.

However, my understanding of the Window TinyLfu policy is that inserting a bunch of entries in a short time period (without reading them) would cause it to drop most of those entries. This actually makes sense, given that this workload is indistinguishable from a scan. So I'm wondering whether there's any way to access and insert the eviction state between different processes, so that loading in the old state takes the access history into account.

**Comment by ben-manes** [comment]
If you are restarting the server, then the cache would be getting populated so they would be admitted into the cache. It wouldn't know how to distinguish if hot or cold, but it would add until it reaches its maximum capacity. You can [obtain](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/com.github.benmanes.caffeine/com/github/benmanes/caffeine/cache/Policy.Eviction.html) the items in their order of hotness using `cache,policy().eviction()`. You might decide to only restore the top 75% of the cache, which allows some time for activity to allow it to relearn an entry's importance. Or you might simulate requests to fake its value, e.g. top 20% perform three reads, 21-40% two reads, 40%-60% a single read. I think some process like that will likely be fast enough to not need an explicit hint via a cache api during your hydration.

**Comment by viveksjain** [comment]
Thanks for the response, that sounds like a good approach! Is there a way to get a notion of hotness of a particular key? I guess this would be exposing implementation details of the eviction policy so I'm guessing not. But we will split the state across multiple other servers when transferring it out, and are thinking to maintain our own index over the keys to do this efficiently. But this wouldn't work with the single global `cache.policy().eviction().hottest()` iterator.

**Comment by ben-manes** [comment]
I don’t think there’s much that could be given even if exposing the details. The item lives on one of 3 LRU lists (but no idea where) and has a frequency score that ages. By the time it’s actually evaluated then it likely has poor recency and the frequency estimates are compared between the candidate/victim for which to retain. That means it’s relative, not global sorted or scored. Since the frequency ages by halving all counters (0..15), e.g. a 10 drops to 5 but is still higher than the 6 to 3. Another server wouldn’t have the same aging so it might see that 5 as low valued until it’s next halving. I’m not sure on a per key, but you could snapshot with a function to capture an index position yourself maybe?

**Comment by viveksjain** [comment]
By snapshot you mean periodically iterate through `hottest()` and capture the index during iteration? We can experiment with that, thanks for your suggestions!
