### ISSUE TITLE
[FEATURE] Temporarily disable eviction for a selected key

### ISSUE THREAD

**Issue by wkuranowski** [ben-manes/caffeine#178]
Hello.

I am using LoadingCache to store URLs as keys and local file paths as values. Files are downloaded during get() operation. I am also using a custom weigher() (based on file size) and a removalListener to cleanup evicted files.

Is there any option to temporarily disable eviction for a specified key? I have a problem with files being evicted just after cache lookup. Probably LRU will be a better algorithm for such an use case.

Do you see any solution? Lock/unlock method?

**Comment by ben-manes** [comment]
This seems to be the same problem that #177 ran into. An LRU would mask the race but not solve it, unfortunately. You probably will need to manage that concurrency yourself, though it often isn't too hard.

The only lock/unlock methods are `asMap().compute`. That would allow a single reader/writer, causing eviction to be blocked if the victim entry was in use.

You can disable size-based eviction using a weight of zero. I think that would get messy though, since you still have to track usage.

You might prefer using reference counting to allow evictions, but only delete when the count reaches zero. You can do that manually (where the cache increments on load and decrements on removal) and have the final reader performs the delete. You could delegate the counting logic to the GC by using phantom references instead.

**Comment by wkuranowski** [comment]
I think that LRU is good enough in my case. Recent files are very important. Old, inactive files were most likely processed by all of my services and could be removed. Even if that race will happen sporadically, it's not a problem, because operation will be repeated later. So, for me LRU is the best option.

Please consider adding this eviction policy.

**Comment by ben-manes** [comment]
I think that goes against our goals, where we want the eviction policy to not be depended on for business logic to work correctly. It tries to make the best prediction to retain the entries most likely to be reused. The behavior similar to an object pool influencing eviction, or making the policy configurable, begins to break down the idea of a cache holding recomputable, transient data.

You could use Guava and likely be okay, if that's the case. A cache doesn't seem like the correct abstraction, perhaps a work queue?

**Comment by wkuranowski** [comment]
I need a cache, because I don't know how many operations will be performed on a single file. They are triggered by users. Older files are less likely to be reused.

Guava is missing an asynchronous interface, so Caffeine with LRU is the best combination :)

I know that you want to provide single best policy for every use case. But sometimes it's not possible. In my case inactive entry that was frequently used in the past is the best candidate for eviction.

**Comment by Maaartinus** [comment]
Ben, I surely agree with you that eviction policy should not depend on the business logic. Moreover, the program correctness definitely should not depend on the cache policy or size or alike.

However, I have a (possibly very) similar use case. Some entries must be guaranteed to be available until some event happens. I could store them somewhere in a small `Map`, but then I'd have to do two lookups, which doesn't sound right.

With something like
```
Caffeine.newBuilder()
    .maximumSize(...)
    ...
    .preventEvictionIf((k, v) -> isStillNeeded(k, v))
```
could be the perfect solution (probably also for the OP). Returning true would veto the eviction for now. It would bump the entry a bit higher (so that the situation won't repeat immediately), but I don't care about how exactly as this is needed for only a small fraction of entries. It's not about changing the policy, it's about (temporarily) exempting some entries from the policy.

**Comment by ben-manes** [comment]
My concern with that is then the eviction could degrade to O(n), with the result of not being able to evict at all. Then when it can evict that notification likely won't be sent to the cache, so it will be over capacity until the next maintenance cycle (enough reads or a write). The penalty of the scan is okay in small caches, but not in large ones. So this works for small caches or when the advisor is rarely rejecting the candidate, but that means it is also likely to be abused by mistake.

The weight=0 has the advantage of no longer taking capacity in the cache, which you might consider good or bad. Currently it does require skipping over the entries, but technically it could be moved into its own queue. That's because the weight it communicated to the cache as part of a write operation so it can shuffle the entry.

To use capacity, a simple option is to have another map for active entries. You could have the cache pull from it during the load and the event remove it from the map. That wouldn't retain full capacity, unless you had a RemovalListener reinsert it into the cache. At that point you are forcing the entries to be pinned and masking eviction by this other map.

**Comment by Maaartinus** [comment]
- **over capacity** - This won't matter in my case because of having just a few pinned entries. Moreover, it'd save me the map, so it'd cost less memory in total. I'm not sure, if the pinned entries should contribute to the total weight or not.
- **penalty of the scan** - I'd surely be rejecting the candidate only rarely, but I can imagine how it could go wrong. However, you'd run in a similar problem if the `RemovalListener` would re-insert the entries (or with another naive racy pinning attempt).
- **weight=0** - But the weight is "effectively static during the lifetime of a cache entry", which is a problem. Such an entry won't ever get removed, right? I'd have to remove it manually, which would probably be better than additionally accessing a map, but it's still rather ugly. Actually, I don't wan't to remove the entry, just unpin it, so it gets managed normally.
- **Loading from the map** - I have to think about it.

Would something like `.pinForMillis((k, v) -> v.isSpecial() ? 1000 : 0)` work better? It could use the time wheel logic and respect or ignore the weight of the pinned entry (whatever is easier to implement). It could go wrong with pinning many entries for a very short time interval, but then it's (more) obviously a user's fault.

Or maybe being explicit with `cache.pin(k)` and `cache.unpin(k)`? Or `putPinned(k, v)` or alike.

**Comment by ben-manes** [comment]
Note that weights are calculated for an entry when it is created or updated. So you could have a weigher that evaluated the entry, saw it was flagged as pinned, and gave it the weight of zero. In effect use a `compute` to pin and unpin.

Definitely things could go wrong with the reinsert hacks (assuming a re-insert is needed for a capacity constraint). Mostly that its clearly a hack of the known domain. That is a much more obvious smell then a feature that degrades poorly, where the code looks right due to the API but the subtle JavaDoc warns of the abuse.

I think `pinForMillis` would get messy as more ways to shoot yourself and weird interactions between policies.

My main concern is over capacity and `preventEvictionIf((k, v) -> true)`, which could be from a bug in the user's code. I know it is useful and those who want it wouldn't abuse it, but API design is about the edge cases. For example does it also stop expiration or clear? An explicit API is better in that respect by letting us know when to unfreeze it. There are just a lot of quirks of mixing in data that can't be recomputed and I don't know of another cache that has offered it successfully.

**Comment by Maaartinus** [comment]
> In effect use a compute to pin and unpin.

Thank you. I guess, this would work perfectly for me. I'm unsure, if also for the OP. If not, apologies for hijacking their issue.

**Comment by ben-manes** [comment]
There's not a lot of usages with this, so do let me know if something doesn't work right. It looks like for put/replace, the weighing is outside of an atomic block by assuming the entry isn't changing. For computations / loads, it is in the block since the function has to be run atomically. We could ensure all weighing calls are within a entry lock, though it may not matter for you. (Its outside for explicit puts with memory estimating, e.g. see Cassandra).

@wkuranowski would the weigher work for you?

**Comment by wkuranowski** [comment]
I think this would work for me too.

**Comment by ben-manes** [comment]
Great! If any issues arise let me know and we'll sort them out.

**Comment by ben-manes** [comment]
I added a [Faq](https://github.com/ben-manes/caffeine/wiki/Faq) for these advanced questions that don't fit into the main guide. Let me know if there are any additions.
