### ISSUE TITLE
is StatsCounter solely intended for consumption by Cache implementors?

### ISSUE THREAD

**Issue by benjaminp** [ben-manes/caffeine#1780]
`StatsCounter` has this javadoc:
https://github.com/ben-manes/caffeine/blob/eafcb4ac9594c281e639d845c41bb786f3c03883/caffeine/src/main/java/com/github/benmanes/caffeine/cache/stats/StatsCounter.java#L26-L27

I suppose the last sentence is slightly ambiguous, but to me, it means `StatsCounter` shouldn't be implemented or used by caffeine reverse dependencies. However, a supplier for `StatsCounter` may be passed to `Caffeine.recordStats` since https://github.com/ben-manes/caffeine/commit/2a8c68832e0864d38af5035eca88e63fb9985f46, which means it is a public interface.

**Comment by ben-manes** [comment]
I suppose that could be reworded. It originates from Guava where it’s nested as an [implementation detail](https://github.com/google/guava/blob/e5b58e2fc8561192338dfe0c68c0bce27066a6aa/guava/src/com/google/common/cache/AbstractCache.java#L139). There a custom one wasn’t provided as Google scrapes stats by polling instead of pushing.

In this case it means it’s not a general purpose utility or meant for extension of additional statistics that an application might want. Those can be added externally to the cache, like a putCount. The native stats are the minimal common ones or those that are otherwise not obtainable, rather than an event callback hook for every permutation of an activity. Thus consumption is who’s utilizing it, rather than implementing the interface to give to the cache.
