### ISSUE TITLE
FR: Support conditional caching in LoadingCache

### ISSUE THREAD

**Issue by chrylis** [ben-manes/caffeine#1787]
The Spring Cache abstraction provides a very useful mechanism in `@Cacheable.conditional`/`unless` that only persists the cached result if it matches the predicate. This is particularly useful in cases such as "cache if the loader returns a result, but don't cache if it returns empty".

Caffeine does not appear to have built-in support for this concept, but I find myself wishing for it frequently. Instead of using workarounds like instaremoval or an infinite-weight Weigher, I would like to be able to write something like

```
Caffeine.newBuilder()
  .cacheWhen(k, v -> !v.isEmpty()) 
  .build(this::fetch)
```

**Comment by ben-manes** [comment]
I'd probably lean towards immediate expiration by `expireAfter(Expiry)` as the cleanest solution.

This isn't a feature available in `ConcurrentMap`, e.g. a compute may return `null` to discard the mapping so one would need to capture the value before returning. Some might want all concurrent calls to receive that value, though, but not hold onto it afterwards which implies an instant removal, whereas others might want independent loads like the compute hack. It is quirky to offer, not in core Java, and may not always be clear what the assumed semantics are.

I think this also has a larger impact, as `Map.put` or `replace` would need to complete successfully but immediately discard the entry. In effect its a valid entry at materialization which on inspection is stale and needs to be purged. If a racy read observes it, then it should know it is stale and treat that appropriately, so some type of metadata is required. Then that becomes condition checks, a removal cause reason, etc. throughout. Piggy backing on expiration would do all of these things and, to me, is more obvious end user behavior.

**Comment by ben-manes** [comment]
Looking at Spring's [support](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/cache/annotation/Cacheable.html#condition()) and it [works](https://github.com/spring-projects/spring-framework/blob/main/spring-context/src/main/java/org/springframework/cache/interceptor/CacheAspectSupport.java) as follows,

- The `condition` is evaluated before the cache lookup in order to skip it and load directly from the loader method if it evaluates to false.
- The `unless` clause requires `sync=false` to load the entry outside of the cache, allowing redundant loads due to races, and only insert if if this evaluates to false.

This means that neither are atomic and are about skipping the cache operations, which I believe would cause more surprises for users due to being non-linearizable. In code their behavior is,

```java
if (!condition.apply(key)) {
  return load(key);
}

if (sync) {
  requireNull(unless, "Unless SpEL cannot be used with sync=true");
  return cache.get(key, this::load);
}

V value = cache.getIfPresent(key);
if (value == null) {
  value = load(key);
  if (unless.apply(value)) {
    cache.put(key, value);
  }
}
return value;
```

The approach uses expiration or otherwise loading through the cache has benefits of linearization, at the cost of serializing the loads for the given key since it would only allow one to be in-flight at a given time. In some cases that's desired, other times one should always bypass the cache, or the middle ground of satisfying all requests but immediately remove. The application behavior shouldn't be a cache setting as these can all be done in client code, so I don't think this is a good feature for us to natively support. Instead, please consider writing a wrapper that adds your functionality for reuse in your project. Thanks for the idea, though!
