### ISSUE TITLE
`Issue30Test` uses incorrect date time format pattern

### ISSUE THREAD

**Issue by Marcono1234** [ben-manes/caffeine#1788]
https://github.com/ben-manes/caffeine/blob/0eaf6f21983a042073c89e99a3309dc13fbeadf5/caffeine/src/test/java/com/github/benmanes/caffeine/cache/issues/Issue30Test.java#L154

- `h` is 'clock-hour-of-am-pm (1-12)', without am/pm marker (`a`) this might not be intended
Should maybe be `H` ('hour-of-day (0-23)')?
- `M` is 'month-of-year'
Should probably be `m` ('minute-of-hour')

So the pattern should probably be: `HH:mm:ss.SSS`

If this won't require signing the CLA, I can submit a pull request for this. Otherwise it might be easier if you fix this incorrect pattern.

**Comment by ben-manes** [comment]
No cla required (which just reiterates its Apache license). PRs welcome

**Comment by Marcono1234** [comment]
> No cla required

Generally not, or only not for this small fix? Because currently there is CLAassistant set up for this repository, and `CONTRIBUTING.md` mentions it as well.

**Comment by ben-manes** [comment]
It is there to encourage an explicit agreement of the Apache license instead of an implicit one through the act of contributing. We use the ASF’s which they consider optional. Unlike CLAs that reassign ownership, the ASF’s is record keeping of the notice as it reiterates the license. When devs feel the need to get lawyer approval for any contribution, this clarifies that there are no extra side agreements to the license. Typically they just send a new CLA for me to sign which reasserts that because that because that is their process assuming no CLA.

For me it’s just a checklist item for community health, like [OSSF’s](https://www.bestpractices.dev/en/projects/5584), which are becoming the norm. There’s not much direct value, but it makes non-technical groups feel respected when topics raise to their awareness.

**Comment by ben-manes** [comment]
> Are contributors' employers required to sign a CCLA?
> ...
> The CCLA is a backup document that the committer/ICLA signer may use to eliminate all of the ambiguity between conflicting laws, contracts, policies and job assignments. We've never required it. Many committers are confident of their individual representations under the ICLA, many other committers find it reassuring that their company has backed up their own ICLA with this umbrella document.

https://www.apache.org/licenses/cla-faq.html#cclas-not-required
