### ISSUE TITLE
Condition that is always true

### ISSUE THREAD

**Issue by lifove** [ben-manes/caffeine#179]
Hi

In a recent snapshot, I've found a following suspicious code.
Path:caffeine/src/main/java/com/github/benmanes/caffeine/cache/Node.java

```
156   int EDEN = 0;
...
160   /** Returns if the entry is in the Eden or Main space. */
161   default boolean inEden() {
162     return getQueueType() == EDEN;
163   }
...
165   /** Returns if the entry is in the Main space's probation queue. */
166   default boolean inMainProbation() {
167     return getQueueType() == PROBATION;
168   }
...
185   /** Returns the queue that the entry's resides in (eden, probation, or protected). */
186   default int getQueueType() {
187     return EDEN;
188   }
```

It seems Line 162 and 167 return always true and false respectively as getQueueType returns EDEN. Since this is interface, those methods are not supposed to be called or would be overridden. So, this might not be an issue but I wanted to report this just in case.

Thanks!

**Comment by ben-manes** [comment]
Thanks for digging into the code! It is very complex and tests often catch my mistakes when making changes. Its just a lot that has to be packed into a few interfaces.

In this case code generation is used to minimize the number of fields on the Node implementations to just those used by the cache configuration. The generated class `NodeFactory` will override this value. Likely the code isn't called or, if it is, only when `expireAfterWrite` is solely enabled since it reuses that queue. If you are interested, the code generator is [NodeFactoryGenerator](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/NodeFactoryGenerator.java).

As an aside, in this case I'd really like to encode those flags somewhere to avoid the extra field. `ConcurrentHashMap` takes a few bits from the hashCode, but that would require forking it to add ours into that.

**Comment by ben-manes** [comment]
A quick reference check and it looks like the calls are things like,

```java
if (node.inEden() && (evicts() || expiresAfterAccess())) {
   ...
}
```

So we could switch the order and have `getQueueType()` throw an exception to be more explicit. I don't have a strong preference, do you?

**Comment by lifoveBible** [comment]
I'm just studying the code and learned a lot from your detailed explanation. Thanks a lot!
