### ISSUE TITLE
Race conditions w/ AsyncCache, pinning, and setMaximum

### ISSUE THREAD

**Issue by jarohen** [ben-manes/caffeine#1791]
Hey Ben :wave: 

Following on from xtdb/xtdb#3466, we think we're hitting a race condition where a newly pinned entry is evicted before it's had chance to update its weight in the cache.

As we understand it:

* We're setting a weigher on the AsyncCache which checks a ref-count in the entry, returning 0 if ref-count > 0, otherwise the entry's weight.
* We're calling `asyncCache.asMap().compute()` on an entry already in the cache in order to update its ref-count - within that lambda, within a CF.thenApply, we're incrementing the ref-count, and decreasing the max-weight of the cache if the ref-count was previously zero [1]. 
  * We're aware of the javadoc that says 'policy operations must not be performed from within an atomic scope of another cache operation.', so this is immediately something we're doing wrong :sweat_smile: although I don't think we hold the entry lock at this point - in an async cache, that lock is only taken when the future completes?
* The update into the cache (for the entry's weight) is only performed when the CF completes, so when setMaximum runs it chooses this entry for eviction, its weight is still positive, so it's evicted - so we can't run setMaximum here.
* Running setMaximum outside of compute may well introduce its own race conditions for us, but we'll accept these for this issue.
* Unfortunately we don't think we can tack the setMaximum update onto the CF returned from `cache.asMap().compute()` either, because the cache node weight update is still not guaranteed to take place [before that future completes](https://github.com/ben-manes/caffeine/blob/3457bf50994121ad924571e9987a39d672c06e1e/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncCache.java#L466-L469). We could potentially return the CF from `handleCompletion` here rather than `result[0]`, but I daresay that's done for performance so that the user gets the computed value ASAP.

Would appreciate any advice/experience you could offer here, I understand we may be operating outside of expected parameters, but also hoping we've missed something obvious! :slightly_smiling_face: 

James & Finn (@fiv0), @XTDB

[1]
```java
public CompletableFuture<V> get(Path k, Function<Path, CompletableFuture<V>> f) {
    return cache.asMap().compute(k, (key, fut) -> {
        CompletableFuture<V> future = (fut != null) ? fut : f.apply(key);

        return future.thenApply(entry -> {
            if (entry.refCount.getAndIncrement() == 0) {
                // calls setMaximum on the cache policy.
                // potentially naughty of us.
                updateMaxWeight(-entry.weight);
            }
            return entry;
        });
    });
}
```

**Comment by jarohen** [comment]
> Can you provide a minimal reproducer to test and debug with?

We'll see what we can do on this one - naturally as a race it's not the easiest thing to repro reliably :slightly_smiling_face: 

> A future uses identity equality so we return the user’s whenever possible to avoid surprises. Otherwise side mappings, cancellations, etc might not work because they wouldn’t be on the source future. For example, a dependent action on the original would run despite canceling in the application because they are different futures with their own lifecycles. Instead the future we’d use for metadata updates would be cancelled causing the cache to never evict the original as it would stay pinned. Therefore we’d have to return a copy(), but again you’d lose the original which would be a bad user experience as difficult to coordinate and many map operations would misbehave (conditional removal, for instance).

Yep, that sounds gnarly :sweat_smile: 

> I think you’d need to call the setMaximum outside of the compute, e.g. using thenApplyAsync, but it is tricky as you don’t know when the cache observed it as pinned.

Exactly the issue we're seeing, yeah.

At the risk of me naively designing a pinning mechanism for Caffeine outside of zero-weights (I recall you being rightfully hesitant about it), might it be an option to add a flag on the cache nodes for whether the cache entry is pinned?

e.g.

* constructing the cache:
  ```kotlin
  Caffeine.newBuilder()
     .weigher { _, value -> value.weight }

     // terrible name
     .pinner { _, value -> value.refCount.get() > 0 } 

     .buildAsync()
  ```
* `BoundedLocalCache/replace` calls `n.setPinned(...)` alongside `n.setWeight(...)`
* `evictEntry` additionally checks `n.isPinned()` with `n.getWeight() == 0` for resurrection
* `evictFromMain` checks `n.isPinned()` with `// Skip over entries with zero weight`
* remaining (obv minor) details left as an exercise to the reader :laughing: /s

(absolutely no offence taken if this isn't something you'd want to add (/right now))

**Comment by ben-manes** [comment]
> We'll see what we can do on this one - naturally as a race it's not the easiest thing to repro reliably 🙂

fwiw, my tests often use [Awaitility](https://github.com/awaitility/awaitility) to coordinate in an attempt to force a race, so that might be possible (but not always).

> At the risk of me naively designing a pinning mechanism for Caffeine outside of the zero-weights pattern (I recall you being rightfully hesitant about it in a previous conversation), might it be an option to add a flag on the cache nodes for whether the cache entry is pinned?

In your predicate idea, since the problem is evaluation order instead it would be called ad hoc rather than the pin state stored. I am against it because a user could accidentally, and trivially, disallow any eviction and cause an unexpected memory leak. Coherence offers this as [EvictionApprover](https://github.com/oracle/coherence/blob/1c054be7c4553b7ba6bd3534f8431f7a67d53b34/prj/coherence-core/src/main/java/com/tangosol/net/cache/ConfigurableCacheMap.java#L333-L363) where their only built-in is to never evict (what?), while Ehcache's [EvictionAdvisor](https://www.ehcache.org/documentation/3.10/eviction-advisor.html) tried to fix that flaw by instead breaking the pinning feature to degrade only to a semi-custom eviction algorithm (_"the cache can decide to completely bypass the eviction advisor and evict anything it sees fit"_).

Now that I've had my morning caffeine, my guess is that your problem could be resolved by `thenApplyAsync`. That wasn't obvious to me when groggy as a convinced myself against it or variants then. I think it might be fine because when an in-flight future is written into the cache, the entry is evaluated under the entry's lock and [pinned](https://github.com/ben-manes/caffeine/blob/3457bf50994121ad924571e9987a39d672c06e1e/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Async.java#L132-L156). The eviction shouldn't remove it because it is either zero weight before [selection](https://github.com/ben-manes/caffeine/blob/3457bf50994121ad924571e9987a39d672c06e1e/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L793-L800), or [resurrected](https://github.com/ben-manes/caffeine/blob/3457bf50994121ad924571e9987a39d672c06e1e/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L1065-L1070) during the computation. When complete then it is re-evaluated by the `handleCompletion`, which would keep it as pinned per your own weigher. However, where your logic fails, is when the previous future is complete so the `thenApply` runs on the calling thread, which results in a recursive write because the mapping has not yet been established in the hash table. By using `thenApplyAsync` the ordering stays correct, cache observes an in-flight future temporarily, and the `updateMaxWeight` runs outside of the computation.

If you want to avoid the async context switch then you could maintain ordering and defer until after the map operation by returning a future that you complete manually. It would look something like,

```java
public CompletableFuture<V> get(Path k, Function<Path, CompletableFuture<V>> f) {
  var future = new CompletableFuture[1];
  var result = cache.asMap().compute(k, (key, fut) -> {
    future[0] = (fut != null) ? fut : f.apply(key);
    return new CompletableFuture<>();
  });
  future.thenRun(entry -> {
    if (entry.refCount.getAndIncrement() == 0) {
      updateMaxWeight(-entry.weight);
    }
    result.complete(entry);
  });
  return result;
}
```

I might still be a bit wrong since I don't recognize the stacktrace in your original issue and haven't had time to read through it. In Java 8 a recursive write would deadlock, whereas afterwards it should throw an exception if detected. I think the last fix for detection was in JDK 12, so if you are using a modern jdk like 17+ then you would be observing these errors. That wouldn't fix anything, but at least not be a deadlock unless your own code lacked the necessary error handling. If its something else then my suggestions might be misleading.

**Comment by jarohen** [comment]
Hey Ben, thanks for your thoughtful reply :pray: 

We'll definitely give `thenAwaitAsync` and similar strategies a go, thank you - on further investigation I think a necessary condition for our issue may be that the entry is already present in the cache before pinning:

* add entry to cache, unpinned (positive weight, so evictable)
* run `compute` to increment the ref-count within the entry lock - this takes effect at handleCompletion
* the call to `updateMaxWeight`/`setMaximum` happens after the ref-count is incremented (reducing the weight to zero) but before this change is applied to the cache node (so it gets evicted), violating our invariant that entries with a positive ref-count never get evicted.
  * one solution is to try enforce a strict happens-before relationship for change-applied -> call setMaximum, but I don't think we're able to hook into that
  * any way we could make these two atomic? :thinking: or at least prevent the maintenance, or eviction of that entry, until the change's applied. (again, just thinking out loud)

It's getting late here (UK) so I have the opposite problem - getting more groggy as we go into the evening :smile:

**Comment by jarohen** [comment]
Mm, it should, shouldn't it - _so where's our bug then...?!_ :thinking: 

I'll close this one for now, unless/until we can repro with just Caffeine.

Thanks for all your help Ben :pray:

**Comment by ben-manes** [comment]
If you can get a full stacktrace, e.g. using `jstack`, that could help. The limited stacktrace in the project's bug isn't very much information. I think the `thenApplyAsync` should fix it, but it certainly would be nice to prove that more conclusively.

**Comment by jarohen** [comment]
> I think the thenApplyAsync should fix it

It seems that way, yep - thanks again :relaxed:

**Comment by jarohen** [comment]
test case:

```java
package xtdb;

import com.github.benmanes.caffeine.cache.Caffeine;
import org.junit.jupiter.api.Test;

import java.util.Objects;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.atomic.AtomicInteger;

import static java.util.concurrent.CompletableFuture.completedFuture;
import static org.junit.jupiter.api.Assertions.assertFalse;

public class CaffeineRace {

    record Entry(AtomicInteger refCount, int weight) {
    }

    @Test
    public void testCaffeineRace() throws ExecutionException, InterruptedException {
        var assertFail = new boolean[1];
        var cache =
                Caffeine.newBuilder()
                        .maximumWeight(4)
                        .<Integer, Entry>weigher((k, v) -> v.refCount.get() > 0 ? 0 : v.weight
                        )
                        .evictionListener((k, v, cause) -> {
                            if(Objects.requireNonNull(v).refCount.get() > 0) {
                                assertFail[0] = true;
                            }
                        })
                        .buildAsync();

        cache.put(1, completedFuture(new Entry(new AtomicInteger(0), 3)));
        cache.put(2, completedFuture(new Entry(new AtomicInteger(1), 1)));
        cache.put(3, completedFuture(new Entry(new AtomicInteger(0), 1)));

        var eviction = cache.synchronous().policy().eviction().get();

        // change to thenApplyAsync to make the test pass
        cache.asMap().computeIfPresent(1, (k, fut) -> fut.thenApply(entry -> {
            entry.refCount.getAndIncrement();
            eviction.setMaximum(2);
            return entry;
        })).get();

        cache.synchronous().cleanUp();

        assertFalse(assertFail[0]);
    }
}
```

**Comment by ben-manes** [comment]
oh I see, so this was not a deadlock in the Cache / ConcurrentHashMap but in your own code because of the premature eviction? That makes sense since Java `synchronized` is reentrant so the compute to the same entry could loop to cause unexpected behavior. Technically this could be detected by encoding a status bit somewhere, but it was never clear to me if Caffeine should be responsible for that. ConcurrentHashMap does it sometimes and I'd naively guess that it could be stricter by using some of the [hashCode control bits](https://github.com/openjdk/jdk/blob/7d8bd21eb0187647ec574abf4fac4f99c435c60b/src/java.base/share/classes/java/util/concurrent/ConcurrentHashMap.java#L303-L306). For now I am following Java's approach of best effort with JavaDoc warnings, but we could ask Doug Lea for some guidance.

**Comment by ben-manes** [comment]
makes perfect sense. I'll softly ping @DougLea here and if I sync with him someday in the future then raise it as a feedback item. The ideal would be for ConcurrentHashMap to detect reentrant writes to disallow updates to the same mapping.

**Comment by DougLea** [comment]
Hi Ben. As always, it's hard to make a case for adding a lot of overhead to help users detect  rare mistakes. As opposed to current very low overhead checks that catch most of them. During next CHM update (not idea when), I'll further contemplate ...
