### ISSUE TITLE
Caffeine returns incorrect size and fails on iteration over collection

### ISSUE THREAD

**Issue by kkocel** [ben-manes/caffeine#1792]
I have a simple registry implemented as Caffeine cache:

```kotlin
class LocalFactorsRegistry(
    duration: Duration,
) : FactorsRegistry {
    private val factors =
        Caffeine
            .newBuilder()
            .expireAfterWrite(duration)
            .build<String, Boolean>()

    override fun getUsedFactors(): Set<String> = factors.asMap().keys

    override fun markFactorAsUsed(factorId: String) {
        factors.put(factorId, true)
    }
}
```

I try to test if item is evicted:

```kotlin
    @Test
    fun `should mark factor as used and wait for expiration`() {
        val factory = LocalFactorsRegistry(Duration.ofMillis(100))

        factory.getUsedFactors() shouldBe emptySet()

        factory.markFactorAsUsed("factor2")

        Thread.sleep(100)

        factory.getUsedFactors() shouldBe emptySet()
    }
```

However tests fails on last assertion:

```
java.util.NoSuchElementException
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$EntryIterator.nextKey(BoundedLocalCache.java:3754)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$KeyIterator.next(BoundedLocalCache.java:3350)
	at kotlin.collections.CollectionsKt___CollectionsKt.toList(_Collections.kt:1323)
	at io.kotest.assertions.print.IterablePrint.print(IterablePrint.kt:6)
	at io.kotest.assertions.print.IterablePrint.print(IterablePrint.kt:3)
	at io.kotest.assertions.print.PrintKt.print(Print.kt:48)
	at io.kotest.assertions.eq.IterableEq.generateError(IterableEq.kt:221)
	at io.kotest.assertions.eq.IterableEq.checkSetEquality(IterableEq.kt:77)
	at io.kotest.assertions.eq.IterableEq.equals(IterableEq.kt:65)
	at io.kotest.assertions.eq.EqKt.eq(Eq.kt:51)
	at io.kotest.assertions.eq.EqKt.eq(Eq.kt:66)
	at io.kotest.matchers.ShouldKt$equalityMatcher$1.test(should.kt:73)
	at io.kotest.matchers.ShouldKt.invokeMatcher(should.kt:38)
	at io.kotest.matchers.ShouldKt.should(should.kt:33)
	at io.kotest.matchers.ShouldKt.shouldBe(should.kt:17)
	at com.example.LocalFactorsRegistryTest.should mark factor as used and wait for expiration(AbstractFactorsRegistryTest.kt:35)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
```

I wonder how I can get an immutable snapshot of keys in the caffeine cache to assert it properly.

**Comment by kkocel** [comment]
Interestingly when I call `factors.asMap().keys.size` I get `1`, even long after expiration period

**Comment by ben-manes** [comment]
The cache documents its size method as best effort,

https://github.com/ben-manes/caffeine/blob/3457bf50994121ad924571e9987a39d672c06e1e/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Cache.java#L175-L182

https://github.com/ben-manes/caffeine/blob/3457bf50994121ad924571e9987a39d672c06e1e/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Caffeine.java#L103-L109

Since expiration is based on time and not activity, to discard the entry would require either the caller triggers this maintenance work or a scheduled thread does it. Generally various activity, like a few reads or a write, will trigger periodic maintenance so it does not linger long (akin to GC garbage). The `Caffeine.scheduler` option allows you to specify a thread, e.g. `Scheduler.systemScheduler` for the JDK built-in one, and the cache will schedule based on the next expiration event. Caffeine does not create its own threads implicitly as that would be a poor practice.

Kotlin's code appears to not be thread safe. Their [toList()](https://github.com/JetBrains/kotlin/blob/9962fdbbe3d0de083798c71289056db3df2fb5d7/compiler/testData/ir/interpreter/helpers/Collections.kt#L111-L120) performs a `size()` and then a forced iteration without actually checking `hasNext` which is simply awful. They have a long history of flagrantly violating Java api contracts despite knowing better, e.g. [unsafe usages](https://github.com/JetBrains/kotlin/blob/a88e4e75cf76992aba461348177ad23c8d7990a6/libraries/stdlib/jvm/src/kotlin/concurrent/Locks.kt#L47-L50) of read-write lock where they argued against proper usages for nicer looking demo code to gain early adopters. I can't find their synthetic `Map.keys.size`, but if it does a full traversal then the cache would suppress the expired entry from the result. I believe they still have many of these historic footguns, so you would need to open an issue with them to resolve the `NoSuchElementException`.

**Comment by ben-manes** [comment]
The Kotlin standard library team opened [KT-22934](https://youtrack.jetbrains.com/issue/KT-22934) over 6 years ago saying that "most of the standard collection operations are unsafe when the collection is being modified". The Java collections framework is not overly strict, e.g. `ConcurrentHashMap` and `WeakHashMap` are only best guesses, where even without concurrency they are making a wild assumption. As of Java 5 when concurrency was a main focus, `toArray()` became the preferred approach because it tolerates deviations and this is used by built-ins and most custom collections. That is more efficient since `size()` may be an O(n) operation (e.g. `ConcurrentLinkedQueue`) so only one traversal is needed which the implementation can optimize. Since that is given exclusively to the receiver, a new collection may initialize its own structure to use this array directly, rather than another copy, like Guava does in `ImmutableList.copyOf`. These are easy fixes for them to make and I am a bit dismayed they haven't.

**Comment by kkocel** [comment]
@ben-manes I wrote the test in pue Java and can reproduce it.

```java
    @Test
    void shouldReturnEmptySetIfNoFactorsUsed() throws InterruptedException {
        final Cache<String, Boolean> factors =
                Caffeine
                        .newBuilder()
                        .expireAfterWrite(Duration.of(10, ChronoUnit.MILLIS))
                        .weakKeys()
                        .build();

        assertIterableEquals(factors.asMap().keySet(), Collections.emptySet());

        factors.put("factor1", true);

        Thread.sleep(11);

        final var usedFactors = factors.asMap().keySet();
        var size = usedFactors.size();
        var isEmpty = usedFactors.isEmpty();
        var hasNext = usedFactors.iterator().hasNext();
        var next = usedFactors.iterator().next();
    }
```

It turns out that set reports it's size to `1`, `isEmpty` returns `false`, but iterator claims that it does not have any elements...

<img width="959" alt="image" src="https://github.com/user-attachments/assets/4f6f4018-b986-4c7c-838d-d53132a65561">

**Comment by ben-manes** [comment]
Correct. The size is an estimate because it does not perform a full traversal, making it fast as a precomputed value. Since the entry may expire or by weak/soft collected, the estimate includes entries that are pending eviction. This is why the behavior is documented, so that users may decide to get a more accurate size by performing a more costly operation first.

When the entries are being traversed then the cache should not return ones that are pending eviction, as that would imply that they are usable. The iterator is able to skip those entries and trigger a background maintenance cycle when encountered. Note too that iterators are _weakly consistent_ in concurrent collections.
