### ISSUE TITLE
How much resources does caffeine consume, beside the cached data(key and value)?

### ISSUE THREAD

**Issue by jiming** [ben-manes/caffeine#180]
Dear Ben,

I am going to create thousands of cache instances.

My concern is does Caffeine has thread pool insides or some others resource used I need care about?

Thanks!

Jiming

**Comment by ben-manes** [comment]
The cache doesn't have manage any threads, but takes advantage of the JVM-wide `ForkJoinPool.commonPool()`. That can be set to a specific executor, perhaps a direct executor is preferred here, as the pool is primarily to mask small latencies from cache maintenance and other work.

There is memory overhead for an instance since it is designed for high concurrency, but I do try to be polite about it. Internally it uses ring buffers for concurrency, with the number growing as contention is detected up to a maximum. Thus if there is low demand there is a smaller footprint and memory is traded for additional speed as needed. The fixed overheads are reduced by code generating specialized classes to minimize the number of fields. That increases the jar size, but since few classes are loaded its just waste disk rather than memory.

So it should work without too much trouble. That said, if you have thousands then it may not be necessary. Thousands implies there is likely low concurrency, so a thread local or synchronized `LinkedHashMap` in LRU mode could be good enough. Caffeine might be good to start with, but its okay by me to choose a less fancy alternative when appropriate.

**Comment by jiming** [comment]
Thanks very much!
