### ISSUE TITLE
Benchmark should operate with less then 100% hitrate

### ISSUE THREAD

**Issue by cruftex** [ben-manes/caffeine#19]
The GetPutBenchmark operates with a cache capacity that is bigger then the used key value range.
This yields 100% hitrate for all benchmarks.

**Comment by ben-manes** [comment]
That's would be additional benchmarks to provide very different information. It would have to be constructed carefully to determine exactly what it is proving.

The benchmarks clearly state that they show the read/write throughput under concurrency. This is most meaningful when measuring the hit penalty, which is the most expensive scenario and ideal case for users. It would be fair to say that the miss penalty could be judged as well (100% miss rate), but that is typically not very interesting for caches.

If a mixed hit/miss benchmark was shown then they can highly skew the results. For example Infinispan [incorrectly](https://github.com/infinispan/infinispan/pull/3282) believe their rewrite is faster due to the high miss rate in their benchmark, which on a Java 8 ConcurrentHashMap is very faster. This would mean that the worse the eviction policy is, the faster the cumulative cache operations might appear. It becomes very problematic to construct a **concurrent** benchmark with less than a 100% hit rate across different implementations that provides meaningful insight.

Reducing the hit rate is more appropriate in a few scenarios,
 * For efficiency benchmarks, which is where a simulator with policies and traces comes in. It would help show what the expected hit rate of the cache is under different loads. This is traditional approach to caching, which is useful but often highly irrelevant for Java applications where the hit rate is often in the 9x%.
 * To show the eviction penalty due to overflowing the cache. Different eviction policies and concurrency schemes have different penalties. This requires care because some policies degrade differently based on the trace data. For example a classic SecondChance CLOCK cache would require a full scan if all the entries were marked.
 * To show the overhead of the cache loader calls, which is a user function. That would be to demonstrate how much concurrency is supported for handling computations in flight. Other than a single exclusive lock approach, this is typically not a concern for users.

For microbenchmarks the current scheme is reasonable, given that all use LRU. When a different policy is in the mix then the results are skewed in that policy's favor. A long running application may have many hiccups due to the cost of eviction, as mentioned above, whereas LRU is O(1) in all scenarios. This is similar to the miss understanding that many had regarding soft references, which appears to be great in a microbenchmark and horrible in practice. When evaluating eviction policies that are not concurrently O(1) the benchmark author needs to be very careful to communicate accurate and meaningful results.

**Comment by cruftex** [comment]
> There should be additional benchmarks to provide very different information. It would have to be constructed carefully to determine exactly what it is proving.

That is correct. And there should always be a benchmark with high or 100% hitrates. The cache hit ultimately needs to be fast. It is good to have an isolated benchmark for this. However, this is one aspect of many.

> For microbenchmarks the current scheme is reasonable, given that all use LRU. When a different policy is in the mix then the results are skewed in that policy's favor. A long running application may have many hiccups due to the cost of eviction, as mentioned above, whereas LRU is O(1) in all scenarios.

Gotcha!

That is an assumption, and falls into the "measure, don't guess" category. You don't know for sure, until you benchmark it.

In most real world workloads modern eviction strategies outperform LRU in terms of achieved hitrate. So additional costs for eviction, might get amortized. As soon as there is some real cost for generating the cache value (CPU usage or latency) it will get amortized.

**Comment by ben-manes** [comment]
> In most real world workloads modern eviction strategies outperform LRU in terms of achieved hitrate. So additional costs for eviction, might get amortized. As soon as there is some real cost for generating the cache value (CPU usage or latency) it will get amortized.

Yep, but unfortunately some policies have high eviction penalties that, if consuming a user thread, can add noticeable latencies. In particular those that are CLOCK-based often have O(n) worst case penalties which, when a cache is 1M+ entries, is unacceptable. How to benchmark to show the eviction penalty is non-trivial, since the that often requires initializing to a worse-case state for a single run.

Unfortunately this is one of many areas glossed over by academics, so those implementing their algorithms may not notice the issue until they observe high production latencies. The simplest solution for an implementation is to be pragmatic by putting a cap on the eviction search space so that it never goes O(n) and chooses a good enough victim (but perhaps not the best).

**Comment by ben-manes** [comment]
The simulator is now pretty well flushed out now. It shows the eviction policy hit rate and actual time complexity (# of steps taken). The execution time is also shown, but that's unfair because the thread may be swapped out, GC, etc due to simulating in parallel. Its fairly trivial to write a JMH benchmark for the policies, though they were written for correctness and ease of understanding rather than raw performance.

The other categories (miss penalty, eviction penalty, compute penalty) are harder to benchmark correctly. Of them I think eviction penalty is the most interesting, but hardest to show accurately across implementations. If implemented as an infinite counter then its a subset of the 100% write benchmark (where all do poorly). It would accurately show the cost for policies that are O(1), like Ehcache's sampling, but not for those that are CLOCK-based. Those policies would mimic a FIFO and appear better than actual usage by never needing to scan. I don't know whether interleaving random reads would solve that, and if so it would probably need to be a single threaded benchmark.

The remaining class of benchmarks are variations of the GetPutBenchmark using different configurations, such as expiration. That's typically dominated by the slow native calls in `System.nanoTime()` or `System.currentTimeMillis()`, where the performance varies widely across operating systems. If one implementation resolves that with a coarser time resolution or background thread then I'm not sure if that remains a valid comparison.

Given the above, I'm inclined to close this task. If you have concrete benchmarks in mind then we can discuss them specifically.

**Comment by ben-manes** [comment]
Added [Efficiency](https://github.com/ben-manes/caffeine/wiki/Efficiency) wiki page to compare hit rates. Otherwise I don't know what other benchmarks provide meaningful information and can be implemented reliably. Closing.
