### ISSUE TITLE
How to change a value atomically

### ISSUE THREAD

**Issue by yanquanyu** [ben-manes/caffeine#190]
I want to limit the rate of request according to a key. here is my code:
```
Cache<String, Integer> cache = Caffeine.newBuilder().expireAfterWrite(1,TimeUnit.MINUTES).maximumSize(10000).build();

public boolean filter(String key){
    cache.asMap().computeIfAbsent(key ,s -> 0);
    Integer sum = cache.asMap().computeIfPresent(key ,(s, num) -> num+1);
    return sum <= 5;    
}
```
When I keep invoking the `filter` method, the cache doesn't expire. But when I stop invoking this method a minute later, the cache expires. The `computeIfPresent` method  invokes the `replace` method, does the `replace` method update the expire time? Is there a way to increase the value like redis's `incr` command?

I am a newbie to this, so would you please tell me how to realize the function? Thanks!

**Comment by ben-manes** [comment]
Note that you could use `compute` to handle both the absent and present case as a single atomic operation. If you want to avoid locking on an update, you could have `computeIfAbsent` return a counter so that updates are cache reads instead. Whether either of those helps depends on the workload.

The `expireAfterWrite` setting will update the expiration time for every mutation for a given key - meaning an insert or update. You can customize this policy by instead using `Expiry` if you want a more variable time, e.g. `num * 30 seconds`, and set different durations for read/create/update.

For rate limiting there are dedicated libraries, like [resilience4j](https://github.com/resilience4j/resilience4j), that may help. They often implement a token bucket algorithm for the decaying behavior. For http/rpc calls, it is also popular to use a side car (like [istio](https://istio.io/)) to avoid special casing each call in an application.

Does any of that help?

**Comment by ben-manes** [comment]
Yes. Note that the policy, using your above configuration, will expire the entry after 1 minute from the time it was created.

**Comment by yanquanyu** [comment]
Thank you very much!
