### ISSUE TITLE
Advice on Collection as value

### ISSUE THREAD

**Issue by adamretter** [ben-manes/caffeine#192]
Hi Ben,

Do you have any advice when I want to have a cache, where there are multiple values for a key? e.g.
```java
Cache<QueryUri, Deque<CompiledQuery>> cache = Caffeine.newBuilder()
                    .maximumSize(maxPoolSize)
                    .expireAfterAccess(timeout, TimeUnit.MILLISECONDS)
                    .build();
```

Basically we want to cache compiled queries. A query is identified by a URI, but its compiled form is not thread-safe and so can only be used by a single-thread at a time. So we keep a stack of compiled queries, the stack can grow (up to a max size), but will never shrink (in the current design).

**Comment by adamretter** [comment]
I guess the question is, if there is any support for adding/removing form the value Deque, or working with Collections as values in Caffeine. I have to head off now, but I will take a look at your suggestions tomorrow AM. Thanks Ben

**Comment by ben-manes** [comment]
Perhaps you want the `asMap` view and a computation? Then you could do `compute`, `computeIfAbsent`, `computeIfPresent`, or `merge` as atomic operations.

**Comment by adamretter** [comment]
@ben-manes Thanks for the suggestion. I did end up using `asMap` along with a concurrent ring-buffer implementation for the value stack. Not sure what you might make of this - https://github.com/adamretter/exist/blob/refactor/caching/src/org/exist/storage/XQueryPool.java#L130

**Comment by ben-manes** [comment]
Makes sense. Be aware that `compute` is a locking operation, so it won't have a high throughput. In the benchmarks that's ~50M ops/s for a `put` regardless of core count. That's likely more than adequate, though, given the bottlenecks are likely elsewhere.

The `MpmcAtomicArrayQueue` might be unnecessary and an `ArrayDeque` used instead. You could create a local `CompiledXQuery[1]` that is populated within the computation. Then the calls outside of the computation check whether this array is filled or not. Since its on the same thread there are no races and no additional costs since you already use a capturing lambda. This assumes you only operate on the queue when inside a computation, since the hash table lock ensures exclusive access.

**Comment by adamretter** [comment]
@ben-manes I assumed that `compute` was lock per-key? Is it rather a single lock for the entire Cache?

Regards your comment about `ArrayDeque` I couldn't see how to operate on it in a thread-safe manner in [`borrowCompiledQuery`](https://github.com/adamretter/exist/blob/refactor/caching/src/org/exist/storage/XQueryPool.java#L191), which is why I opted for the MpmcAtomicArrayQueue. Unfortunately some of the operations that I need to perform in `borrowCompiledQuery` rely on consulting the database and may throw exceptions. That said... I do believe that you might see a better way than I can, so if you have any ideas there that I have misunderstood or not yet explored, please do let me know.

Thanks for all your help as always. Cheers Adam.

**Comment by ben-manes** [comment]
> I assumed that compute was lock per-key? Is it rather a single lock for the entire Cache?

Yes, you're right that it is roughly per-key. `ConcurrentHashMap` locks on the hash bin as a compromise and, assuming uniformly random writes, states that...

```
Lock contention probability for two threads accessing distinct elements is roughly 
1 / (8 * #elements) under random hashes.
```

This is a correct statement for the best they can predict for a general hash table, but in practice many workloads are not uniformly distributed. When that is used in a benchmark it is often idealistic (minimal contention) or to invalidate a competitor's optimizations (e.g. better caching). A good bet is to assume the Pareto principle, and even more so for caches which academics have shown follows the Zipf pattern. 

So while there will be random placement in the hash table, your workload will likely favor certain keys. In a dedicated microbenchmark one might see a performance penalty due to contention. In practice, given the short hold time and real application work, it likely won't matter.

> I couldn't see how to operate on it in a thread-safe manner in borrowCompiledQuery

Your current code is fine, so please don't take my suggestion as anything against JCTools! Merely a trick that I use in the cache to handle this same problem with lambdas, effectively final variables, and concurrent state. In these cases you are using volatile state in order to pass across the lambda boundary for data that is scoped to the same thread. You are using that queue to handle the race since another could steal your item.

```java
CompiledXQuery[] query = new CompiledXQuery[1];
cache.asMap().computeIfPresent(source, (key, queue) -> {
  // do computation work....
  query[0] = queue.poll();
  return queue;
});
return query[0];
```

The `queue` is never accessed outside of the key's lock, so it is not being operated on concurrently. So an `ArrayDeque` or other non-threadsafe structure would be adequate.

The tradeoffs is that this trick isn't beautiful code, adds an allocation, and could add confusing logic. It may be escape analyzed away and a mpmc queue read/write could be more expensive and adds a dependency.
