### ISSUE TITLE
Overlapping classes in the cache.tracing package

### ISSUE THREAD

**Issue by michaelhixson** [ben-manes/caffeine#20]
This might not be an issue that needs solving.

My project uses the `maven-shade-plugin` to build itself into a fat jar.  When I do this, I get warnings that `caffeine` and `tracing-api` define overlapping classes:

```
[WARNING] caffeine-1.2.0.jar, tracing-api-1.2.0.jar define 7 overlappping classes:
[WARNING]   - com.github.benmanes.caffeine.cache.tracing.TraceEvent$Action
[WARNING]   - com.github.benmanes.caffeine.cache.tracing.TracerIdGenerator
[WARNING]   - com.github.benmanes.caffeine.cache.tracing.TraceEvent
[WARNING]   - com.github.benmanes.caffeine.cache.tracing.DisabledTracer
[WARNING]   - com.github.benmanes.caffeine.cache.tracing.TracerHolder
[WARNING]   - com.github.benmanes.caffeine.cache.tracing.TraceEventFormats
[WARNING]   - com.github.benmanes.caffeine.cache.tracing.Tracer
[WARNING] maven-shade-plugin has detected that some .class files
[WARNING] are present in two or more JARs. When this happens, only
[WARNING] one single version of the class is copied in the uberjar.
[WARNING] Usually this is not harmful and you can skeep these
[WARNING] warnings, otherwise try to manually exclude artifacts
[WARNING] based on mvn dependency:tree -Ddetail=true and the above
[WARNING] output
[WARNING] See http://docs.codehaus.org/display/MAVENUSER/Shade+Plugin
```

If I exclude the `tracing-api` dependency like this, I don't get those warnings:

```
<dependency>
  <groupId>com.github.ben-manes.caffeine</groupId>
  <artifactId>caffeine</artifactId>
  <version>${caffeine.version}</version>
  <exclusions>
    <exclusion>
      <groupId>com.github.ben-manes.caffeine</groupId>
      <artifactId>tracing-api</artifactId>
    </exclusion>
  </exclusions>
</dependency>
```	  

But I'm not actually using any tracing features (that I know of), so I don't know if I'm breaking Caffeine by doing that.

Why does `caffeine` declare classes that overlap with `tracing-api`?  Why doesn't it instead (a) not declare those classes, or (b) not depend on `tracing-api`?

Are the two sets of classes equivalent?  Said another way, do I need to be concerned with which versions of those classes that `maven-shade-plugin` chooses to place in the resulting .jar file?

**Comment by ben-manes** [comment]
> Why does caffeine declare classes that overlap with tracing-api?

This is odd, as I don't know why there should be overlapping classes. Each artifact uses its own sub-packages under the `caffeine` package hierarchy and all classes have unique names. Even if you glob them to a single package there should be no conflicts.

> Are the two sets of classes equivalent? Said another way, do I need to be concerned with which versions of those classes that maven-shade-plugin chooses to place in the resulting .jar file?

I assume so, since this shouldn't occur. If you provide a sample I can help you debug what is going on.

> But I'm not actually using any tracing features (that I know of), so I don't know if I'm breaking Caffeine by doing that.

Unfortunately it will, because the tracing api is tightly integrated, but the JIT should dead code eliminate it at runtime. The api is a stub that service loads and no-ops if no implementation is discovered.

> Why doesn't it instead ... not depend on tracing-api?

Because instrumenting it in user-code is selective, error prone, and negates the limited value tracing might provide. The intent is that tracing can be enabled system wide and analyzed offline, but otherwise is a tiny jar. We had wanted this in Guava to answer some design questions, but without good data we abandoned our non-LRU policy prototypes. We also thought it might provide some value to recommend cache sizes, back when Googlers liked the simplicity of soft-references "auto sizing" their caches.

The tracing package is future proofing and shouldn't be causing any problems.

**Comment by michaelhixson** [comment]
Ah...  If I'm reading you right, it sounds like the `com.github.benmanes.caffeine.cache.tracing` package was not meant to be included in `caffeine`.  Could it be a glitch in the deployment then?  If you download the two jars from Maven and look at the class files inside, they do both have that set of classes.

Here are the jars I just verified with:

`caffeine` - http://search.maven.org/remotecontent?filepath=com/github/ben-manes/caffeine/caffeine/1.2.0/caffeine-1.2.0.jar

`tracing-api` - http://search.maven.org/remotecontent?filepath=com/github/ben-manes/caffeine/tracing-api/1.2.0/tracing-api-1.2.0.jar

**Comment by ben-manes** [comment]
Ah, I see what's going on now. It seems that this is an unintentional effect of using the [gradle-bundle-plugin](https://github.com/TomDmitriev/gradle-bundle-plugin) to generate the OSGI manifest. For some reason it is packaging the dependency into the jar too, though it doesn't appear to to do that with other artifacts.

I'm only using the bundle plugin because its a little more convenient to configure than Gradle's [OSGI plugin](https://docs.gradle.org/current/userguide/osgi_plugin.html). I'll see if switching over to that solves this for the next release.

**Comment by ben-manes** [comment]
So the problem was that I declared the bnd instruction `Export-Package`, com.github.benmanes.caffeine.*` assuming that it would only inspect the classes in the module. Instead the bnd tool is also inspects the classes inside dependencies and, since the tracing package falls inside of the wildcard, it grabs them as well.

Both the bundle and official plugin require stating each packages explicitly for this scenario. Once I did that instead of the wildcard the output jar was correct.

Sorry about the inconvenience.

**Comment by ben-manes** [comment]
I just released v1.3.0 which includes this fix. Sorry that it took a while.

**Comment by michaelhixson** [comment]
Thanks!  I imagine this was the least interesting change in the release. :)

**Comment by ben-manes** [comment]
Sadly any bug is a feature (#22) to someone else =)
