### ISSUE TITLE
NPE with AsyncWeigher

### ISSUE THREAD

**Issue by Ked-Ki-Work** [ben-manes/caffeine#206]
When using an `AsyncLoadingCache` where `asyncLoad` can return `CompletableFuture(null)`, there is a potential for `NullPointerException` in `AsyncWeigher`.

Essentially, if the weigher does not null check the value, it can throw an NPE. This violates the documentation of `Weigher`, which has the value argument marked `@NonNull`. 

The culprit for the `Weigher` case seems to be in the definition of `AsyncWeigher`, which delegates to the user-defined weigher whenever the future is done, without null-checking:
```java
    @Override
    public int weigh(K key, CompletableFuture<V> future) {
      return isReady(future) ? delegate.weigh(key, future.join()) : 0;
    }
```
Even though `LocalAsyncLoadingCache.put(K, CompletableFuture<V>)` attempts to check if the future contains null before passing it to the backing cache (and thus invoking the weigher), if the future finishes just after the initial check, but before the weigher is called, this NPE occurs. (See around [this line](https://github.com/ben-manes/caffeine/blob/a8640ef3a8040f76b6bf4f1973204affa9fa5058/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncLoadingCache.java#L246).)

**Comment by ben-manes** [comment]
Thanks for debugging this. The fix seems pretty simple.

Most likely we should also fix the test weighers, etc. in [CacheSpec](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/test/java/com/github/benmanes/caffeine/cache/testing/CacheSpec.java#L183) to assert non-null key/value when appropriate. I think this is why the null tests pass since they assert the entry being discarded, but the configured classes don't NPE due to not inspecting the value.

**Comment by ben-manes** [comment]
I'll try to have a fix out shortly after the holidays.

**Comment by ben-manes** [comment]
Released. Sorry this took a while to get out as it was held up while resolving other bugs.
