### ISSUE TITLE
Make LocalLoadingCache public?

### ISSUE THREAD

**Issue by hugares** [ben-manes/caffeine#208]
Hi,

I am trying to migrate a project from Guava cache to Caffeine. One of the project's cache is extending AbstractLoadingCache and looking around in Caffeine, LocalLoadingCache seemed to be a good starting point but it's not public.

Any chance you can make it public?

Thanks
Hugo

**Comment by ben-manes** [comment]
`AbstractLoadingCache` doesn't carry its weight and I think including it in Guava was a mistake. The code is trivial, it isn't used by the implementation, and doesn't assist much in a new one. `LocalLoadingCache` does a bit more, but was intended to be internal so I am hesitant to open it up. A full fledged cache would be fairly complex, so likely the reuse is very minimal.

I think you'd be better served implementing the methods directly. Since `AbstractLoadingCache` doesn't do anything intelligent, you should be able to write similarly simple code.

**Comment by hugares** [comment]
Thanks for answer. I will follow your advice and implement the methods directly.

**Comment by ben-manes** [comment]
Great. Also note that `ConcurrentStatsCounter` is our equivalent to `SimpleStatsCounter`, as that's perhaps the only class that is useful.
