### ISSUE TITLE
Issue with generics

### ISSUE THREAD

**Issue by panterose** [ben-manes/caffeine#21]
Hi,
I'm trying to do: 
Map<K,V> map = Caffeine.newBuilder()
            .maximumSize(10)
            .build()
            .asMap()
but the compiler is not happy.
It works only if I split the operation in 2: instanciate the cache, then call .asMap() on it.
I'm using 1.8.0_45
Tks
.

**Comment by ben-manes** [comment]
Unfortunately this is a limitation in Java's type inferencing. The problem is that the types are inferred for `Caffeine`, but due to the extra chaining it doesn't look at the LHS until the statement completes. It instead infers `<Object, Object>` as the most generic type.

The way to do this in one statement is to add a type hint,
```java
Map<K, V> map = Caffeine.newBuilder()
    .maximumSize(10)
    .<K, V>build()
    .asMap();
```

That can get pretty verbose when the key/value types are explicit, so your approach of using two statements is probably cleaner code most of the time.

[Past experience](http://concurrentlinkedhashmap.googlecode.com/files/ConcurrentCachingAtGoogle.pdf) showed that using `Map` as a base for a cache wasn't the right model. The `asMap` view is an escape hatch to more explicit control, but most of the time a `LoadingCache` is more appropriate. That lets you avoid explicit `get` / `put` operations and self populate on a `LoadingCache#get`.

The only way to make this perhaps a little friendlier is to have `newBuilder()` be generic to move the type hint to the beginning of the build chain. Then it would look like,
```java
Map<K, V> map = Caffeine.<K, V>newBuilder()
    .maximumSize(10)
    .build()
    .asMap();
```
I don't recall the rational for not doing that in Guava's CacheBuilder, but I'm sure there was one that @kevinb9n would remember. I know it doesn't provide much weight, makes reusing the builder more awkward, and promotes poor usage. Providing a `buildMap()` to support inference would be considered a poor choice for similar reasons.

**Comment by ben-manes** [comment]
Here's the [Guava issue](https://github.com/google/guava/issues/738) which confirms the above rational.

**Comment by ben-manes** [comment]
Feel free to reopen if you have any suggestions. Thanks.

**Comment by xenoterracide** [comment]
could we revisit this in 2024

> The only way to make this perhaps a little friendlier is to have newBuilder() be generic to move the type hint to the beginning of the build chain. Then it would look like,

so I could write

```java
var builder = Caffeine.<String, T>newBuilder()

// or even

var map = Caffeine.<String, T>newBuilder()
    .maximumSize(10)
    .build()
```

this is especially more annoying in the case of adding something like a `removalListener`
