### ISSUE TITLE
Please publish Automatic-Module-Name entries in jars

### ISSUE THREAD

**Issue by io7m** [ben-manes/caffeine#211]
Hello!

I'm in the process of modularizing all of my projects, and I depend on `caffeine` in a couple of places. As `caffeine` isn't modularized (in the JDK 9 sense) it doesn't have a reliable name upon which I can depend for module `requires` clauses.

The easiest way to provide one is to add an `Automatic-Module-Name` field in the manifests of the published jars.

**Comment by ben-manes** [comment]
This has been in my backlog to see how other projects handle it (notably Guava). In particular due to the JSR having poor history of recommendations on module names and we'd likely want to follow Stephen Colebourne's [advice](http://blog.joda.org) instead.

One issue that keeps coming up is the jsr305 annotations and the lack of good alternatives. You might run into issues there due to package conflicts, even though I think the JSR spec was modified to allow it. If we switch, we might need to make the annotations a required dependency to be Scala friendly, since only jsr305 is well known / tolerated and the partial alternatives aren't. Of course then some Java users are frustrated due to their builds failing due to unused transitive dependencies, so it becomes a bit murky.

**Comment by johnou** [comment]
Discussion for Netty project can be found here https://github.com/netty/netty/pull/7245

**Comment by ben-manes** [comment]
Added the manifest entries. You may still need to deal with `javax.annotation` as concerns have been expressed in other projects. This will be in the snapshot repository if you'd like to verify before the next release.

**Comment by ben-manes** [comment]
Released
