### ISSUE TITLE
Provide standard getters in CacheStats

### ISSUE THREAD

**Issue by gmazza** [ben-manes/caffeine#213]
Hi, attempting to return a CacheStats object directly via a [Spring REST API call](https://github.com/gmazza/tightblog/blob/14a0acdb7e3d406309e91bb3bb1e050231b2ff3b/app/src/main/java/org/tightblog/ui/restapi/AdminController.java#L108-111) (in order to display stats on a web UI) returns this error:

org.springframework.http.converter.HttpMessageNotWritableException: Could not write JSON: No
serializer found for class com.github.benmanes.caffeine.cache.stats.CacheStats and no properties
discovered to create BeanSerializer (to avoid exception, disable SerializationFeature.FAIL_ON_EMPTY_BEANS);
nested exception is com.fasterxml.jackson.databind.JsonMappingException: No serializer found for
class com.github.benmanes.caffeine.cache.stats.CacheStats and no properties discovered to create BeanSerializer.

Because there are no standard-named getters in CacheStats (e.g., missCount() and evictionCount() are provided instead of getMissCount() and getEvictionCount()), the Jackson JSON parser can't detect the properties to add to a JSON response.  This results in needing to create and wire in a [JsonSerializer class](https://github.com/gmazza/tightblog/blob/master/app/src/main/java/org/tightblog/rendering/cache/CacheStatsSerializer.java) in order to be able to return a JSON representation of the CacheStats data.  Request here is to either replace the current methods or duplicate them with standard getters so we no longer need this extra coding to get Jackson to process CacheStats objects.

**Comment by ben-manes** [comment]
I think the preferred means to export statistics is using a metrics reporter. Spring uses [Micrometer](http://micrometer.io/) which has [native support](https://github.com/micrometer-metrics/micrometer/blob/master/micrometer-core/src/main/java/io/micrometer/core/instrument/binder/cache/CaffeineCacheMetrics.java) for Caffeine, so it should be easy to use. Then the metrics library handles reporting to different endpoints, be it json / jmx / graphite / etc.

Since the metric libraries, such as [Dropwizard's](http://metrics.dropwizard.io/), don't use bean-bindings this typically hasn't been an issue. So I'd prefer keeping the Guava-style API as is and I think you'll get much more by leveraging a metrics system. Thoughts?

**Comment by gmazza** [comment]
Micrometer is probably a bit heavyweight for what I'm doing right now (that may change).  Looking at their CaffeineCacheMetrics, it would appear to be an easy matter for them to update their code to .getXXX() should you later evaluate it beneficial for Caffeine adoption to update the method names in a major release (you're a better judge than me, so refraining from providing advice here).  Either way,, I already created the JsonSerializer so no problem for me to continue using it.  Thanks!

**Comment by ben-manes** [comment]
I'm going to close for now. I think its too high impact to change and remove the old names and mostly cosmetic. It may not always be perfect, but such is API design. Thanks!
