### ISSUE TITLE
Expiration for maximumSize

### ISSUE THREAD

**Issue by adamretter** [ben-manes/caffeine#214]
Hi @ben-manes can you help us (@joewiz) understand when Cache eviction happens based on Maximum size?

For example if we do:

```java
final Caffeine<String, String> cache = Caffeine.newBuilder().maximumSize(3).build();

cache.put("foo1", "bar1");
cache.put("foo2", "bar2");
cache.put("foo3", "bar3");
cache.put("foo4", "bar4");
cache.put("foo5", "bar5");

System.out.println("estimatedSize=" + cache.estimatedSize());
System.out.println("size=" + cache.asMap().size());
```

Then we see that both `estimatedSize` and `size` report `5`, and not `3`. Is expiration only in-play when using `get` operations?

**Comment by ben-manes** [comment]
By default the policy work is performed asynchronously. This is to avoid locking which would blocking the caller, so instead policy work is batched when possible. After a read or write, an operation is appended to a bounded queue and draining this queue is scheduled on an executor. For reads this occurs after a threshold while writes are immediate. This causes the maximum to be exceeded temporarily, but to not expose a penalty as user-facing latency. The queues are bounded so this can never run away under load.

For unit tests, you can either use a same-thread executor (`Caffeine.executor(Runnable::run)`) or call `cleanUp()`. Both force the calling thread to perform the work. Since the policy is O(1) the work is tiny, as its really the locking that gets expensive under load that we're trying to avoid.

**Comment by adamretter** [comment]
Thanks @ben-manes
