### ISSUE TITLE
Feature Request:  Add .clearStats() to Cache Interface

### ISSUE THREAD

**Issue by gmazza** [ben-manes/caffeine#215]
When calling cache.invalidateAll(), I would also like to erase the CacheStats object returned by Cache.stats() so the stats all start at zero again.  I can't see any way to that with Caffeine currently.  One way I can see is to add .clearStats() to the Cache object, another option would be to add a boolean to the Cache.invalidateAll() method, i.e., .invalidateAll(boolean clearStats).

**Comment by ben-manes** [comment]
The statistics are documented as "monotonically increasing over the lifetime of the cache" so this is not directly supported. You can emulate it using the `CacheStats.minus` method, e.g.

```java
volatile CacheStats snapshot = CacheStats.empty();

void clear() {
  cache.invalidateAll();
  snapshot = cache.stats();
}

CacheStats stats() {
  return cache.stats().minus(snapshot);
}
```

Alternatively, you can provide your own `StatsCounter` and reset the metrics.

Generally this isn't a problem if you export your statistics into a time series database, e.g. using Dropwizard Metrics. Then one can run computations, like a time window, over the data set. These systems tend to expect increasing values rather than each actor performing its own computations, like histograms, by delegating that work to the metrics application.

**Comment by ben-manes** [comment]
The rational when designing this for Guava (Kevin's comment):

>The stats that tend to matter most are things like "stats over the last 2 minutes" and "stats over the last 15 minutes" etc. If you reset, you'll be resetting constantly! And you will have to pick one increment or the other. If you reset every minute, then to get the stats for the last hour you have 60 things to sum up.
>
>In contrast, just saving absolute snapshots and diffing any two endpoints you want to is a lot simpler and more flexible.
>
>Google's monitoring tools are designed so that components who want to report stats only have to worry about reporting monotonically increasing counts, and they handle the rest, which I think is a good approach that keeps the burden of things like "resetting" from being shoved onto every individual component that wants to report stats.
```

**Comment by gmazza** [comment]
Hi Ben, thanks for the alternative implementation suggestion!  Closing this ticket.
