### ISSUE TITLE
BoundedLocalCache.doComputeIfAbsent may infinite loop

### ISSUE THREAD

**Issue by liyongjun1** [ben-manes/caffeine#216]
`private LoadingCache<String, Value> valueCache;

    {
        valueCache = Caffeine.newBuilder()
                .build(key -> {
                    Value value ;
                    if (key.equals("test")) {
                        value = new Value("always");
                    } else {
                        value = valueCache.get("test");
                    }
                    return value;
                });
    }

    private static class Value {
        private String name;

        public Value(String name) {
            this.name = name;
        }
    }

    @Test
    public void testInfiniteLoop() {
        Value value = valueCache.get("a");
        logger.info(value.name);

    }`

When I wanted to get the value from my cache, but the value which I needed were trying to get another value in the cache. Then the infinite loop occurred. I googled the similar scene , is it the bug of  jdk1.8(Infinite loop of ConcurrentHashMap)?

**Comment by ben-manes** [comment]
Yep, please see my [StackOverflow answer](https://stackoverflow.com/questions/28840047/recursive-concurrenthashmap-computeifabsent-call-never-terminates-bug-or-fea/28845674#28845674). I raised the issue during the unveiling of the rewrite, and helped resolve it for JDK9. I had hoped they would backport the fix since it was early after JDK8's release. It turns out that `HashMap` corrupts itself in JDK8 in this scenario and they now throw an exception in JDK9 as well.

In the [FAQ](https://github.com/ben-manes/caffeine/wiki/Faq) there is a workaround discussed using `AsyncLoadingCache`.

**Comment by ben-manes** [comment]
Hope that helped and thanks for checking in about it.

**Comment by liyongjun1** [comment]
yup, I just checked the answer, It helped me to understand the problem I had met. thx!

**Comment by aalku** [comment]
I think this bug should remain open until in https://github.com/ben-manes/caffeine/wiki/Population is explained that it's not a good idea to access the same cache from the loader. Or until you can safely do it :)
