### ISSUE TITLE
Dependency in tracing-async

### ISSUE THREAD

**Issue by GenghisChen** [ben-manes/caffeine#22]
When switching to v1.3.0 the exception below is thrown; this is resolved only if tracing-async is added as a dependency to the project.

    Caused by: java.lang.ClassNotFoundException: com.github.benmanes.caffeine.cache.tracing.Tracer
	    at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1313) ~[catalina.jar:8.0.24]
    	at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1164) ~[catalina.jar:8.0.24]
	    at com.github.benmanes.caffeine.cache.LocalCache.tracer(LocalCache.java:64) ~[caffeine-1.3.0.jar:?]
	    at com.github.benmanes.caffeine.cache.BoundedLocalCache.<init>(BoundedLocalCache.java:140) ~[caffeine-1.3.0.jar:?]

**Comment by ben-manes** [comment]
tracing-api should be added, but automatically due to being a maven dependency. Previously the api classes were accidentally bundled into the jar by the OSGi bnd tool. 

If that doesn't work can you provide me a sample project to investigate with?

**Comment by michaelhixson** [comment]
I get the same thing.  It's a runtime error; the project builds fine.  Was `tracing-api` always `<scope>compile</scope>`?

**Comment by ben-manes** [comment]
Sorry I missed this comment, or I would have replied sooner.

I wonder if this might be because Gradle generates the pom with `tracing-api` in both `compile` scope and `test` scope. Perhaps that's messing it up?

I'll experiment with this on my way home (Caltrain), using Maven as a baseline. I'll make a new release if we can figure this out.

**Comment by michaelhixson** [comment]
Yeah that's it.  1.2.0 had `<scope>test</code>` before `<scope>compile</code>`.  1.3.0 has them in reverse order.  Apparently Maven uses the last defined scope in that situation.

**Comment by ben-manes** [comment]
That's a weird convention. I checked `mvn dependency:tree` with your example and it shows that its not coming in.

I think the only reason the test is used is due to a handy place to stash a reusable utility class, so I can probably fix that another way. I'm not sure how to prioritize the pom dependency order.

**Comment by ben-manes** [comment]
Yeah if I hack the pom in the `.m2/repository` I see that it can resolve iff the scope `test` is before `compile`. So Maven takes the last one defined, probably by abusing a  HashMap.

**Comment by ben-manes** [comment]
I'll release this tonight as `1.3.1`. Thanks!

**Comment by ben-manes** [comment]
Released. I checked all the poms in the staging repository and they all looked good. The jars should sync to central within the next two hours.

**Comment by ben-manes** [comment]
FYi,

Release v2 which no longer includes the tracing packages. A new eviction policy was chosen so capturing traces is no useful enough to be part of the API.
