### ISSUE TITLE
Expire after read

### ISSUE THREAD

**Issue by sjoblomjsqueed** [ben-manes/caffeine#226]
Hi!

I have a rather peculiar use case, and was wondering how to set up a Caffeine Cache to have entries only being hit once, i.e. they should expire directly after being read. So I'd like entries to be kept indefinitely after write, but removed directly after read.

Is this possible, and if so how? I was looking at the `expireAfter(Expiry)` method, but have not been able to find a suitable example.

Thanks in advance!

**Comment by ben-manes** [comment]
That is a very unusual scenario. Yes, you should be able to use `expireAfter(Expiry)` to model this. Note that due to races, etc. there is always the possibility of multiple readers to an entry, as it is not exclusively locked. You may find that a different data structure, even just a synchronized `LinkedHashMap`, is a better fit. Hard to say.

**Comment by ben-manes** [comment]
You might also consider the asMap() view, e.g. remove(key) returns the value or computeIfPresent() can return null for removal.

**Comment by sjoblomjsqueed** [comment]
Thanks for the answers! Would `asMap()` be thread safe? Is there an example of using it somewhere?

**Comment by ben-manes** [comment]
It is threadsafe. It really sounds like a regular ConcurrentHashMap may be enough for you. You might want to review its documentation on the removal and compute methods.

**Comment by ben-manes** [comment]
Closing, but feel free to reopen or discuss further.
