### ISSUE TITLE
BoundedLocalCache never returns

### ISSUE THREAD

**Issue by panghy** [ben-manes/caffeine#228]
Just throwing it out here to see if @ben-manes if you have any ideas, we have seen a cluster of machines suddenly going into a loop and stack trace shows the following:

  ```
 java.lang.Thread.State: RUNNABLE
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:1666)
	- locked <0x00007fc92afffff8> (a com.github.benmanes.caffeine.cache.PSAMS)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache.put(BoundedLocalCache.java:1602)
	at com.github.benmanes.caffeine.cache.LocalManualCache.put(LocalManualCache.java:64)
```

This is running 2.6.1 and essentially threads just yield to one another on the monitor on BoundedLocalCache:1666. The threads never exit the for loop at line 1633. This is a bounded cache (with size limit) and an expire after access of 1 hour.

Thanks for the help.

**Comment by ben-manes** [comment]
hmm, that's surprising. This has not changed much for quite a while, so if there was a race then I'd have hoped the CI would have hit it in the thread thrashing tests.

A quick glance and nothing looks wrong to me, but another set of eyes would help. I am too familiar with the code so I miss issues, unfortunately.

In this case the entry was present so it tries to update (rather than insert, in the earlier block). The entry's lock is acquired for exclusive access, for double checking its state and modifying it accordingly.  If a race occurs like the entry's deletion, it will release the lock and retry. So there is an infinite loop, but it usually terminates quickly since it is unusual of many threads to be modifying an single entry at once.

The entry's lock is held during a computation, e.g. `Map#computeIfPresent` or removal / eviction. If you are using a `CacheWriter` with an expensive `delete(k, v, cause)` implementation, that will execute under the entry's lock. That can block eviction since it is forced wait until the writer completes so that the entry is removed atomically. If you do implement it or other computations, then can you check if this is prone to timeouts or similar failures? If so, do you handle timeouts, etc. correctly?

**Comment by panghy** [comment]
Will take a look at the code to see how it could happen. We are not using a `CacheWriter`. We are really just doing `getIfPresent` and `put`s against the cache but since we have metrics around the code that actually does those calls, we are pretty certain that they are not exiting at all. I also don't see past culprits (from puts with in-flight refresh on a non-async cache or our last embarrassing issue of keys changing hashcode/equality after being in the cache for instance).

**Comment by ben-manes** [comment]
For immediate term, can you use a `get(key, func)` or a `CacheLoader`? That is the preferred usage since it avoids races causing redundant computations (two threads `getIfPresent`, compute, and `put`). That might fix it for the short term, and then maybe you can help me figure out what the problem with `put` is.

**Comment by panghy** [comment]
For our particular use case we can't actually use a loader but thanks for the suggestion. Will continue to look. The strange thing is that it happened to a cluster of machines which seems to suggest that there is a particular key or data shape that can trigger this (would almost be impossible for a race condition by itself to happen across a fleet of machines).

**Comment by ben-manes** [comment]
Are you certain that the threads never return, or do you think you have some DoS attack (usually a misfit internal service) causing a write storm?

**Comment by panghy** [comment]
Yes, because we have counters around the entry points into the cache calls, we are pretty sure that they are in a loop. jstack also shows that they are basically all contending on the same monitor, blocking on each other, with only one single thread gaining access but apparently relinquishing the monitor after the synchronized block (I can only see that from the continue call) and then another thread acquires it, does the same.

**Comment by ben-manes** [comment]
When the entry is no longer "alive", it is either "retired" or "dead". When retired, it should no longer be in the hash table. In all usages that I see, it either retires after a `Map.remove` or as the final statement to a `Map.compute` and returning `null` for removal. The loop should then be that if the cache read the entry, but had a stale read causing it to see a now retired / dead entry, it will retry. In that case, the next read should cause it to see the latest mapping which is either absent or a new insertion. There shouldn't be a case where a `retired` or `dead` entry is present in the cache. So the `continue` should be very rare, which makes this weird. I could imagine cases like an improper expiration time causing constant eviction, but nothing jumps out as causing it to spin forever.

**Comment by ben-manes** [comment]
@panghy have you had any luck in your investigation?

**Comment by panghy** [comment]
Still trying, we just had another occurence of that and again since it hits multiple machines at the same time, I am still going by a data issue (hashCode inconsistencies?). Or there's a bug in CHM? :) dunno

Still chasing.

**Comment by ben-manes** [comment]
If it helps, you could use a patched version of the cache that logs the key info (hash, identity hash, etc) if the loop retries > N times. Should be a very simple hack and easy to add. If you don't have an internal repository then I can push a change to the snapshot. Let me know if there's any way that I can help.

**Comment by panghy** [comment]
We do, we are planning to have the JVMs listening for debugger attach, should be pretty easy to see what's going on once it happens.

**Comment by ben-manes** [comment]
Perhaps you could try using `cache.asMap().compute(key, (k, v) -> value)` as an experiment? This method does not have an infinite loop in Caffeine's code, but does in the underlying `ConcurrentHashMap`. It of course cannot be as optimized. Either it works or fails in a different way, which may tell us something (though I'm not sure what).

**Comment by ben-manes** [comment]
Any updates?

**Comment by panghy** [comment]
Unfortunately I have been on a business trip and AFAIK this hasn't happened again, let me close this for now until we can get another repro
