### ISSUE TITLE
RemovalListener is not worked well

### ISSUE THREAD

**Issue by jiayeee** [ben-manes/caffeine#241]
there maybe a bug, when i using RemovalListener, code **System.out.println(key)** in my testcase is not worked, and my version is 2.6.2. here's the code

```
public static void main(String[] args) throws InterruptedException {

        Cache<String, String> cache = Caffeine.newBuilder() //
            .maximumSize(100) //
            .expireAfterWrite(1, TimeUnit.SECONDS) //
            .removalListener((RemovalListener<String, String>) (key, value, cause) -> {
                System.out.println(key);
            }) //
                .build();

        cache.put("a", "a");
        cache.put("b", "b");
        cache.put("c", "c");

        cache.cleanUp();

        TimeUnit.SECONDS.sleep(5);
    }
```

**Comment by ben-manes** [comment]
The notification is delegated to an executor, by default the shared ForkJoin common pool. For testing an easy fix is to use a same-thread executor by setting `Caffeine.executor(Runnable::run)`. Alternatively you might use Awaitility to test asynchronous behavior.

**Comment by ben-manes** [comment]
Oh, and our expiration is triggered by activity on the cache to cause periodic maintenance cycles. Therefore nothing will happen due to your thread sleeping. This is to avoid creating our own threads, which is typically problematic for libraries. In the future we will offer more eager expiration using the new shared scheduled executor, but for now we restrict ourselves to Java 8 apis.

You can instead use a `FakeTicker` to manipulate time and call cleanUp afterwards to see the expiration occur.

**Comment by jiayeee** [comment]
ok. after i read some introduction about Caffeine and other cache components(such as guava), i understood the working mechanism of RemovalListener, thank you
