### ISSUE TITLE
CacheWriter is not notified of writes done via compute methods

### ISSUE THREAD

**Issue by wburns** [ben-manes/caffeine#245]
I am curious why the CacheWriter is not notified of entries modified when using computational methods. This is mentioned at https://github.com/ben-manes/caffeine/wiki/Writer. It seems like a valid use case to have a user notified of an entry written or deleted via Map.compute and other methods.

It can't be that you don't want to invoke user code while holding a lock, because the writer does this for other methods. The compute method even notifies writers when an entry expired or was collected, when invoking compute. https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L2221

Also, it seems inconsistent that a removalListener can get notified of entries removed via compute. https://github.com/ben-manes/caffeine/wiki/Removal

**Comment by ben-manes** [comment]
Yes, it is a bit surprising at first. (Sorry for being a long, but trying to explain my thought process)

The `write` method could be used to persist the changes to an external system (db, remote cache, etc). It wouldn't be desirable to invoke write as a side effect of your code loading from that resource, only to push it back in. Then when you do an external read and write for every cache miss, which is confusingly wrong.

The intent and desired property is for a user to have the ability to synchronously intercept changes that they otherwise can't. This would be a `put`, `replace`, `remove`, or any form of eviction. In the case of a computation, the user already has a synchronous block controlling the evaluation. If the user knows that the change should be propagated to the external resource (update, delete), then it seems less confusing to have their function do that work. In that case they might extract the shared code (e.g. `deleteFile(entry)`) and call it both from the compute method and `CacheWriter`.

The `RemovalListener` is a slightly different concept. In that case you want to be notified on a removal to do some work. If that work is expensive and does not need to block the map operation, the listener is appropriate because it is asynchronous. However that could lead to conflicts due to the race, e.g. it seems that [guava-cache-overflow-extension](https://github.com/raphw/guava-cache-overflow-extension) was abandoned due to not being a good fit with an asynchronous listener.

So use the `RemovalListener` when you want to perform some action when an entry is removed, and don't need to slow down the map operation. Switch to `CacheWriter` when you need to expand an atomic operation that you don't control to perform some work. And when using a compute method, call the writer logic manually. I think that leads to the least surprising code, even if a subtle characteristic.

Since the interface names are all different (function, listener, writer) it seems okay to have different semantics even when aspects might seem to overlap.

**Comment by wburns** [comment]
Let me explain my use case, first. I am using this for is to store entries into a bounded Caffeine map, but I want to index these entries in an external resource, so some operations don't have to read all contents of the map. In this case I never populate the Caffeine map with values from the index (always the inverse).

> It wouldn't be desirable to invoke write as a side effect of your code loading from that resource, only to push it back in.

Shouldn't the user be using a `CacheLoader` to do this?

The core issue is that the creation of a `Cache` may be completely disconnected from the invocations of said `Cache`. The only way to keep it all at creation time is to build the `ConcurrentMap` and then wrap that using a forwarding map wrapping any user `Function` in another one, causing additional allocations.

Luckily the code I wanted to use this for is only a single level of indirection away so I can I merge the function together with the logic I am invoking in the `CacheWriter`. It just seems like this shouldn't be required and a `CacheWriter` should handle all writes into the map from the user.

**Comment by ben-manes** [comment]
> Shouldn't the user be using a CacheLoader to do this?

`LoadingCache.get(key)` delegates to `Cache.get(key, func)` with the `CacheLoader`, which in turn delegates to `Cache.asMap().computeIfAbsent(key, func)`. I think most users would expect that `get` behaves the same as `computeIfAbsent`, and that `compute` and `computeIfPresent` behave similar to `computeIfAbsent`.

Take the simple case of a local cache backed by memcached, e.g.
```java
Caffeine.newBuilder() // ... plus eviction config
    .writer(new CacheWriter<K, V>() {
        public void write(K key, V value) {
          memcached.put(key, value);
        }
        public void delete(K key, V value, RemovalCause cause) {
          if (!cause.wasEvicted()) {
            memcached.delete(key);
          }
       }
    }).build(key -> {
      V value = memcached.get(key);
      if (value == null) {
        value = repository.get(key);
        memcached.put(key, value);
      }
      return value;
    });
```

If the writer was invoked after a load/compute, then we could avoid the loader's `memcached.put`. Unfortunately, we also wouldn't know if the load was satisfied by finding the value in memcached or the database, and wouldn't have a way to communicate that. In that case we'd perform a `memcached.put` unnecessarily on a remote cache hit.

For caching libraries with a `CacheLoader` and `CacheWriter`, they don't typically have ad hoc compute methods. JCache kind of does, but its APIs are also wildly inconsistent and often incompatible with itself. Instead most caches restrict flexibility to provide more features (like multiple caching tiers). Rather than build lots of variations of similar features, by being in-memory we can try to keep it simpler and more adaptable. Then our library feels more like a fancy `ConcurrentMap` and treated as another encapsulated data structure, rather than a full blown storage service like memcached or Postgres.

> The core issue is that the creation of a Cache may be completely disconnected from the invocations of said Cache. The only way to keep it all at creation time is to build the ConcurrentMap and then wrap that using a forwarding map wrapping any user Function in another one, causing additional allocations.

Yes, that's unfortunate and understandable for Infinispan. I think most users can get away with encapsulating the cache within domain abstraction, e.g. `UserService`, and use dependency injection to wire it up. Then their code is making on a few explicit calls to the cache, can wrap tweak as needed, and hide that from consumers of their interface. The cost for them is really low.

> Luckily the code I wanted to use this for is only a single level of indirection away so I can I merge the function together with the logic I am invoking in the CacheWriter. It just seems like this shouldn't be required and a CacheWriter should handle all writes into the map from the user.

I think that would have to be another variation, as that's understandable but the current behavior is also required for other users. However, it might not carry its weight since the current versions let you do something you can't do otherwise. This new variation would only assist in a less common scenario, which also adds confusion of which type to use. So far my feeling is that it does not have a good power-to-weight ratio, but I am open to being convinced otherwise.

**Comment by wburns** [comment]
> I think most users would expect that get behaves the same as computeIfAbsent, and that compute and computeIfPresent behave similar to computeIfAbsent

I am not sure what you mean by `computeIfAbsent` working like get. Unless you mean if the value is present, then I would think it work like get. But I would think computeIfAbsent would work like the Javadoc states https://docs.oracle.com/javase/8/docs/api/java/util/Map.html#computeIfAbsent-K-java.util.function.Function-. That is that it inserts the value if there was no value before and the function returned a non null value. I would expect to get a write notification in this case.

> If the writer was invoked after a load/compute, then we could avoid the loader's memcached.put. Unfortunately, we also wouldn't know if the load was satisfied by finding the value in memcached or the database, and wouldn't have a way to communicate that. In that case we'd perform a memcached.put unnecessarily on a remote cache hit.

It sounds like you are lumping `CacheLoader.load` invocation in with `compute` methods. These are totally different things. They might be the same in the current implementation, but that is just implementation details. I personally believe that the `CacheLoader.load` should not cause notifications for write operations, otherwise you would get the double remote invocations as you stated. But there is no reason a `compute` method should cause double in this case.

The code that you showed above wouldn't need to change if only `compute` and friends were changed to raise write notifications. It sounds like just the underlying caffeine impl of `CacheLoader.load` would have to change to no longer call into `compute` allowing notifications (put already has an argument like that).

In fact the code above seems it could be a bit cleaner even. This uses two external sources (memcached and some resource to create data). In my opinion memcached should only be in the `CacheWriter` and `CacheLoader` and the user would use `compute`  or other method themselves to call into the resource. If `compute` notifications are generated then the following could be done.

```java
Caffeine<K, V> caffeine = Caffeine.newBuilder() // ... plus eviction config
    .writer(new CacheWriter<K, V>() {
        public void write(K key, V value) {
          memcached.put(key, value);
        }
        public void delete(K key, V value, RemovalCause cause) {
          if (!cause.wasEvicted()) {
            memcached.delete(key);
          }
       }
    }).build(memcached::get);
   ConcurrentMap<K, V> map = caffeine.build().asMap();
   V value = map.computeIfAbsent(k ->repository.get(key));
```

This way storage isn't tied to how objects are created (meaning you could have different services per key even). This seems much cleaner to me. Lets say for example if you want to only do a get and ignore calculating the value if it can't read from memcached, there is no way with the impl you posted. And I assume that `getIfPresent` doesn't query the `CacheLoader`, allowing the user to possibly hit both cache levels (caffeine, memcached) and the actual service, as needed.

And as I mentioned above, your code would still work and the user can just call `get` if they wanted instead of `computeIfAbsent`.

> For caching libraries with a CacheLoader and CacheWriter, they don't typically have ad hoc compute methods.

Not that it matters, but Infinispan supports this.

**Comment by wburns** [comment]
> Map.get does not invoke the loader and only peeks into the cache, as Cache.getIfPresent

I didn't realize this. I guess I thought since `LoadingCache.get` was the same name they did the same thing. In that case I agree that the behavior should be the same between the value returned from `Map.get` and the value provided to `Map.computeIfAbsent` etc. Although I think this was a bit off course from the original issue.

Also, this means that the writer beneath can't hold the various `Map` contracts like `put` since it won't be able to return the previous value if an entry was evicted. So `Writer|Loader` and `asMap` should only be used in conjunction for secondary caching, and not storage with eviction (`Cache/LoadingCache` hold their contracts). Just putting this here for posterity :)

I am still not fully convinced that `Map.compute` shouldn't raise a notification, but I understand the predicament you have now :( So I can go ahead and close this out. Luckily I have an easy enough workaround for my use case anyways.

> Well of course it does! Infinispan is quite rich and well thought out 😄

It took a few versions and me wondering why we weren't consistent with the API, to get there, haha.
