### ISSUE TITLE
[Feature request] Add OccupancyRate in Cachestats 

### ISSUE THREAD

**Issue by jiming** [ben-manes/caffeine#249]
Hi Ben,

`Cachestats.OccupancyRate = Cache.estimatedSize()/Cache.maximumSize().`

This rate is useful when I want to monitor a cache instance, whether should I enlarge the maximumSize. In real life, it is not easy to set proper maximumSize. With `Cachestats.OccupancyRate` and other metrics in CacheStats, which will help a little bit.

Thank!

Jiming

**Comment by ben-manes** [comment]
Thanks for the suggestion.

This isn’t general since some configurations do not use maximumSize, e.g. maximumWeight. So pushing additional metrics like this might make sense for your reporting (e.g. Dropwizard) rather than ours.

Since most caches fill to capacity (100%), I’m not sure how useful it is. What you really want is to know the miss rate curve at different maximum sizes. Can the cache be reduced while maintaining the effective hit rate? Will an increase result in a large gain? This is likely out of scope for us, though papers like MiniSim provide mechanisms. It requires sampling with ghost caches, which could be helpful as profiling but not generally enabled. I don’t think we should venture here as it’s fairly murky.

**Comment by jiming** [comment]
Dear Ben,

I think the way I use cache might not totally same with you. Some cases, the cache fill to capacity(100%). However there have other case, I hope capacity should not over n%, otherwise it should be warned. 

For example, some config information in database, I expect that all of them should be in cache and can be refreshed by expireAfterWrite. I do not know exact config item count. So I will set the maximum sizes to 100 if I estimate the count is less than 80. When OccupancyRate is over 80%, I should be warned and I will tuning the maximum sizes.

I think maximumWeight is resolvable. If maximumWeight is set, use maximumWeight to calculate OccupancyRate. Otherwise use maximumSize.

Thanks!
Jiming

**Comment by ben-manes** [comment]
That's a good point, sometimes a cache is merely a limit against unexpected growth.

There are two reasons I'm hesitant. First is still the generality of the metric. For example weak or soft reference-based caches, while less ideal, do not have an occupancy rate due to being bounded by the JVM. The existing metrics are a baseline that are not coupled to a particular setting.

The other reason is philosophical of trying to provide capabilities that users can't easily implement themselves, but also avoid excess "kitchen sink" bloat. This is pretty minor request, but pragmatically I'd imagine wouldn't gain much versus doing it yourself. Typically metrics are reported using Dropwizard, Prometheus, Micrometer, etc. As a library (vs framework) it doesn't prefer a transport (e.g. JMX) and instead you can wire it up. For example to do this using Dropwizard Metrics you might write,

```java
MetricRegistry metrics; // likely injected
Gauge<Double> occupancyRate = () -> 
    cache.estimatedSize() / (double) cache.policy().eviction.get().getMaximum();
metrics.register(name("usersCache", "occupancyRate"), occupancyRate);
```

When you wrap that into an instrumentation helper class, for any cache constructed, you'd have all the metrics exposed using shared code. Then the benefit of having them in `CacheStats` is a very minor convenience factor, saving maybe a line of code. When using a library like Micrometer, you can report the stats anywhere (console, jmx, grafana, etc) to easily create alerts and dashboards.

For now I do think you write the above calculation isn't such a bad thing. What do you think?

**Comment by jiming** [comment]
Thanks ben, I'll use your method:)

**Comment by ben-manes** [comment]
And thank you for the suggestions! 😄
