### ISSUE TITLE
CacheWriter.delete not called instantly when an entry expires.

### ISSUE THREAD

**Issue by mehwhatever** [ben-manes/caffeine#253]
With reference to this [stackoverflow post](https://stackoverflow.com/questions/51006885/have-a-partitioned-segregated-in-memory-in-process-guava-caffeine-cache)

I have a map `keyToCacheMap` which keeps  a track that which key is present in which Caffeine cache. `keyToCacheMap` is updated via a common `CacheWriter writer` when a key is inserted. This `writer` also takes care to remove from `keyToCacheMap` when an entry gets evicted.

What is happening is `keyToCacheMap` says that a key exists and is pointing to a `cache`. However when I look up that `cache` it simply returns null. This is  happening because when an entry is getting expired, the `writer` is not being notified (I put logs) , and a lookup is happening on that specific `cache`.

Let me know if you are not able to understand something. Will post some code then.

**Comment by ben-manes** [comment]
Oh, I see now. Sorry that I misunderstood and thanks for the explanation.

The cache does not create its own dedicated threads to schedule and promptly expire entries. Some caches do this, either as a framework singleton or per cache instance. That can be problematic or create a lot of overhead. But we might offer something similar in a JDK9+ release by taking advantage of the new `CompletableFuture.delayedExecutor` API, which provides a JVM-wide scheduler. This would allow best-effort prompt expiration if desired.

Instead the cache hides expired entries when queried for and evicts them during a maintenance cycle. The maintenance cycle is triggered on a write, accumulation of reads, or `Cache.cleanUp()`. The expiration order is kept in amortized O(1) data structures, so the work is pretty fast. But since is concurrent and we don't want to stop all reads/writes with a blocking lock, there will always be a possible race of reading a to-be-expired entry before the eviction occurs.

If your cache has low activity and you need a little better promptness, you can schedule a call to `cleanUp()` yourself on a `ScheduledExecutorService`.

Does that help?

**Comment by mehwhatever** [comment]
Got you. I want to avoid a `ScheduledExecutorService` since my cache would be under heavy load.

So when I want to implement `isKeyPresentInCache`, I will have to look up the `keyToCacheMap` as well as do a `cache.asMap().containsKey` on the cache it points to. Correct?
