### ISSUE TITLE
Questions - Cache clean up without using a maintenance thread

### ISSUE THREAD

**Issue by azagniotov** [ben-manes/caffeine#257]
Hi @ben-manes,

I could not find a better place to ask the following, therefore I am opening the current issue. 

My question is regarding a maintenance clean up approach that I am thinking to implement. This approach does not make use of a maintenance thread.

I want to make use of `CacheWriter` and cache's notification mechanism by acting on `RemovalCause.EXPIRED` events to perform a maintenance clean up. Consider the following interface:

Implementations of this interface would construct instances of the `Cache<String, T>` by invoking the `build(long)`. At runtime, when a cache entry expires and the `delete` handler is invoked, a reference to the respective cache instance is obtained by invoking `nativeCache()` and then calling `cleanUp()` on it to clean up.  The idea here is to call `cleanUp()` after `N` entries have expired.

Do you see any issues with this approach?

```
public interface MyCache<T> {
    
    default Cache<String, T> build(final long expireAfterWriteSeconds) {

        final Cache<String, T> nativeCache = Caffeine.newBuilder()
                .expireAfterWrite(expireAfterWriteSeconds, TimeUnit.SECONDS)
                .writer(new CacheWriter<String, T>() {

                    private static final int CACHE_CLEANUP_THRESHOLD = <SOME_VALUE>; 
                    private final AtomicInteger expiredEntryCounter = new AtomicInteger(0);

                    @Override
                    public void write(String key, T value) {
                        //NO-OP
                    }

                    @Override
                    public void delete(final String key, final T value, final RemovalCause removalCause) {
                        if (removalCause == RemovalCause.EXPIRED) {
                            if (expiredEntryCounter.incrementAndGet() == CACHE_CLEANUP_THRESHOLD) {
                                nativeCache().cleanUp();
                                expiredEntryCounter.set(0);
                            }
                        }
                    }
                })
                .build();

        return nativeCache;
    }

    Cache<String, T> nativeCache();
}
```

**Comment by ben-manes** [comment]
Hi @azagniotov,

There are a few potential issues. I think it would be helpful if you described the problem you are trying to solve, which led this your idea.

Firstly, I think your code will fail if you try running it. `CacheWriter` methods are invoked within a `ConcurrentHashMap#compute` block to allow the work to be performed atomically. A nested write to the map within this block is not allowed and will either livelock (JDK8) or throw an exception (JDK9). This might be solved using a `RemovalListener` which is invoked outside of the computation.

Another issue is that expiration is performed lazily, as in when the maintenance cycle runs or the entry is overwritten. This means that there will be a delay as the cache does not create dedicated threads to event on, but rather is triggered by usage activity. JDK9 introduced a dedicated JVM-wide scheduling thread via `ComputableFuture#delayedExecutor`, so a future version might leverage this for prompt expiration as a configuration option. This might mean your maintenance trigger is less useful if you are expecting immediate expiration events.

`Cache#cleanUp` is fairly fast, assuming the eviction `compute` call is not slow (e.g. an `CacheWriter#delete`). All of the algorithms that Caffeine uses are strict or amortized O(1), and that work is inexpensive. If you are concerned about the usage of `ForkJoinPool#commonPool()` by default, you can use `Caffeine#executor(Runnable::run)` instead to avoid the background thread.

Anyway, I hope that helps. If you can provide more background then maybe we can find a better solution.

**Comment by azagniotov** [comment]
Hi @ben-manes ,

Thank you so much for this elaborate response. It definitely helps to gain a better understanding about the shortcomings of my suggested approach.

To have a background maintenance worker that does periodic clean up is totally fine for my use case. Thank you again for clarifying the low level details.

**Comment by ben-manes** [comment]
The background worker is really just there to avoid variability in your response times. It definitely can be run on the callers without much of a penalty. So I am glad that's not an issue.

We trigger maintenance pretty regularly when there is activity. Effectively we have an access and write queues, which when populated the maintenance is scheduled. We replay the operations to keep the policies up to date, rather than have the callers bang on our locks. So other than adding improvements for prompt expiration, its usually quite seamless and performant.

Happy to answer more questions; Have a great weekend!

**Comment by azagniotov** [comment]
Thanks, @ben-manes ! I do want to clarify the following:

According to my understanding when an entry expires, a miss is emulated by the cache if entry is still present. With that in mind and what you said earlier, consider the following potential use case:

A single instance of my service processes around 50 QPS. I cache query result for 30 seconds (expire after write). Since (as you mentioned) you perform maintenance pretty regularly when there is activity, I am curious if there a need for a maintenance task? 

I am asking this not because I am concerned about incurring a penalty of running a thread, but whether I should just let the cache do its work. 

Thank you and have a great weekend too!

**Comment by ben-manes** [comment]
Your observation makes sense when there is also a maximum size, as it would leave pollution but not require extra work. That improves concurrency and is simpler, but wastes space. Ehcache, memcached, and redis all use that solution. However, the pollution adds significant waste which is why both memcached and redis have dedicated threads to scan the cache and remove expired entries.

In a size unbounded cache, then of course waiting until the entry is queried would be a potential memory leak. I've seen some do this and may use the background thread to assist, but then they usually use a full scan to discover the expired entries.

For us the maintenance task is used for a few cases. In particular for size-bounding, where every cache read is actually a write to the eviction policy (e.g. LRU). That mutation requires locking on shared state, which is a bottleneck. We could use a concurrent policy like Clock (FIFO-based) or random sampling, but that can negatively impact the hit rate or runtime performance. Instead we record the work into ring buffers and replay it in batch under a tryLock, so that calling threads don't block. We replace lock contention with the cost of appending to a ring buffer (a single CAS). The actual policy work is usually just pointer manipulation, so its very tiny per element.

With these ring buffers in place, we get to use the maintenance task to easily handle complex algorithms that are not concurrency friendly:
 - size eviction: We maximize the hit-rate using an advanced algorithm called W-TinyLFU
 - fixed expiration: We use time-ordered LRU lists for expireAfterWrite and expireAfterRead
 - variable expiration: We use a Hierarchical TimerWheel as an O(1) priority queue
 - references: We can poll a `ReferenceQueue` without synchronization overhead

So instead of the maintenance task being something to avoid, its actually a great approach that allows us to offer a lot of performance and capabilities.

**Comment by azagniotov** [comment]
Thank you, @ben-manes

**Comment by ben-manes** [comment]
I missed your question on the queue sizes. They are based on the number of CPUs and grow based on contention / usage. (On phone so not checking code for sizes)

The read buffer is dynamically striped, with each ring buffer holding 16 elements if I recall correctly. I think it’s 4xcpu max stripes. When full it drops additions and triggers the maintenance task. The striping is based on LongAdder.

The write buffer is a jctools growable ring buffer. It starts small and expands as needed. If full there is back pressure by forcing the caller to block on the policy lock and perform the maintenance. This improves throughput by descheduling threads. The maximum is likely overly generous but hasn’t been an issue so far. It was set by monitoring the throughput in a synthetic write heavy stress test.

**Comment by azagniotov** [comment]
Thank you for clarifying more, @ben-manes. 

I ended up configuring an instance `ScheduledExecutorService` and passing it to `Caffeine.newBuilder().executor(...)`. 

The executor is scheduled to call `cleanUp()` at fixed rate using the following formulae `Math.ceil(expireAfterWriteSeconds * 0.05)` where `0.05` is a multiplication factor. In other words, if cache entry lifetime is `30` secs, the maintenance task will kick in every `2` secs. I just picked this number to start with.

I am planning to run a series of performance tests and observe heap utilization with and without the maintenance thread. I can scale up my service to around 450 qps, so I am curious to see if maintenance task makes any difference in my case.

**Comment by azagniotov** [comment]
Thank you. Yes, in my case I am only doing a maintenance task, without other user-facing async tasks.

Stay tuned, will report shortly

**Comment by azagniotov** [comment]
The limitation that I see with the maintenance task is that it is configured with a static period. e.g.: the clean up frequency has to be manually adjusted if throughput increases/decreases over time, in order to optimize heap utilization (when it makes sense to do so).

**Comment by ben-manes** [comment]
The task will still be scheduled automatically when enough reads or a write occurs. I imagine your schedule would kick in to more proactively notify listeners when an entry expires. Or do you delay the tasks submitted into your executor?

**Comment by azagniotov** [comment]
Yes, I understand that the cache will internally perform a maintenance when queues will get full. I submit a task to trigger `cleanUp()` that will be invoked by executor periodically at a fixed rate. For clarity, this is my code:

```
default Cache<String, T> build(final long expireAfterWriteSeconds, final long maxHeapEntries) {
    final double multiplicationFactor = 0.05;
    final long maintenanceFrequencySeconds = (long) Math.ceil(expireAfterWriteSeconds * multiplicationFactor);

    final ScheduledExecutorService maintenanceService = Executors.newScheduledThreadPool(1);
        maintenanceService.scheduleAtFixedRate(() -> {
            nativeCache().cleanUp();
        }, maintenanceFrequencySeconds, maintenanceFrequencySeconds, TimeUnit.SECONDS);
      
    return Caffeine.newBuilder()
                .expireAfterWrite(expireAfterWriteSeconds, TimeUnit.SECONDS)
                .maximumSize(maxHeapEntries)
                .executor(maintenanceService)
                .softValues()
                .build();     
}

Cache<String, T> nativeCache();
```

**Comment by ben-manes** [comment]
great, looks good!

**Comment by azagniotov** [comment]
Thanks for reassurance, @ben-manes. I will start a few perf test runs tonight

**Comment by azagniotov** [comment]
Hello @ben-manes, I ran a two performance tests runs where in one run I was running without the maintenance thread, while in the other run I had it configured as per above.  Please see the heap utilization from both runs in the graphs below:

#### Running with a periodic maintenance task
Gradually increased load: 200 rps, 250 rps, 300 rps, 350 rps & 400 rps

<img width="683" alt="55 caffeine heap" src="https://user-images.githubusercontent.com/989900/43482121-a3481596-94bc-11e8-95b9-c4e65fc59192.png">

#### Running without a maintenance task
Gradually increased load: 200 rps, 250 rps, 300 rps, 350 rps & 400 rps

<img width="685" alt="99 caffeine heap" src="https://user-images.githubusercontent.com/989900/43482109-993def94-94bc-11e8-9f79-8cc6665c175d.png">

**Comment by ben-manes** [comment]
The dedicated thread for maintenance does seem to have better heap behavior, if we go by percent used. A likely cause could be that `ForkJoinPool` is share JVM-wide so its threads are being used for handling http requests, etc. That would delay the maintenance task from running, so more writes accumulate. The dedicated thread wouldn't have this problem, but is of course less friendly in the general case to have a thread-per-cache (but okay for dedicated systems). You could verify that by using your threadpool w/o the periodic task.

It would also be interesting if you used `Runnable::run`, e.g. no executor, which would defer to calling threads. Since you are not doing heavy work during eviction, the penalty imposed on the caller's latency is probably insignificant. That would avoid the dedicated thread and any task scheduling issues.

What are your thoughts when reading the graphs?

**Comment by azagniotov** [comment]
As you pointed out: if judging by %, it does seem that when a maintenance thread is configured, the heap utilized better. A little more context about my service: it does not actually have an explicit threadpool configured. It is an event-drive & non-blocking IO app on Netty+Vert.x stack that uses `N` event loop threads (configurable). I do not do any CPU-intensive operations, therefore I do not configure an explicit threadpool through Vert.x to perform those

I can have another run with `Runnable::run` and see whether there is a difference. If I understand you correctly, my Cache config should be now as follows:
```
default Cache<String, T> build(final long expireAfterWriteSeconds, final long maxHeapEntries) {
    return Caffeine.newBuilder()
                .expireAfterWrite(expireAfterWriteSeconds, TimeUnit.SECONDS)
                .maximumSize(maxHeapEntries)
                 .executor(runnable -> {
                    nativeCache().cleanUp();
                })
                .softValues()
                .build();     
}
```

**Comment by ben-manes** [comment]
You shouldn't need to ignore the submitted task. The same effect will be more safely done by using:

```java
default Cache<String, T> build(final long expireAfterWriteSeconds, final long maxHeapEntries) {
    return Caffeine.newBuilder()
                .expireAfterWrite(expireAfterWriteSeconds, TimeUnit.SECONDS)
                .maximumSize(maxHeapEntries)
                 .executor(Runnable::run)
                .softValues()
                .build();     
}
```

**Comment by azagniotov** [comment]
Alright. Stay tuned. Will report back shortly

**Comment by azagniotov** [comment]
@ben-manes I did the perf test run:

#### Running with `Runnable:run`

Gradually increased load: 200 rps, 250 rps, 300 rps, 350 rps & 400 rps

<img width="668" alt="999 caffeine heap" src="https://user-images.githubusercontent.com/989900/43500476-988a4180-9505-11e8-8559-4f665a964cc3.png">

Going by the heap utilization percentage, it appears that in my case the heap was utilized better when running with `ScheduledExecutorService`. Using the `Runnable:run` showed better results than not using executor at all, but not as good when using `ScheduledExecutorService`

**Comment by ben-manes** [comment]
Thanks for the feedback! It’s definitely interesting to see. Are there any takeaways we should highlight from your investigation?

**Comment by azagniotov** [comment]
Hi @ben-manes ,

The takeaway that jumps at me after my investigation: in the case of non-blocking I/O & event-driven app that runs on a main event loop thread, it made sense to have a dedicated thread doing periodic cleanup. 

Regarding the soft references, to be honest I was not driven by any concrete data from my own testing when I configured `.softValues()`. I just wanted to signal to GC that it can clear soft referenced objects on response to memory demand if required. It may be a premature optimization at this stage, I admit.

What do you think?

**Comment by ben-manes** [comment]
That sounds reasonable. If you have a few big caches in critical sections, e.g. Druid's or Cassandra's row caches, then the performance gain is worth the dedicated thread. If a typical web application with lots of ad hoc caches, then it won't be worth it.

I typically avoid soft references and view it as a last resort. It can cause hard to diagnose performance problems if unbounded, due to causing a GC death spiral of full collections. It sounds good in theory, but typically isn't. However, some managed environments (like AppEngine) were so memory constrained that it was impossible to size and forced poor GC behavior regardless, so it can be a necessary evil. For the most part, avoiding the GC from doing extra work is a performance gain.

I do try to be respectful to the GC regarding references, so hopefully the setting doesn't change your results. When an entry is evicted / removed, `Reference#clear()` is invoked which hopefully helps the GC know not to do the weak/soft reference work. If you have the free resources, it would be interesting to know if `softValues()` causes heap pollution regardless or if your heap utilization is unaffected.

**Comment by azagniotov** [comment]
Based on this discussion that we are having, I think I should rethink whether to have this option enabled (e.g.: `softValues`) when I do not have an apparent reason. I will run another set of performance tests without the `softValues`, but with a maintenance task and one more time with  `Runnable:run`

**Comment by Maaartinus** [comment]
>  If a typical web application with lots of ad hoc caches, then it won't be worth it.
> 
> I typically avoid soft references and view it as a last resort. It can cause hard to diagnose performance problems if unbounded

@ben-manes In case of many caches, it's unclear, how to optimally size them. Assuming all of them are about equally important and use somehow compatible settings, it'd be probably best to sort of join them in a single big cache. I wonder, if something like
```
SharedWeightLimit limit = Caffeine.sharedWeightLimit(1000);
Cache<SomeKey, SomeValue> cache1 = Caffeine.weighter(...).maximumWeight(limit).build();
LoadingCache<AnotherKey, AnotherValue> cache2 = Caffeine.weighter(...).maximumWeight(limit).build(key -> createValue(key));
```
makes sense to you?

**Comment by Maaartinus** [comment]
> might want to take into account the hit rate, load penalty, popularity, etc. of the caches

This can get arbitrarily complicated and you may spend years tuning the settings... My idea was actually the opposite: Inside of a cache, there's a clear policy telling us which entry is more important. So, I'd apply the same idea across caches: The very same algorithm should be used for comparing entries from different caches.

A very hacky implementation for two caches having the same settings would be just:
```
Cache<Object, Object> implCache = Caffeine.weighter(...).maximumWeight(limit).build();
Cache<String, Integer> cache1 = new Cache<>() {
    public Integer get(String key) {
        return (Integer) implCache.get(composeKey(key, 1));
    }
    ...
};
Cache<Whatever, Whatever> cache2 = new Cache<>() {...};
```
Yes, I mean put them all in a single cache and let them all compete against each other. As long as their settings are the same (or somehow compatible), all what's needed are some facades. With different settings, some support inside of the cache would be needed (I can't see how much and if it could work well).

This is assuming that all caches are equally important. Otherwise, we could use something like my old knapsack analogy, giving not only `weight` but also `value` to entries.

> You're welcome to try =)

I'd gladly would (caching is one of the most interesting topics for me), but somehow, I'm always short of time.... I can recall, some long time ago I wanted to continue playing with the simulator.

**Comment by ben-manes** [comment]
> but somehow, I'm always short of time....

haha, yes. I think we're in the same boat. I do enjoy these conversations, though.

**Comment by azagniotov** [comment]
Hi @ben-manes, I did another run: 

#### Running with a periodic maintenance task, without softValues option set.
Gradually increased load: 200 rps, 250 rps, 300 rps, 350 rps & 400 rps

<img width="654" alt="9999 no soft caffeine heap" src="https://user-images.githubusercontent.com/989900/43801981-629ef1c6-9a49-11e8-848a-dcc5cdbda943.png">

Judging by the `%` only and comparing with the graph in https://github.com/ben-manes/caffeine/issues/257#issuecomment-409340779 (`Running with a periodic maintenance task` graph), I see that it is better to have `.softValues` enabled

**Comment by ben-manes** [comment]
cool, thanks for the info! Its good to see the JVM takes the opportunity to scavenge proactively when it makes sense.

G1GC (now default) treats soft references different than previous collectors and is more aggressive. Older collectors, like CMS, are generational and require waiting for the full GC. G1 is region-based so it does not wait until a stop-the-world event and collects within that region. This can mean it will discard soft references too quickly, e.g. my tests run with parallel GC for predictable outcomes. By chance did you capture the hit rates between runs? Just curious if as a side effect the hit rate dropped significantly, or if comparable and it was purely a gain.
