### ISSUE TITLE
How to Keep order of Cache?

### ISSUE THREAD

**Issue by alx696** [ben-manes/caffeine#258]
Cache data order(from sql with order by):
```
[t1-c2, t1-c1, t3-c2, t3-c1]
```
Cache.asMap().keySet() order(just need to return the data with same order):
```
[t1-c2, t3-c1, t1-c1, t3-c2]
```
How to Keep order of Cache?

Some times, after  `Cache.put` the order changed too?!

**Comment by ben-manes** [comment]
The cache does not maintain insertion or sorted order. The `asMap()` order is from `ConcurrentHashMap`, which is hashed mappings. The cache otherwise can provide order from the `policy()` for the hottest/coldest or youngest/oldest as determined by its eviction policy.

You could maintain a separate map that is kept in sync with the cache by using a `CacheWriter` and `CacheLoader`.

**Comment by alx696** [comment]
Thanks for your reply!

I add a List<String> to cache the keys, so the keys keep order. And i want to know, do i need to use Cache?

I just Cache all, Iterator all.

Cache is better than Map?

**Comment by alx696** [comment]
Ok, thanks very much.
