### ISSUE TITLE
Can Expiry be used to mimic "expireAfterAccess"

### ISSUE THREAD

**Issue by boschb** [ben-manes/caffeine#259]
I've been digging through the code and it seems that the behavior of Expiry and expireAfterAccess type methods are totally decoupled.  They appear to operate independently, but correct me if I am wrong.

I would like to be able to use an Expiry to utilize the variable nature of the expiration time but also apply it to an 'access' type policy.  I thought I might just use the same value in Update/Read to mimic the behavior but that now seems totally wrong as doing a read wont stop the 'update' expiration from firing... Hopefully you know what i'm talking about :) Maybe you can comment further on the behavior?

As always thanks!

**Comment by ben-manes** [comment]
Yes, you should be able to. `expireAfterAccess` is a fixed policy that resets the timestamp on any read or write to the entry. The corresponding `Expiry` would look like:
```java
var duration = Duration.ofMinutes(???);
new Expiry<K, V> {
  public long expireAfterCreate(K key, V value, long currentTime) {
    return duration.toNanos();
  }
  public long expireAfterUpdate(K key, V value, long currentTime, long currentDuration) {
    return duration.toNanos();
  }
  public long expireAfterRead(K key, V value, long currentTime, long currentDuration) {
    return duration.toNanos();
  }
}
```

`Expiry` is called on the creation, update, or read of an entry. If you want to ignore the change, such as expire after a fixed time from creation, you can return `currentDuration`.

You can't combine `expireAfter(Expiry)` with `expireAfterAccess` or `expireAfterWrite`, so you'll be fine there. `Expiry` provides a variable, custom policy whereas the others set fixed lifetimes.

The implementations differ because `Expiry` was added later. The fixed policies were simple to implement using time-bounded LRU list, e.g. it merely reorders the entry to the tail of a doubly-linked list. The cache uses only O(1) algorithms, but variable expiration traditionally requires either O(lg n) priority queue (like a heap) or polluting the cache with dead entries and evicting on a size constraint (e.g. memcached). Instead, we use a Hierarchical TimerWheel which does this using a nifty hashing trick. Since the fixed policies were implemented, it didn't seem worth the effort / bugs to replace their logic with an `Expiry`.

**Comment by boschb** [comment]
I should have wrote my tests first because they would have confirmed this behavior indeed works.  If you're interested here is what I was doing:

```java
/** Helpers for creating a custom {@link Expiry} using lambda {@link Supplier}s */
public final class Expiries {
  /**
   * combines: {@link Expiry#expireAfterCreate(Object, Object, long)} and {@link
   * Expiry#expireAfterUpdate(Object, Object, long, long)} to simulate the same behavior as {@link
   * com.github.benmanes.caffeine.cache.Caffeine#expireAfterWrite(java.time.Duration)}
   */
  public static <K1, V1> Expiry<K1, V1> expireAfterWrite(Supplier<Duration> supplier) {
    return new DefaultExpiry<K1, V1>() {
      @Override
      public long expireAfterCreate(K1 key, V1 value, long currentTime) {
        return Durations.toNanos(supplier.get());
      }

      @Override
      public long expireAfterUpdate(K1 key, V1 value, long currentTime, long currentDuration) {
        return Durations.toNanos(supplier.get());
      }
    };
  }

  /**
   * combines: {@link Expiry#expireAfterCreate(Object, Object, long)}, {@link
   * Expiry#expireAfterUpdate(Object, Object, long, long)}, and {@link
   * Expiry#expireAfterRead(Object, Object, long, long)} to simulate the same behavior as {@link
   * com.github.benmanes.caffeine.cache.Caffeine#expireAfterAccess(java.time.Duration)}
   */
  public static <K1, V1> Expiry<K1, V1> expireAfterAccess(Supplier<Duration> supplier) {
    return new DefaultExpiry<K1, V1>() {
      @Override
      public long expireAfterCreate(K1 key, V1 value, long currentTime) {
        return Durations.toNanos(supplier.get());
      }

      @Override
      public long expireAfterUpdate(K1 key, V1 value, long currentTime, long currentDuration) {
        return Durations.toNanos(supplier.get());
      }

      @Override
      public long expireAfterRead(K1 key, V1 value, long currentTime, long currentDuration) {
        return Durations.toNanos(supplier.get());
      }
    };
  }

  /** see: {@link Expiry#expireAfterCreate(Object, Object, long)} */
  public static <K1, V1> Expiry<K1, V1> expireAfterCreate(Supplier<Duration> supplier) {
    return new DefaultExpiry<K1, V1>() {
      @Override
      public long expireAfterCreate(K1 key, V1 value, long currentTime) {
        return Durations.toNanos(supplier.get());
      }
    };
  }

  /** see: {@link Expiry#expireAfterUpdate(Object, Object, long, long)} */
  public static <K1, V1> Expiry<K1, V1> expireAfterUpdate(Supplier<Duration> supplier) {
    return new DefaultExpiry<K1, V1>() {
      @Override
      public long expireAfterUpdate(K1 key, V1 value, long currentTime, long currentDuration) {
        return Durations.toNanos(supplier.get());
      }
    };
  }

  /** see: {@link Expiry#expireAfterRead(Object, Object, long, long)} */
  public static <K1, V1> Expiry<K1, V1> expireAfterRead(Supplier<Duration> supplier) {
    return new DefaultExpiry<K1, V1>() {
      @Override
      public long expireAfterRead(K1 key, V1 value, long currentTime, long currentDuration) {
        return Durations.toNanos(supplier.get());
      }
    };
  }

  /** Default implementation of {@link Expiry} which has no expiration */
  private static class DefaultExpiry<K, V> implements Expiry<K, V> {
    @Override
    public long expireAfterCreate(K key, V value, long currentTime) {
      return Long.MAX_VALUE;
    }

    @Override
    public long expireAfterUpdate(K key, V value, long currentTime, long currentDuration) {
      return currentDuration;
    }

    @Override
    public long expireAfterRead(K key, V value, long currentTime, long currentDuration) {
      return currentDuration;
    }
  }
}
```

And I use it like this:
```java
AtomicLong expireTime = new AtomicLong(1_000); // Just some mutable reference

Caffeine.newBuilder()
        .expireAfter(Expiries.expireAfterAccess(() -> Durations.fromNanos(expireTime.get())))
        .build();
```

I have the test too if you want just let me know.

**Comment by ben-manes** [comment]
I have wondered if some utility like your `Expiries` would be helpful, but the need didn't come up. The main quirk with `Expiry` is that it uses `long` instead of `Duration` for time. That's to avoid allocations on hot paths, as the cost is non-negligible until value types land. Since it is a special case feature, it felt okay to put that burden on those few users. Since `Expiry` doesn't get used very often, I haven't been sure what utility methods might make it more attractive / usable.

We did add `expireAfterAccess(Duration)` and `expireAfterWrite(Duration)` convenience methods. What is the benefit of your `Supplier` parameter? I'd have thought it would be `BiFunction<K1, V1, Duration>` if you wanted the time to vary per entry.

If you're just wanting to change the fixed expiration setting at runtime you can use `cache.policy().expireAfterAccess().get().setExpiresAfter(Duration)`.

**Comment by boschb** [comment]
Ohh that is very interesting, I didn't know there was a way to change the policy at runtime.  I'll have to see if that works better for the real implementation which is pulling from a `@ConfigScoped` Guice binding that might change infrequently O(days) (this is CDD/ProtoConf if that rings a bell).  Is there any performance gain you think to using the original expireAfterAccess version instead of Expiry?

Thanks! I'm seriously starting to get how many fine details you've put into this project.

**Comment by ben-manes** [comment]
Yeah, `policy()` turned out to be a handy place to stash all the crazy asks that pop up without corrupting the core interfaces.

> Is there any performance gain you think to using the original expireAfterAccess version instead of Expiry?

In practice, nope. The fixed expiration is strict O(1) because it is just LRU reordering, so insanely cheap. The variable expiration is amortized O(1) because it hashes to a bucket (linked list of items in the same time range) for add/delete, but cascades to lower buckets as time progresses. The Kafka folks wrote a nice [article](https://www.confluent.io/blog/apache-kafka-purgatory-hierarchical-timing-wheels/) on the algorithm, and its used by OSes for interrupt scheduling. I fine tuned my implementation with bitwise tricks, so it's very speedy. You might enjoy taking a [look](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/TimerWheel.java). :)

> @ConfigScoped

Is that a custom scope? I grok what you're doing, but haven't seen related code. I've tended to use static flags and bounce the fleet to avoid oddities that occur when runtime changes are only partially picked up. But I can appreciate both perspectives.

**Comment by boschb** [comment]
Thanks I will check that out.

Yah it is a custom scope for configuration that can get pushed out at runtime.  I'm experimenting with this for things that should be immune to oddities (like cache expiration time for instance).  Worst case should just be a cache miss (I hope).  There is pretty good validation protection around the values during pushes so I thought I'd give it a go for once and see what "large fleet runtime configuration tuning" feels like :)
