### ISSUE TITLE
AsyncLoadingCaches will cache Mono's in error.

### ISSUE THREAD

**Issue by dave-fl** [ben-manes/caffeine#260]
The following will cache the error.  This test should pass, it does not.

	public static <KEY, VALUE> Mono<VALUE> lookupAndWrite(
			AsyncLoadingCache<KEY, VALUE> cache, KEY key, Mono<VALUE> mono) {
		return Mono.fromFuture(cache.get(key, (k,e) -> mono.toFuture()));
	}

	@Test
	public void repeat5() {
		WebClient client = WebClient.create();
		String uri = "http://idontexist";

		AsyncLoadingCache<String, String> cache = Caffeine.newBuilder().maximumSize(1000)
				.expireAfterWrite(Duration.ofMinutes(60)).buildAsync(key -> null);

		Mono<ClientResponse> response = client.get().uri(uri).exchange();
		Mono<String> stringMono = response.flatMap(clientResponse -> clientResponse.bodyToMono(String.class));
		Mono<String> cachedValue = lookupAndWrite(cache, "key", stringMono);
		StepVerifier.create(cachedValue).verifyError();
		Assert.assertEquals(0, cache.synchronous().asMap().size());
	}

**Comment by ben-manes** [comment]
This is probably because there is a race condition between the error and the callback removing the entry from the cache. This was also in #254, but I don't see any good solution to that.

Since you are dealing with asynchronous code, you probably want to use [Awaitility](https://github.com/awaitility/awaitility) and `await().until(cache.synchronous(), is(anEmptyMap())`.

**Comment by dave-fl** [comment]
On subsequent is it possible that the key will be there?

Is this a bug or is the test case invalid?

**Comment by ben-manes** [comment]
pardon? There is a race condition that the cache cannot control

t0. Future is added to cache
t1. Future starts computing
t2. Future sets state to error
t3. Future notifies callback
t4. Callback removes from cache

There isn't an opportunity to remove from the cache between `t1` and `t2` because we do not control the computation logic. We have to wait until `t3` to be notified, but that is after the future's state was set. Therefore, there is a small duration where the cache will return the failed future.

The only wait to inject ourself into the computation is to wrap the user's. However, if the user provides a future then they might expect the same instance be returned by the cache. There could be adjacently managed logic depending on that, as it seems reasonable to not expect an intermediary. If we broke that assumption would could hide the race, but valid arguments can be made in either decision. Instead, you could eagerly invalidate the entry as part of the computation by providing your own callback and caching the chained instance. For example,

```java
var future = ...
cache.get(key, k -> {
  return future.whenComplete((r, e) -> {
    if (e != null) {
      cache.invalidate(key);
    }
  });
});
```

**Comment by dave-fl** [comment]
Thank you for explaining the internals.  These intricacies should be outlined as most users might be unaware of this (the case here until running the test).  It doesn't feel right for an item to briefly be there and potentially removed, but it is good that both can be handled.

**Comment by dave-fl** [comment]
Shouldn't invalidate be part of the `AsyncLoadingCache` interface?

**Comment by ben-manes** [comment]
I think that's the trouble with any asynchronous / concurrent code, because we typically think synchronously. It's the same behavior if you wrote the code manually using a `Map<K, Future>` and using callbacks, which would be idiomatic. I usually find it best to have that type of code at the edges of an application, so that most code can be in their own sequential universe.

> Shouldn't invalidate be part of the AsyncLoadingCache interface?

Currently you have to drill through the synchronous view. It could be added as a default method for convenience, but that's not much of a difference.

**Comment by dave-fl** [comment]
Had some deadlock issues with the above.  This seems to correct it.  Could you explain why that might be the case.

	public static <KEY, VALUE> Mono<VALUE> lookupAndWrite2(
			AsyncLoadingCache<KEY, VALUE> cache, KEY key, Mono<VALUE> mono) {
		CompletableFuture<VALUE> future = mono.toFuture();
		return Mono.fromFuture(cache.get(key, (k, e) -> future.whenCompleteAsync((r, t) -> {
			if (t != null) {
				cache.synchronous().invalidate(key);
			}
		},e)));
	}

**Comment by ben-manes** [comment]
I guess the future's computation was invoked immediately, e.g. if the `Mono` was already done. Sorry, forgot about that case.

The reason is that `ConcurrentHashMap` does not support writes within a computation, so it livelocks (Java 8) or throws an exception (Java 9) when that occurs.

**Comment by dave-fl** [comment]
Here is the test that causes that.

	public static <KEY, VALUE> Mono<VALUE> lookupAndWrite2(
			AsyncLoadingCache<KEY, VALUE> cache, KEY key, Mono<VALUE> mono) {
		CompletableFuture<VALUE> future = mono.toFuture();
		return Mono.fromFuture(cache.get(key, (k, e) -> future.whenCompleteAsync((r, t) -> {
			if (t != null) {
				cache.synchronous().invalidate(key);
			}
		},e)));
	}

	public static <KEY, VALUE> Mono<VALUE> lookupAndWrite3(
			AsyncLoadingCache<KEY, VALUE> cache, KEY key, Mono<VALUE> mono) {
		CompletableFuture<VALUE> future = mono.toFuture();
		return Mono.fromFuture(cache.get(key, (k, e) -> future.whenComplete((r, t) -> {
			if (t != null) {
				cache.synchronous().invalidate(key);
			}
		})));
	}

	@Test
	public void simpleError() {
		Mono<Object> error = Mono.error(new NullPointerException());
		AsyncLoadingCache<String, Object> cache = Caffeine.newBuilder().maximumSize(1000)
				.expireAfterWrite(Duration.ofMinutes(60)).buildAsync(key -> null);
		Mono<Object> cacheResult = lookupAndWrite3(cache, "key", error);
		StepVerifier.create(cacheResult).verifyError();
	}

Is `lookupAndWrite2` here safe in that case?

**Comment by ben-manes** [comment]
I think you deleted the comment. But you're right, `lookupAndWrite2` is safe and `lookupAndWrite3` is unsafe. Because the mono was completed, the `whenComplete` executed on the same thread and wrote back into the cache. Thus, it was in a `computeIfAbsent` calling `remove` which is a recursive write. For a bit of history, you can follow the links in this SO [answer](https://stackoverflow.com/a/28845674/19450).

**Comment by dave-fl** [comment]
For anyone who might find these writes useful.

	public static <KEY, VALUE> Mono<VALUE> lookupAndWrite2(
			AsyncLoadingCache<KEY, VALUE> cache, KEY key, Mono<VALUE> mono) {
		CompletableFuture<VALUE> future = mono.toFuture();
		return Mono.fromFuture(cache.get(key, (k, e) -> future.whenCompleteAsync((r, t) -> {
			if (t != null) {
				cache.synchronous().invalidate(key);
			}
		},e)));
	}

	public static <KEY, VALUE> Mono<VALUE> lookupAndWrite3(
			AsyncLoadingCache<KEY, VALUE> cache, KEY key, Mono<VALUE> mono) {
		CompletableFuture<VALUE> future = mono.toFuture();
		return Mono.fromFuture(cache.get(key, (k, e) -> future.whenComplete((r, t) -> {
			if (t != null) {
				cache.synchronous().invalidate(key);
			}
		})));
	}

**Comment by dave-fl** [comment]
Hopefully the last thing.

One thing that I am uncertain of (the size of the cache does not matter to me).  But a realistic use case.

Referencing above.

What happens if thread TR0 is at (step t1) and thread TR1 comes and tries to access the cache (step t0) with the same key as thread TR0.

Will the second thread get the same object?  Would this behavior be different depending on if `lookupAndWrite` or `lookupAndWrite2` is used?

**Comment by ben-manes** [comment]
`Cache#get` is the same as `ConcurrentHashMap#computeIfAbsent`, and we use the hash table behind the scenes. It will take a (roughly) per-key lock so the first thread creates the entry, while the second blocks until complete and returns the entry's value. The cache will return the same entry, assuming it wasn't discarded due to an error / null value / eviction.

If the Mono fails, then I think in `lookupAndWrite` it will propagate that error until the cache is notified by its `whenComplete` on the future to remove the entry. Thus the entry will be completed and failed for a short duration within the cache. In `lookupAndWrite2` the failed entry will be removed from the cache prior to being completed, as it removes itself from the cache as part of its finalization logic. The cache will only hold successful or in-flight entries. All previous lookups or lookups during the `whenCompleteAsync` execution will see obtain a `Mono` that will fail.

The only difference is whether you see the cache holding `success`, `error`, `in-flight` or `success and `in-flight`. However, reads are lock-free so they may walk an immutable chain created by a writer. So there is always a chance (measured in nanoseconds) that all three states might be in the cache, from a consumers perspective. I think your code won't be different between the 2 or 3 state conditions, so I think 3 is okay as you have to handle failures regardless.

**Comment by dave-fl** [comment]
Thank you for the discussion Ben.

One thing that I just noticed.  Was that none of the futures are being run on the executor pool that is passed to Caffeine.  They are being run on the main thread.  Changing `lookupAndWrite3` to

	public static <KEY, VALUE> Mono<VALUE> lookupAndWrite3(
			AsyncLoadingCache<KEY, VALUE> cache, KEY key, Mono<VALUE> mono) {
		return Mono.defer(() -> Mono.fromFuture(cache.get(key, (k, e) -> {
			CompletableFuture<VALUE> future = mono.subscribeOn(Schedulers.fromExecutor(e)).toFuture();
			return future.whenComplete((r, t) -> {
				if (t != null) {
					cache.synchronous().invalidate(key);
				}
			});
		})));
	}

Seems to solve the blocking issue as it forces the code to run on Caffeine's executor.  All similar to how `lookupAndWrite2` does its invalidation on another thread.  I am guessing you would expect your users to want to run the task on Caffeine's executor.

I am not certain on the full implications of this, but I would think we lose some of the benefits of NIO, so I am not certain how much this changes things over using `Mon.block()` on a separate scheduler.

I think the important point here is this isn't necessarily a one size fits all solution.  There will be times where a stampede might not be likely and thus you want to enjoy the benefits of NIO and times where a stampede can take place and you want to be able to prevent that.

**Comment by ben-manes** [comment]
Oh, thank you. These types of things are always fun to discuss (less so to debug!).

Caffeine will execute the map operations on the caller and then defer any future it creates to the configured executor. If the loading function is synchronous, then it will be wrapped as asynchronous using the executor (see [CacheLoader#asyncLoad](https://github.com/ben-manes/caffeine/blob/29389bef6351bad4b60e8d432a5d1cb208d2db52/caffeine/src/main/java/com/github/benmanes/caffeine/cache/CacheLoader.java#L99-L111)).

I would think if users don't have a preference, then they'd expect to have their work executed on Caffeine's executor. Sometimes when integrating with an async library, e.g. an http call, it is already being done on the http client's pool and wrapping that is undesirable. One reason why I think returning the given future instead of chaining it (per original discussion) is then cancelling / obtrudung / etc might be hard to propagate correctly (user cancels A' but original A still running).

I agree you don't want to block on a future / promise / mono unless absolutely required. I'm not super familiar with Reactor / RxJava, so the best idioms there is your expertise. 😄

**Comment by dave-fl** [comment]
Based on what I see - `Mono.toFuture` is fully blocking.  The future will run as soon as its called.

**Comment by ben-manes** [comment]
[MonoToCompletableFuture](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/MonoToCompletableFuture.java) appears to be invoked by `onNext` and calls `complete(t)`. So I think it shouldn't be blocking.

**Comment by dave-fl** [comment]
I have a very simple test case where I go from a callable, to a defer to a future and the callable is called the same time that toFuture is invoked.

**Comment by dave-fl** [comment]
Check out [Mono.toFuture](https://github.com/reactor/reactor-core/blob/master/reactor-core/src/main/java/reactor/core/publisher/Mono.java)

Everything preceding that call will be suscribed to the newly generated `MonoToCompletableFuture`

**Comment by ben-manes** [comment]
right, that's how I found `MonoToCompletableFuture` earlier. But shouldn't that only be called when the `Mono` completes? If you use `Awaitility`, you can test concurrent lifecycle behavior using `AtomicBoolean` and `awaits()`. Then you'll know for sure.

A quick usage example,

```java
AtomicBoolean started = new AtomicBoolean();
AtomicBoolean done = new AtomicBoolean();
CompletableFuture<Void> future = cache.get(context.absentKey(), () -> {
  started.set(true);
  await().untilTrue(done);
});

await().untilTrue(started); // wait until future is running
done.set(true); // allow future to complete
await().until(valueFuture::isDone, is(true)); // wait until completed
```

**Comment by dave-fl** [comment]
The subscription behavior that I saw in the `Mono.toFuture` seems to have an issue with Spring Security.  I've opened an issue here.

https://github.com/spring-projects/spring-security/issues/5690

Not your bug obviously but something to be aware of.
