### ISSUE TITLE
Difference of Caffeine and JCache ExpiryPolicy semantics

### ISSUE THREAD

**Issue by cruftex** [ben-manes/caffeine#265]
Hi Ben,

I just found that sentence on the wiki:

> WARNING: JCache designed ExpiryPolicy to lazily expire entries and rely on a maximum size constraint for eviction.

The term "lazily expire" could be misleading and interpreted as "lagging expiry" meaning it is legal that the entry becomes invalid a little after the expiry duration. The standard doesn't say something about that, but there is a TCK test that checks whether expiry happens after a few milliseconds, so I would assume that JCache implementations should not have a lagging expiry.

> It is expected by the specification that all uses have an additional size constraint, even though the specification does not support that capability.

I don't see that need. Why you think so?

In JCache, "expiry" means the entry is invalid and not returned any more, or, reloaded in case of a read through configuration. The JCache standard does not say anything about eviction in this case. Since the entry is invalid it can be evicted eagerly (to use your terminology) or not, as the implementation prefers.

Maybe this can be clarified. Why is the Caffeine native implementation incompatible to the JCache expiry concept?

**Comment by ben-manes** [comment]
hmm... yeah, I should rewrite that. Thanks for the note. I think it was before I had variable support, initially implementing the adapter, and was listening to one of the spec members talk’s. But it’s not quite right as you point out and just got pulled along with other edits, rather than revisited.

**Comment by ben-manes** [comment]
I forgot about this, but took the new years break to catch up.

The actual problem is that Caffeine's expiration and JCache's were not integrated together. At the time this was because we lacked variable expiration. Therefore, like Ehcache and others, it relied on eventually evicting the entry by a maximum size constraint by wrapping the entry to include extra metadata. However, since JCache doesn't have that concept in its configuration, it would be trivial to observe a memory leak because expired entries are not discarded until accessed again. That was ugly and the wiki tried to warn about it, but didn't phrase the problem well.

The adapter already had support for native expiration to remove entries promptly. The ideal would be to drop the value wrapper to not retain any custom metadata and defer entirely to Caffeine's variable support. Unfortunately that almost worked, but had some lifecycle differences from the TCK due to event notifications. The one that blocked me is that a create event is not published if the inserted entry immediately expires. This requires that the adapter evaluates the duration during a `Map.compute` to return `null` and suppress the callbacks. Otherwise the callbacks will observe the entry, fire, and evict. To bridge these lifecycles would require some entry metadata. At that point we gain a little less expiration code, but more special logic that can be confusing, and the configuration wouldn't be backwards incompatible for other reasons. 

Given the need for some metadata, instead I simply allowed Caffeine's native handling to consume it to read the entry's timestamp to schedule its removal. That was a minor, more surgical improvement and something I should have realized much sooner. I'll also update the wiki to remove this incorrect messaging.
