### ISSUE TITLE
Possibility to clear Stats for cache after invalidation of all entries?

### ISSUE THREAD

**Issue by woidda** [ben-manes/caffeine#27]
There should be a possibility to clear all stats for a cache. As far as I can tell there is no such option -- at least I could not find one for the current API. This is usefull for having some kind of poor mans "cache manager", that displays basic information for used caches and enables invalidation of certain caches.

Invalidating a cache via `cache.invalidateAll()` does remove the objects from the cache, but there should be a "reset all stats" option -- since the stat apply  only to the old state.

**Comment by ben-manes** [comment]
When this came up in Guava the reason we didn't do this was,

>
The stats that tend to matter most are things like "stats over the last 2 minutes" and "stats over the last 15 minutes" etc. If you reset, you'll be resetting constantly! And you will have to pick one increment or the other. If you reset every minute, then to get the stats for the last hour you have 60 things to sum up.
>
In contrast, just saving absolute snapshots and diffing any two endpoints you want to is a lot simpler and more flexible. 
>
Google's monitoring tools are designed so that components who want to report stats only have to worry about reporting monotonically increasing counts, and they handle the rest, which I think is a good approach that keeps the burden of things like "resetting" from being shoved onto every individual component that wants to report stats.

You can use a reporting library like [Dropwizard Metrics](https://dropwizard.github.io/metrics) or similar to get that behavior. This keeps the cache statistics simple, and those wanting to build a caching framework can handle the bridge code (cache manager, config file, reporting, etc).

**Comment by woidda** [comment]
Well, thanks for your quick reply. I see the point. I do not think that the stats are very useful for doing some serious monitoring / statistics. Dropwizard Metrics and other are indeed better suited for achieving that goal.

On the other hand, for me it seemed to be a little bit strange that after a cache invalidates its content, the hit count and other metrics remain unchanged. But I see the point.

**Comment by ben-manes** [comment]
It would get weird. An `invalidateAll()` resets the hit count, but `invalidate(key)` and `invalidateAll(keys)` does not? Its simpler to think of the statistics over the lifetime of the cache. The `plus()` and `minus()` methods on `CacheStats` makes it easy to take a snapshot prior to clearing the cache to report on the increment.

**Comment by woidda** [comment]
I guess, that makes sense. In the JavaDoc for `Cache.stats()` it describes this behavior implicitly. 
Thanks for your great work.

**Comment by ben-manes** [comment]
Closing, but feel free to reopen if you (or anyone else) has thoughts on this. I'm happy to entertain api changes for V2.

**Comment by ben-manes** [comment]
FYI,

In v2 you can supply your own `StatsCounter` implementation. That could provide a hook to manually reset the counters, if deemed necessary. The intent was to simplify integration with reporting tools, though.

**Comment by woidda** [comment]
Excellent ;-)
