### ISSUE TITLE
Cache Persistence

### ISSUE THREAD

**Issue by QubitPi** [ben-manes/caffeine#274]
We have a need to flush cache into disk for few minutes and then read them back into memory again.

Does Caffeine support such use case?

**Comment by ben-manes** [comment]
You might use a `CacheWriter` for that. It probably depends what semantics you want for `flush`. If you do so on size eviction, `CacheWriter` to persist and `CacheLoader` to fetch would be a good fit. If you are updating through the cache, you can of course use `asMap().computeXXX` which bypasses the loader and writer. Most likely the only thing you want to avoid is using `RemovalListener` since it is asynchronous to the cache operation, so you would have possible data races.

**Comment by QubitPi** [comment]
We are not flush parts of the cache. We are flushing everything in cache to an external source. 

We would flush periodically; something like dumping all cache into an persistent resource readable by Caffeine cache.

**Comment by QubitPi** [comment]
In that case, does Caffeine provides an interface for easy writes and reads between the cache and the external temporary storage? It looks like we have to implement out own `CacheWriter` for that, is that correct?

**Comment by ben-manes** [comment]
In that case you might just use the `asMap()` view and iterate over the contents.

The `CacheWriter` is mostly helpful when you need a synchronous hook for removal, e.g. when done automatically by eviction. But it's also a little brittle by not being able to intercept all calls, e.g. loads, since the various concepts (load, map methods) don't always mix together well.

**Comment by QubitPi** [comment]
`asMap()` sounds good.

Thank you!
