### ISSUE TITLE
Is LFU behavior deterministic?

### ISSUE THREAD

**Issue by QubitPi** [ben-manes/caffeine#275]
Based on its doc, https://github.com/ben-manes/caffeine/wiki/Efficiency#window-tinylfu, there seems to be no guarantee that the least frequently used entry will be evicted. Does that mean a test on the LFU behavior is expected to fail with some small probability?

**Comment by ben-manes** [comment]
Its true that it is not a strict LFU, as we do not retain frequency order. The latest work to appear at the Middleware Conf in December (can send privately) further evolves the policy to adapt towards recency or frequency depending the the workload. The goal is to maximize hit rates rather than be deterministic.

The implementation is explicitly non-deterministic, which can cause test failures. This is to protect against HashDoS attacks ([explanation](https://github.com/ben-manes/caffeine/wiki/Design#hashdos-protection)). This small amount of jitter protects against an attack vector without degrading the hit rate, but also adds enough noise to make tests flaky.

**Comment by QubitPi** [comment]
Thanks! We'll modify out tests for that.
