### ISSUE TITLE
When using Jcache extension, add a way to provide an Executor factory in TypeSafe's Config to populate CaffeineConfiguration

### ISSUE THREAD

**Issue by phylexx** [ben-manes/caffeine#276]
When using the Jcache extension and loading Caffeine using the `CachingProvider` SPI implementation (`CaffeineCachingProvider`), the cache is easily setup and configured. But the TypeSafe's config does not provide any way to use a dedicated `Executor` instead of the `ForkJoinPool` used by default in `CaffeineConfiguration`.
Which means, to set up a custom `Executor`, one cannot use the SPI, but needs to manually assemble the pieces and eagerly load the caches as follow : 
* load the TypeSafe's Config (`ConfigFactory.load()`)
* call the `CacheManagerImpl` constructor passing the loaded Config
* iterate over all caches defined in the config to call `CacheManagerImpl.createCache` with the tuned `CaffeineConfiguration` built from `TypesafeConfigurator.from` method.

I may have missed something, but it would be easier if we could specify in the TypeSafe's config : 
* an `Executor` factory (which could be provided by a Dependency Injection Framework)
* or some kind of customizer/initializer class which could be called to customize the `CaffeineConfiguration` before instantiating caches.

**Comment by phylexx** [comment]
Thanks for your quick reply.
I read in other issues, that you only override the Executor for test purposes. In our case, Caffeine is used as an application cache for slow changing data (combined with Spring @Cacheable). But we prefer libraries do not rely on ForkJoinPool by default and would like to set a dedicated Executor for a given library. The goal is to segregate resources to avoid libraries to compete for ForkJoinPool threads.

I agree I can achieve my goal by using the JCache/Caffeine API's, this issue is a non blocking one. The Executor is the only configuration part which is not copied from TypeSafe's config to CaffeineConfiguration. The idea of this issue is to try to close the gap since it took some time to figure out how to do it :)

**Comment by ben-manes** [comment]
Have you considered using Spring's native Caffeine support? That would let you configure the cache as bean with the executor. Our use of FJP is lightweight, so usually it doesn't compete much and setting to a same-thread executor is okay. We mostly use it to avoid impacting calling threads if user-facing, e.g. any latencies incurred by a configured removal listener. Otherwise the cache's maintenance work is cheap O(1) operations so fast and cheap.

Sorry for that bit of pain due to the missing configuration. I'm on a bit of a hiatus and I know a lot of work is piling up. I do hope to get back to this project, perhaps as things slow down for the holidays, but otherwise I can only promise to provide prompt responses and fix critical issues. So I hope you can live with this pain for a little bit longer, but thanks for pointing it out and we should definitely fix it.

**Comment by phylexx** [comment]
Our first try was to use Spring Caffeine native support, but we are using a 4.1.x spring which was not providing it, we then fallback to jcache integration.

We are quite confident about your usage of FJP. Another point is that the need for FJP is hidden when using default Caffeine configuration,  customizing the conf will express more clearly in the app the requirement.

But we can definitely live without this improvement since this issue is providing 3 workarounds :
* the one in the original issue message
* yours : create cache, get conf, customize it, destroy cache and recreate it using customized conf.
* use spring Caffeine native integration

I let you choose,  if this is a real need for Caffeine in the future. This issue will at least document a few ways to customize the executor.

Thanks for your answers and the interisting job you have done with Caffeine.

**Comment by ben-manes** [comment]
Released 2.7

**Comment by phylexx** [comment]
Hi Ben,

Thank you for taking this feature request into account.
I'm glad you found some time to release a new version of Caffeine, we will test it as soon as possible !

**Comment by ben-manes** [comment]
Thanks! Sorry it took so long to get to. This was a big release with some cool additions.
