### ISSUE TITLE
Behavior of Caffeine when concurrent requests are waiting on cache loader and it throws exceptions

### ISSUE THREAD

**Issue by mmmkkaaayy** [ben-manes/caffeine#287]
Hi, apologies if this is already known - I had tried searching for it but couldn't find anything relevant.

Let's say you have some concurrent requests to a Caffeine cache for the same key such that they are combined into a single invocation of the CacheLoader. If the loader throws an exception, then Caffeine will not throw the exception to all waiting threads. Rather, it will throw an exception to the first thread that called it, then try to call the loader again for the second thread. If the loader keeps throwing exceptions, this is repeated for all waiting threads. 

This is different from Guava's behavior, where it immediately throws the exception to all waiting threads. It is potentially dangerous for systems where threads are a limited resource. When you have a lot of concurrent requests && the loader invocation is somewhat expensive && loader is returning a non-retryable exception, then the threads near the end of the 'queue' will be stuck waiting for a long time.

Asks
1. Consider improving documentation around this behavior on the `get` API
2. Add a configuration to the Caffeine builder to change this behavior to mirror Guava's. Right now, to achieve that, I have to create a wrapper class which can either return a result or exception, and return that from the loader. Then I have to immediately invalidate the result. This looks/feels very hacky. 
2.5 Alternatively, this behavior could be exposed via another `get` API

Code to reproduce issue:
```
import com.github.benmanes.caffeine.cache.Caffeine;
import com.google.common.cache.CacheBuilder;
import com.google.common.util.concurrent.UncheckedExecutionException;
import org.junit.Test;

import java.util.concurrent.*;
import java.util.function.Supplier;

public class ConcurrentCacheExceptionTest {

    public static final int NUM_THREADS = 8;

    @Test
    public void testCaffeine() throws InterruptedException {
        com.github.benmanes.caffeine.cache.Cache<String, String> caffeineCache = Caffeine.newBuilder().build();
        testConcurrentException(() -> caffeineCache.get("key", this::doWork));
    }

    @Test
    public void testGuava() throws InterruptedException {
        com.google.common.cache.Cache<String, String> guavaCache = CacheBuilder.newBuilder().build();
        testConcurrentException(() -> {
            try {
                return guavaCache.get("key", () -> doWork("key"));
            } catch (ExecutionException e) {
                throw new UncheckedExecutionException(e);
            }
        });
    }

    private void testConcurrentException(Supplier<String> cache) throws InterruptedException {
        ExecutorService executorService = Executors.newFixedThreadPool(NUM_THREADS);

        for (int i = 0; i < NUM_THREADS; i++) {
            executorService.submit(() -> accessCache(cache));
        }

        executorService.awaitTermination(15, TimeUnit.SECONDS);
    }

    private void accessCache(Supplier<String> cache) {
        print("Thread started");
        try {
            cache.get();
        } catch (RuntimeException e) {
            print("Caught exception");
        }
    }

    private String doWork(String s) {
        print("Doing work");

        try {
            Thread.sleep(1000);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        throw new RuntimeException();
    }

    private void print(String output) {
        System.out.println(String.format("[%s] %d: %s", Thread.currentThread().getName(), System.nanoTime(), output));
    }

}
```

Caffeine output:
```
[pool-1-thread-3] 1661560358525: Thread started
[pool-1-thread-4] 1661560358818: Thread started
[pool-1-thread-2] 1661560552905: Thread started
[pool-1-thread-4] 1661562178497: Doing work
[pool-1-thread-6] 1661562349457: Thread started
[pool-1-thread-1] 1661562297935: Thread started
[pool-1-thread-5] 1661562643369: Thread started
[pool-1-thread-7] 1661562691964: Thread started
[pool-1-thread-8] 1661562717726: Thread started
[pool-1-thread-8] 1662563143078: Doing work
[pool-1-thread-4] 1662563126392: Caught exception
[pool-1-thread-2] 1663565764575: Doing work
[pool-1-thread-8] 1663565847421: Caught exception
[pool-1-thread-5] 1664568698133: Doing work
[pool-1-thread-2] 1664568676470: Caught exception
[pool-1-thread-5] 1665570433209: Caught exception
[pool-1-thread-6] 1665570462484: Doing work
[pool-1-thread-7] 1666573181755: Doing work
[pool-1-thread-6] 1666573196100: Caught exception
[pool-1-thread-7] 1667576450502: Caught exception
[pool-1-thread-3] 1667576203136: Doing work
[pool-1-thread-1] 1668578707829: Doing work
[pool-1-thread-3] 1668578707829: Caught exception
[pool-1-thread-1] 1669581549466: Caught exception

Process finished with exit code 0
```

Guava output:
```
[pool-1-thread-2] 1484000415985: Thread started
[pool-1-thread-1] 1484000415692: Thread started
[pool-1-thread-3] 1484000577285: Thread started
[pool-1-thread-4] 1484001010542: Thread started
[pool-1-thread-5] 1484001346316: Thread started
[pool-1-thread-6] 1484001587242: Thread started
[pool-1-thread-7] 1484001762886: Thread started
[pool-1-thread-8] 1484001826997: Thread started
[pool-1-thread-1] 1484009018181: Doing work
[pool-1-thread-4] 1485012307713: Caught exception
[pool-1-thread-8] 1485012391436: Caught exception
[pool-1-thread-5] 1485012487748: Caught exception
[pool-1-thread-6] 1485012519364: Caught exception
[pool-1-thread-3] 1485012329668: Caught exception
[pool-1-thread-7] 1485012540442: Caught exception
[pool-1-thread-2] 1485012402561: Caught exception
[pool-1-thread-1] 1485012763510: Caught exception

Process finished with exit code 0
```

**Comment by ben-manes** [comment]
Guava forked Java 5's `ConcurrentHashMap` to add loading (basic computations). This was built as a future within the entry so that multiple threads could wait on it and the exception propagates. Guava switches the hash table entry (k/v, k/future. k/v/future) based on the context in order to minimize memory waste.

Caffeine is built on top of Java 8's `ConcurrentHashMap` which can load through `computeIfAbsent`. Its built by using `synchronized` on the hash bin (~ per entry). This is why the exception cannot be shared as it is an intrinsic lock. The hash table entry is not swapped based on the load state, though different versions are used for a list vs tree bin for HashDoS protection.

Because of the different algorithms, we can't emulate Guava's approach without using a custom hash table. The Java 8 table is far more advanced, Guava's emulation of the compute/merge methods is poor, and they don't interact with loads correctly. I had brought this up to Doug Lea when [reviewing](http://jsr166-concurrency.10961.n7.nabble.com/ConcurrentHashMapV8-tc7312.html#a7387) his first draft of the Java 8 version, and he was against handling exceptions the way Guava did.

Longer term I think users will be more familiar with `ConcurrentHashMap` `computeIfAbsent` than with Guava's. So from a behavior perspective could be argued Guava's will be surprising in a few years. I agree it has nice characteristics in rate limiting from a caching context. From a collection context, one could argue that's incorrect with capturing lambda using different parameters, so the failure with a different parameter set would be surprising. That may be quirky and surprising, but from a JDK perspective they should ensure correctness in puzzlers like that.

I don't think we could do anything smarter than adding a note to the Guava wiki page. I probably couldn't do more than emulate your hacky solution in the Guava adapters, either. Unfortunately I don't have any good ideas for you.

**Comment by mmmkkaaayy** [comment]
Thanks for the quick answer!

Given Caffeine's position as a low-level performance library, don't you think it makes sense to provide this behavior to users as a feature? Even if it's a hacky implementation, I think developers of low-latency/realtime systems may prefer the predictability and performance of immediate exception propagation.

Also, can please you comment on the best way to immediately invalidate the wrapped entry in the cache? If I have an `Expiry` implementation to specify a dynamic TTL per entry, should I just set it to 0 if it's an exception?

**Comment by ben-manes** [comment]
Actually, you can have exactly the same behavior if you use `AsyncLoadingCache`. This stores a future that is removed if the result is null or a failure. That should behave identical to Guava.

Note that the non-loading version hasn't been released yet, as I haven't been able to work on this project due to other commitments. You can emulate it in your test case as,

```java
com.github.benmanes.caffeine.cache.Cache<String, String> caffeineCache =
    Caffeine.newBuilder().buildAsync((String key) -> (String) null).synchronous();
testConcurrentException(() -> caffeineCache.get("key", this::doWork));
```

The output is,
```
[pool-1-thread-2] 663140678692693: Thread started
[pool-1-thread-1] 663140678638680: Thread started
[pool-1-thread-3] 663140679292165: Thread started
[pool-1-thread-5] 663140680252611: Thread started
[pool-1-thread-4] 663140680059127: Thread started
[pool-1-thread-6] 663140683278439: Thread started
[pool-1-thread-7] 663140685093971: Thread started
[pool-1-thread-8] 663140686922632: Thread started
[ForkJoinPool.commonPool-worker-1] 663140688284229: Doing work
[pool-1-thread-1] 663141693963491: Caught exception
[pool-1-thread-2] 663141693963480: Caught exception
[pool-1-thread-5] 663141693963951: Caught exception
[pool-1-thread-7] 663141693979484: Caught exception
[pool-1-thread-3] 663141693963541: Caught exception
[pool-1-thread-4] 663141694121909: Caught exception
[pool-1-thread-8] 663141694051358: Caught exception
[pool-1-thread-6] 663141693984187: Caught exception
Nov 30, 2018 11:42:39 AM com.github.benmanes.caffeine.cache.LocalAsyncCache lambda$3
WARNING: Exception thrown during asynchronous load
java.util.concurrent.CompletionException: java.lang.RuntimeException
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.RuntimeException
	at ConcurrentCacheExceptionTest.doWork(ConcurrentCacheExceptionTest.java:63)
	at com.github.benmanes.caffeine.cache.LocalAsyncCache$AbstractCacheView.lambda$1(LocalAsyncCache.java:206)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
	... 5 more
```

The exception is logged as a common mistake is to not handle failures on futures, so errors can be swallowed and lost. You can disable logging if desired through your logging framework (e.g. slf4j's jul bridge).

**Comment by mmmkkaaayy** [comment]
Can you elaborate on how rate limiting would be a solution to this problem? I don't see how it would help achieved the desired behavior of fail-fast to all callers on an exception.

Also, the `AsyncLoadingCache` solution is not truly identical to Guava as the work should be done by a calling thread, not on `ForkJoinPool`/`Executor`. But it's definitely an alternative to consider...

**Comment by ben-manes** [comment]
You set `Caffeine.executor(Runnable::run)` to perform the work on the calling thread.

Rate limiting was if you were concerned about a query storm due to errors, as it would help still have a problem at the client-side, without failing over the shared resource due to a self-imposed DoS attack.

**Comment by mmmkkaaayy** [comment]
Ah cool, didn't know you could set the executor like that to use the calling thread. I will experiment with the proposed solutions and see which one feels the best.

Thanks for your help!
