### ISSUE TITLE
AsyncLoadingCache: get during consuming failed load

### ISSUE THREAD

**Issue by arkrost** [ben-manes/caffeine#290]
Consider the following example (in kotlin):

```kotlin
  val future = AtomicReference(CompletableFuture<String?>())

  val cache = Caffeine.newBuilder().buildAsync<Int, String> { _, _ -> future.get() }

  val firstFuture = CompletableFuture<String?>()
  future.set(firstFuture)

  val secondFuture = CompletableFuture<String?>()

  val result = cache.get(42).thenAccept { value ->
    require(value == null)
    future.set(secondFuture)

    val retry = cache.get(42)
    require(retry == secondFuture) // actually retry == firstFuture
  }
  firstFuture.complete(null)
  result.join()
```

Here we imitate loading process. The first attempt completed with `null` so subsequent get should try to load once more. Unfortunately, the first future is returned. It happens because `whenComplete` listeners would be called in lifo order. So first future would be removed from cache in the last listener :(

I propose to return future obtained after handling null value, i.e.
*LocalAsyncCache.java*
```java
 default CompletableFuture<V> get(K key,
      BiFunction<? super K, Executor, CompletableFuture<V>> mappingFunction, boolean recordStats) {
    long startTime = cache().statsTicker().read();
    @SuppressWarnings({"unchecked", "rawtypes"})
    CompletableFuture<V>[] result = new CompletableFuture[1];
    CompletableFuture<V> future = cache().computeIfAbsent(key, k -> {
      result[0] = mappingFunction.apply(key, cache().executor());
      return requireNonNull(result[0]);
    }, recordStats, /* recordLoad */ false);
    if (result[0] != null) {
      AtomicBoolean completed = new AtomicBoolean();
      return result[0].whenComplete((value, error) -> {
        if (!completed.compareAndSet(false, true)) {
          // Ignore multiple invocations due to ForkJoinPool retrying on delays
          return;
        }
        long loadTime = cache().statsTicker().read() - startTime;
        if (value == null) {
          if (error != null) {
            logger.log(Level.WARNING, "Exception thrown during asynchronous load", error);
          }
          cache().statsCounter().recordLoadFailure(loadTime);
          cache().remove(key, result[0]);
        } else {
          // update the weight and expiration timestamps
          cache().replace(key, result[0], result[0]);
          cache().statsCounter().recordLoadSuccess(loadTime);
        }
      });
    }
    return future;
  }
```

**Comment by ben-manes** [comment]
The concern is that the returned future is not the same instance as the supplied one (from `mappingFunction`). That could be surprising if a user depends on interacting with the underlying future.

For example, what if the future is supplied by an an http client and cached directly. If the client's future supports the `cancel()` method, then this would not be communicated. Similarly since futures don't have equality, one might have mapping somewhere else with lookups via reference equality. If the cache returns a different instance than the `mappingFunction`, it could break a reasonable expectation.

Since a future highlights that there is asynchronous and concurrent behavior, it seems less surprising that a caller might race to obtain a failed future before its been removed. I agree your ask is the common case desire, but I think the principle of least astonishment promotes the existing logic. Your logic also leads to the cache returning both futures (one on load, one on cache hit), though that might be easy to resolve.

A pending enhancement (90% done) is to add an async map view (`Map<K, CompletableFuture<V>>`) which would let you perform a conditional remove (`remove(key, firstFuture)`). Then your retry would be guaranteed to be a new load. That work is done except resolving statistic calculations.

You might also consider using [Failsafe](https://github.com/jhalterman/failsafe/issues) with a delay time for your retry logic. That's not a great fix, but you probably want a delay / backoff anyway rather than an immediate retry.

**Comment by arkrost** [comment]
Ok, thanks for explanation. I only faced this case during unit testing and was confused with behaviour. In production code we already use retry policies, so it shouldn't be a problem. Moreover, we can fix it on our side.

**Comment by ben-manes** [comment]
In your unit tests, you can set the executor to same thread to disable asynchronous execution (`Caffeine.executor(Runnable::run`).
