### ISSUE TITLE
how to return old value

### ISSUE THREAD

**Issue by chainyu** [ben-manes/caffeine#292]
How to return old value when multiple requests are concurrent access to an expired key. Current test results: One request back source, other requests blocked

**Comment by chainyu** [comment]
@Bean(name = CACHE_MANAGER_NAME)
    public CacheManager caffeineCacheManager() {
        SimpleCacheManager cacheManager = new SimpleCacheManager();

        ArrayList<CaffeineCache> caches = new ArrayList<CaffeineCache>();
        for(Caches c : Caches.values()){

            caches.add(new CaffeineCache(c.getName(), Caffeine.newBuilder().recordStats().maximumSize(c.getMaxSize()).refreshAfterWrite(c.getTtl(), TimeUnit.SECONDS).build(cacheLoader())));

        }
        cacheManager.setCaches(caches);
        return cacheManager;
    }

    @Bean
    public CacheLoader<Object, Object> cacheLoader() {

        CacheLoader<Object, Object> cacheLoader = new CacheLoader<Object, Object>() {
            @Nullable
            @Override
            public Object load(@Nonnull Object o) throws Exception {
                return null;
            }
        };
        return cacheLoader;
    }

**Comment by ben-manes** [comment]
Spring Cache is meant to be a basic abstraction for the common, simplest cases. It doesn't support modestly complex scenarios like this, and the authors suggest using the underlying implementation directly. As in, they don't want to add more advanced features and don't think forcing all cases through their abstraction is healthy. In this case, I'd recommend using Caffeine directly.

Spring doesn't provide the `CacheLoader`, as you figured out. Instead it provides a function to the `cache.get(key, func)` method. So we don't have a reliably stable reload method to invoke, which is why a `CacheLoader` is required for `refreshAfterWrite`.

For Spring questions, I think you're best bet is StackOverflow since I don't use it.
