### ISSUE TITLE
NullAway not running on the caffeine module

### ISSUE THREAD

**Issue by msridhar** [ben-manes/caffeine#296]
Not sure what's intended, but it looks like NullAway is not running on the caffeine module.  I made the following modification:
```diff
$ git diff
diff --git a/caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/node/NodeRule.java b/caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/node/NodeRule.java
index d408af8c..f3873af8 100644
--- a/caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/node/NodeRule.java
+++ b/caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/node/NodeRule.java
@@ -48,6 +48,7 @@ public abstract class NodeRule implements Consumer<NodeContext> {
     if (applies()) {
       execute();
     }
+    Object x = null; x.toString();
   }

   /** @return if the rule should be executed. */
```
But the code still compiled; I got an NPE during the `:caffeine:generatedNodes` task.

**Comment by ben-manes** [comment]
Are you running with JDK9+? I had early builds against that JDK when new and some things like the ErrorProne gradle plugin hadn't worked correctly then. It looks like I cleaned this up, but haven't thought much about JDK9+ since those early attempts. This project is still Java 8 and I haven't had the time to start on a JDK11 (v3.0) overhaul.

Oh, this is also probably due to this configuration. I don't recall why, but might be to avoid it in testing code where the checks are not necessary. It was probably back when you were helping me resolve false positives and I wanted to reduce the burden. We can try removing that conditional. The JavaPoet is codegen task that produces classes for inclusion into the `compileJava` task.
https://github.com/ben-manes/caffeine/blob/55f5078d485bc14c14736a4a8d6a5e244e5b1467/gradle/codeQuality.gradle#L97-L101

**Comment by msridhar** [comment]
I'm still on JDK 8 as well.  I tried removing that `if` condition in `codeQuality.gradle` but still didn't see an error.  It seems that none of the error prone config in that file is getting applied to the `:caffeine:compileJavaPoetJava` task that actually compiles the Java code.  (I added an unused import but the `RemoveUnusedImports` check did not fire.)  I'm not sure why; it seems it should be a `JavaCompile` task and so things should work.

**Comment by ben-manes** [comment]
If I add that line to `BoundedLocalCache.java` it gives the warning. Though I would have thought it should be an error, given the above. Anyway, it's working in some places and I agree it needs to be revisited.

```gradle
$ gradle build -x test
> Task :caffeine:compileJava
/Users/ben/projects/caffeine/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java:229: warning: [NullAway] dereferenced expression x is @Nullable
    Object x = null; x.toString();
                      ^
    (see http://t.uber.com/nullaway )
1 warning
```

**Comment by ben-manes** [comment]
It seems to be due to using the [older approach](https://github.com/tbroyer/gradle-errorprone-plugin#custom-error-prone-checks) of,
```gradle
dependencies {
  annotationProcessor <nullaway>
}
```
instead of the newer
```gradle
dependencies {
  errorprone <nullaway>
}
```
to register the custom checks.

`annotationProcessor` -> `compileJava`
`testAnnotationProcessor` -> `compileTestJava`
etc

That caused the checks to not be run. I was previously using the `apt` plugin which was deprecated for Gradle's built-in `annotationProcessor` and didn't realize that they behaved differently in this regard.

Of course now I get a bunch of warnings for code that I don't particularly care about. 😃 

```bash
/Users/ben/projects/caffeine/caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache/NodeFactoryGenerator.java:110: warning: [NullAway] initializer method does not guarantee @NonNull field nodeFactory is initialized along all control-flow paths (remember to check for exceptions or early returns).
  public NodeFactoryGenerator(Path directory) {
         ^
    (see http://t.uber.com/nullaway )
```

**Comment by ben-manes** [comment]
Fixed in the [adaptive](https://github.com/ben-manes/caffeine/tree/adaptive) where I'm trying to wrap up the eviction policy improvements. They are ready to merge in except for a lack of unit tests.
