### ISSUE TITLE
Multiple Simultaneous Async Requests For Same Key

### ISSUE THREAD

**Issue by adamzr** [ben-manes/caffeine#297]
I want to build an async loading cache. My loader will call a REST API. If my cache gets several requests in quick succession for the same key, I don't want that to result in multiple calls to the backing API. I want the first call to trigger the loader. I want all 3 cache calls to wait on that single load. This way the backing API only gets called once. Is this possible with Caffeine?

Thanks!

**Comment by ben-manes** [comment]
Yes, that is what the loading (or Map.compute) methods do. They will ensure that the loader is executed atomically and that other callers wait instead of racing to load as well. In your case you want to use an `AsyncLoadingCache`. This will store a `CompletableFuture` into the cache and execute it asynchronously, so that other callers can obtain a future immediately while the load is in-flight.

You can enable stats, execute a test run, and see the output. You should see the minimal number of loads. 😃
