### ISSUE TITLE
[Question] Cache item pre-expiration policy?

### ISSUE THREAD

**Issue by avboy72** [ben-manes/caffeine#299]
Hello,

We have a cache where a single item gets hits thousands of times per second. With a 30 second expiration period.

For security reasons, the key and cache item purposefully do not have enough information to reload the cache item in the background.  ( The Key is a peppered hash ).  

However, every 30 seconds when the cache item expires, we have a feeding frenzy of all of our threads requesting the value of the cached item from an external webservice.

If there was a way to immolate a single cache request ( pretend the item isnt within the cache), prior to when the item actualy expires.... a single thread could reload that item and avoid feeding frenzy.

Does anyone know of a way, with the current API to configure an expiration policy with a preexpiration immolation feature?

Thanks!

**Comment by ben-manes** [comment]
If you use the computing `get` apis, then only one thread will do the work per key and pass extra information through to the lambda. Then you don't need all of the information on the key while still loading. If that doesn't work, you might consider some form of lock striping to avoid the stampede.

Usually `refresh` is the mechanism to do this, but since your keys lack enough details there isn't a means through the cache itself. You might need to build some queuing system around the cache to schedule a prefetch. It's not very obvious since your keys lack enough details to load, so I don't know how you can associate when expiring regardless.

**Comment by avboy72** [comment]
Thanks Ben.

I should note that we are also using the spring boot annotations.  

  @Cacheable(value = cacheName, keyGenerator = "hashingKeyGenerator")

**Comment by ben-manes** [comment]
Oh, at then you are restricted to their abstraction. I haven't used Spring since 1.x - 2.0, so my knowledge is very out of date. You might ask on StackOverflow?

I do know that the Spring team views it as the common case abstraction, and not intended to be feature rich. For more advanced cases they recommend using the implementation directly. I don't think you have the desired feature directly in their abstraction, which means you may need to discard it.

**Comment by avboy72** [comment]
If we used Caffeine directly... is their a way to get the cache item expiration time? Also, a way to store on the cache item if the immolation has already occurred?

**Comment by ben-manes** [comment]
You can use the `cache.policy()` api to inspect lower-level details, like expiration times.

I don't know what you mean by `immolation`. You can use the get/put or `Map` apis to store items.

**Comment by avboy72** [comment]
basically what I mean by immolation is to sacrifice a single get on the cache by NOT returning the existing cached item that hasnt yet expired... some amount of time prior to expiration.  This way a single thread would get the resource and replace it within the cache with a new version of it before the item is actually evicted from the cache.  Allowing other threads to continue using the cached item.

Its kind of like a zero downtime cache item refresh.

**Comment by ben-manes** [comment]
We do support that, but in terms of `Caffeine#refreshAfterWrite`, `LoadingCache#refresh`, and `Map.compute` methods. If `refreshAfterWrite` is used, then the item will be reloaded (by key and old value) before expiration if accessed after the refresh time period. This is typically the solution to your problem.

**Comment by avboy72** [comment]
Yeah, makes sense... but then we would have to store the sensitive information in the cache so that the background Executor can refresh the item.

**Comment by ben-manes** [comment]
Yes. We don't have a `refresh(key, function)`, which I suppose would do this. Otherwise you'd need hacks like a request-scoped object (e.g. `ThreadLocal`) to pull from.

**Comment by ben-manes** [comment]
You might also consider wrapping the value with metadata, to determine if it should be reloaded. Then use an atomic boolean to CAS so that only one thread does the work. So then (1) fetch, (2) check, (3) CAS, (4) reload. That would be outside of the cache but would give you the desired properties without much pain.

**Comment by ben-manes** [comment]
Thinking through this, I think that using custom metadata is probably the best to reload with. When it fails your check, you would use an `asMap().compute` method. I don't think there is an addition to the API or general logic that I could add to do this any better, and most likely would be worse than a custom solution. Since the custom logic should be very straightforward (at least outside of Spring), I think it okay to close this issue. Please reopen if you disagree / have other thoughts.
