### ISSUE TITLE
Admission window and the main body of cache on different servers

### ISSUE THREAD

**Issue by leventov** [ben-manes/caffeine#303]
Is this a reasonable idea to have admission part of the cache on a local machine, the "main" part of the cache on a remote server, a-la memcached?

In [Druid](http://druid.apache.org), "historical" nodes compute partial query results over "segments" (time-sliced parts of the data) and send them to remote memcached servers. Then "broker" nodes (which normally aggregate partial query results from "historical" nodes) may query those memcached nodes too.

In this setup, the idea would be to have the admission windows reside the "historical" nodes and when the partial query result proves to be "hot" enough, historical node "promotes" the result to a remote dedicated cache node (be it memcached or a Java server running Caffeine).

**Comment by ben-manes** [comment]
I don't know enough about the mechanics to make a fair judgement. If you mean to use different caching policies, then I think using the multi-level cache is best. Since Caffeine will adjust to the best configuration, you shouldn't have to tune this level.

I do know that LRU tends to perform poorly in db / analytics / search workloads, because those queries scan lots of rows which flushes LRU. Postgres and ElasticSearch use local LRU buffer caches to protect their main LRU cache from this pollution, thereby holding more frequent items. If you were to have use only LRU on historical nodes then you may see very low hit rates. I guess what you're thinking is then to have a filter to determine when to promote to the remote cache, thereby reducing pollution / serialization cost / wasted bandwidth, which makes sense to me. The first step would be to quantify the cost and benefit from an X% improvement, to determine if it is worth investing in.

I don't feel comfortable making a recommendation, but would be happy to help brainstorm or analyze data.

**Comment by ben-manes** [comment]
fyi, @drcrallen had a nice chart of the multi-level cache performance in Druid, which may help?
https://github.com/apache/incubator-druid/pull/3028#issue-71618510

**Comment by ben-manes** [comment]
I'll close this in favor of https://github.com/apache/incubator-druid/issues/7186 since this isn't directly related to Caffeine. Happy to discuss further wherever though.
