### ISSUE TITLE
[Feature Request] Add more informations in stats about eviction cause

### ISSUE THREAD

**Issue by cschockaert** [ben-manes/caffeine#304]
Hello,

Would it been possible to add the eviction reason to evictions stats metric : 
cache_eviction_total / cache_eviction_weight

For eg add the `com.github.benmanes.caffeine.cache.RemovalCause ( MANUAL / EXPIRED / SIZE ...)` in a tag like it is done for the metric : cache_gets_total (result=hit/miss)

Thanks

**Comment by ben-manes** [comment]
We probably won’t add more than the basic stats, but it’s a fair point. Usually the eviction cause metrics won’t be useful, e.g. all expire eventually if unused. The eviction metrics we currently offer are mostly for sizing which is manually determined, whereas expiration is typically about data freshness.

In your case, would capturing custom metrics in a RemovalListener suffice?

**Comment by cschockaert** [comment]
perhaps i missed a point, you are saying that the eviction metrics i actually see is the eviction due to max cache size reached only ? 

i thought it was the sum of all eviction events, max size + expiration+ ...

in fact i just need a metric that is reporting the eviction due to max cache size but not expiration.

**Comment by cschockaert** [comment]
I saw that RemovalListener offer the behaviour i need, i'll dev some custom metrics around it

**Comment by ben-manes** [comment]
Sorry for the misunderstanding. Yes, it’s of all eviction types (but not manual removal). The cause is not taken into account.

**Comment by cschockaert** [comment]
OK thanks

**Comment by ben-manes** [comment]
For the future, I think we can add `recordEviction(int weight, RemovalCause cause)` and deprecate the prior one, like we did when adding `weight`. The cause won't be utilized in the standard stats, but you can implement your own `StatsCounter` to push (instead of polling from `Cache.stats()`). That would allow optionally capturing this metric. Potentially we could do that for other cases (manual removal, puts, etc) as requested, where the default behavior ignores those operations but custom ones can instrument as desired.

https://github.com/ben-manes/caffeine/blob/4a8c9690e56e24f24c194ffe9bafa60171994146/caffeine/src/main/java/com/github/benmanes/caffeine/cache/stats/StatsCounter.java#L73-L94

**Comment by cschockaert** [comment]
Yes should be a better solution than using RemovalListener.

**Comment by ben-manes** [comment]
Released in v2.8
