### ISSUE TITLE
What should be the effect of returning a null pointer from a cache callback?

### ISSUE THREAD

**Issue by PaulKlint** [ben-manes/caffeine#31]
We use  this very nice library in the implementation of the Rascal meta-programming language (see http://www.rascal-mpl.org). However, I was hit by the following: when a cache call back function returns `null` this is not registered in the cache and the next time around the same call back function will be called with the same arguments. The net effect is that no caching is done despite a lot of redundant calling activity.

If this is intended behavior, please add a warning in the documentation. Otherwise: change this behavior.

Here is a code snippet, where `getCompanionDefaultsFunction` may return `null`.

```
private Cache<String, Function> companionDefaultFunctionCache = Caffeine.newBuilder().build();
	
	public Function getCompanionDefaultsFunction(String name, Type ftype){
		String key = name + ftype;
		return companionDefaultFunctionCache.get(key, k -> rvm.getCompanionDefaultsFunction(name, ftype));
	}
```

**Comment by ben-manes** [comment]
I'm sorry to hear there was confusion. However I do think this is properly documented.

```java
* If the specified key is not already associated with a value, attempts to compute its
* value using the given mapping function and enters it into this cache unless {@code null}.
```

This follows the pattern set out by the Java Collections Framework, namely `computeIfAbsent`.
```java
[Map]
* If the function returns {@code null} no mapping is recorded.
[ConcurrentMap]
* This implementation assumes that the ConcurrentMap cannot contain null values
* and {@code get()} returning null unambiguously means the key is absent.
[ConcurrentHashMap]
* If the specified key is not already associated with a value, attempts to compute its
* value using the given mapping function and enters it into this map unless {@code null}.
```

Like `java.util.concurrent` collections, the cache does not allow storing `null` values and a `null` is always an indicator that the mapping is absent. If your intent is to support negative caching (cache that the entry does not exist), then the pattern is to return an `Optional` value. This works well except in the case of weak/soft value reference caching.

In Guava we disallowed null computations, threw a checked `InvalidCacheLoadException` if a loader returned null, and `LoadingCache.get(k)` is checked. We had originally used nulls as above, but switched based on Josh Bloch's review where he preferred checked exceptions as better matching Java 5's coding style. Now that Java 8 makes null the preferred style (lambdas are hostile to checked exceptions, JCF's compute methods), we're following that idiom.

Do you think the JavaDoc should be more explicit by discussing `null` in its own paragraph, with a little more warning in the writing? I'm a little hesitant only because I think once developers become more familiar with Java 8 and Map's compute methods this won't seem so surprising. It will instead seem natural and the warning verbose.

**Comment by PaulKlint** [comment]
Thank you for your extensive answer. As documented above I would say: yes that is enough. However, I have only read the information on the Caffeine Wiki pages and there I did not find any mention of null pointers. Perhaps you could add a warning there.

**Comment by ben-manes** [comment]
Thanks! I updated the [Population](https://github.com/ben-manes/caffeine/wiki/Population) wiki page.
