### ISSUE TITLE
Eviction may be over maximum size even with WithinThreadExecutor

### ISSUE THREAD

**Issue by wburns** [ben-manes/caffeine#319]
I have a bounded cache that has writes from two different threads. After both writes are complete the cache can be in a state where it has more entries in it than the eviction configuration. This can be reproduced with this very simple test.

```java
@Test
public class SimpleTest {
   public void testCaffeine() throws InterruptedException, ExecutionException {
      Cache cache = Caffeine.newBuilder()
            .maximumSize(1)
            .executor(new WithinThreadExecutor())
            .build();

      Phaser phaser = new Phaser(2);
      ExecutorService executorService = Executors.newFixedThreadPool(2);
      ExecutorCompletionService<Void> executorCompletionService = new ExecutorCompletionService<>(executorService);
      executorCompletionService.submit(() -> runWriteCheck(cache, phaser, "k1", "v1"), null);
      executorCompletionService.submit(() -> runWriteCheck(cache, phaser, "k2", "v2"), null);

      Future<Void> future = executorCompletionService.poll(10, TimeUnit.MINUTES);
      if (future != null) {
         future.get();
      }
   }

   private void runWriteCheck(Cache cache, Phaser phaser, Object key, Object value) {
      for (;;) {
         phaser.arriveAndAwaitAdvance();
         cache.put(key, value);
         phaser.arriveAndAwaitAdvance();

         long estimatedSize = cache.estimatedSize();
         assert estimatedSize == 1 : "Estimated size was: " + estimatedSize;
      }
   }
}
```

Eventually there will be a size of 2. I can work around this by invoking cleanUp before doing bulk operations, such as iterator or size. But if not sometimes these methods will return an extra unexpected entry.

**Comment by ben-manes** [comment]
Yes, we use a threshold that can be temporarily exceeded rather than a hard limit.

```java
/**
 * Specifies the maximum number of entries the cache may contain. Note that the cache <b>may evict
 * an entry before this limit is exceeded or temporarily exceed the threshold while evicting</b>.
 * As the cache size grows close to the maximum, the cache evicts entries that are less likely to
 * be used again. For example, the cache may evict an entry because it hasn't been used recently
 * or very often.
```

A hard limit would require that all writes block against a single lock. In the most stringent form of this that ensures a strict limit, all write operations would need to be performed under that lock. This of course creates a bottleneck by severely limiting per-entry locking, etc. It can impact hash-table design, e.g. making it hard to build on top of `ConcurrentHashMap` and requiring a custom version (like Guava's) which may not handle compute methods as well.

Instead we use a write buffer that is drained whenever populated. The Map operation completes, the entry is added to the buffer, and the buffer replayed under the lock. If the lock is held then a writer can move on, knowing its work will be picked up by another thread. If this write buffer is full then writers degrade to blocking on the eviction lock, to drain the buffer and perform their work. This creates back pressure which deprioritizes writing threads to allow the draining thread to make progress. The [Stresser](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/test/java/com/github/benmanes/caffeine/cache/Stresser.java) class shows how this occurs and is able to handle a high synthetic write load without a memory leak.

When a [drain completes](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L1409) (policy maintenance), it could unlock with more work having arrived in between. If `ForkJoinPool.commonPool()` is used then a new drain will be immediately scheduled asynchronously (2.7.0). If a custom executor is used, we don't want to penalize a thread (e.g. caller-runs) forever so it will be scheduled by the next reader or writer.

The delicate detail that isn't clear is how large the writer buffer should be. Currently it's sized to lazily grow up to a threshold based on the number of cpus. That equation might be too lenient, but there's not been feedback indicating one way or the other.

For massive bulk writes, like a data import, usually it is best to bypass the cache rather than populate it  (e.g. write-through). Those cases usually only invalidate on write.

I hope that helps clarify the tradeoffs and why it works that way.

**Comment by wburns** [comment]
I kinda figured it was something like this, but had to log something to make sure :)

Thanks for the explanation, especially with this much detail. To be honest this shouldn't really be an issue for actual use cases it is more about test assertions.

**Comment by ben-manes** [comment]
Thanks, I’m glad to hear it! :)
