### ISSUE TITLE
Please clarify what Infinispan_New_Lru impl is.

### ISSUE THREAD

**Issue by alkemist** [ben-manes/caffeine#32]
I'm particularly interested whether it has any relation to https://github.com/infinispan/infinispan/blob/master/core/src/main/java/org/infinispan/util/concurrent/BoundedConcurrentHashMap.java.

If it doesn't, would it be possible to include this in your benchmarks?

**Comment by ben-manes** [comment]
That's `Infinispan_Old_Lru` which was written around the same time as Guava's Cache. They also ported Charles' prototype of LIRS, which we never integrated into Guava. So not surprisingly it has similar performance characteristics.

[Infinispan_New_Lru](https://github.com/infinispan/infinispan/blob/master/commons/src/main/java/org/infinispan/commons/util/concurrent/jdk8backported/BoundedEquivalentConcurrentHashMapV8.java) is a rewrite based on `ConcurrentHashMapv8` and `ConcurrentLinkedDeque`. Its similar to my earliest prototypes, where a lock-free deque is used for the LRU queue. The problem is that every read is a write, so it thrashes worse than a lock (hence the poor performance). In its favor is that the LIRS implementation correctly handled non-resident entries, so it has a much better hit rate than Charles' prototype code.

`OLD` would be much faster if it used a ring buffer, like CLHM does (and I keep trying to get Guava to). `New` could be a lot faster if it borrowed @thomasmueller fast-path trick to skip over hot reads.

The reason why `New` was adopted is their benchmarks incorporate a high miss rate. The new CHM is much faster, so misses skew the results dramatically. I intentionally avoid that as hits are the expensive and desirable case of a cache.

See [CacheType](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/jmh/java/com/github/benmanes/caffeine/cache/CacheType.java)for the factory of all the integrated implementations.

**Comment by alkemist** [comment]
Thanks for the info.

**Comment by ben-manes** [comment]
You'll probably be interested in [Window TinyLfu](https://github.com/ben-manes/caffeine/wiki/Efficiency). The integration is complete, I just haven't had the time to benchmark which is holding up the release.

**Comment by alkemist** [comment]
So just to confirm, is your starting recommendation for a bounded concurrent cache for pre Java 8 ConcurrentLinkedHashMap?

**Comment by ben-manes** [comment]
If you want performance, then yes. Its used by Cassandra, Spray, Camel, Solr, etc, and was the first concurrent Java cache. Guava was the intended successor, but a lot of simple performance fixes weren't carried over. If you want features, which is the most common case, then Guava's is a good default.

**Comment by alkemist** [comment]
Thanks again.

**Comment by ben-manes** [comment]
I released v2.0. This would be a better fit for `ratpack` as both are Java 8 based, is significantly faster, and has a much higher hit rate.

**Comment by alkemist** [comment]
Yeah thanks, I do intend to introduce it there. This “thread” was actually in the context of Gradle.

**Comment by ben-manes** [comment]
I know, but saw you used BCHM in ratpack and Gradle is 1.6 :)

**Comment by ben-manes** [comment]
@alkemist You may enjoy reading our [research paper](http://arxiv.org/pdf/1512.00727.pdf).

**Comment by alkemist** [comment]
Will do. Thanks for the pointer.
