### ISSUE TITLE
Customizable Backends

### ISSUE THREAD

**Issue by mgrandi** [ben-manes/caffeine#321]
Hello,

A application that I work on has data that is "expensive" to calculate (an API call), but we want this data to be shared across all instances of this application , so we store it in redis

This library seems perfect for our use case, except it seems relatively hard coded in the default implementation to use a ConcurrentHashMap as the underlying 'cache' ( see  https://static.javadoc.io/com.github.ben-manes.caffeine/caffeine/2.7.0/com/github/benmanes/caffeine/cache/Caffeine.html) 

I was wondering if there are any plans to have a swappable backend built into the API for caffeine for situations where you don't want the 'cache' to be just a ConcurrentHashMap on the local system, such as my use case, where we want the "cache" to be redis, and then the (Async)CacheLoader would do the expensive work (in my case, an API call) to calculate the value, and then store it in the cache (redis). 

It seems like we could just write our own class that extends (Async)Cache / (Async)LoadingCache, but I feel that I wouldn't be the only one who would want this kind of functionality without re-implementing the entire (Async)Cache/(Async)LodingCache interface ourselves.

**Comment by ben-manes** [comment]
We rely on atomic behavior of `ConcurrentHashMap`, such as `computeIfAbsent`. A different backend could violate this expectation, such as `ConcurrentSkipListMap` does not support atomic computations. A network-based cache, like Redis, would also fail for our purposes. For an in-memory cache, I think it's hard to do better than `ConcurrentHashMap` while maintaining these atomic properties.

Replacing the backend means you wouldn't have local state, as the data would all be remote. Then all of the metadata we store (like eviction state) would not be relevant, because Redis does that itself. If one instance evicts it would cleanup its metadata, but another instance wouldn't have been informed so that would be corrupted. Basically things would break down quickly and its not designed for that use-case. 

For redis / memcached, you often use the cache-aside pattern to combine a local & remote caching layer. This is implemented via the `CacheLoader` as,
1. Fetch from redis
2. If found, return value
3. If not found, perform expensive work
4. Put value into redis (optionally async)
5. Return value

If you want to abstract out caching to a set of interfaces where local is optional, you might write your own with adapters. That unified interface will probably drop features, like `Cache.asMap().keySet()` as  iterating over all keys may not be supported (e.g. memcached).

**Comment by mgrandi** [comment]
thanks, i think that helps me out. I will close this issue for now

**Comment by asarkar** [comment]
> 1. Fetch from redis
> 2. If found, return value
> 3. If not found, perform expensive work
> 4. Put value into redis (optionally async)
> 5. Return value

@ben-manes Do you've any code samples for the sequence above? On the same token, is it possible to automatically delete the entry from Redis when it's invalidated in the local cache?

**Comment by ben-manes** [comment]
@asarkar Those steps would go into your `CacheLoader` or `AsyncCacheLoader`, depending on whether you want a sync or async cache.

The removal callback can be done either after the map operation completes (`Caffeine.removalListener`) or atomically as part of the map computation. In the atomic case, a manual removal can use `asMap().computeIfPresent(k, f)` which returns null, where your function deletes from Redis. In the case of automatic removal, `Caffeine.evictionListener` can be supplied and is invoked with the eviction's compute operation. In older versions of Caffeine we had a `CacheWriter` which did both of these, but it was too error-prone and quirky that we deprecated & removed it in favor of more obvious and explicit functions.

**Comment by asarkar** [comment]
Got it, thanks. Do you think the removal options are worth documenting?

**Comment by ben-manes** [comment]
I tried to and hopefully the wiki pages [removal](https://github.com/ben-manes/caffeine/wiki/Removal) and [compute](https://github.com/ben-manes/caffeine/wiki/Compute) are helpful.
