### ISSUE TITLE
Caffeine is marked by Snyk as having vulnerability - request for easy fix

### ISSUE THREAD

**Issue by patrykks** [ben-manes/caffeine#324]
Hi, @ben-manes Caffeine library is great. However there is one problem. Library is marked by Snyk as having medium severity vulnerability.

https://snyk.io/vuln/SNYK-JAVA-COMGITHUBBENMANESCAFFEINE-174818

I see that fix is already commited (2721dbf). I have a question. Is it possible to make Caffeine release in order to allow users of Snyk get rid of errors reported by mentioned tool?

btw: Thank you for your contribution to the development of Caffeine library :)

**Comment by ben-manes** [comment]
hmm.. it may be marked by Synk, but they also resolve it as `This was deemed not a vulnerability.`. I think they could mark `2.7.0` as verified to not be impacted and silence the error when users upgrade to that version? I don't particularly want to release simply to quiet a reporting tool for a non-issue.

The question of that issue was whether the build was compromised to produce an invalid artifact. The artifacts themselves do not refer to an http resource. Since the build was not impacted by this issue, users will not download an artifact and observe vulnerabilities. Therefore it was pretty easy to manually check, which I did for the latest release.
