### ISSUE TITLE
java.lang.IllegalStateException: com.github.benmanes.caffeine.cache.SSMSW

### ISSUE THREAD

**Issue by YervandAlexanyan** [ben-manes/caffeine#334]
Hi have a runtime error
with this stack trace 
`java.lang.IllegalStateException: com.github.benmanes.caffeine.cache.SSMSW
        at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:101)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3341)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3337)
        at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:936)`
its caused from this proprerty
`private val cacheVenues: Cache<String, List<Venue>> = Caffeine.newBuilder()
        .expireAfterWrite(cacheDuration, TimeUnit.MINUTES)
        .maximumSize(recordsCount)
        .build<String, List<Venue>>()`

Thanks

**Comment by ben-manes** [comment]
That exception wraps a `ReflectiveOperationException` to rethrow, since it is checked. You would need to show that.

Reflection is used to load the implementation classes, which are memory optimized for your configuration. Are you performing dead code elimination, e.g. using Proguard?

**Comment by YervandAlexanyan** [comment]
No, I don't use Proguard I use a library in an android application I think I doing something wrong can you please me explain have differences in a configuration depends on the platform

**Comment by YervandAlexanyan** [comment]
`java.lang.Error: java.lang.NoSuchFieldException: No field threadLocalRandomProbe in class Ljava/lang/Thread; (declaration of 'java.lang.Thread' appears in /system/framework/core-oj.jar)`

**Comment by ben-manes** [comment]
This library is not optimized for Android and intended for server-side cases (high concurrency, etc). Android typically pushes for a lot of dead code elimination due to DEX being an inefficient format (e.g. method count limits) and the binary/memory size being limited for mobile environments. You may want to consider an alternative library designed specifically for Android, such as Android's LruCache.

> No field threadLocalRandomProbe in class Ljava/lang/Thread

Perhaps this is because the Android compiler can targeting pre-JDK8 runtimes, using the ancient Apache Harmony semi-compatible API classes instead of OpenJDK's like in the later API versions.

**Comment by YervandAlexanyan** [comment]
@ben-manes Thanks

**Comment by GongHuixue** [comment]
@ben-manes ,@YervandAleksanyan ,Have you resolved the issue "No field threadLocalRandomProbe in class Ljava/lang/Thread"?
i am also meat the issue as i loaded the caffeine in Android project.

**Comment by ben-manes** [comment]
Android is a very different set of needs compared to server-side Java. You might consider [Store](https://github.com/dropbox/store) from Dropbox & the NYTimes.
