### ISSUE TITLE
Async cache and async writes

### ISSUE THREAD

**Issue by cruftex** [ben-manes/caffeine#339]
On the `AsyncCache` there is:

```java
void put(@NonNull K key, @NonNull CompletableFuture<V> valueFuture);
```

I would have expected,  maybe something like:

```java
CompletableFuture<Void> put(@NonNull K key, @NonNull V value);
```

Is there a way to get notified or continue operation as soon as the put is completed?
When there is a `CacheWriter` a `put` takes an indefinite amount of time.

**Comment by ben-manes** [comment]
`CacheWriter` is not allowed/supported when the cache is built as async. This blocks only as long as the map write to insert the future, so the hold time is generally short across other usages.

The alternative api could make sense if the cache was external (e.g. memcached), but we’re not trying to be a generic facade.

For us the writer is used to run user code atomically when the mapping is established or removed, rolling back if the writer fails. The mapping to a future is not very interesting to intercept if in flight. Otherwise we have to block in the map on the future until complete which would defeat the purpose of this type of cache. For what our apis means, this concept doesn’t make sense and is not supported.

**Comment by cruftex** [comment]
> For us the writer is used to run user code atomically when the mapping is established or removed, rolling back if the writer fails.

What is happening when rolling back in case of removal cause eviction or expiry?

> ... but we’re not trying to be a generic facade.

Ahh, got it. That's our different approaches. I misinterpret the API documentation since my expectations are different.

Please mind that in the `AsyncCache` documentation the word `value` is not consistently used, which leads to confusion. Example: `@param <V> the type of mapped values`. However, as I understand it now, the type of the mapped value is `CompletableFuture<V>`.

**Comment by ben-manes** [comment]
> What is happening when rolling back in case of removal cause eviction or expiry?

The exception is propagated and from the cache back into the calling code. This would halt the eviction, I suppose trying again the next. Since we are calling into foreign code, there doesn't seem to be anything more intelligent we can or should do for an error that wouldn't cause confusion.

> Please mind that in the AsyncCache documentation the word value is not consistently used, which leads to confusion.

Thanks, I'll do a review of the JavaDoc. I probably copied from `Cache` and modified.
