### ISSUE TITLE
BoundedLocalCache storage is unable to find cached items when weakKeys is turned on

### ISSUE THREAD

**Issue by exmortal** [ben-manes/caffeine#343]
Hello,

I'm playing with Spring Boot 2 and Caffeine 2.8 integration and faced with some weird behavior when `weakKeys` option is turned on.

When weakKeys is enabled, BundleLocalCache storage key is represented by `References.WeakKeyReference` and it uses `System.identityHashCode(key)` to obtain it's own hashcode, so that means if key class has custom hashcode implementation cache won't work property.  

Spring uses SimpleKey class and it has generate custom hashcode based on the params field. Thus SimpleKey won't work properly with Caffeine cache when weakKeys option enabled. Basically, cache can unpredictably grows and contains references to the duplicate data because hashmap won't be able to match any items by keys because of wrong hashcode. 

I feel like I can provide my own `NodeFactory` that will fix that issue, but it'd be just a workaround.

Any ideas ? Maybe I did something wrong ? 

Code snippet:

```
@Service
@CacheConfig(cacheNames = {"fake-service-cache"})
public class FakeService {

    @Cacheable
    public List<String> getData(String code) {
        return asList(code, "test-1", "test-2");
    }
}
```

```
spring.cache.cache-names=fake-service-cache
spring.cache.caffeine.spec=initialCapacity=100, maximumSize=1000, expireAfterAccess=1m, weakKeys, recordStats
```

Thanks,
Vlad

**Comment by ben-manes** [comment]
This seems to fall into a case where an abstraction, like Spring's, is incompatible with some of the provider's features. A weak key requires that the same key instance be used, which can't happen if Spring wraps it behind the scenes. For advanced cases Spring recommends using the implementation directly, and only using theirs for the easy cases where it makes things simpler.

> Caffeine.weakKeys() stores keys using weak references. This allows entries to be garbage-collected if there are no other strong references to the keys. Since garbage collection depends only on identity equality, this causes the whole cache to use identity (==) equality to compare keys, instead of equals().

Is there a reason why you are using `weakKeys`? Generally we recommend using an explicit bound instead of relying on the garbage collector, as GC'ing is performance critical work. A weak key'd cache can be very useful for cases like request scoped / session data, where you want to discard when the external lifecycle completes.

**Comment by exmortal** [comment]
Thanks for a quick answer. Glad to hear that it works as expected.
However from my perspective it's not intuitive to expect when you think in a context of using `weakKeys` that cache would use identity instead equality. I'd expect option like `identityCache` or something. But anyway it's out of scope of this ticket. 

Btw there is no reason I'd use `weakKey`, I have experience with various cache implementations and I'd like to see what options/benefits Caffeine has. 

Thanks,
Vlad

**Comment by ben-manes** [comment]
It follows Guava's semantics, and I don't recall why it was done that way (identity vs equality for lookup). Both make sense, depending on the use-case.

Since the entry is eligible for removal when the key can be GC'd, keeping the original key instance is of critical importance. However `WeakHashMap` does check equality. I suspect it was an oversight in `MapMaker`, but not a problem when it allowed plugging in a custom `Equivalence`, and carried forward in the cache.

**Comment by Maaartinus** [comment]
@ben-manes 
> It follows Guava's semantics, and I don't recall why it was done that way (identity vs equality for lookup). Both make sense, depending on the use-case.

Yes, both make sense, but Guava [does not allow](https://stackoverflow.com/a/12284794/581205) to use standard equals with `weakKeys()`, which is IMHO wrong. There's a sort of setter (`keyEquivalence`), but it's package-private. I can't find the reasoning why it's not allowed, but I recall, I found it pretty weak.

I agree that, in case of `weakKeys()` identity makes more often sense than `equals`, but sometimes, `equals` is better - imagine, you cache some pure function and the key gets re-created: When using `equals`, you may be lucky and get a hit, with identity, it's always a bad luck. All workarounds mean more work and more overhead. Given that Caffeine uses generated classes, I'm not sure, how big the effort would be. WDYT?

**Comment by ben-manes** [comment]
I believe the `keyEquivalence` was public in an early beta, but never used correctly within Google so removed. It is used only within Guava for `Interners.weak()` from what I recall.

I think the effort would be small, for the reasons you said. I think due to codegen it could increase the JAR size for all the variations, unless there is an elegant alternative that I'm missing?

I'm not against the feature, though not sure what the cache builder setting would be, e.g. `weakKeysByEquality()`?

I know offering the full-baked `keyEquivalence` feature isn't compatible, e.g. for `byte[]` keys, because that requires forking the hash map. The weak key by equality should be same, since we have to wrap and can control that flow.

**Comment by ben-manes** [comment]
Oh, and if you want that then please open a new issue 😃
