### ISSUE TITLE
Disabled cache not working as expected

### ISSUE THREAD

**Issue by slovdahl** [ben-manes/caffeine#348]
While investigating a flaky test I found out that Caffeine's suggestion to use `maximumSize(0)` for disabling caching in tests isn't working reliably. Calling `cache.getIfPresent(key)` soon after putting something in the cache with the same key sometimes returns a cached value. Is this expected behaviour?

[The javadoc](https://static.javadoc.io/com.github.ben-manes.caffeine/caffeine/2.7.0/com/github/benmanes/caffeine/cache/Caffeine.html#maximumSize-long-) suggests that this is the correct approach.

Very easy to reproduce with:
```java
class CaffeineTest {
    @Test
    void disabledCache() {
        Cache<String, String> cache = Caffeine.newBuilder()
                .maximumSize( 0 )
                .build();

        for ( int i = 0; i < 1_000; i++ ) {
            cache.put( "foo", "bar " + i );
            assertNull( cache.getIfPresent( "foo" ) );
        }
    }
}
```

**Comment by slovdahl** [comment]
FWIW, this was found when using 2.7.0, but I updated to 2.8.0 and see the same kind of failures.

**Comment by ben-manes** [comment]
Can you set `Caffeine.executor(Runnable::run)`? Since the policy work is done async by default, this allows for a race between your test thread and that work being done.

**Comment by slovdahl** [comment]
Thanks for the tip! Yes, that's definitely possible in this case.

Might be hard to answer without knowing about the exact type of load, but would you expect it to have any noticeable impact if used in production?

**Comment by ben-manes** [comment]
For the most part it's perfectly fine to use in production. It will then behave more like Guava by amortizing the work on the calling threads. The policy overhead is pretty low, but other async work might be more expensive (like removal listener) so leveraging async helps ensure the a lower user-facing response latencies.

The things to consider are,
- `RemovalListener:` In Guava/CLHM this was deferred to a ConcurrentLinkedQueue to be processed outside of the policy's lock on a caller. In Caffeine this is submitted to the executor under the lock, assuming it manages when to run. This means an expensive callback would under the policy lock, penalizing that thread with all removal tasks. The quick would be to have the implementation submit to your own executor to become async again.
- `AsyncCache:` The configured executor is passed to the factory methods of `CompleteableFuture`, which would then run inline. You can forward to your own in the loading methods (e.g. `get(key, bimapper)` or in `AsyncCacheLoader`.
- `LoadingCache.refresh(key)` passes uses the executor to `AsyncCacheLoader.asyncReload`, which `CacheLoader` provides a default implementation of.

For unit tests I use the same-thread executor since its much simpler than calling `cleanUp()`. I know some usages in production work fine, e.g. JBoss' Infinispan does that. I haven't heard any problems in doing so except the need to forward expensive removal listener calls manually to a different executor.

**Comment by slovdahl** [comment]
Thanks for the very detailed and insightful answer, much appreciated! 🙇 Sounds like it won't cause any problem in our case 👍
