### ISSUE TITLE
asMap size values  Different meaning

### ISSUE THREAD

**Issue by CHDQ** [ben-manes/caffeine#356]
I found a bug. The `size()` method in the map returned by calling the `asMap()` method, the size result is the entire map size, not the number of valid elements. But `map.values()` returns all valid elements. After I looked at the source code, the method `BoundedLocalCache.size()` directly called `ConcurrentHashMap.size()` and did not filter out the invalid data, but the method `BoundedLocalCache.values()` filtered the invalid elements. I think `LocalManualCache.asMap() `should return a snapshot instead of the underlying map. like this
`@Override
    default Map<K, V> asMap() {
      return new HashMap<>(cache());//snapshot map
    }`

**Comment by ben-manes** [comment]
`asMap` provides a view which allows modifications, such as using `compute` methods. That is very powerful and useful. It also simplifies integrations by libraries not depend on a provider's interfaces and instead the Map.

The `estimatedSize` method doesn't promise to be exact, as that would be O(n) expensive.
```
  /**
   * Returns the approximate number of entries in this cache. The value returned is an estimate; the
   * actual count may differ if there are concurrent insertions or removals, or if some entries are
   * pending removal due to expiration or weak/soft reference collection. In the case of stale
   * entries this inaccuracy can be mitigated by performing a {@link #cleanUp()} first.
   *
   * @return the estimated number of mappings
   */
```

The `Map.size` doesn't state strictness either, only that is `the number of key-value mappings in this map`. Those mappings, as described above, might be pending removal and not be visible during iterations.

You may use `Cache.cleanUp()` to trigger maintenance work to obtain a more accurate estimate. As you showed, you could calculate by traversing the entries.

These are design tradeoffs that don't violate the collections contract. Those have to be vague due to concurrency, e.g. `ConcurrentHashMap` can be mutated concurrently and does not lock the map for its size (also an estimate!).

Sorry if this was confusing.
