### ISSUE TITLE
Why don't we copy the original table to the new table in FrequencySketch#ensureCapacity

### ISSUE THREAD

**Issue by klion26** [ben-manes/caffeine#371]
From currently [implementaion](https://github.com/ben-manes/caffeine/blob/9c100e709d0f42805ea73195c6c9717b3f92a687/caffeine/src/main/java/com/github/benmanes/caffeine/cache/FrequencySketch.java#L86) we do not copy the original table to new table size, seems this will affect the frequency of all the items we've seen.

Is there some reason not copy the original table (copy may consume too much CPU?  or there are some other reasons?

**Comment by ben-manes** [comment]
This is because we use the table's length as part of the indexing to a counter. The `tableMask` is `table.length - 1`, which thanks to power-of-two sizing lets us implement an expensive modulus (division) with a simple bitwise-and. When resizing the counters they would need to go into different locations, the keys would collide at different places, etc.

https://github.com/ben-manes/caffeine/blob/9c100e709d0f42805ea73195c6c9717b3f92a687/caffeine/src/main/java/com/github/benmanes/caffeine/cache/FrequencySketch.java#L191-L195

The entries are stored in LRU order so we would still pick a decent victim while the frequency statistics are being rebuilt. Since reads far outnumber evictions and popular items are accessed read more often, we assume that the statistics will be quickly rebuilt before impacting the hit rate too much.

**Comment by klion26** [comment]
Thanks for your reply.

> The entries are stored in LRU order

Seems we will not change the order when accessing the node, the order is LRU with write order, (come to this after a few debugging, and please correct me if I'm wrong), will the write order LRU here affect the hit rate?

> we assume that the statistics will be quickly rebuilt before impacting the hit rate too much

For this assumption, could you please share more about this?  asking about this, there is some relevance to the above question.

**Comment by ben-manes** [comment]
> Seems we will not change the order when accessing the node, the order is LRU with write order

The eviction policy uses access order queues split into an LRU (window) and SLRU (main). When the accumulated reads are applied to the eviction policy, the access should reorder the entry. Note that we stage reads into a ring buffer to apply in batches to avoid lock contention.

https://github.com/ben-manes/caffeine/blob/9c100e709d0f42805ea73195c6c9717b3f92a687/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L1530-L1553

 > For this assumption, could you please share more about this?

Caches typically follow Pareto principle, "for many events, roughly 80% of the effects come from 20% of the causes." This distribution means that some entries are much more popular than others, else we would have a uniform distribution where random is optimal. As there is some hit rate gains to be had above random, some entries will be requested more frequently. The better the hit rate, the higher percentage of cache requests can be served with a read (rather than a miss + load => write).

Since we want reads to greatly outnumber writes, likely the hot entries in the cache will be requested soon after the statistics are reset and they have been promoted into the SLRU's protected region. It's also likely that the victims are cold, or else they wouldn't be evaluated by LRU for removal. If we are dominated by reads then the statistics are rebuilt before an eviction and if not then we will have a good chance to be discarding lower value items anyway.

Note too that the sketch's resizing is triggered when either the cache's `maximumSize` was programmatically increased or when using `maximumWeight` and the cache has to discover the average number entries. The latter will mean during the initial population of the cache the sketch is resized, but often you'll reach a steady state of the maximum observed entry count. Since the resizing is usually part of the warm-up, the statistics don't matter yet since the cache won't evict until the capacity has been reached.

All of these characteristics leads me to believe it won't be a

**Comment by klion26** [comment]
Thanks for the detailed reply, very helpful 
I know why my demo did not reorder the list, In my demo there is no `UpdateTask` created, all the reorder logic's entrances is `UpdateTask`

**Comment by ben-manes** [comment]
The other entrance is in drainReadBuffer, via a lambda callback. Likely you needed to call cache.cleanup() to force the read buffer to drain early.
