### ISSUE TITLE
Question about action after readbuffer is full

### ISSUE THREAD

**Issue by klion26** [ben-manes/caffeine#380]
Currently, we'll stage reads into a ring buffer in `afterRead`, and apply to evictPolicy when drainReadBuffers

https://github.com/ben-manes/caffeine/blob/a34ba0d4ae09c040834dd810fda5f209e33b5317/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L1149-L1159

I'm asking here for the situation if the readbuffer is full (line-1154), then we'll reject all the new read-access, then these accesses would not apply to evictPolicy.

I'm just curious why do we not apply to the accesses to evictPolicy after readbuffer is full, is this about performance or anything I missed

The cache I inited is something like below
```
LoadingCache<Integer, Integer> caffeine =  Caffeine.newBuilder()
				.maximumSize(5)
				.executor(Runnable::run)
				.build(new CacheLoader<Integer, Integer>() {
					@Override
					@Nullable
					public Integer load(@NonNull Integer integer) throws Exception {
						return integer;
					}
				});
```
Thanks.

**Comment by ben-manes** [comment]
Yes, it is due to performance.

The eviction policy is shared, global state that is not itself thread-safe. For a classic LRU (via doubly-linked list), every read is a write to retain the ordering. This is why LRU caches are typically protected by a single lock, which requires reads to block each other.

The read buffer lets us accumulate this pending work very cheaply and then apply it in a batch under the lock. To obtain good hit rates we don't need perfect accuracy, as we are trying to make a probabilistic guess based on the usage history. Since a cache has hot and cold items, the hot items will have multiple events in the read buffer and stay pinned in the policy. Thus by being lossy we avoid blocking on an exclusive lock, don't over allocate the buffer, and capture a good sampling of the usage activity. We can then use more advanced and efficient single-threaded algorithms when replaying these events against the policy (e.g. W-TinyLFU, hill climbing, timing wheel).

The alternative is to degrade the eviction policy to be concurrency friendly by not retaining any global state. For example FIFO does not modify on a read, only on a write, and CLOCK policies build on that idea by maintaining usage bits. They may sweep over the FIFO multiple times trying to find a candidate by decrementing a frequency count, resulting in an O(n) worst-case cost for eviction. Similarly sampling policies record per-entry bits for fast reads, but have worse hit rates by evaluating a small distribution of entries to find the victim. We have to balance concurrency, hit rate, and worst-case tail latency.

The lossy and striped read buffer approach has a small impact on best-case read concurrency, the difference is 1-2ns per operation so not impacting performance budgets. At a cost not observable to users, we get to maximize the hit rates and have predictable and minimal tail latencies (see [The Tail at Scale](https://research.google/pubs/pub40801/)).

**Comment by klion26** [comment]
@ben-manes thanks for the detailed reply, and this wonderful project. learn many things by reading 
 the code and debugging the demo. close the issue now, will reach to the references you gave. close the issue now.
