### ISSUE TITLE
Sketch and adaptation sample size with weighted caches

### ISSUE THREAD

**Issue by ohadeytan** [ben-manes/caffeine#382]
In regular caches, the sketch halving and adaption period size is `10 * maximumSize` where the `maximumSize` is the number of items in the cache. On the contrary, in weighted caches the number of items in the cache is typically much smaller and unknown in advance. That could lead to a too long period, which would lead to sketch saturation and slow adaptation. 
Determine the number of items in the cache and set the period dynamically could benefit the performance. 
@ben-manes, do you consider that at some point and have some ideas about this issue?

**Comment by ben-manes** [comment]
This is implemented in Caffeine, which checks if the sketch is large enough each time an item is added. This is lazily initialized, but can be eagerly created by using `Caffeine.initialCapacity`. The minor problem with not easily initializing is that during the warmup the history is lost, which slightly hurts hit rates for small traces.

https://github.com/ben-manes/caffeine/blob/757f6d5d99dec825421378db99cd2e8e0869cee3/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L1647-L1652

I think the root problem is actually that the simulator doesn't have this concept and over-allocates for weighted traces when a policy is expensive to create. Since we create them unaware of the trace's characteristics and then filter, it can crash if out-of-memory. For example `SampledPolicy` creates a sampling array based on `maximumSize`, which is then dropped as the policy does not support weights. 

I'm not sure what the best fix for the simulator is. The simplest is probably to pushed the characteristics into the constructors to let them decide how to handle it.

**Comment by ohadeytan** [comment]
Thanks. I think I have a better understanding of the `ensureCapacity` concept now.

Is there a reason we can't implement something similar in the simulator (for `WTinyLFU` and its versions)? I see that the sketch does have the `ensureCapacity` method.

**Comment by ben-manes** [comment]
No reason against doing so. The adaption period in caffeine is driven by the reset period in the sketch.

**Comment by ohadeytan** [comment]
Great. Thanks again for the explanations!
