### ISSUE TITLE
Flawed JMH benchmarks

### ISSUE THREAD

**Issue by bobymicroby** [ben-manes/caffeine#39]
If you do not return a value from a test method, the JVM is free to do dead-code elimination optimizations.

All the benchmarks in the codebase I have seen are subject to a dead-code elimination. 
For example : 
https://github.com/ben-manes/caffeine/blob/master/caffeine/src/jmh/java/com/github/benmanes/caffeine/cache/FrequencySketchBenchmark.java#L57

**Comment by ben-manes** [comment]
That's a fair critique and should be fixed.

However, dead code elimination shouldn't affect the benchmarks. The reason is because it cannot eliminate code that has stateful side-effects, such as mutating a map. It can eliminate branches or computations that are never used. In all other cases those side-effects mean elimination can't occur, except in the one you pointed at (where it by chance doesn't appear to). I vaguely remember a discussion of if JMH tries to fix that in its byte-code rewriting, but regardless the style should be improved to minimize the chance.

**Comment by bobymicroby** [comment]
This is fair as well. Still the pitfall exists, and whenever possible it should be avoided . By the way  I have tried to to do ./gradle jmh in the project dir, but there was an error about non existing 'includePattern' . I have removed the check from the build file in order  run the benchmarks, but if you point me how to run them as intended it will be very nice.

**Comment by ben-manes** [comment]
Oops, I misspoke about that one case. You're definitely right :)

|Benchmark|Throughput
|---|---|
freq (elimination) | 522,384,286
freq (no elimination | 62,048,286
increment | 48,950,376

That also shows that the gain of using `Unsafe` to avoid array overhead (object header, bounds checking) isn't adding much anymore as when removed the frequency result is `59,098,743`. So I might revisit and simplify that code.

**Comment by ben-manes** [comment]
You can run the benchmark using,
```
# terminal 1
$ gradle jmh -PincludePattern=FrequencySketchBenchmark
# terminal 2
$ tail -f caffeine/build/reports/jmh/human.txt
```

**Comment by bobymicroby** [comment]
Thanks, I look around the benchmarks then . Bye bye.
