### ISSUE TITLE
CacheLoader vs. different mapping function per entry? Performance considerations

### ISSUE THREAD

**Issue by cdekker** [ben-manes/caffeine#393]
Is there a difference between these 2 use cases?

```
Cache<K, V> cache = Caffeine.newBuilder().build();
...
cache.get(k, (key) -> myCustomMapping(key));
```
and
```
LoadingCache<K, V> cache = Caffeine.newBuilder().build(key -> myFixedMapping(key));
...
cache.get(k);
```

For my use case, I'd like to have a **singleton** cache that is shared between different implementations. While the `K` and `V` types remain the same, the **mapping function is different** for each implementation (and will be provided as a lambda). 

So, only the first example would work for me, since I don't know that mapping function until I need to lookup in the cache, but I wonder if I am missing out on something important doing it that way.

----

My mapping functions will be rather expensive, some of them even including a remote API call. It is important that multiple threads will only block **on the same key** while computation is in progress, but not globally on the entire cache. Reading the JavaDoc on the `LocalCache#get` it is not clear to me how that is implemented:

>    If another call to {@link #get} is currently loading the value for the {@code key}, this thread
>    simply waits for that thread to finish and returns its loaded value. **Note that multiple threads
>    can concurrently load values for distinct keys.**
>     
>    If the specified key is not already associated with a value, attempts to compute its value and
>    enters it into this cache unless {@code null}. The entire method invocation is performed
>    atomically, so the function is applied at most once per key. **Some attempted update operations
>    on this cache by other threads may be blocked while the computation is in progress, so the
>    computation should be short and simple**, and must not attempt to update any other mappings of
>    this cache.

I bolded the 2 parts that are confusing to me. Could you clarify based on my use case if this is the right approach?

**Comment by ben-manes** [comment]
> Is there a difference between these 2 use cases?

None. `LoadingCache` wraps the `CacheLoader::load` method with a try-catch block to adapt it to a `Function`. Both methods then call into `computeIfAbsent, which is backed by a `ConcurrentHashMap` computation. They are entirely equivalent code paths.

We promote `LoadingCache` only because many developers do not realize that a racy get-compute-put can result in duplicated work (cache stampede). The only limitation is that you cannot use automatic refresh (`refreshAfterWrite`) because the cache does not have a known function to call. Otherwise the manual cache offers all the same features (such as `getAll`).

> It is important that multiple threads will only block on the same key while computation is in progress, but not globally on the entire cache. 

We defer to `ConcurrentHashMap` which uses per-bin locking. Typically a bin has only a few entries, often just 1, so there is high write concurrency. However collisions will occur and that may mean that a writer is blocked waiting on the hash bin lock. This means any caveats with `ConcurrentHashMap` will apply to Caffeine. Their internal documentation provides only this rule of thumb,

```
Lock contention probability for two threads accessing distinct elements is
roughly 1 / (8 * # of elements) under random hashes.
```

If you use `AsncCache` then we will map the key to a `CompletableFuture<V>` value. This will provide per-entry concurrency as establishing the mapping is immediate and blocking occurs outside of the map and on the future. However you are then delegating work to an thread pool, which may not always be ideal (e.g. if using ThreadLocal scoped context).
