### ISSUE TITLE
Incr + Thread safety

### ISSUE THREAD

**Issue by asad-awadia** [ben-manes/caffeine#395]
I am trying to emulate something like an `incr` in Redis i.e. an atomic increment. I might be misunderstanding the thread safety of caffeine.

Q1) The instance of caffeine itself is thread-safe - but the underlying data being mutated is not?

Q2) Is the `asMap` function provided to be used? Or is that something that should be avoided?

```
val cache = Caffeine.newBuilder().maximumSize(100).build<String, Int>()
  repeat(10) {
    thread {
      val s = (cache.get("test") { 0 } ?: 0) + 1
      println("adding ${Thread.currentThread().name} $s")
      cache.put("test", s)
    }
  }

  Thread.sleep(5000)

  println(cache.asMap()) // prints test  == 1
```

I was under the assumption that caffeine would handle this sort of situation - and test would be 10 at the end i.e. only the first invocation of 'get' would go to the mapping function - the rest would get the value from the cache

I know I can use atomic integer - but that is not the point of this question [https://github.com/ben-manes/caffeine/issues/190]

```
val cache = Caffeine.newBuilder().maximumSize(100).build<String, Int>()
  repeat(10) {
    thread {
      cache.asMap().putIfAbsent("test", 0)
      cache.asMap().computeIfPresent("test") { _, c -> c + 1 }
    }
  }

  Thread.sleep(5000)

  println(cache.asMap()) // prints test == 10
```

@ben-manes Any thoughts? Am I missing something?

**Comment by Maaartinus** [comment]
> I was under the assumption that caffeine would handle this sort of situation - and test would be 10

It can't. You're doing twenty independent cache accesses: 10 reads and 10 writes. They're all atomic and thread-safe, but there's no ordering among accesses from different threads. That's not a bug or a missing feature - it's how concurrency works in general.

That's why `Map.compute` exists. Your second approach works, but the best way is just
```
cache.asMap().compute("test") { _, c -> c==null ? 1 : c + 1 }
```

**Comment by asad-awadia** [comment]
does that mean asMap can and should be used if needed? It's not a 'hack' ?

**Comment by ben-manes** [comment]
The first snippet never writes back into the cache after the first read of the key. If you stored an AtomicInteger then it might work, but Integer is immutable.

Yes, asMap is perfectly fine to use and works nicely here.

**Comment by asad-awadia** [comment]
awesome

@ben-manes just for my understanding - is a `get()` faster than a `asMap().get()` - or not really since caffeine is built on top of a ConcHashMap

**Comment by ben-manes** [comment]
They are about the same.

`Cache.get` performs a `Map.get` as a lock-free optimistic lookup if the entry is present and not expired. If it is, it falls back to a computation to possibly load the entry. This means that in the common case you will observe the same performance and number of map operations (get+put vs get+compute). The `Cache.get` and `Map.computeIfAbsent` have the same code paths.

We do build on top of CHM, but do have to coordinate various details like expiration, reference collection, etc. that makes the calls not a direct pass through. However they are relatively lightweight additions.

**Comment by asad-awadia** [comment]
One last thing:
```
We do build on top of CHM, but do have to coordinate various details like expiration, reference collection, etc. that makes the calls not a direct pass through. However they are relatively lightweight additions.
```

How does adding things on top of CHM improve performance https://github.com/ben-manes/caffeine/wiki/Benchmarks

How does caffeine become faster than CHM if it is based on CHM?

**Comment by ben-manes** [comment]
We improve performance for a `computeIfAbsent` call because we perform an optimistic pre-screen for the entry. Unfortunately CHM is pessimistic by locking if present, whereas we get to be lock-free. You can [read](http://jsr166-concurrency.10961.n7.nabble.com/Re-ConcurrentHashMap-computeIfAbsent-td11687.html) Doug Lea's thoughts on why he made this choice.

In JDK8 the map will always take a lock and block. In JDK9 a partial pre-screen was added based on that discussion which skip locking if the hash bin head holds the desired entry, but otherwise lock to search the bin. In a micro-benchmark we incur worst case results so this may not be problematic in most usages.

For a `Map.get` versus `Cache.getIfPresent`, Caffeine is about 33% of the performance of an unbounded CHM. That difference is single digit nanoseconds per operation, so we shifted focus to other topics like optimizing writes, the hit rate, and features.

**Comment by asad-awadia** [comment]
Perfect thank you!

Will read the link
