### ISSUE TITLE
When does an entry get removed if computation fails

### ISSUE THREAD

**Issue by lwshuo** [ben-manes/caffeine#396]
Apologies if this is asked before, and feel free to just send a link to answers.

I'm using AsynLoadingCache. The doc says `If the asynchronous computation fails, the entry will be automatically removed`. I'm wondering when does it get removed? 

I want to return 202 to the users while the cache is loading and they can come back for it later. Is it possible that the entry just got removed between their checks and when they come back the cache tries to load again? If the cache does wait for get() or join() before the entry is removed, what happens when there are multiple users checking the same entry? Does the first one get the exception and then the entry gets removed so the second one will trigger another load?

**Comment by ben-manes** [comment]
Caffeine is a `ConcurrentHashMap` with eviction policies. An async cache is then a `Map<K, CompletableFuture<V>>`. The behavior that you would get using a CHM directly is the same that we provide.

For async computations, this works by using a `computeIfAbsent` to store the future as a map entry. When present and in-flight, the same entry is returned to all callers for that key. When it fails then there is a race between the entry's removal and concurrent callers. This means you might retrieve the failure before the cache can remove it, simply because of concurrency.

Caffeine removes the entry using a `whenComplete` handler on the future, which on an error will perform a `Map.remove(key, oldValue, newValue)`. The conditional removal ensures we only remove the failed future if mapped, to avoid stampedes. Since future's add callback into an internal stack, this means any of your own callbacks added after the entry is returned will be invoked before Caffeine's. That causes another possible race of being informed that the future failed by a callback, but it still being in the cache because our own handler has yet to be invoked.

When the future is finally removed, then the next call perform a new load.

**Comment by lwshuo** [comment]
Thank you so much for the quick reply!
