### ISSUE TITLE
AsyncCache with "expiry-after-write" may return stale values or call the loader more frequently than needed

### ISSUE THREAD

**Issue by stepanv** [ben-manes/caffeine#404]
While writing tests in my own application I found out Caffeine AsyncCache is not working as I expect as far as expiration goes when using "expiry-after-write".

I created a suite of reproducers as a PR: https://github.com/ben-manes/caffeine/pull/403

In general, when the cache is under load, it intermittently happens 
* to return a stale value (the expiration didn't work) 
* to load the value even though the item did not expire yet (this may not be a bug)

I hope the problem would be easy to understand based on the submitted test reproducer.

**Comment by ben-manes** [comment]
A confusion is subtle race conditions on a callback attached to the future. When it completes we update the cache, either removing if a failure or adding the metadata if successful (weight, expiration time). When a future is in-flight it is not eligible for expiration or size eviction, as that would be surprising and often wrong. This callback is attached after the future is stored into the cache for reasons described in #372. This can cause a race condition in your tests.

**Comment by ben-manes** [comment]
The following addition to your loop corrects this by delaying the next iteration until the entry is updated. It seems to pass your tests, though the high `count` value means I'm still waiting for it to finish!

```java
Awaits.await().until(() -> {
  OptionalLong age = policy.ageOf(2, TimeUnit.NANOSECONDS);
  return !age.isPresent() || (age.getAsLong() > 0);
});
```

**Comment by stepanv** [comment]
Thanks @ben-manes , the above mentioned snippet avoids obtaining a stale value in the tests (although some are failing in other ways but probably by design).

So just to verify my understanding, is it correct the AsyncCache is eventually consistent (by its nature) and as a result one might get a stale value (i.e., getting a value for a key that recently expired) but it's expected/proved it would happen very rarely and also the consistency is promptly restored in such case (so the next get almost certainly succeeds)?

**Comment by ben-manes** [comment]
Yes.

I wouldn't call it eventually consistent, as that has a formal meaning, but the very nature of asynchronous calls means we are subject to concurrency, the scheduler, etc. If you disable concurrency by using a same-thread executor then there should be exactly how you'd expect.

Due to concurrency a read and write thread may overlap, and the reads are lock-free so they won't block. The overlap means the reader may see either the old or new value, depending on what they obtained from a volatile read. If the read value has expired (comparing a `now()` versus the entry's timestamp), then the cache will fake a miss and treat it as if absent. That can mean the entry is reloaded, e.g. on a `get(key)`.

When an entry is being loaded the expiration time doesn't start, it starts when the item has materialized. In AsyncCache the map entry is key => future and that future is populated asynchronously. The only way to update the entry's timestamp is after the future completes, which requires adding a callback handler (`whenComplete`). Because the user may supply the future, we should return that directly back rather than a chained instance. This means you cannot wait on your future and expect the cache to have done its work, as the callback may not have been invoked yet. That causes the start time for expiration to be delayed by a short while (usually nanos).

That's as close as we can get with being asynchronous/concurrent and maintaining consistent reference identity of the future.

**Comment by stepanv** [comment]
Thanks @ben-manes for the exhaustive explanation. I just wonder why not to return the chained instance of the future but maybe that's implied by the Caffeine overall design. Or maybe by the characteristics of the CompletionStage API which has multiple imperfections. But anyway thanks a lot!

**Comment by ben-manes** [comment]
The main reasons are,

1. It would lose identity, as futures lack an equals / hashCode. This means advanced uses would break because the references would differ.
2. Explicit completion (success, errors, cancel) is not propagated upward, only down. This means canceling an expensive operation doesn’t work.

If we broke those two then it would be much more surprising and limit advanced usages. It’s the least worst between two bad options.
