### ISSUE TITLE
.getIfPresent(key) triggers refresh?

### ISSUE THREAD

**Issue by VytautasSer** [ben-manes/caffeine#405]
Hello,

I have found this unexpected behavior, maybe it's not a bug, but I have not expected such behavior from docs: 

_"Returns the value associated with the {@code key} in this cache, or {@code null} if there is cached value for the {@code key}."_

```
@Test
public void test_getIfPresent() {
	FakeTicker ticker = new FakeTicker();

	LoadingCache<String, String> cache = Caffeine.newBuilder()
			.ticker(ticker::read)
			.refreshAfterWrite(5, TimeUnit.MINUTES)
			.expireAfterWrite(30, TimeUnit.MINUTES)
			.build(key -> key);

	String key = "key";

	cache.get(key); // initial load
	ticker.advance(10, TimeUnit.MINUTES);
	cache.policy().expireAfterWrite().get().ageOf(key).get().toMinutes(); //10

	cache.getIfPresent(key); // refreshes value?

	ticker.advance(21, TimeUnit.MINUTES);

        // 21, but should be 31?
	cache.policy().expireAfterWrite().get().ageOf(key).get().toMinutes(); 

        // finds value, but should be null and expired with time 31?
	cache.getIfPresent(key); 
}
```
Seems like if I'm in range of value age 5-30 minutes and use .getIfPresent(key) method, loader is activated and value is updated (refreshed).

Thank you for your great lib and time.

**Comment by ben-manes** [comment]
In this case age refers to the time that has passed since the timestamp was last reset. The remaining time until the entry expires is the difference between the expiration setting and the entry's age. From the JavaDoc,

> Returns the age of the entry based on the expiration policy. The entry's age is the cache's estimate of the amount of time since the entry's expiration was last reset.

The timestamp is reset when the entry is refreshed; see the [wiki page](https://github.com/ben-manes/caffeine/wiki/Refresh).  This allows your threads to avoid a periodic penalty when popular entries expire and the callers must block while it is being loaded. The refresh triggers this earlier, allowing those entries to stay updated and hiding the penalty from the callers. This is a form of prefetching. The unpopular items would not be refreshed due to inactivity, allowing them to expired and reclaim memory.

**Comment by VytautasSer** [comment]
Great! Thank you for your answer.
