### ISSUE TITLE
Add loadSuccessTime() and loadFailureTime() to CacheStats

### ISSUE THREAD

**Issue by john-karp** [ben-manes/caffeine#409]
CacheStats tracks loadSuccessCount and loadFailureCount independently, but doesn't do a corresponding breakdown of load time.

I think it would be helpful to know if time is being spent in success vs failure.

Came up in https://github.com/micrometer-metrics/micrometer/pull/2020

**Comment by ben-manes** [comment]
Can you explain the benefits from the perspective of the metrics themselves? I understand it is nice consistency for metric reporting, but I do not know how you would operationally react to this data. I suspect that is why they were combined in Guava, where this was never asked for. More often you would be trying to understand why failures occurred at all, rather than the time spent on each.

Note that you can supply your own `StatsCounter` which could track these independently.

**Comment by jkschneider** [comment]
@ben-manes One of the big benefits would be in unifying both success and fail outcomes under one metric name, something like `load.count` which could be dimensionally drilled down to the different outcomes.

Many monitoring systems don't support shipping a timer `loads{outcome=success}` and a _counter_ `loads{outcome=fasilure}`. They would expect that all metrics with the same name have the same type.

Having unified the metric names, we can plot total _attempted_ loads by simply plotting the count statistic shipped by `loads`. monitoring systems by default sum across distinct tags unless you drill down on one of them. This is more intuitive than having to do `load.success + load.failure` when building a dashboard.

Also, plotting error ratio as a function of throughput (rather than error rate which isn't as useful) is more intuitive. It becomes `loads{outcome=failure}/loads`.

**Comment by ben-manes** [comment]
For more advanced cases, you could implement your own `StatsCounter`. See this [example](https://github.com/ben-manes/caffeine/tree/master/examples/stats-metrics) using dropwizard metrics. That pushes the metrics rather than having to poll the summation from `CacheStats`.

The cache only knows of a failure when either an exception is thrown or the expected entry is absent. This is reported identically and, most often, is unexpected failures that cause application errors. The fine grained causes would have to be instrumented in application code.

Given that failures that we can report are typically an application bug to be fixed, I'm still confused as to the operational value. Yes, for symmetry it is a reasonable ask. But I am confused as to how this metric would help developers?

It would seem that this particular ask is not very valuable but that supplying a custom `StatsCounter` could provide a richer experience. I am open to making additions, but would like to understand if there are more concrete benefits.

**Comment by ben-manes** [comment]
I am working on v3 where we could make this change. Unfortunately my concerns were not addressed in your reply so I am still inclined to not provide this. I do not see how it would assist operational teams (performance, SREs) and therefore lean against tracking metrics that don’t carry their weight.

**Comment by john-karp** [comment]
FYI, I implemented StatsCounter for micrometer: https://github.com/micrometer-metrics/micrometer/pull/2163

So micrometer users who want the full breakdown will be able to get what they want that way.

**Comment by ben-manes** [comment]
Thanks, I think that's a nice approach. Closing.

**Comment by jkschneider** [comment]
@john-karp The `StatsCounter` has been merged in Micrometer. Thanks!
