### ISSUE TITLE
Please add synchronous expiring

### ISSUE THREAD

**Issue by opendedup** [ben-manes/caffeine#41]
I would like to use this cache in my open source project sdfs but am stuck because data expires in an asynchronous fashion. This causes an out of memory issue for me because I then flush the expiring data to disk when it is aged out. This takes time and can cause an out of memory issue if there are a lot of pending writes. Would it be possible to add a synchronous option to the builder that would cause new inserts to block until data is expired, similar to guava?

**Comment by ben-manes** [comment]
In Guava the processing is performed under the segment lock, thereby blocking future writes to that segment. The removal of segments means that there is a global lock, which is operated on asynchronously to not become a bottleneck. I'd expect you'd see a similar problem in Guava because `RemovalListener` is asynchronously processed too. So I'm a little surprised by this as it seems the problem could occur in either library.

You can specify the Executor which is where the maintenance work is performed. Perhaps that can be leveraged to throttle writes? It might be enough to put the penalty back on the calling thread (`Runnable::run`) or use a lock that blocks writers until complete. There could be a hack with `CacheWriter`.

I'm not sure what makes sense to change at the library level, but I think we could figure out a way to tune it at your usage.

**Comment by opendedup** [comment]
Thanks for the Reply Ben,

I believe Guava locks inserts based on the RemoveListener because its what
I use to throttle IO based on pending writes. The cache itself is small,
sometimes only 100 entries, which may mean that Guava's lock segmentation
still blocks on most inserts.

Thanks for the consideration and this great project.

Sam

**Comment by ben-manes** [comment]
In Guava the `RemoveListener` is executed outside of any locks on a caller's thread. Most likely the writers are busy processing the removals, so it appears to throttle the rate (unintentionally). Technically the segments are free for other writers to busily insert entires while the listener is doing work.

It seems like you need a more explicit rate limiting scheme. If your writes are in a thread pool then you could have Caffeine use it, which would then throttle based on the number of threads in the pool. Another option might be to block inserts while expiration is being processed, perhaps with a lock. I'm not sure what to recommend so you might need to experiment a little to find the best match.

Hope that helped a little.

**Comment by ben-manes** [comment]
Sam,
I sat on this for a while in case an idea struck me for how to map this to a generally useful feature. I think it could be adequately solved at a layer above the cache and is better suited to a customization in your code.

Basically you're using the cache as a means to throttle the write rate. The fact that Guava delegates execution of the removal listener (outside of any lock) to the calling threads was sufficient. Guava [optionally](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/cache/RemovalListeners.html) lets that be asynchronous to avoid high latencies and have a predictable response time. Now that Java comes with a globally shared executor, I think making it asynchronous is a better default choice.

I see a few simple approaches that might work well for you.
 * Use a shared [Semaphore](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/Semaphore.html) within your `RemovalListener` and `CacheLoader` to limit the number of concurrent writes.
 * Use a Guava [RateLimiter](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/util/concurrent/RateLimiter.html) in your `CacheLoader` to reduce the pace of creation.
 * Mimic Guava by having removal listeners publish a task to a shared `ConcurrentLinkedQueue`. All cache accesses should poll the queue checking for pending work and running the consumed tasks.

**Comment by ben-manes** [comment]
Closing because I don't think there is anything actionable to be done within this project. Feel free to reopen to discuss or email me privately if I can be of help. Thanks!

**Comment by JiahuiJiang** [comment]
@ben-manes Can we reopen this ticket?
Currently we are using Caffeine where it builds a working directory during population time, and in the removal listener we remove the directory. And for the same key, the path to the directory is always the same for debugging easiness.
But what happened to us is, the removal listener doesn't get called right away (or at least before next time someone accesses the key), so when a user access that key again, it doesn't recreate the directory because it's still there, then the working directory gets deleted.

So maybe we can make it optional to be "guarantee to finish cleanup before the next access"?
Thanks!

**Comment by ben-manes** [comment]
Would CacheWriter work here? It is called synchronously with the removal.

**Comment by ben-manes** [comment]
If you are using a LoadingCache and removal is delayed until the next access due to races or inactivity, the writer is notified synchronously before the computer. So it could be the right approach.

**Comment by JiahuiJiang** [comment]
ohh! wasn't aware of the existent of CacheWriter. This looks exactly like what I need. Thanks! :)
