### ISSUE TITLE
Performance Measures with HTM

### ISSUE THREAD

**Issue by JohannesLichtenberger** [ben-manes/caffeine#415]
I'm working on a persistent (preserving previous states), durable data store[1] in my spare time and I'm using Caffeine for the in-memory caches of dynamically sized page fragments. As I'm currently reading a Ph.D. thesis from Dr. Viktor Leis I came across Harware Transactional Memory and some talks from the guys behind Azul Zing and I think Caffeine might benefit a lot and I think for Hotspot there might be a JVM flag to activate the optimizations.

So, I wonder if you made some performance tests :-)

[1] https://sirix.io

**Comment by JohannesLichtenberger** [comment]
My case of using Caffeine caches in a light-weight buffer manager might be a bit special as I'm setting direct in-memory references, too once a page is read from durable storage and use it for instance to null the references on cache eviction or for other transactions, the first time they read a fully reconstructed database page (they might be scattered on persistent storage as the page-fragments are created based on a sliding window With only a few records which have been changed plus a few more which would not be in the window size).

**Comment by ben-manes** [comment]
If you find a flag in the JVM then you can run our benchmarks. I'm not aware of any, as Azule used to use a modified Linux kernel with and a custom JVM to benefit from it. If any improvements went into OpenJDK then it would be for its lock implementations and likely doesn't have a user-visible flag.

Caffeine avoids blocking on locks on a read-path. The lock contention you might experience would be collisions for write operations to the underlying ConcurrentHashMap. This is rarely a problem unless you have a write-heavy workload, e.g. perform all of your work under `asMap().compute` calls for exclusive access to the entry.

I suppose you could try to run Azul's Zing trial jvm has those [optimizations](https://www.azul.com/press_release/azul-systems-announces-general-availability-release-16-07-zing-runtime-java/).

**Comment by JohannesLichtenberger** [comment]
I think in the first place they implemented it for `synchronized` methods (as it's way more easy than for ReentrantLock for instance), but the first talk was from 2016 and he mentioned it should be optimized in Hotspot, too. I'm just curious, as obviously other languages might have some advantages when you want to write a database system and regarding I/O. Currently, I also wonder to what extend JVMs make automatically use of SIMD instructions for some loops or if I have to specify a JVM flag... but that's not really Caffeine relevant.

But I guess the `ConcurrentHashMap` might benefit from HTM. In my case the number of read-only transactions isn't limited, which all might write and read from Caffeine for the first time a page is reconstructed in-memory. Then, a PageReference holds both an in-memory reference and a long offset into a file (not sure if I could do real pointer swizzling in Java or Kotlin).

I currently just want to learn what's possible with JVMs and modern hardware :-) what's particularly interesting is also Byte Addressable Non-volatile Memory (as I need fast, concurrent random reads of small page-fragments). Ok, that's getting off-topic...

**Comment by ben-manes** [comment]
Looking at your usages, Sirix doesn't use any of the cache's computation abilities. It only does getIfPresent, put, and invalidate operations, sometimes in bulk. This would then lock only as long as the `ConcurrentHashMap` and related logic takes for per-entry writes. 

A micro-benchmark of 8 threads performing only put + remove in a Zipfian distribution:
- ConcurrentHashMap - 58M ops/s
- Synchronized LRU - 6.5M/ops
- Caffeine - 16.5M ops/s
- Guavs - 10.5M ops/s

That's fairly good, but we do pay a cost on removals due to having to perform them under a `Map.computeIfPresent`, rather than a cheaper `Map.remove`, to handle races with the eviction policy. Despite that, it is still quite reasonable for a hostile workload as a cache.

For your workloads I would recommend investigating if you can replate your racy getIfPresent-load-put calls with an atomic get call. A cache stampede can result in many threads performing the expensive loading call concurrently, whereas a computeIfAbsent call will perform this work once and deliver it to any waiting threads. That tends to have a nice performance boost.

Otherwise there is not much for us to do here. I think a comparison of OpenJDK versus Zing would be neat.

**Comment by ben-manes** [comment]
Both ConcurrentHashMap and Caffeine prefer using `synchronized` over `ReentrantLock` for per-entry locking. So any benefits would be taken advantage of. We do use a ReentrantLock but for its tryLock ability so as to be non-blocking when scheduling our maintenance work.

For SIMD, the yearly [JVM Language Summit](https://openjdk.java.net/projects/mlvm/jvmlangsummit/) has progress reports from Intel & Oracle on their work to bring this into the JVM. While some work is in C2 / Graal for an automatic optimization, bringing it into the language is an ongoing effort via the Vector API project.

For NVM you might look at [Apache Mnemonic](https://github.com/apache/mnemonic). For direct support via the JVM, see [Project Panama](https://www.youtube.com/watch?v=r4dNRVWYaZI&list=PLX8CzqL3ArzXFRVYmbvZfZQ0CQMfIIFCH&index=4&t=0s) for their progress.

A lot of really neat work, but no new APIs that I think would be able to take advantage of. I think most of the changes, e.g. Loom's virtual threads, will be transparent performance improvements.

**Comment by JohannesLichtenberger** [comment]
Thanks a lot. Yes, I think besides using a memory mapped file would be much faster, using the Foreign Memory API I guess...

And thanks for all the links. Amazing, that you work on Caffeine in your spare time, that's a great incentive. Thanks, and have a ģreat weekend :-)
