### ISSUE TITLE
Question regarding cache.get() with MappingFunction

### ISSUE THREAD

**Issue by schlangz** [ben-manes/caffeine#430]
Hi, 

I want to implement a cache for objects that otherwise need to be loaded from a database. If I specify a mappingFunction to cache.get() which will load the object from the database, will the entire cache being blocked for updates while the mappingFunction is being executed? 

I guess in that case it would be better to see if the object is already in the cache, and in case it isn't it should load it afterwards? Thank you.

**Comment by ben-manes** [comment]
It will use fine-grained locking so that other writes may occur in parallel. See details below if interested.

We use `ConcurrentHashMap` compute methods, so this behaves similar to `computeIfAbsent`. That uses a per-bin lock, where a bin holds a small set of entries. The number of bins grow with the map size, so a very small cache might suffer from lock contention. See the [FAQ entry](https://github.com/ben-manes/caffeine/wiki/Faq#write-contention).

If your calls are async in nature, an `AsyncCache` can optimize a little more because it stores a `CompletableFuture` as the Map's value. This way we only lock the map to generate this future, and then callers are blocked on the future's lock for the result. This also lets us perform a more optimal `getAll` by filling in multiple map entries with incomplete futures, performing the bulk operation, and finishing them with the result. The sync cache can't lock multiple entries, so it's a more naive racy loadAll & putAll sequence. However, `AsyncCache` requires executing the work on a different thread pool and storing the future, so it can be slightly wasteful for synchronous usages.

**Comment by ben-manes** [comment]
> I guess in that case it would be better to see if the object is already in the cache, and in case it isn't it should load it afterwards? 

We do this for you as an optimization to avoid locking, which has a nice [improvement](https://github.com/ben-manes/caffeine/wiki/Benchmarks#compute) on a cache hit.

**Comment by schlangz** [comment]
Awesome, thank you for your quick and detailed response.
