### ISSUE TITLE
Question: ForkJoinPool usage when having multiple Caffeine caches

### ISSUE THREAD

**Issue by schlangz** [ben-manes/caffeine#432]
I have a quick question regarding the usage of ForkJoinPool when using multiple Caffeine cache instances. Since they all execute their maintenance work through FJP I'm wondering if it would be beneficial to supply my own thread pool executor to the specific cache instances? Thank you.

`Stack trace:`
`sun.misc.Unsafe.unpark(Native Method)`
`java.util.concurrent.ForkJoinPool.signalWork(ForkJoinPool.java:1649)`
`java.util.concurrent.ForkJoinPool.externalPush(ForkJoinPool.java:2414)`
`java.util.concurrent.ForkJoinPool.execute(ForkJoinPool.java:2648)`
`com.github.benmanes.caffeine.cache.BoundedLocalCache.scheduleDrainBuffers(BoundedLocalCache.java:1419)`
`com.github.benmanes.caffeine.cache.BoundedLocalCache.scheduleAfterWrite(BoundedLocalCache.java:1386)`
`com.github.benmanes.caffeine.cache.BoundedLocalCache.afterWrite(BoundedLocalCache.java:1356)`
`com.github.benmanes.caffeine.cache.BoundedLocalCache.removeNoWriter(BoundedLocalCache.java:2118)`
`com.github.benmanes.caffeine.cache.BoundedLocalCache.remove(BoundedLocalCache.java:2081)`
`com.github.benmanes.caffeine.cache.LocalManualCache.invalidate(LocalManualCache.java:140)`

**Comment by ben-manes** [comment]
Typically the maintenance work is very fast, since it uses O(1) algorithms. However writes do trigger it to be run promptly, since an eviction may be required. Even then, it usually isn't a problem since concurrent writes stage their policy updates in a ring buffer, allowing the FJP task to perform the work in batch. So unless you observe an issue in your performance profile, you can probably ignore our usage entirely.

We defer the work to an executor primarily to minimize latency on user-facing calls. For example eviction would need to obtain the entry lock (via a `compute`) and a hash-table conflict on the same bin lock against a long-running load would penalize the evictor thread. So little things like that, which was reasonably fine in Guava, we delegate to give users the choice by supplying their own executor.

You might consider penalizing your callers and use a same-thread executor (`Runnable::run`). That's fast for all of the cache's own operations, but also means any of your usages would be serial (removal listener, AsyncCache, refresh). If you did use the same thread, then your calls might override to delegate to a different executor as you saw fit.

A reason to perhaps consider a different thread pool is if you are already overloading FJP with I/O tasks, such as file transfers. In that case it will create compensating threads, may even starve if an async task blocks on another future waiting to be executed. In those cases you might prefer having a dedicated threadpool subsystem, such as workers consuming from a message queue. If your cache is performing these expensive calls, e.g. via an AsyncCache making long-running remote calls, then you might prefer decoupling from FJP used for quick calls by other parts of the application.

If none of that sounds applicable and you don't observe a bottleneck, then leaving the defaults should be okay.

**Comment by schlangz** [comment]
Perfect explanation as always, thank you.
