### ISSUE TITLE
Forcing synchronous reload on refreshAfterWrite?

### ISSUE THREAD

**Issue by noobgramming** [ben-manes/caffeine#433]
This may be a feature request. I'm attempting to use Caffeine to implement a fail-over style cache. I want to be able to return stale values when loading fails. reload() seems like a good fit for this, but I'm having trouble determining if I can force it to be synchronous. I want it to always attempting loading the value synchronously, not return the stale value first and reload a fresh one in the background.

Does it already behave this way when using the version of reload() that doesn't return a Future? If not, can I make it behave this way by using the asynchronous reload but returning CompletableFuture.completedFuture(slow loading code here)?

**Comment by ben-manes** [comment]
You can override `asyncReload` in your cache loader, which returns the future. However that will still return the stale value and only penalize the caller with the computation. A concurrent get for that entry won't try to reload since one was started, but also will not wait for the in-flight reload to complete, so you will observe stale values from other calls regardless. This makes it unclear exactly what a synchronous refresh should mean, as some may want different staleness characteristics.

I think your case might be more like expiration with a victim cache. If when expired the entry is evicted into a secondary cache, then on load it can fallback to it if available. This could be done by coordinating a synchronous removal listener (cache writer) and a cache loader, so that (1) the entry is evicted to victim cache, (2) gets block while one caller loads it, (3) loader falls back to victim if needed, (4) victim evicts as desired.

Otherwise, you could use the compute methods from `Map` to rebuild this functionality. The simplest might be to always use a `compute` to block readers and writers for that key. That would reduce performance, so it depends on the use-case and how much complexity is justified.

**Comment by noobgramming** [comment]
I'll try these options, thanks!
