### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by farendaibiao** [ben-manes/caffeine#435]
Part of Java code:

```
 bigData = Caffeine.newBuilder()
                            .initialCapacity(MAX_NUM)
                            .maximumSize(MAX_SIZE)
                            .expireAfterAccess(12, TimeUnit.HOURS)
                            .build(new BitIntentDataCacheLoader());
```

    private class BitIntentDataCacheLoader implement CacheLoader<String, Object> {
        @Nullable
        @Override
        public Object load(@NonNull String key) throws Exception {
            return "null";
        }
    } 

Crash only happens on Android Q (10)

Caused by: java.lang.IllegalStateException: com.github.benmanes.caffeine.cache.SSMSA
	at com.github.benmanes.caffeine.cache.LocalCacheFactory.newBoundedLocalCache(LocalCacheFactory.java:101)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalManualCache.<init>(BoundedLocalCache.java:3357)
	at com.github.benmanes.caffeine.cache.BoundedLocalCache$BoundedLocalLoadingCache.<init>(BoundedLocalCache.java:3692)
	at com.github.benmanes.caffeine.cache.Caffeine.build(Caffeine.java:1021)

**Comment by ben-manes** [comment]
That stacktrace is when a reflective call fails to load the specialized implementation class. Unfortunately you didn't include the nested exception, just the runtime wrapper, which specifies the exact cause. Most likely it is a `ClassNotFoundException` and you have dead code eliminated the class (e.g. via Proguard). We use code generation to reduce runtime overhead by including only the necessary cache or entry fields and reflection to load that specialized type on construction.

Note that Android is very a different environment to optimize for, and Caffeine is oriented towards server-side JVMs. During the development of Guava's cache it was considered overkill for most Android users so the Android team built a lighter weight alternative, [LruCache](https://developer.android.com/reference/android/util/LruCache). You might consider an Android-specific library like Dropbox's [Store](https://github.com/dropbox/store) as more suitable, since it will make design tradeoffs more appropriate to your application.

**Comment by farendaibiao** [comment]
> That stacktrace is when a reflective call fails to load the specialized implementation class. Unfortunately you didn't include the nested exception, just the runtime wrapper, which specifies the exact cause. Most likely it is a `ClassNotFoundException` and you have dead code eliminated the class (e.g. via Proguard). We use code generation to reduce runtime overhead by including only the necessary cache or entry fields and reflection to load that specialized type on construction.
> 
> Note that Android is very a different environment to optimize for, and Caffeine is oriented towards server-side JVMs. During the development of Guava's cache it was considered overkill for most Android users so the Android team built a lighter weight alternative, [LruCache](https://developer.android.com/reference/android/util/LruCache). You might consider an Android-specific library like Dropbox's [Store](https://github.com/dropbox/store) as more suitable, since it will make design tradeoffs more appropriate to your application.

I am very grateful to you for your advice and I am still hope this wonderful project could be optimized to support on Android Q.

**Comment by ben-manes** [comment]
Are you sure that you don't have unused classes removed during your compilation (via Proguard, DashO, etc)? The AOT compiler is likely removing the classes and that requires a configuration change on your end. There is nothing that should stop Android Q from working on our side, except it is a very different target to optimize and Caffeine might not be the best library for your usage.

**Comment by farendaibiao** [comment]
> Are you sure that you don't have unused classes removed during your compilation (via Proguard, DashO, etc)? The AOT compiler is likely removing the classes and that requires a configuration change on your end. There is nothing that should stop Android Q from working on our side, except it is a very different target to optimize and Caffeine might not be the best library for your usage.

            zipAlignEnabled false
            shrinkResources false
            minifyEnabled false
all false, and this happens only on Android Q, and the system lower than Android Q is all OK.

**Comment by ben-manes** [comment]
What is the nested exception? That is likely a `ClassNotFoundException`, but only a guess since you didn't include it.

Android Q [changed](https://developer.android.com/about/versions/10/behavior-changes-10#aot) ART's AOT behavior for discovering classes. If you can list the included classes in your dex output, e.g. via `dexdump`, then you'll be able to see if the missing class is included in your distribution.

**Comment by ben-manes** [comment]
You might also look into [dex2oat](https://source.android.com/devices/tech/dalvik#AOT_compilation) which compiles on the device, and might be removing the class for those users.

**Comment by farendaibiao** [comment]
> You might also look into [dex2oat](https://source.android.com/devices/tech/dalvik#AOT_compilation) which compiles on the device, and might be removing the class for those users.

I see. I am very grateful to you for your detailed reply.

**Comment by ben-manes** [comment]
If you want minimal code changes, you could switch to Guava's Cache since your usage would be identical. It is probably less effort to do that than try to debug how to use Caffeine, as Android is not our target platform. Moving to an android-first library like Dropbox's is your best long-term bet. I'd be happy to see you use Caffeine on the server-side, but I can't really help much in this scenario.
