### ISSUE TITLE
'expireAfterWrite' Cache behaves incorrectly, when existing key being updated

### ISSUE THREAD

**Issue by haron4igg** [ben-manes/caffeine#436]
Discovered this issue in my scala project.
`Lib Version: "com.github.ben-manes.caffeine.2.8.5"`

When already existing key in cache being updated, the expiration of all other keys in cache being aligned with updated one.
The test case bellow fails:

```scala
  test("example") {
    var currentTime = 0.millis
    val ticker: Ticker = () => currentTime.toNanos

    val cache: Cache[Seq[String], Unit] = Caffeine.newBuilder()
      .expireAfterWrite(10, MILLISECONDS)
      .maximumSize(100000)
      .ticker(ticker)
      .build[Seq[String], Unit]()

    cache.put(Seq("a"), ())
    cache.put(Seq("b"), ())
    cache.put(Seq("c"), ())
    cache.put(Seq("d"), ())

    cache.cleanUp()
    cache.estimatedSize() shouldBe 4

    currentTime += 5.millis

    cache.put(Seq("a"), ())

    currentTime += 6.millis

    cache.cleanUp()
    cache.estimatedSize() shouldBe 1  // Fails here, with "4 != 1" assertion.
  }
```

If i insert another key after 5ms timeout, or invalidate the old key before insert - then test case passes.

```scala
  test("example") {
    var currentTime = 0.millis
    val ticker: Ticker = () => currentTime.toNanos

    val cache: Cache[Seq[String], Unit] = Caffeine.newBuilder()
      .expireAfterWrite(10, MILLISECONDS)
      .maximumSize(100000)
      .ticker(ticker)
      .build[Seq[String], Unit]()

    cache.put(Seq("a"), ())
    cache.put(Seq("b"), ())
    cache.put(Seq("c"), ())
    cache.put(Seq("d"), ())

    cache.cleanUp()
    cache.estimatedSize() shouldBe 4

    currentTime += 5.millis

    cache.invalidate(Seq("a"))
    cache.put(Seq("a"), ())

    currentTime += 6.millis

    cache.cleanUp()
    cache.estimatedSize() shouldBe 1  // Success
  }
```

**Comment by ben-manes** [comment]
Offhand not sure, but I would disable all other threads since that ticker is not threadsafe. That can be done by configuring a direct executor. I agree otherwise the final cleanUp should have discarded the expired entries promptly.

**Comment by ben-manes** [comment]
A quick debug and this is because of an optimization to handle a high write rate to popular entries. To avoid throttling writers to allow the write buffer to catch up, a tolerance duration is used to degrade to mimic a read. This causes the write order queue to be out of order but for short durations that were considered tolerable. If you increase the time unit from millis to seconds then your test passes.

https://github.com/ben-manes/caffeine/blob/40f2d1b2894df96e866b3d3719bb5420ba241bcc/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L208-L209

https://github.com/ben-manes/caffeine/blob/40f2d1b2894df96e866b3d3719bb5420ba241bcc/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L2054-L2060

https://github.com/ben-manes/caffeine/blob/40f2d1b2894df96e866b3d3719bb5420ba241bcc/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L2076-L2086

**Comment by haron4igg** [comment]
Thank you for explanations :D
This optimisation makes sense, so lets close this issue then.

**Comment by haron4igg** [comment]
But also, it could make cense to ensure that EXPIRE_WRITE_TOLERANCE is less then expiration timeout.

**Comment by ben-manes** [comment]
That might mask it slightly in a unit test, but have little practical value in an application.

Instead it would be interesting to see if we can replace this with an alternative scheme that is not tied to an arbitrary time threshold. The goal in https://github.com/ben-manes/caffeine/commit/2c5c1d96106cebb8d036043ffdd897f053fd32bb appears to have been to avoid spamming the write buffer (unbounded then, bounded now) to improve performance in a user's benchmark when migrating from Guava.

If we used the LSB of the timestamp as an in-flight flag, then we could detect if a prior write was still in the process of being replayed. If so, then the entry is already in the write buffer and we can skip appending for a smaller degradation from strict ordering. Since we drain the write buffer aggressively it should only be pending for a small time window, less than the current threshold. That should resolve your test case, but we'll have to benchmark to see if write performance degrades before making.

**Comment by ben-manes** [comment]
> But also, it could make cense to ensure that EXPIRE_WRITE_TOLERANCE is less then expiration timeout.

Reviewing this again (due to #478), and that idea won't work robustly. When we use variable expiration the entries are placed in timer wheel buckets, where the smallest interval is ~1s. The entire bucket has to expire before it is evicted, so even without this tolerance optimization your test case would fail if `expireAfter(Expiry)` was used instead. The `cleanUp` wouldn't discard the bucket so `estimatedSize` would stay higher than expected. This also negates my other idea of using some logical bit, since the tolerance time doesn't matter in all cases.

Since the JavaDoc of `estimatedSize` is clear that there are various reasons for that to exceed the expected count, I'm going to close this as nothing further to review. The actual count can be obtained by traversing the entries, assuming you don't hit #472 (fixed but not yet released).

Thanks for the thought provoking scenarios!
