### ISSUE TITLE
Proactively refresh after write  

### ISSUE THREAD

**Issue by shannonbay** [ben-manes/caffeine#437]
I would like my cached object to be updated periodically, as per refreshAfterWrite - except that I would like the refresh to be triggered immediately.  That way, all queries can return immediately with either the current (during refresh) or updated value.

Essentially, I would like a variant of refreshAfterWrite without "refresh only initiated when the entry is queried."

**Comment by ben-manes** [comment]
Can you use a ScheduledExecutorService and the asMap view to iterate and reload the entries? That seems to be all that would be needed, if I understand correctly.

**Comment by shannonbay** [comment]
Yes.  Actually that's what I've been doing - I thought you must already have a schedule internally that could be re-used.  Just a thought anyway, thanks.

**Comment by ben-manes** [comment]
I'm not really sure how, why, or what the benefit would be for us to do something different.

For expiration we maintain data structures to (linked list, timer wheel) to maintain a sorted order and evict the stale entries. The scheduler can peek at when the next expiration might occur and have a thread perform a `cleanUp` at that time. This might discard one or more expired entries, with the main benefit of calling a listener more promptly.

For refresh we don't yet offer a bulk reload option, so there is no optimization if we could reload multiple. The only benefit is instead of scheduling every entry individually is if we maintained this sorted order, which could reuse the `expireAfterWrite` one if enabled. Then we could schedule one task for the next event to submit the refresh, and schedule for another. That does drop the number of scheduled tasks by a lot compared to the naive version, since a cache might be quite large.

However, I think you could do this yourself using `Policy.refreshAfterWrite`. That offers some metadata lookup, like the age and order, just in case it was useful. The ordered view is efficient if `expireAfterWrite` is enabled by walking that list, but otherwise sorts the cache using a parallel stream. If you peak at the next refresh time then you can schedule one task against that, rather than each individually or as a periodic task.

My fear of this feature is it promotes never evicting items from the cache, as the entries are constantly reloaded before they become eligible for removal. Some users may mitigate this using a size bound, but the requests in StackOverflow always showed code unbounded. If it can be done in user code, then being very explicit and knowledgable indicates to the next developer the intent. A simple builder setting could be easily misused and cause surprises, so I'm afraid we'd do more harm than good.
