### ISSUE TITLE
best pattern for freezing Cache keys on miss?

### ISSUE THREAD

**Issue by dhalperi** [ben-manes/caffeine#439]
I'm wondering if I'm doing something wrong here:

I have a possibly-mutable cache key `K`, a function to freeze it `K -> FrozenK`, and a function to compute value: `K -> V`.

Things like `LoadingCache<K,V>` or [`Cache#get`](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/com/github/benmanes/caffeine/cache/Cache.html) do not let me freeze `K` on miss - it just computes `V` from `K`, and presumably retains a reference to `K` and `V`.

The way I can do this is something like:

```java
@Nullable v = CACHE.getIfPresent(k);
if (v != null) {
  return v;
}
FrozenK frozenK = freeze(k);
v = computeValue(frozenK);
CACHE.put(frozenK, v);
return v;
```

Is there a better way to do something like this? In practice, `K` is something like `Set` and `FrozenK` is something like `ImmutableSet`, so I assumed this would come up other places. Maybe we're just doing something strange in our codebase.

(h/t to the guava team for pointing me to Caffeine after I [asked this Q](https://github.com/google/guava/issues/3972) for Guava's Cache - this library looks awesome!)

**Comment by ben-manes** [comment]
The best practice would be to freeze prior to the cache call, as usually copying a `Set` is fast. The key hashes to a lock and replacing it with an unequal copy would violate Map semantics. This is the same as if you were using any of the Map.compute methods. A mutable map key is broken in general because the hashCode/equals must not change, else it corrupts the hash table and causes a memory leak.

Your code looks fine, except that you could use `frozenK` in a computation to avoid races causing redundant writers. Since the key is already frozen it should be safe. Ideally you wouldn't need the lookup and freeze the key immediately, since usually a Set copy is fast. But as an optimization that looks fine and we similarly to a getIfPresent-then-compute to avoid `ConcurrentHashMap` locks.

So this is fine, but I might change it to,
```java
@Nullable v = CACHE.getIfPresent(k);
if (v != null) {
  return v;
}
FrozenK frozenK = freeze(k);
return CACHE.get(frozenK, this::computeValue);
```

**Comment by dhalperi** [comment]
:+1:

Yeah, the safety concerns about mutability are precisely what brought me here; in our case the object is mutable but not used in multiple threads, so freeze-during-miss would be safe - we can guarantee that freezing it won't change the hash code.

Regardless, thanks for the tips!
