### ISSUE TITLE
LeanStore cache policy / tracking infrequent pages

### ISSUE THREAD

**Issue by JohannesLichtenberger** [ben-manes/caffeine#442]
Hi Ben, have you seen the LeanStore paper[1] from Viktor Leis? The replacement strategy is really interesting :-)

[1] https://db.in.tum.de/~leis/papers/leanstore.pdf

**Comment by ben-manes** [comment]
Thanks! I watched the CMU [in-memory database](https://15721.courses.cs.cmu.edu/spring2020/schedule.html) videos a few weeks back. At the time I felt a little uncomfortable at the assumption that all data had to fit in memory, though I had already come around to transactional persistence being optional if using network txns instead (as network is often faster than disk I/O). It's all an interesting area!

The paper mentions Linux's paging algorithm being poor for databases due to its swappiness. I just implemented that algorithm over the weekend and evaluated the hit rates! See the latest commit and link to the data. The amount of space oriented towards recency vs frequency depends on the machine's specs, which dramatically impacts the resulting hit rate. It ranges from 50% - 99%, reducing the recency area as more memory is added. In the DS1 & F1 traces this has a 10pt difference and 15-20pt in F2. Certainly some room for improvements in the base algorithms.

> "The main mechanism of our replacement strategy is to speculatively unswizzle a page reference, but without immediately
evicting the corresponding page. If the system accidentally unswizzled a frequently-accessed page, this page will be quickly swizzled again—without incurring any disk I/O."

This sounds very similar to FreeBSD's [page-used bit](https://www.freebsd.org/doc/en_US.ISO8859-1/articles/vm-design/freeing-pages.html), where it hides the page being available and the page fault promotes an infrequent page, else performs the actual I/O. Reading the referenced [2014 paper](http://www.vldb.org/pvldb/vol8/p37-graefe.pdf) on pointer swizzling for the buffer manager, and I think they rediscovered BSD's technique (much older). Both assume memory-first storage and offload to disk as needed, so the difference is VM versus DB use-case and that BSD can leverage native hardware support.

**Comment by JohannesLichtenberger** [comment]
Regarding pointer swizzling, I guess in Java we can not really swizzle pointers. What I'm currently doing is storing both, a long-value and the actual reconstructed in-memory page in the page references. Caffeine caches are then for instance also used to set the in-memory reference to null, when the page is going to be evicted.

I wonder if the assumptions of mostly in-memory database systems are really true, having tons of main memory for a reasonable price. That said, I guess I'm also writing software in my spare time with SirixDB[1], which will behave best with byte addressable NVM, for instance Intel Optane Memory due to huge persistent, and durable trees of tries, which are sequentially written to durable storage (and for data pages only records, which fit into a predefined sliding window), thus basically page fragments. Thus, fast, fine granular concurrent random reads of a predefined (low) number of page-fragments at max are needed to recreate a page in-memory.

Currently, however, I guess a much more pressing issue (than the best cache efficiency) is, that I maybe should implement some form of a simple group commit (even though single writer per resource), such that a snapshot with structural sharing is not immediately written to durable storage, which is very inefficient and to amortize the cost of rewriting ancestor paths while still being able to track who committed what at which time.

[1] https://sirix.io and https://github.com/sirixdb/sirix

**Comment by JohannesLichtenberger** [comment]
But their cache policy is at least interesting ;-)

**Comment by ben-manes** [comment]
yes, it's a neat trick if you can do it.

I like the idea of modern databases using distributed commits, and thereby replication, as a means to avoid I/O on a commit. At that point the commit doesn't have to take an fsync penalty for durability, if the probability of a distributed outage is infeasible. Then one can treat the database as memory-first and persistence as cold storage, asynchronously written out, which negates much of the complexity costs. It still needs to figure out what to page out, but it becomes more like a virtual memory than a traditional database. I presume that is one of the insights behind Aurora being able to decouple compute and storage.

that's the extent of my understanding so the rest is of your thread is a little too specific and outside of my limited knowledge 😁

**Comment by JohannesLichtenberger** [comment]
Hm, in my case the changes are buffered / the transaction log is in-memory, in a LinkedHashMap as it's a private buffer of the read-write transaction. I think, instead of writing it during a commit to durable storage immediately, I'd rather write the serialized pages to a synchronized commit queue, which informs the transaction asynchronously of when the data is fsynced. I think it's even useful with a single-writer per resource (a resource is currently a binary JSON or XML representation) for small sized transactions. I could introduce an upper bound for instance, such that the queue is also fsynced within a given timespan, if the resource doesn't get any modifications, such that the transaction can return to the user, that the data could not be lost afterwards. Sirix has no WAL. Basically the storage is the log and a UberPage (root page to the storage) is swapped atomically after each snapshot.

I have to read a bit more about your mentioned approach and Aurora, however :+1: 

But I assume that's a bit offtopic here, just have noone to discuss some stuff :-D

**Comment by JohannesLichtenberger** [comment]
However, I guess for a group commit of probably small sized read-write transactions (only one can exist at-a-time), I'd have to release the lock, after preCommitting to the queue, such that a new writer can start and also share the transaction private buffer with the new read-write transaction.

**Comment by ben-manes** [comment]
sorry, I haven't written my own db yet so this level of details on commit side is outside of my experience level :)
