### ISSUE TITLE
is there any mechanism to release resource after expired?

### ISSUE THREAD

**Issue by bthulu** [ben-manes/caffeine#450]
I need to connect to many databases dynamically, and keep connect only for a few minutes.
A DataSource such as hikaricp can only connect to one database, and won't release connect before hikaricp close.
So i want to use caffeine to cache connections for a few minutes, and close it when expired.
But i don't know if caffeine can do this?

**Comment by ben-manes** [comment]
By default expiration is lazily removed during routine maintenance, which is triggered by reads/write operations on the cache. This is done by buffering events and replaying under a tryLock, rather than a traditional cache which locks on every read and is severely penalized by lock contention. This means that removal will be delayed until there is activity, so if the cache is idle then it won't evict (like any other passive data structure).

If you want more prompt removal regardless of activity then a scheduling thread is required. While we don't create our own threads, you can supply one using the `Scheduler` interface. This will schedule a the routine maintenance based on the next expiration event, paced to at most once per second. You can use `Scheduler.systemScheduler()` if on JDK9+ to use the JVM's scheduling thread.

You can either close the resource using a `RemovalListener` or `CacheWriter`. These are async/sync listeners, depending on whether the removal should be performed within the ConcurrentHashMap's `compute` operation. For your case it sounds like an async `RemovalListener` is fine.

You do need to be careful because a long running query could cause a connection to be in use, but no cache activity would allow the DataSource to be discarded. One way to work around this is to pin the entry while in use by disabling the eviction policy, as described in the [FAQ](https://github.com/ben-manes/caffeine/wiki/Faq#pinning-entries). All this means is that it may be a bit more complicated if you want to be careful about handling all concurrent edge cases.

**Comment by bthulu** [comment]
thanks very much , it helped me a lot, i love you
