### ISSUE TITLE
Avoiding SystemScheduler reflection with MRJAR

### ISSUE THREAD

**Issue by A248** [ben-manes/caffeine#453]
I noticed the SystemScheduler uses reflection to call `CompletableFuture.delayedExecutor` on Java 9+. However, reflection is notably slower than a direct call. Would you be open to using the [multi-release feature](https://openjdk.java.net/jeps/238) to implement this instead?

Also, the CLA on the wiki and CONTRIBUTING.md appears to be down. Do I need to sign it if I want to PR?

**Comment by ben-manes** [comment]
The overhead is small since we cache the `Method` and we pace the invocations at a maximum of once per second. At that point, I don't think it is worth the complexity of an MRJ which isn't well supported by tooling unfortunately.

The `FactoryBenchmark` jmh benchmark shows the throughput of the alternatives.
```
Benchmark                                   Mode  Cnt          Score          Error  Units
FactoryBenchmark.direct                    thrpt   10  189499490.979 ±  8023047.719  ops/s
FactoryBenchmark.methodHandle_invoke       thrpt   10  126743039.533 ±  5132410.239  ops/s
FactoryBenchmark.methodHandle_invokeExact  thrpt   10  125193723.944 ± 10177345.328  ops/s
FactoryBenchmark.reflection                thrpt   10   55219351.321 ±  5037057.803  ops/s
```

So while 4x slower, it is still fast and shouldn't be a problem. Unfortunately there is a memory leak in Java 8 when using MHs, so that isn't an option.

The CLA wasn't required, just a best effort to be proactive. I guess it was [quietly deleted](https://github.com/clahub/clahub/issues/174) and all signatures lost, which is unfortunate...

**Comment by A248** [comment]
Ahh, I understand. Thank you for the explanation.

Before I close this, do you have more information about the MethodHandle-related memory leak? I found [this one](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8162795) which was patched in 8u121.

**Comment by ben-manes** [comment]
I believe that is the one, see #222 for our revert to reflection.

[Pacer](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Pacer.java) is how we govern to once per second, fyi. The variable expiration uses a [TimerWheel](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/TimerWheel.java) with a minimum bucket size of ~1s, so that becomes our lower bound. The bucketing lets us use a hash for a coarse sorting, so the bucket has to expire before the entries are evaluated for removal. Since we don't want to thrash by tiny rescheduling anyway, that ends up having a nice effect where we do not abuse the scheduler.

**Comment by A248** [comment]
Okay, thank you! I'll take a look at that.
