### ISSUE TITLE
Using FakeTicker.advance does not trigger cache reload?

### ISSUE THREAD

**Issue by rvplauborg** [ben-manes/caffeine#455]
Looking at https://github.com/ben-manes/caffeine/wiki/Testing, I am attempting to not have to expose my cache property from my UUT. Instead, I am passing the cache into the UUT, and in my test setting `.ticker(fakeTicker::read)`. The cache is set to `.refreshAfterWrite(Duration.ofMinutes(5))`, but calling `fakeTicker.advance(Duration.ofMinutes(5))` does not trigger `reload` being called like explicitly calling `cache.refresh(..)` does. Any ideas?

**Comment by ben-manes** [comment]
`refreshAfterWrite` is not a proactive refresh, it is in response to activity on that entry. This is most often desired when combining with expiration so that active entries are reloaded (to hide latency) and inactive ones are discarded. If you want to reload all entries periodically, then a `ScheduledExecutorService` is a very simple approach.

If you increment the time and then read the entry again, you should see `reload` being called if not otherwise needing eviction.

does that help clarify the test's behavior?

**Comment by rvplauborg** [comment]
The thing is, after advancing the fake ticker, I do call cache.get(someKey), from my test to trigger the reload, but `reload` is still not called.

**Comment by ben-manes** [comment]
I'm not sure if this helps, but our test class is [RefreshAfterWriteTest](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/test/java/com/github/benmanes/caffeine/cache/RefreshAfterWriteTest.java).

**Comment by ben-manes** [comment]
I generally disable all async behavior for unit tests, via `Caffeine.executor(Runnable::run)`. Perhaps your tests are hitting a race condition during the reload?

**Comment by rvplauborg** [comment]
Thanks for the tip! Turns out it indeed was a race condition issue. Setting the executor to i.e. `Runnable::run` did the trick. Maybe we should consider adding a line about this in the Testing wiki page?

**Comment by rvplauborg** [comment]
Wait.. Actually it seems that that did not fix it, it was another change that did..

**Comment by ben-manes** [comment]
that tip is in the wiki (2nd paragraph).

okay, sounds promising tho. please close if you can nail it down :)

**Comment by rvplauborg** [comment]
What worked for me was to advance the ticker with 6 minutes (cache expiry is set to 5), and call `cache.get` to trigger a refresh. The next get would then return the new value from the cache.
