### ISSUE TITLE
How are classes like FD FDA generated?

### ISSUE THREAD

**Issue by asasas234** [ben-manes/caffeine#459]
@ben-manes I was looking at the caffeine source code and noticed that a lot of classes like FD and FDA have the words GENERATED CODE written on their class comments, I'm rather curious as to how they were generated and why they did it.

**Comment by ben-manes** [comment]
The reason for the generated code is reduce memory overhead. Since the cache has many features each entry has to hold metadata such as the expiration timestamp, the entry's weight, policy link list pointers, etc. An unused feature would add bloat, so ideally we would use have specialized classes with only the fields required for the builder's configuration. Since that's too many to do by hand, it is done by code generation. The cost of lower runtime memory overhead is added jar bloat as the other classes are not loaded, wasting a bit of disk space.

The [code generator](https://github.com/ben-manes/caffeine/tree/master/caffeine/src/javaPoet/java/com/github/benmanes/caffeine/cache) leverages [JavaPoet](https://github.com/square/javapoet) to emit the source files. The actual code is a bit messy, but I settled on styling it as rules to evaluate against. The approach is to construct the cartesian product of all features (combinations) and run each through the rules to build the source file. At runtime when the cache is first built, its configuration is evaluated to build a string which is the class name and it is loaded reflectively. This is done for the cache instance and an entry factory (which is the entry class due to implementing the factory interface). For these generated classes we also strip out the class debug information and use short names to try and not incur too much bytecode bloat.

**Comment by asasas234** [comment]
@ben-manes thanks
