### ISSUE TITLE
Some JMH benchmarks give false impression of performance as they group different operation states into single measure

### ISSUE THREAD

**Issue by nitsanw** [ben-manes/caffeine#46]
For example, when measuring queue throughput it is not enough to benchmark the poll method as follows:

    @Benchmark
    Object poll() {
      q.poll();
    }

This benchmark groups the failure case with the success case. It would make a queue with very low throughput look great as long as it failed to deliver values quickly. The throughput of the queue is the number of successful polls. There are several ways to achieve this measurement either by using the Control object and spinning until a value is available or by using AuxilaryCounter objects and counting the success and fail metrics separately. I personally prefer the latter as the different cases can be quite telling.
This same issue is visible in the ReadBufferBenchmark. I assume the number of drain() calls is immaterial if they deliver nothing. In this case one must use an AuxilaryCounter to reflect the number of elements drained.

**Comment by ben-manes** [comment]
You're right, as usual. :)

I was mostly focusing on `offer` when I originally wrote the benchmarks. The case for the cache is lots of user threads writing and an async task draining to replay the events. So the draining part is only there for avoiding OOME in the queue, and to keep filling the buffer. The read buffers can be lossy, so its mostly about minimizing the cost when contended (which `StripedBuffer` helps alleviate). I wouldn't be surprised if my collection wiki pages have skewed numbers, as when generalizing I could have forgotten my original intents with the benchmarks.

I am planning on gradually dropping the collections, since your jctools covers that more thoroughly and this project has matured to have more focus. The stack is marked `@Beta` so its not bound by semver rules and not used by the cache, so it will go in the next minor release. The queue is public, so that has to wait for a major release. The reason why I'd like to hide it is that I don't know how migrating to VarHandles will affect things, e.g. such as the inability to use the `threadLocalRandomProbe` trick.

I would like to learn how to write better and more correct benchmarks. Do you have any good examples that I can borrow from and experiment with?

**Comment by nitsanw** [comment]
JCTools queues benchmarks are (I think) good. The 'state' of your benchmark can have significant impact on the results (i.e. is the benchmark measuring behaviour at full/empty/other). There's some interesting issues around concurrent code warmup/profile. It's hard to get right and I'm not 100% sure I did...

**Comment by ben-manes** [comment]
Thanks for the tip on `@AuxCounters`! I started playing with them and its really nice to see the data broken down.

**Comment by ben-manes** [comment]
I removed the stack, scheduled the queue for removal in v3, added `@ AuxCounters` to some benchmarks, and removed the collection wiki pages.

When the `SingleConsumerQueue` is embedded I'll revisit what to do with it. Its usage as a write buffer never shows up in profiling, so the extra complexity of the arena isn't useful. The best options then is either to track JCTools' `MpscLinkedQueue` or use a [growable mpsc array queue](http://www.adm.hb.se/~AGD/Presentations/CacheAwareQueue_OPODIS.pdf). If the queue is not a hotspot, then being GC hygienic seems like the right design preference. An [implemented](https://github.com/eclipse/jetty.project/blob/master/jetty-util/src/main/java/org/eclipse/jetty/util/ConcurrentArrayQueue.java) is available in Jetty so that should be easy to experiment with.

Since the flawed benchmarks and associated classes were removed, I'll close this issue. Thanks for teaching me another neat JMH trick! =)

**Comment by nitsanw** [comment]
JCTools now has a growable MPSC (in experimental, but will move to core shortly), was not familiar with the paper you point to, will have a look.

**Comment by ben-manes** [comment]
Oh perfect. Those are the slides, here is the [paper](http://citeseerx.ist.psu.edu/viewdoc/download;jsessionid=1DDF2867D1B7ECFE894700B9178E11E6?doi=10.1.1.309.6202&rep=rep1&type=pdf). You might have read it because I mentioned them in [jctools #59](https://github.com/JCTools/JCTools/issues/59#issuecomment-95062239), but hadn't known of the Jetty implementation then.
