### ISSUE TITLE
Should errorprone and checker be optional dependencies?

### ISSUE THREAD

**Issue by agentgt** [ben-manes/caffeine#474]
It appears Caffeine does not have  a runtime dependency on Checker or Error Prone but they are included as dependencies.

That is doing something like this in maven (sorry I can't remember the gradle analog):

```
      <dependency>
        <groupId>com.github.ben-manes.caffeine</groupId>
        <artifactId>caffeine</artifactId>
        <version>xyz</version>
        <exclusions>
          <exclusion>
            <groupId>org.checkerframework</groupId>
            <artifactId>checker-qual</artifactId>
          </exclusion>
          <exclusion>
            <groupId>com.google.errorprone</groupId>
            <artifactId>error_prone_annotations</artifactId>
          </exclusion>
        </exclusions>
      </dependency>
```

Works completely fine.

I looked around and I didn't see a single use of checker being used at runtime.

Ideally the published pom of caffeine would have those  dependencies marked as `<optional>true</optional>` (I think).

However maybe there are plans to use checker's runtime stuff in the future (as much as I like the looks checker I would hope not)?

Thoughts?

**Comment by ben-manes** [comment]
Back when we used JSR-305 annotations they were marked as optional/provided. This has problems for some alternative JVM languages which require annotations at runtime and would fail to class load. But it was a well-known problem so that package was often brought in manually, but not well known enough to cover other artifacts. There is a long thread on Guava's issue tracker about them switching to compile scope on that dependency, which we didn't do since it was being phased out due to JPMS.

The simplest approach has been to follow Guava's lead since there is more active community feedback there. They decided to use these two annotation packages as jsr305 replacements, at compile scope, so we mirror that. There is an [effort](https://github.com/google/guava/issues/2960#issuecomment-573876214) standardize these annotations at [jspecify](https://github.com/jspecify/jspecify). If that is successful then Guava will migrate, so we should too.

I think using exclusions is the simplest strategy and, if that is bothersome, advocating for change in Guava first. I don't have a strong opinion on the matter, except for a desire to not constantly change due to quirks one way or the other.
