### ISSUE TITLE
Would caffeine benefit from a faster hashmap/hashset? 

### ISSUE THREAD

**Issue by LifeIsStrange** [ben-manes/caffeine#476]
Disclaimer:
I am not at all an expert in cache systems but as caffeine performance is foundational to a lot of software, I was wondering whether the data structures it uses are optimal?
There is a recent, new generation of hashmaps/sets that is significantly faster than the existing ones 
https://github.com/rust-lang/hashbrown
The same can be said about hashing algorithms.
Finally, could caffeine benefits from SIMD and TSX ?

Thanks for this great software @ben-manes

**Comment by ben-manes** [comment]
Caffeine is backed by `ConcurrentHashMap`, which is even more foundational! If improvements were made there, then it would benefit everyone including us.

`ConcurrentHashMap` is actually one of the jewels of Java and I am unaware of anything equivalently in quality in any other language. Rust lacks a similarly high-quality concurrent hash table, with DashMap's experimental branch being the leading candidate.

The JVM has limitations which favor its current approaches. First it is not yet able to exploit SIMD or TSX in user code, though the SIMD is actively being worked on and I could image TSX being used internally by lock primitives. Second is the lack of value types which results in a sparse graph of objects rather than a flat array of data. That too is in the works. When these two land then maybe there will be improvements to the core data structures. Of course there are other challenges, like concurrency, which can favor alternative algorithms than Rust's.

You would need to ask on the [core-libs-dev](https://mail.openjdk.java.net/mailman/listinfo/core-libs-dev) what their thoughts are, and we'll gain their improvements transparently with JDK upgrades.
