### ISSUE TITLE
Cost weighted efficient caching

### ISSUE THREAD

**Issue by xbotuk** [ben-manes/caffeine#480]
Can you enable caching based on cost weights?

The purpose of cache is to save on costs, that would have occurred had the cache not existed. Normally cache libraries assume constant cost for cache misses. But in real world costs of cache misses are not constant. Having a cache that maximizes on cost saving would be ideal. Cost saving should be a weighted function of cache hit frequency and and cost for each miss

**Comment by ben-manes** [comment]
@xbotuk see the reply in https://github.com/ben-manes/caffeine/issues/345#issuecomment-530571533

This is an open research topic and that comment discusses some of the recent work in this area. If I recall correctly, I believe that @gilga1983, @himelbrand, and @ofanan have been working on this topic but I am not familiar with their progress and may be mistaken. The core algorithms have to be determined and evaluated for effectiveness before we can determine if the engineering work is worth the effort.

There is also a lack of good data to evaluate against, e.g. traces that include response times from different data sources intermixed. The lack of data means that any algorithm is merely a best guess, which isn't very comforting from an engineering perspective. To be integrated into this caching library, we would want to have data that helps us determine that the added complexity is a win, is robust across a variety of workloads (identify and resolve edge cases), and has an acceptable time/memory cost for maintaining the policy metadata (ideally O(1)).

Your suggestion of `hit frequency / miss penalty` may or may not be ideal. We just don't know without data. Would you be able to provide access traces that included miss penalties for researchers to investigate with?

**Comment by xbotuk** [comment]
The user code can calculate a cost factor and then provide this number when adding the item.

Cache library can then calculate:

    total cost saving = Sum of (each items's cache hit * cost factor)

Then the cache should optimise by maximizing the total cost saving, by deciding what items to keep and which ones to remove.

**Comment by ben-manes** [comment]
A cache could do that, but without data there is no way to argue that this is better than an alternative approach. It wouldn't be reasonable for us to blindly add APIs and logic without being able to show when and why it is better. When that has been determined, then deciding on how to optimize the memory / time overhead for this algorithm has to be explored.

You are welcome to write your own cache or fork this one to implement your ideas. For it to be in this project we have to prove out ideas using data to guide our decisions and ensure it covers needs for many of our users.

**Comment by xbotuk** [comment]
I don't see why you won't get users of a cache capability that optimises based on cost-weights. The cost can be as simple as time to derive the item before caching.

**Comment by ben-manes** [comment]
I would happily provide features once the algorithms and benefits have been proven. In this case we only have hunches and no analysis, which is not enough to go on.

We have a simulator with dozens of eviction policies implemented. It turns out most are not that great, some good in a few cases but not attractive in most. Each is based on a reasonably good idea and we can build better algorithms by learning where the flaws are. That led to our current policy which is excellent in frequency / recency workload goals.

Your suggestion may be good or it might suffer in some workloads. We don’t know yet. That is why data and analysis is required before we do the engineering work. I don’t think this is an unreasonable expectation.

**Comment by xbotuk** [comment]
I completely agree with you. At the moment I am busy with some other priorities, however I can look into this a bit later. At the moment I do not have inside knowledge of the caffeine library, it may speed up if you can please point me to the classes where the eviction policies are instantiated and implemented. Thanks

**Comment by ben-manes** [comment]
That would be great. At this phase you can add onto our simulator so that we can analyze our theories against different workloads and compare them. That way you are not dealing with the complexity of the user-facing library, e.g. concurrency.

1. Trace files are critical for an evaluation. A trace reader will parser a text/binary format and produce an [AccessEvent](https://github.com/ben-manes/caffeine/blob/master/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/AccessEvent.java) stream where each event holds metadata like the key, hit/miss penalty, etc. For example, the [AddressPenaltiesTraceReader](https://github.com/ben-manes/caffeine/blob/master/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/parser/address/penalties/AddressPenaltiesTraceReader.java) enriched a simple trace with synthetic penalties. We would like to have many real world traces to evaluate against. The [wiki page](https://github.com/ben-manes/caffeine/wiki/Simulator) lists the currently supported traces and file locations.
2. The [Policy](https://github.com/ben-manes/caffeine/blob/master/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/Policy.java) interface defines the eviction algorithm and records the statistics. Most page replacement algorithms only focus on object or byte hit ratios, e.g. by the frequency and recency. This primarily needs to implement the `record(AccessEvent)` method.
3. New policies are added to the [Registry](https://github.com/ben-manes/caffeine/blob/master/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/Registry.java) and the configuration file, [reference.conf](https://github.com/ben-manes/caffeine/blob/master/simulator/src/main/resources/reference.conf).
4. The [Simulator](https://github.com/ben-manes/caffeine/blob/master/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/Simulator.java) can be run in your IDE or at command like, `./gradlew simulator:run`. An initial command-line build is required due to code generation, `./gradlew build -x test`.
5. A table or csv report is generated and printed to the console. This auto-prunes empty columns and is based on the results accumulated by the [PolicyStats](https://github.com/ben-manes/caffeine/blob/master/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/PolicyStats.java). This class holds common metrics, but custom ones can be added by extending the class and registering an additional metric.

Feel free to ping us if you have any troubles, discuss ideas, etc.

**Comment by ben-manes** [comment]
I'm going to close this for now, since this is research work and nothing actionable yet. Let's continue the discussion if we can obtain traces and have insights towards an algorithm.
