### ISSUE TITLE
BoundedLocalCache#remove doesn't notify removeListener if the key doesn't exist in memory

### ISSUE THREAD

**Issue by suchintan** [ben-manes/caffeine#485]
I found this behaviour a bit odd, I wasn't sure if it was by design or not
```
  @Override
  public @Nullable V remove(Object key) {
    @SuppressWarnings("unchecked")
    K castKey = (K) key;
    @SuppressWarnings({"unchecked", "rawtypes"})
    Node<K, V>[] node = new Node[1];
    @SuppressWarnings("unchecked")
    V[] oldValue = (V[]) new Object[1];
    RemovalCause[] cause = new RemovalCause[1];

    data.computeIfPresent(nodeFactory.newLookupKey(key), (k, n) -> {
      synchronized (n) {
        oldValue[0] = n.getValue();
        if (oldValue[0] == null) {
          cause[0] = RemovalCause.COLLECTED;
        } else if (hasExpired(n, expirationTicker().read())) {
          cause[0] = RemovalCause.EXPIRED;
        } else {
          cause[0] = RemovalCause.EXPLICIT;
        }
        writer.delete(castKey, oldValue[0], cause[0]);
        n.retire();
      }
      node[0] = n;
      return null;
    });

    if (cause[0] != null) {
      afterWrite(new RemovalTask(node[0]));
      if (hasRemovalListener()) {
        notifyRemoval(castKey, oldValue[0], cause[0]);
      }
    }
    return (cause[0] == RemovalCause.EXPLICIT) ? oldValue[0] : null;
  }
```

In the method above, `notifyRemoval` only gets called if `cause[0] != null`.
`cause[0]` is only ever not-null if `data.computeIfPresent(` evaluates, and if the key isn't in memory, there's no way the `notifyRemoval` would be called.

This is an issue if Caffeine is backed with a distributed cache as often the backing cache (like Redis) could have the key being invalidated, but the local memory cache doesn't. 

We implemented a workaround by calling invalidate on our distributed cache manaully, which is fine, but I was just surprised that an event doesn't get propagated through (as expected).

**Comment by suchintan** [comment]
Perhaps the best approach for this would be a new `RemovalCause` saying "Hey, we didn't delete anything but maybe you want to propagate that to the thing that backs this cache"

**Comment by ben-manes** [comment]
Yes, this is a reason why I think `CacheWriter` is a idea because it doesn't notify then either. I had a TODO in the old [roadmap](https://github.com/ben-manes/caffeine/wiki/Roadmap#version-30) plan, `Propagate invalidations to CacheWriter delete when the entry is not present in the cache` because it seemed error prone. However there is no way to communicate `invalidateAll()`, as those absent keys are unknown. This type of behavior makes me question if `CacheWriter` was even a good idea or if it is a broken abstraction.

`RemovalListener` is meant only for clean up of removed entries, e.g. closing a socket. It is called outside of an entry lock, which is often preferred as clean up doesn't need tot block other writes. Sometimes that has to, though, when some consistency is needed to avoid race conditions writing to a file. This is where CacheWriter came in and, if we pull back from that idea, then a more focused `evictionListener` might be better.

When you want to propogate then the `Map` computations are a more powerful option that I think is clearer.

**Comment by suchintan** [comment]
Thanks for the context! I think your answer generally makes sense. Gonna close this ticket out.
