### ISSUE TITLE
eviction when not reach capacity

### ISSUE THREAD

**Issue by qiuyi116** [ben-manes/caffeine#488]
I had set initCapcity same as maximumSize as 1000, then I found  key eviction happen when estimatedSize is around 200. 

Is eviction not active key even though not reach capacity is by design? 

I'd like have it always keep key until reach capacity.

**Comment by ben-manes** [comment]
Can you provide a test case?

The cache will evict after it exceeds the maximum. However, it does not evict in LRU order. In your case the total cache size should be 1000 but a recent insertion may be evicted early due to the policy.

Of course if you have other eviction criteria, such as expiration, then the cache may discard prior to reaching a maximum size.

**Comment by qiuyi116** [comment]
Thank you. I just found the cache builder write by others has set `expireAfterWrite` by default.
