### ISSUE TITLE
Is Writer thread-safe?

### ISSUE THREAD

**Issue by srividrs** [ben-manes/caffeine#489]
I am planning to use the "Writer" feature to write data to Redis whenever a new entry is added/removed/modified in Caffeine Cache . **Does Caffeine ensure that all Get requests to the same key is blocked until the Writer method finishes execution?** My code looks something like below:
```
public class RedisCacheLoader<K,V> implements , CacheWriter<K, V>{
       @Autowired
	@Qualifier("redisTemplate")
	RedisTemplate<K, V> template;
       public void write(K key, V value) {
		// code to save in Redis
	}
}
```

**Comment by ben-manes** [comment]
The prior mapping can be read when the writer is executing. It is called within a Map.compute method.

Note that I am planning on deprecating the writer for removal in v3. It will be replaced by an eviction listener and recommending to use `asMap().compute` instead. This is more obvious code. There will be a 2.9 release to deprecate with a replacement before 3.0. Just an FYI and it will be easy to migrate. If you only use `write` then consider using a compute method instead.

**Comment by srividrs** [comment]
Thanks for the update! I have few more questions:
1. The newly planned eviction listener --> I assume this will be called only on evict? Will there be any listener for Add/Modify?
2. What about loader? - I m planning to use the loader to load values from Redis into Caffeine cache.  Hope the loader is not planned for deprecation?

**Comment by ben-manes** [comment]
__fyi, I am open to reconsidering this deprecation and removal.__ I haven't started on it yet, but it is the next task I was looking into. The reasons why it seemed like the wrong approach is,
1. Most usages only implement the `delete` method for performing the removal atomically within the map computation.
2. Users may (or may not) be surprised that removal of an absent entry does not notify the writer. That is less write-through because a 2nd layer cache might hold the entry to invalidate.
3. The behavior of (2) is because clearing the cache would require notifying on an unknown keyspace. This is also confusing, as the writer cannot communicate that externally.
4. The writer is not invoked on a cache load or compute, because those are already managed user actions. This avoids incorrect behavior, such as having the writer to communicate an add to the external system that the loader just fetched from.
5. The write method does not communicate if a create or update, and therefore what the old value was.
6. Ideally a functional interface would be used to allow for a less verbose configuration in simple cases.
7. The `CacheWriter` concept comes from other libraries which needed hooks into their distributed caching lifecycle. We try to extend Java's Collection Framework, so the `compute` methods tends to feel more natural and uniform.
8. The writer is not used very often, so the impact seems to be low. We're hoping that v3 incompatibilities do not affect most users (95%+).

In regards to your questions,
1. _The newly planned eviction listener - I assume this will be called only on evict? Will there be any listener for Add/Modify?_
    - The eviction listener would be called on eviction only, atomically within the ConcurrentHashMap computation. This differs from removal listener which is called after the compute.
    - There would be no add/update listeners. The compute methods provide more flexibility to handle create, update, replace, and remove cases. This could easily dispatch to a custom listener.
2. _What about loader?_
The loader is staying and won't be deprecated or removed.
3. _I suppose asMap().compute needs explicit invocation unlike the writer which can be configured while building the Cache? Currently i m using Spring Cache Abstraction with Caffeine_
    - Yes. In non-framework code this should be clearer due to the above rational. By wrapping the cache and this logic into a custom class, the application can share it if desired.
    - That is a an interesting scenario. Spring Cache is intentionally limited to keep it simple and they recommend using the native apis for complex cases. For example it might not work well with annotated methods because it does not invoke through your loader but instead perform a computation that invokes the method. The blog articles that I've seen, e.g. this [one](https://programmer.help/blogs/sprboot-spring-cache-implements-two-level-caching-redis-caffeine.html), instead write a custom Spring Cache implementation to ensure the multiple layers coordinate correctly. __Can you review this problem, as maybe your idea won't work out so simply?__

**Comment by srividrs** [comment]
My initial approach was quite similar to the one mentioned in the blog article ( with Spring custom cache implementation). But later I realized i could achieve the same with  caffeine Writer and loader instead with much simpler code! Now it seems like I d have to go back to the previous approach!

**Comment by ben-manes** [comment]
Would you be able to given `@Cachable` method interactions? I included a few more examples that I dug up. I couldn't find a case using the CacheWriter in the wild.

**Comment by srividrs** [comment]
Yes.. it worked with `@Cacheable` annotation (based on some minimal testing that I did). 
** In case of Caffeine Cache Miss** 
The Caffeine `loader` was able to load it from Redis. 
If not present in Redis, the actual method did get invoked. The result was cached in Caffeine and then the `CacheWriter` was able to persist it in Redis

**Comment by ben-manes** [comment]
Interesting. Is there any chance you could provide me a trimmed down sample version to see the interactions with? My understanding of the Spring Cache code is that the AOP interaction for a load would have been,

1. invoke api method
2. @Cachable AOP interceptor
3. cache.get(key, function)
4. execute user method
5. wrap for caching nulls
6. store in cache's map
7. AOP interceptor unwraps
8. return value to caller

I wouldn't think then the `CacheLoader` would be invoked because Spring uses `LoadFunction` instead ([get(key, callable](https://github.com/spring-projects/spring-framework/blob/cfae40afb456c98b2a11be600096da89b8aacafd/spring-context-support/src/main/java/org/springframework/cache/caffeine/CaffeineCache.java#L89-L91)).

It seems that they recently make [lookup(key)](https://github.com/spring-projects/spring-framework/blob/cfae40afb456c98b2a11be600096da89b8aacafd/spring-context-support/src/main/java/org/springframework/cache/caffeine/CaffeineCache.java#L95-L100) call via the loader, instead of just peek into the current mapping. Is that now called? If so, then how does the loader and `@Cachable` method interact, aren't they mutually exclusive?

I haven't used Spring since 1.x, so I'd have to dig into their AOP code again as my mental mapping seems a little outdated. I didn't expect your flow to work, but maybe this new `lookup` change somehow gets the right interactions. Offhand I'm a bit confused.

**Comment by srividrs** [comment]
Yes. Can you take a look at https://github.com/srividrs/spring-caffeine-redis? `RedisCacheLoader`  (which implements Loader and Writer!)and `CacheConfig` classes may be of interest.

**Comment by ben-manes** [comment]
Thank you. I’ll trace through it again get the weekend.

I guess it does a get-invoke-put so your scheme works thanks to their new lookup() implementation. If you use sync=true on the cache method annotation, does it still load from Redis? It might not and be the flow that calls into caffeine with their LoadFunction. The default is false which allows for a cache stampede.

**Comment by ben-manes** [comment]
Take a look at the [AOP invoker](https://github.com/spring-projects/spring-framework/blob/cfae40afb456c98b2a11be600096da89b8aacafd/spring-context/src/main/java/org/springframework/cache/interceptor/CacheAspectSupport.java#L374). If the method is marked as synchronous then it won’t work because it passes the loader function to be cache in handleSynchronizedGet. That function is called instead of the Redis cacheloader and writer, because there is no prior load or put back into the cache. So I think your idea isn’t compatible with that feature, which you likely will want to enable.

**Comment by srividrs** [comment]
Thanks for pointing this out! I missed this scenario. :(

**Comment by ben-manes** [comment]
I traced through your sample app with a debugger and unfortunately `sync=true` causes it to not utilize `RedisCacheLoader` whatsoever. This means that a cache stampede occurs when a miss occurs in both cache layers, causing multiple threads to invoke the cache method and store the results. At scale, that stampede can cause a high latency and excess load on the underlying resource. For example, Doordash [reported](https://doordash.engineering/2018/08/03/avoiding-cache-stampede-at-doordash/) an 87% latency reduction (1447ms => 176ms) when switching to that mode. I wish `sync=true` was the default as it is very rare to not want to do that (typically due to a weird recursive calls in the application causing lock ordering issues).

The new lookup() behavior of using LoadingCache is kind of neat by making your idea work otherwise. But I strongly feel like `sync=true` is how users should use a cache, which I suspect you'd agree with? If so, then the CacheWriter isn't helpful and it would be okay for removal in v3? What do you think?

**Comment by srividrs** [comment]
Yes. CacheWriter may not be helpful when used alongside Spring Caching Abstraction. But I still believe it would be nice if we could somehpw to extend Spring Cache functionality to support the `sync` behavior with CacheWriter

**Comment by ben-manes** [comment]
Closing as cache writer will be removed in 3.0
