### ISSUE TITLE
How long will caffeine support java 8?

### ISSUE THREAD

**Issue by patped** [ben-manes/caffeine#499]
I can see in the branch for v.3 that you're dropping support for java 8. Do you have a timeline for how long v.2 (java 8 support) will be maintained?

**Comment by ben-manes** [comment]
As long as needed. There will be improvements in v3 as minor compatibility breaks. I’m not sure if further v2 releases will be needed but it would be bug fixes rather than new features. I think it’s okay to restrict feature development to the current major version. Does that sound good?

I still casually maintain CLHM and Guava Cache. The former hasn’t needed a release, though, and I don’t have commit access to guava. I have sent them PRs but external fixes are near impossible to get in, as not their development model. I haven’t ever stopped maintaining an OSS  project, but they do naturally mature and become replaced such that no new activity it needed or asked for.

**Comment by ben-manes** [comment]
Here is an example of a PR that I sent to guava last December, since there is no one familiar with their cache implementation anymore so unlikely to be fixed otherwise. It’s still open, but at least available if they decide to fix the problem.

https://github.com/google/guava/pull/5348

**Comment by patped** [comment]
Btw, I forgot to say thanks for the quick reply! 💯
