### ISSUE TITLE
Expire after time and a succesful retrieval 

### ISSUE THREAD

**Issue by aschuhl** [ben-manes/caffeine#501]
So currently we are using caffeine to store an item for 2 minutes very successfully. 

Our implementation is basically:
 ```
  return cache.get(
        cacheKey, k -> retrieveSchema());
  }
```

We had an issue where the service retrieveSchema calls failed, so we no longer had the item. So I am wondering is there a way to set it so it won't expire until 2 minutes after creation and another retrieval occurs? We would rather use a more stale schema then no schema, so wondering if this is possible.

**Comment by ben-manes** [comment]
I'm not sure that I follow. 

Expiration is a hard cutoff for when an entry can no longer be used because its data may be too old (e.g. freshness, inactivity). The cache can then discard it to reclaim space.

Refresh might be more appropriate. This will return the existing value but, if it is older than the duration, a reload will occur asynchronously. That hides latency by not penalizing the caller with the load. When combined with expiration, the refresh keeps active content fresh and inactive content is discarded automatically. These rules are time-based.

Would refresh serve your needs?

**Comment by ben-manes** [comment]
Closing due to lack of clarification.

**Comment by aschuhl** [comment]
Sorry about that Ben, but refresh looks exactly what we need. Thank you!

**Comment by aschuhl** [comment]
@ben-manes Looking into this a little further, I noticed there is not a similar api as new Expiry() to create a custom expiration. We have our data in two different states, that we would like to refresh at a different times. This is possible with eviction, but doesn't seem possible with refresh unless I am missing something. Is my understanding correct?

**Comment by ben-manes** [comment]
Unfortunately that is supported yet. The feature is described in https://github.com/ben-manes/caffeine/issues/504 but no work has stain it.
