### ISSUE TITLE
Waiting until removalListeners have completed on invalidateAll

### ISSUE THREAD

**Issue by ginkel** [ben-manes/caffeine#510]
Hi there,

I have a couple of cache instances built using:

```
Caffeine
    .newBuilder()
    .maximumSize(500)
    .expireAfterAccess(5, TimeUnit.MINUTES)
    .removalListener(this::onCacheEntryRemoval)
    .build(key -> new Foo());
```

Upon application shutdown I'd like to to invalidate the cache using `invalidateAll` and perform some operations on the invalidated entries via the `removalListener`. ATM, the listener seems to be called asynchronously.

Is there a way to block until all maintenance tasks have completed?

Thanks,
Thilo

**Comment by ben-manes** [comment]
You can supply your own executor, either one you shutdown or a direct executor (Runnable::run).

Another approach is to use the asMap() view to iterate and call the method directly.

Do either of those work for you?

**Comment by ginkel** [comment]
> You can supply your own executor, either one you shutdown or a direct executor (Runnable::run).

That sounds like it would work. Thanks for the speedy reply!

Just to be on the safe side: Tasks like time-based expiration will then happen synchronously during cache access?

**Comment by ben-manes** [comment]
Yes, but the work caffeine does asynchronously is very cheap O(1) operations, so doing it directly is fine. We don’t know what the cost of user callbacks are so it’s safest to defer to the executor. The maintenance work is performed under a tryLock so it does not block other readers or writers, who can instead add their work to a buffer for replaying later against the eviction policy.

Expiration by default is cleaned up when activity on the cache triggers a maintenance cycle due to enough reads or a write. This means an inactive cache won’t discard those expired entries. If you expect them to be removed regardless of activity, a Scheduler can be configured. It doesn’t sound like it hat is needed, but I wanted to avoid confusion by explaining this behavior if not known.

**Comment by ginkel** [comment]
Perfect, thanks for the detailed explanation! :-)
