### ISSUE TITLE
JDK8 doesn't supported?

### ISSUE THREAD

**Issue by catap** [ben-manes/caffeine#514]
Hey,

I've tried to use the last release (3.0.0) with JDK8 and can't build it with error:
```
[ERROR]   bad class file: /Users/catap/.m2/repository/com/github/ben-manes/caffeine/caffeine/3.0.0/caffeine-3.0.0.jar(com/github/benmanes/caffeine/cache/Cache.class)
[ERROR]     class file has wrong version 55.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
```

Is JDK8 supported? I haven't find any clear statement about it.

**Comment by ben-manes** [comment]
Hi @catap,

Java 8 is supported by 2.x versions which will still be actively maintained. Java 11 is required for 3.x in order to use VarHandles instead of requiring Unsafe. This is briefly mentioned in the [release notes](https://github.com/ben-manes/caffeine/releases) for v3.

**Comment by catap** [comment]
@ben-manes sorry, I've missed that.

**Comment by ben-manes** [comment]
No problem! I added more emphasis in the release notes, as I can certainly understand the concern.

**Comment by ben-manes** [comment]
Correct. That was a large change to the feature which bordered on not being appropriate for a minor release. A major release would highlight that possibly incompatible changes were made which requires more diligence when upgrading.

See for example https://github.com/ben-manes/caffeine/issues/537#issuecomment-830780086 where a deadlock occurs because the user took advantage of the prior implementation not being linearizable, where returning the refresh future would block as part of a batching enhancement. This has to be changed to fit the new implementation. While it is unfortunate to see this bite someone, the major version bump gave a stronger warning of a potential break so it comes as less of a surprise.
