### ISSUE TITLE
Custom Validator

### ISSUE THREAD

**Issue by nitinsh99** [ben-manes/caffeine#531]
Hi. I am not sure if this is something that is already possible using existing caffiene apis but I have a use case of storing jwt tokens in cache. the TTL is non deterministic so I am looking for a way to have a custom jwt validator predicate. Upon each cache hit, the validator can validate if the token is valid or not and return or call build predicate accordingly.

Happy to provide more context.

**Comment by ben-manes** [comment]
There is expireAfter which calculates the duration on a read or write. However that is after the entry was obtained and to be returned. It could mark a flag on the object as invalid and set to expire, with the client retrying if the flag is set.

Otherwise maybe do it outside of the cache. It is a bounded map, so you might find the compute methods helpful if the validation check is expensive.

**Comment by nitinsh99** [comment]
Thanks.. I am right now doing it outside the cache but will explore expireAfter as you suggested..
