### ISSUE TITLE
cache keep growing

### ISSUE THREAD

**Issue by wtao-volvo** [ben-manes/caffeine#533]
I am using spring-boot-starter-cache:2.4.0 and com.github.ben-manes.caffeine:3.0.1 for a quick performance check.

The idea is single weigher is 1024 bytes per item, and max weight (100 * 1024) bytes or a max 100 items in a cache. Then I feed 1000 items in the cache at once.

I expect the System.out.println will report max estimated cache size around 100.

```java
private static void testCaffeine() {
    Cache<Object, Object> caffeine = Caffeine.newBuilder()
            	.weigher((key, value) -> 1024).maximumWeight((long) (100 * 1024)).build();
    CaffeineCache cache = new CaffeineCache("Dummy", caffeine);

    int[] array = IntStream.range(0, 1000).toArray();
    List<Integer> list = Arrays.stream(array).boxed().collect(Collectors.toList());
    list.forEach(item -> {
        cache.put(item.toString(), new Byte[1024]);
        System.out.println(item.toString() + " round, cache estimated size = " + caffeine.estimatedSize());
    });
}
```

but the result is, the cache keep growing. 
<img width="686" alt="Screen Shot 2021-04-12 at 9 16 21 PM" src="https://user-images.githubusercontent.com/61992869/114496227-5b2d4e80-9bd4-11eb-9dc4-42664635d400.png">

of cos, after a while, the size drops to around 100,
<img width="337" alt="Screen Shot 2021-04-12 at 9 17 40 PM" src="https://user-images.githubusercontent.com/61992869/114496345-9465be80-9bd4-11eb-8a33-df4ca500ab06.png">

So here comes the question. Is the peak size (like ~300 items) expected?

**Comment by ben-manes** [comment]
The cache is allowed to temporarily exceed the maximum size as a means to support a higher degree of concurrency. If this wasn't allowed then all writes would be serialized against a lock to perform eviction, which reduces throughput. If that was done then the only way to scale writes is to split into multiple locks by creating many smaller caches, like Guava did. However then each cache has an N / k maximum size, which can mean that large objects are not cacheable. This also doesn't have high throughput or scale linearly, as Guava's [benchmarks show](https://github.com/ben-manes/caffeine/wiki/Benchmarks#write-100-1).

Caffeine instead uses a write buffer to batch writes and replay them under the eviction lock. This way writers can hand off work into a buffer if there is free capacity and schedule a thread to drain the buffer. If the buffer is full because the write rate exceeds the eviction rate, then back pressure is applied by having the writers acquire the lock and assist in the draining process. This deschedules the writers, allowing the eviction thread to receive higher priority and overall write throughput increases. This results in a write throughput much closer to that of an unbounded map.

The write buffer may grow up to `128 * ceilingPowerOfTwo(NCPU)`, e.g. 512 entries for a 4 core machine. As writes are rare compared to reads and are immediately handled, typically the write buffer remains close to empty. The maintenance task to drain the buffer is scheduled on the `Caffeine.executor(e)`, which by default is `ForkJoinPool.commonPool()`. If you switch to a same-thread executor, e.g. `Runnable::run`, then for a single threaded loop you'll see it stay strictly within bounds. If you ran with multiple threads, then it would exceed again as the maintenance becomes amortized on the callers. The actual eviction logic is very cheap, but the policy's data structures are not thread-safe so we use log-based concurrency to decouple it from the hash table operations.

Because a cache is used to trade memory for improved response times and that high concurrency is required by modern applications, this technique of a write buffer should be acceptable. It means the cache will only grow by small amount over the limit in order to improve responsiveness, but is not unbounded.

Does that help and make sense?

**Comment by wtao-volvo** [comment]
Well explained. Thanks

**Comment by jacek-psiuk** [comment]
We have an interesting case that I cannot find an explanation for. As the subject is similar, I decided not to open a brand new issue for this.

We are using Caffeine caches with a simple configuration:
```java
Caffeine.newBuilder()
        .expireAfterAccess(Duration.ofHours(3)) // expireAfter was also tested
        .recordStats()
        .build(cacheLoader);
```

The read rate is `~166 r/q`. The miss rate is `~0.82 r/s`. After 18 hours of a service running, its stats look like this:
```
CacheStats{
  hitCount=10708235,
  missCount=53145,
  loadSuccessCount=48462,
  loadFailureCount=0,
  totalLoadTime=4468143763686,
  evictionCount=15007,
  evictionWeight=15007
}
```

Every 3 minutes, a thread executes a `cleanUp` and manually refreshes the entries by updating them the way presented below. As a very small fraction of all items get modified (125 different keys were reported over the course of 18 hours), we excluded it as a cause of the issue:
```java
Map<UUID, Optional<T>> entities = cache.asMap();
Map<UUID, Long> versionedIds = entities.entrySet().stream()
        .collect(toMap(
                Entry::getKey,
                entry -> getVersion(entry.getValue())));
List<T> modified = loader.loadChangeset(versionedIds);
modified.forEach(t -> entities.put(t.getId(), Optional.of(t)));
```

The issue is that the value reported by `cache.estimatedSize()` is constantly growing:
![image](https://github.com/ben-manes/caffeine/assets/20296625/500952cb-f32e-4817-8eea-8c9f59cd1a80)

The expected behavior would be a stabilization after the expiry time (3 hours), as is the type of workload we serve. However, the number of entries that are visible in `cache.asMap().entrySet().stream()` (I will call it "stream length") is much smaller and seems correct not to include the entries that should expire. We log the maximum age of all entries and it does not exceed the expiry time, as expected. After 18 hours the estimated size was reported as `36228` whereas the stream length was `16865`. Stats for all visible entries' age is:
```
LongSummaryStatistics{count=16865, sum=54657649242, min=3, average=3240892.335725, max=10799916}
```

Those two values were in sync throughout the first 3 hours of service operation (`20267` at the last point in sync), and then they started diverting.

What causes the estimated size to drop:

- When I take a service instance out of the load balancer, the estimated size falls down to the same value as reported by the stream length. So the issue is observed only under load.
- When I disable the manual trigger of `cleanUp`, the estimated size (`13728`) does drop being just slightly higher than the stream length (`13504`).

What might be the cause of that issue? @ben-manes, could you advise, please?

**Comment by ben-manes** [comment]
You could try using `expireAfter(expiry)` which uses a more advanced data structure. See the second half of this [article](http://highscalability.com/blog/2019/2/25/design-of-a-modern-cachepart-deux.html) that explains how it works internally.

My guess is that the head of the list queue is constantly being updated but the reordering to the tail is lost. That might happen on a burst of activity causing it drop the events to keep up (as lossy ring buffers to replay under a lock). If every few minutes you are forcing it to be reset, maybe its causing the head elements to be pinned so it never sees expiration work to purge.

The timer wheel approach is always cycling through the buckets. A lost reordering would mean the entry was left in an earlier bucket instead of moved later, so when that bucket is flushed it will reorder it rather than expire the entry. This way it is more tolerant and handles variable expiration policies. If that's the cause then we might want to drop the earlier doubly-linked list approach, as the performance difference should be negligible since both schemes are O(1).

**Comment by jacek-psiuk** [comment]
Indeed, using the `expireAfter(expiry)` method successfully resolved the problem (before when I was trying it, I implemented the interface in the wrong way, which I managed to discover thanks to your message):
![image](https://github.com/ben-manes/caffeine/assets/20296625/3d9def9b-b539-4b2e-82e3-7f26289e3a73)

The `cleanUp` invocations last microseconds and the estimated size is kept in line with the stream length. We realized that in one of the caches we had 1.5x more entries than the live ones. Given the above, it looks like the `expireAfterAccess/Write` should also use the hierarchical timing wheel or be deprecated overall. It was actually a bit of a surprise to me that `expireAfterAccess` updates the expiry at the time of updating an entry. This keeps unused entries if they get refreshed and this is what we unknowingly had.

Thanks for the advice and in general for Caffeine 👍

**Comment by ben-manes** [comment]
"access" is defined by the Java Collections Framework in `LinkedHashMap` to include both read and writes. Since Guava/Caffeine try to feel like extensions to that well-known framework, the terminology was established by them. I think we struggled with finding short and meaningful builder configuration names, since the complex features cannot be easily conveyed in so succinctly.

I put off removing the simpler doubly-linked logic since it was built and no problems reported, even if a redundant algorithm once the timer wheel was introduced. A quirk is that we naively allowed both `expireAfterWrite` and `expireAfterAccess` in  Guava, even though that rarely makes sense and was retained for compatibility. It would require some playing to see if we can emulate that with `Expiry` to avoid a breaking change. If so, then I think a refactoring to simplify the internals wouldn't be too difficult and would avoid this footgun.
