### ISSUE TITLE
cleanUp() does not flush write buffer

### ISSUE THREAD

**Issue by StephenFlavin** [ben-manes/caffeine#538]
Following up from https://github.com/ben-manes/caffeine/issues/536#issuecomment-821540494 I've been working on my implementation but I ran into some issues writing tests.

given the following code:
```java
public static void main(String[] args) {
    int batchSize = 1;
    AtomicInteger callsToRemovalListener = new AtomicInteger();

    LoadingCache<String, List<String>> cache = Caffeine.newBuilder()
            .ticker(Ticker.disabledTicker())
            .executor(new ForkJoinPool(2))
            .removalListener((k, v, r) -> callsToRemovalListener.incrementAndGet())
            .expireAfter(new Expiry<String, List<String>>() {
                @Override
                public long expireAfterCreate(String s, List<String> values, long currentTime) {
                    return Long.MAX_VALUE;
                }

                @Override
                public long expireAfterUpdate(String s, List<String> values, long currentTime, long currentDuration) {
                    return values.size() >= batchSize ? 0L : Long.MAX_VALUE;
                }

                @Override
                public long expireAfterRead(String s, List<String> values, long currentTime, long currentDuration) {
                    return values.size() >= batchSize ? 0L : Long.MAX_VALUE;
                }
            })
            .build(key -> synchronizedList(new ArrayList<>()));

    addOneElementToList("myKey", cache);
    System.out.println(callsToRemovalListener.get()); // 0 after hitting the batch size

    addOneElementToList("myKey", cache);
    System.out.println(callsToRemovalListener.get()); // 0 after exceeding the batch size

    cache.cleanUp();
    Uninterruptibles.sleepUninterruptibly(Duration.ofSeconds(1)); // since removals are happening in a different thread I'm sleeping to be sure
    System.out.println(callsToRemovalListener.get()); // 0 after cleanup

    cache.get("myKey");
    Uninterruptibles.sleepUninterruptibly(Duration.ofSeconds(1));
    System.out.println(callsToRemovalListener.get()); // 1 after read
}

private static void addOneElementToList(String key, LoadingCache<String, List<String>> cache) {
    cache.asMap().compute(key, (k, values) -> {
        if (values == null) {
            values = new ArrayList<>();
        }
        values.add(UUID.randomUUID().toString());
        return values;
    });
}
```
with a `batchSize` of 1 the added entry isn't immediately evicted nor is it evicted after another entry is added which I understand from a performance perspective however I would expect that the cleanup method would cause an write buffers to immediately commit.
I'm unsure if this is intentional or if there is an another way to flush the write buffer.

Using caffeine 2.9.0 with Java 8.

**Comment by ben-manes** [comment]
My guess is that the disabled ticker means time is not moving forward. The entry is at the edge of expiration, but not yet expired. If you use FakeTicker to increment by 1ns then I’d expect it to work.

**Comment by StephenFlavin** [comment]
FakeTicker isn't doing the trick 😕
Using the default ticker and sleeping for 1 second get's the removal listener called once but I would still expect cleanup to have the removal listener to get called twice.

**Comment by StephenFlavin** [comment]
I thought I could work around the issue by using `cache.asMap().keySet().forEach(cache::get);` but the map is empty since the buffer hasn't been written.

**Comment by ben-manes** [comment]
Oh, I see. The underlying data structure for variable expiration is a timing wheel. This uses buckets of ~1s to hash entries into, which are expired in bulk. That offers O(1) roughly sorted order but also means it isn’t as prompt. Can you tolerate a 1s delay?

**Comment by StephenFlavin** [comment]
I can definitely tolorate it it's just slightly ugly.
Is it possible for `cleanUp` to force the flush? Or potentially adding a `cleanUpAndFlushBuffers` method? 
`invalidateAll` seems to force it so I assume its possible.

Apologies, I have been trying to read the code however I'm new to it so it's taking me a while to understand all that's going on.

**Comment by ben-manes** [comment]
It’s not really a flush, but that the expiration data structure doesn’t tell us it’s eligible yet. The invalidation forces the cache to discard everything, rather than peek into the priority queue.

If you add a Scheduler that will trigger the clean up based on the next timing wheel rotation. It might help a bit.

The code in question is TimerWheel. This is a bit hard to read, but this Kafka article explains it well
https://www.confluent.io/blog/apache-kafka-purgatory-hierarchical-timing-wheels/

**Comment by ben-manes** [comment]
I apologize for not having time to run your code until now, as my day has been very busy.

Because `Ticker.disabledTicker()` was used, the entry never expired due to periodic maintenance, which `cleanUp()` runs. This is because the entry the priority queue data structure is not advanced, so the entry is not flushed from it. As described before, for variable expiration we use a Timer Wheel which hashes entries into buckets, where the entire bucket expires as a batch of work. We use a resolution of 2^30 ns (~1.1 seconds). This reduces the resolution quality, but ensures O(1) eviction to ensure that performance does not degrade as the cache's size increases (e.g. compared to an O(lg n) sorted queue).

The last call cause expiration due to the `cache.get("myKey");` line. The cache observes an entry is in the hash table, but it is expired so eligible for usage. Instead a computation is performed which publishes the value as expired, loads and replaces the value, and updates the timestamp. That new value is expired as well, but the write's internal call to `cleanUp` doesn't flush it because the priority queue did not advance.

A real ticker and `Caffeine.scheduler` would advance the timer and cause `cleanUp` to be called automatically based on the next expiration event, here in 1.1s.

A simpler approach might be to do the `values.size() >= batchSize` check within a map computation. Then it is very obvious rather than a callback. For example,

```java
cache.asMap().compute(key, (k, values) -> {
  if (values == null) {
    values = new ArrayList<>();
  }
  values.add(value);
  if (values.size >= 1_000) {
    executor.execute(() -> flush(values);
    values = new ArrayList<>();
  }
  return values;
});
```

You can use expiration as another trigger to have a max time-to-live after create, in case the buffer doesn't fill up to 1_000 within your time period. This should also use `Caffeine.scheduler` because by default expiration piggybacks on the calling thread, so inactivity would not trigger the removal. The scheduler provides a thread that calls `cleanUp` when appropriate, so you are ensured that the entry will be removed promptly. If you want expire-after-create then use variable expiration where the update and read methods return `currentDuration`. This approach of using expiration only for its purpose and putting the size evaluation logic within your compute method helps to ensure that the code is very explicit and clear, other than the caveat of ~1s delay in when expiration can be triggered.

**Comment by StephenFlavin** [comment]
No worries on not having a chance to run the code, you're more responsive than I generally expect 😄 

I've done some playing around with doing it this way however concurrent writes to the same key have the possibility of expiring/flushing elements early (multiple threads flushing for a given key), maybe I've not implemented `flush(values)` as you expected.

I can share some more code if you're interested later today but for now I'm going to synchronize writes to the cache.
```java
private static synchronized void addOneElementToList(String key, LoadingCache<String, List<String>> cache) {
    List<String> batch = cache.asMap().compute(key, (k, values) -> {
        if (values == null) {
            values = new ArrayList<>();
        }
        values.add(UUID.randomUUID().toString());
        return values;
    });
    if (batch.size() == BATCH_SIZE) {
       cache.invalidate(key);
    }
}
```
just using `expireAfterWrite(Duration)`

**Comment by ben-manes** [comment]
A compute is exclusive, so if you write into the buffer through it then it should be safe. I believe that you want the call to `flush` to be asynchronous, which means if ordering was required then it would have to be managed somewhere. That might be through a single threaded executor or a weak cache of key -> future. The latter would look like,

```java
Cache<K, CompletableFuture<?>> flushes = Caffeine.newBuilder().weakValues().build();

cache.asMap().compute(key, (k, values) -> {
  // ...
  flushes.compute(key, future) -> {
    if (future == null) {
      return CompletableFuture.runAsync(() -> flush(key, values));
    }
    return future.thenRun(() -> flush(key, values));
  });
  // ...
});
```

The above will submit the future to the executor to hold a strong reference and chain against the prior future. When the last future in the chain completes, the entry becomes eligible for GC and may be discarded from the map. This allows you to have per-key ordering with automatic cleanup if the key ages out of use.
