### ISSUE TITLE
When load throws exception

### ISSUE THREAD

**Issue by surabhikannan** [ben-manes/caffeine#539]
I am working on code where I am using Vertx Web Servers(which is reactive like programming) with Caffeine Async Cache. 

I have come to a scenario and not able to proceed further. 
When in CacheLoader, if load() throws an exception and as Caffeine swallows the exception, the control doesn`t come back to the calling method and we have a dangling request.

whereas when we do handle the exception inside load(), and return the default value we will end up storing the default value back into the caffeine cache. 

for the first condition, I was hoping if there is a way for me to directly access the stale entry as reload() method gets and I can return if that exists. 

If anyone has an answer, please help.

**Comment by ben-manes** [comment]
I don’t understand.

AsyncCache loads within a CompletableFuture, which is what swallows the exception. The load() method is delegated to by CacheLoader.asyncLoad(). Caffeine will automatically remove the future if it fails by adding a whenComplete handler.

When load() is called, there is no valid entry (absent, expired, or reference collected). If you want to resurrect expired entries, then you can implement a victim cache that the primary evicts to. Otherwise you can use refresh for its reload capability.

I don’t understand the hang because we return a future that will fail. I would expect downstream consumers to handle failures appropriately.

**Comment by ben-manes** [comment]
Closing due to lack of feedback.
