### ISSUE TITLE
Agrona Queue Comparison

### ISSUE THREAD

**Issue by nosideeffects** [ben-manes/caffeine#54]
How does your own single consumer queue implementation compare to the two variants in https://github.com/real-logic/Agrona ?

**Comment by ben-manes** [comment]
The [Argona Queue](https://github.com/real-logic/Agrona/blob/master/src/main/java/uk/co/real_logic/agrona/concurrent/ManyToOneConcurrentLinkedQueue.java) is based on Dmitry's algorithm as well. I use relaxed reads for the consumer and enhanced the queue with a backoff arena to handle producer contention. Their's also does not fully implement the Queue interface by throwing `UnsupportedOperationException` for most methods.

I plan on removing the queue from the public api in 3.0. It is only used for write operations and the cache might switch to an array based approach to avoid garbage. That is because the queue doesn't appear to be a performance bottleneck for the write path. If you need a queue, then prefer [jctools](https://github.com/JCTools/JCTools) which is dedicated towards providing those collections.

**Comment by ben-manes** [comment]
Closing, but I'd be happy to discuss further (especially if you have any suggestions).

**Comment by nosideeffects** [comment]
Nah, I was just wondering. Our use of your cache is very write heavy during high traffic, so I was just looking for the lowest overhead mechanism for the job. Thanks!

**Comment by ben-manes** [comment]
Writes seem to be throttled by the entry update time. A concern I have is if heavy writes causes excessive queuing up of the async tasks. I have an idea of how to reduce that with a smarter state machine, but it also might be a tad complex. Is that the problem you're observing?

**Comment by nosideeffects** [comment]
No observations with Caffeine as of yet. Still in the early testing phase to swap out Ehcache for Caffeine. I am only asking about it because there are bouts in our system where we can actually have more writes that reads and Ehcache's put was far slower than its get. Thanks for the quick responses by the way.

On a separate note, is there any current or potential support for an asynchronous weigher. As in, allow the entry into cache immediately, but weigh and evict if necessary on a separate thread?

**Comment by ben-manes** [comment]
Let me know if you see anything. The scheduling state machine is very simple (idle, required, processing) and ideal for read-centric workloads. A write forces the state to `required`, potentially causing a pile up. The idea is to break `processing` into two states indicating its transition point (processing_idle, processing_required) so that a write can safely skip scheduling if it sees that a maintenance task will be triggered promptly. This shouldn't be too hard, but I haven't prototyped the idea yet.

[Asynchronous weighing](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Async.java#L95) is [already supported](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncLoadingCache.java#L115). The incomplete future is inserted with a weight of zero, meaning that it won't be evicted and takes up no capacity. When the future completes successfully it is re-inserted (`replace(k, f, f)`) to trigger a new weighing based on the materialized value. That may then trigger an eviction.

**Comment by nosideeffects** [comment]
How do I make use of the asynchronous weigher without a loading cache? My use case is as follows:
```
private static final Cache<String, Object> cache = Caffeine.newBuilder()
        .maximumWeight(MAX_WEIGHT)
        .weigher(expensiveWeigher)
        .build();
```
That is, I already have the values that I want to put into the cache, but I don't want to wait for for the weighing to complete before the `put` returns.

**Comment by ben-manes** [comment]
Oh! I see. By asynchronous weighing I meant for use by an `AsyncLoadingCache` which holds futures.

The weight has to be calculated up front and is computed outside of any atomic blocks. I think you could use a similar scheme based on the same principles (initially zero -> async ->  re-weigh & replace). Then you could use a `ThreadLocal` to observe whether the weigher was called by a user or async thread. I'm thinking something like,

```java
class AsyncWeigher<K, V> implements Weigher<K, V> {
  static final ThreadLocal<Boolean> isAsyncThread = ...

  Cache<K, V> cache;
  final Executor executor = ...
  final Weigher<K, V> delegate = ...

  @Override public int weigh(K key, V value) {
    if (isAsyncThread.get()) {
      return delegate.weigh(key, value);
    }
    executor.execute(() -> {
      isAsyncThread.set(true);
      cache.asMap().replace(key, value, value);
      isAsyncThread.set(false);
    });
  }
}

AsyncWeigher<K, V> asyncWeigher = AsyncWeigher.of(expensiveWeigher, ...);
Cache<String, Object> cache = Caffeine.newBuilder()
        .maximumWeight(MAX_WEIGHT)
        .weigher(asyncWeigher)
        .build();
asyncWeigher.setCache(cache);
```

**Comment by ben-manes** [comment]
There is a slight chance of a race where the async thread completes before the user's (e.g. same thread executor). Not sure how to handle that nicely.

I didn't see a use-case for an `AsyncCache`, but that could be added if proven useful. An `AsyncLoadingCache` would probably solve your problem, but as a hack you would have the `load` return `null` indicating a miss if anyone does a loading get. You could probably avoid that from ever occurring by using the `synchronous()` view to access only with the `Cache` interface.

**Comment by nosideeffects** [comment]
Thanks! I will give your initial suggestion a go first. I think it might be an acceptable race, since for our use case it is more important that larger weights (which take longer to compute) to be accurate than the smaller ones.

**Comment by ben-manes** [comment]
The initial suggestion could leave a zero-weight value in the cache, so unlikely but annoying if it occurred in production. A zero-weight is never evicted, so a potential memory leak worse case.

The second suggestion has a mistake where the completed future is weighed immediately (`whenComplete` instead of `whenCompleteAsync`). That could be changed, as I hadn't seen a good reason for not running it on synchronously on the completing thread (writer or async completer). For the current version you'd need a wrapper, but I'd be open to making the change if it is helpful to you.

**Comment by nosideeffects** [comment]
If I return a weight of 1 instead of 0 initially, the first suggestion may be good enough for now. Thanks for your help.

**Comment by ben-manes** [comment]
I investigated whether heavy writes would cause any user-visible issue. My concerns of potential excessive scheduling was unfounded, as I had forgotten that the `tryLock` guard provides adequate protection. A prototype of perfect scheduling (larger state machine) didn't appear to make much of a difference other than be slightly slower to operate on.

The only issues I'm aware of could only occur in synthetic tests or a system already in a bad state. If writer threads spin performing no work but inserting unique keys (e.g. a counter with the full scheduling quantum), then the maintenance task cannot drain the queues and evict fast enough. If the writer threads do any other work, like `Thread.yield()`, then no issue occurs. If I switch to a growable array-based queue to avoid the GC of linked nodes this will throttle that case as a side effect.

A slight improvement to your async weigher idea to avoid the race is to synchronize on the value before inserting into the cache and within the executor's lambda. If we assume the executor will never run the task on the same thread (e.g. no `CallerRunsPolicy`) then this avoids the race condition entirely.

I also strongly recommend using self populating caching whenever feasible. It often results in cleaner code and avoids racy get-compute-put by being atomic. Then your issue would be naturally solved using an `AsyncLoadingCache` because the future be inserted at weight zero, load asynchronously and be readable, and the async thread would re-weigh.

Let me know how your prototyping works out :-)

**Comment by ben-manes** [comment]
I just realized there is an easy hack to make the `AsyncWeigher` detect the race. Instead of using a boolean for the ThreadLocal, store `Thread.currentThread().getId()` and compare.

```java
@Override public int weigh(K key, V value) {
  Long threadId = Thread.currentThread().getId();
  if (isAsyncThread.get() == threadId) {
    return delegate.weigh(key, value);
  }
  executor.execute(() -> {
    Long asyncThreadId = Thread.currentThread().getId();
    isAsyncThread.set(asyncThreadId);
    if (threadId != asyncThreadId) {
      synchronized (value) {
        // If we assume caller of cache.put(k, v) also wraps in a synchronized block, then the
        // async task is blocked from re-weighing until the insertion has completed.
        cache.asMap().replace(key, value, value);
        isAsyncThread.set(null);
      }
    }
  });
  if (isAsyncThread.get() == null) {
    return 0;
  }
  isAsyncThread.set(null);
  return delegate.weigh(key, value);
}
```

```java
synchronized (value) {
  cache.put(key, value);
}
```

I'm pretty sure with the threadId and synchronization hacks, there won't be any race conditions and you get the desired behavior. It is ugly, but cheap.

**Comment by nosideeffects** [comment]
Thanks a bunch!
