### ISSUE TITLE
Configure JSR107 cache to use Caffeine expiration using .conf 

### ISSUE THREAD

**Issue by AlecZorab** [ben-manes/caffeine#55]
Caffeine's default expiration policy doesn't conform to the JSR107 standard, but despite that, I'd prefer to use it over the JSR107 compliant one.

It looks like, currently, the CacheFactory implementation, whilst resolving, will not configure a cache from the application.conf unless it is specifically named in its own config object.

Is there a way to get a cache using the Caffeine expiration policy using only jsr107 methods during construction?

**Comment by ben-manes** [comment]
Yes, Caffeine's native expiration model is not compatible with the JSR's. Unfortunately that means there is no direct mapping, so additional configuration options have to be provided and the `CacheProxy` provides a JSR compatible version. Unfortunately the JSR's expiration approach is very error prone, a tad confusing, and relatively slow.

The JSR's configuration object is pretty limited and I don't think configuration should have been part of the spec. From the other implementations, the assumption appears to be that you either use a configuration file (e.g. `application.conf`) or the implementor's config object (e.g. `CaffeineConfiguration`).

If you want to use an `application.conf` defaults for an anonymous cache and are using annotations, you need to override the `DefaultCacheResolverFactory` binding.

I'm not quite sure what else you're asking, so please clarify if I missed something.

**Comment by AlecZorab** [comment]
If you'll excuse the use of some genuinely appalling scala:

```
  def getCache[T: ClassTag]: Cache[Handle, T] = {
    var cache = cacheManager.getCache[Handle, T](cacheName[T], classOf[Handle], ct[T].runtimeClass.asInstanceOf[Class[T]])
    if (cache == null) {
      cache = cacheManager.createCache(cacheName[T], getConfig[T])
    }
    cache
  }
```

I would, in an ideal world, like to be able to use just the `getCache` call and have that come back with a cache configured with using the `application.conf`.

Should I expect the following block to return true?

```
  val provider = Caching.getCachingProvider
  val cacheManager = provider.getCacheManager
  val sampleCache = cacheManager.getCache[Handle, String]("aCache", classOf[Handle], classOf[String])
  sampleCache == null
```

**Comment by ben-manes** [comment]
If `aCache` is defined in `application.conf` then I'd expect it to resolved and configured. Otherwise the spec expects you to create the cache, so you'd have to use `TypesafeConfigurator.defaults(ConfigFactory.load())` if you want to fallback. If you asking that an unknown cache is automatically created using the default values in your `application.conf`, then I think it will break in the TCK.

Or is there a problem and `application.conf` is not being honored and the named cache isn't found?

**Comment by AlecZorab** [comment]
Yeah, if I explicitly an empty object in the config it finds it fine. My problem is that I don't know ahead of time what caches I'll need.

I had hoped I'd be able to just code the whole module against jsr107 without reference to a specific implementation, but I guess I'll have to drop that and just use the `TypesafeConfigurator`

**Comment by ben-manes** [comment]
Unfortunately I don't think automatically creating an anonymous cache would pass the TCK and seems to not be the expected behavior from what I can tell. I could try this evening (or you are welcome to give it a quick hack) and see if the TCK tests pass (`gradle jcache:testCompatibilityKit`). If they do, we'd probably want to ask on the JSR mailing list and review their Google Doc to see if that is a TCK bug or a viable implementation behavior. But, if it was then it wouldn't be generic all other implementors who don't do that so you're still kinda stuck...

**Comment by AlecZorab** [comment]
Yeah, I think the most pragmatic thing to do is for me to just configure it directly as needed and just provide multiple implementations at my end to provide the relevant configs.

My reading of the spec around `getCache` was obviously a little bit overly optimistic. Apologies for the noise!

**Comment by ben-manes** [comment]
I'm not a fan of JCache's design and APIs, so my default recommendation is to avoid it unless you do foresee using multiple implementations.

If you are on Spring (unlikely given Scala) then their cache is a better abstraction. If you're using JCache's annotations (also unlikely given Scala), then be careful because they prone to cache stampeding by using a racy get-compute-put instead of an atomic load.

It sounds like the experts group is expecting to make breaking changes in 2.0, if that ever happens. Its very much vendor-ware to push commercial products, rather than designed to make happy developers.

**Comment by AlecZorab** [comment]
Yeah, I'm expecting to need to move to an as yet unknown distributed cache at some point in the next 12 months, otherwise I'd just be coding against a proper api.

**Comment by ben-manes** [comment]
Fyi, I gave it a shot out of curiosity and as expected the TCK failed. Unfortunately your only option is to forego the generic configuration and rely on implementation-specific in general. A distributed cache with have its replication and other settings, so really the generic configuration API is for show and pretty much unusable (e.g. anonymous caches for JCache annotations causes memory leaks).

```gradle
org.jsr107.tck.CacheManagerTest > getCache_Missing FAILED
    java.lang.AssertionError: expected null, but was:<com.github.benmanes.caffeine.jcache.CacheProxy@1296409e>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotNull(Assert.java:755)
        at org.junit.Assert.assertNull(Assert.java:737)
        at org.junit.Assert.assertNull(Assert.java:747)
        at org.jsr107.tck.CacheManagerTest.getCache_Missing(CacheManagerTest.java:395)

org.jsr107.tck.CachingTest > cachingProviderGetNonExistentCache FAILED
    java.lang.ClassCastException: Incompatible cache key types specified, expected class java.lang.Object but class java.lang.Long was specified
        at com.github.benmanes.caffeine.jcache.CacheManagerImpl.getCache(CacheManagerImpl.java:120)
        at javax.cache.Caching.getCache(Caching.java:279)
        at org.jsr107.tck.CachingTest.cachingProviderGetNonExistentCache(CachingTest.java:167)
```
