### ISSUE TITLE
Requires Static Transitive and the Maven-Javadoc-Plugin

### ISSUE THREAD

**Issue by A248** [ben-manes/caffeine#551]
It seems like there is a bug in the maven-javadoc-plugin which prevents generating javadocs when depending on modules which use `requires static transitive`. No one else has confirmed this bug so far, but I'm highly sure of it. If you like, you can try the reproducer and confirm.

https://issues.apache.org/jira/projects/MJAVADOC/issues/MJAVADOC-677

In #540 the added module descriptor uses `requires static transitive`. This may surprise Maven users upgrading to 3.0.2 when their javadoc starts to fail. (In fact, this is where I ran into MJAVADOC-677 myself). I haven't checked but it's most likely that this only affects JPMS users - if it affected non-JPMS users this bug would have been reported much more widely.

Although `requires static transitive` is strictly speaking the correct directive in the current module descriptor, you may want to temporarily use `requires transitive` until a release version of the maven-javadoc-plugin contains a fix for this bug. I thought I would leave the decision up to you before filing a PR.

**Comment by ben-manes** [comment]
Thanks @A248. I would prefer to put pressure on Maven to fix their bug and resolving it rather than making dependencies implement a workaround.

JavaDoc usually doesn't require all dependencies, so you might be able to skip this if an error. Otherwise maybe the [moditect](https://github.com/moditect/moditect#adding-module-descriptors-to-existing-jar-files) could rewrite the descriptor in your build.

I'll try running the reproducer this evening to see if I have any suggestions.

**Comment by A248** [comment]
That's a reasonable decision. Maven still has some work to do with regards to JPMS support around the edge cases.

Don't worry about myself - this was more in case someone else had the same problem. After all, I wouldn't want to *not* report it considering I was the one who introduced the module descriptor PR.

I'll close this issue now since the bug belongs to the maven-javadoc-plugin and not caffeine.
