### ISSUE TITLE
Refresh a single cache entry periodically

### ISSUE THREAD

**Issue by hjohn** [ben-manes/caffeine#566]
I have the following use case for which I'm trying to use Caffeine.

I have a database table that I want to completely load into memory. I store the whole table in a single key. The data can be modified externally, and I must guarantee that such an external change is picked up within a certain period (within 60 seconds for example).

The service may be accessing this cache either very frequently (which rules out doing a query each time) or may be completely idle for minutes at a time. It is crucial that after idling the service does not get stale data from the cache as an external change may have occurred making the stale data incorrect for use by the service.

Currently I have this:

    Caffeine.newBuilder()
            .refreshAfterWrite(Duration.ofSeconds(60))
            .build(k -> repository.findAllAggregates())

I gather that `refreshAfterWrite` is not covering this use case.

I only use a single entry in the cache, splitting each row into its own entry would not really be beneficial as the table is evaluated
as a whole (first matching row wins).  Perhaps I'm not using Caffeine for an intended use case? :)

**Comment by ben-manes** [comment]
Yes, this is not the right fit for this library. Instead you can use java.util.concurrent to handle this by using a `ScheduledExecutorService` to periodically set a volatile (or `AtomicRefernece`) field.

For periodic work like your case, Caffeine can't do anything more intelligent than what you can using the j.u.c. package. Regarding `refreshAfterWrite`, it is intended as a latency hiding mechanism that is usually combined with an expiration policy. This way hot entries (like a configuration) can be reloaded asynchronously rather than expired, causing a periodic delay as readers block waiting for a fresh load. If instead the entry is inactive then expiration will kick in and reclaim memory. This provides a nice effect of fading away expired content while allowing active content to stay fresh and fast to access.

**Comment by oshai** [comment]
We have a similar use case. I think `refreshPeriodically` of the cache has some benefits and implementing it with `ScheduledExecutorService` might be tricky with the initial value in some scenarios.

In case you want to reconsider it.
