### ISSUE TITLE
Concurrency level question

### ISSUE THREAD

**Issue by mtheos** [ben-manes/caffeine#567]
Hi, Guava cache has a [concurrency level](https://guava.dev/releases/19.0/api/docs/com/google/common/cache/CacheBuilder.html#concurrencyLevel(int)) that segments the table internally to allow uncontended concurrent operations. Does Caffeine not have or not require this?

I'm leaning towards not require due to the terminology in the docs but I wanted to confirm.

Thanks

**Comment by ben-manes** [comment]
yeah, it's not needed.

Guava is a fork of Java 5's `ConcurrentHashMap`, which is segmented as you mentioned. Java 8 rewrite the hash table so that the number of locks increase as the map grows, allowing for more fine-grained write concurrency. Caffeine is similarly dynamic about its resources based on contention. That legacy setting isn't used by Java nor Caffeine, so we dropped it.

**Comment by mtheos** [comment]
Wonderful! Thank you!
