### ISSUE TITLE
[Feature Request] Add weighed size as first-class stat

### ISSUE THREAD

**Issue by smourapina** [ben-manes/caffeine#572]
I think it would be useful to have occupied cache size (in bytes) as a first class stat being returned in `CacheStats`. I am up to work on adding this feature. Is there any reason why this should not be done, and do you have any pointers on how to implement this?

**Comment by ben-manes** [comment]
Hi @smourapina,

You can inspect this value using the the policy's [weightedSize()](https://github.com/ben-manes/caffeine/blob/8ffce2563bc2464acf7dca1b8b51c71b7cd75596/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Policy.java#L147-L153) method:
```java
cache.policy().eviction().ifPresent(policy -> {
  long weightedSize = policy.weightedSize().getAsLong();
  // publish into metrics reporter
});
```

This assumes that you are evicting by maximum weight and supplied a `Weigher`. For example, you could use [JAMM](https://github.com/jbellis/jamm) to estimate the entry size and evict when the cache exceeds a byte threshold. Otherwise you can use this type of tool outside of Caffeine, e.g periodically iterate over the entries using the `asMap()` or maintaining a running total when entries are added or removed. There is a [draft JEP](https://openjdk.java.net/jeps/8249196) that you might be interested in.

Does that work for you?

**Comment by smourapina** [comment]
Thank you for your comprehensive answer @ben-manes. Using the `weightedSize` method provided with the `Policy` interface was indeed the solution I was considering.

My question was also: would it make sense to add this metric to `CacheStats`? If yes, I would like to contribute this feature to the project by creating a PR (but would prefer to only start working on this if/ when I get your ok).

**Comment by ben-manes** [comment]
I understand the desire to, but I'd prefer not to at this time. If one bounds a cache by a maximum size, then at capacity the value won't change much. That differs from metrics like the hit rate or load times whose changes might indicate a regression. In other libraries the size is not a statistic and it can be queried for separately, so I don't think we need to include it.

**Comment by smourapina** [comment]
Valid points! Thank you for your feedback, will now go ahead and close this issue, if it is ok.
