### ISSUE TITLE
High concurrency & atomic removal() action

### ISSUE THREAD

**Issue by mdhsl** [ben-manes/caffeine#573]
Hi all, I'm trying to use Caffeine in a highly concurrent environment and I'm encountering a concurrency problem when using the removal. Indeed, I am using the caffeine cache to maintain multiple JDBC Connections in cache. During an eviction (time/maxSize or weak), I have to close the connection otherwise I would have a memory leak.

To do this, I think I need to use the removal that alerts me when a data is evicted. The problem is the following:
During the removal, and this for a short time, the object is still available to be retrieved.  

From my point of view, I would say that the removal() call should be made after the object has been removed from the cache. I don't think this is a problem with Caffeine, but could you confirm that the removal() method call is exclusively done after the cache eviction, and this in an atomic way?

I think the multiple threads get a reference to the object and the removal is done before all the threads have had time to process the information.
But I wanted to ask to be sure

Here is the reference project I use: https://github.com/mdhsl/caffeine-concurrency-bug

**Comment by ben-manes** [comment]
The removal listener is invoked after the entry was removed from the underlying ConcurrentHashMap. This means it is no longer in the cache itself. However, a previous read from the cache might still be using entry and 
that does not mean that a the value is n not in use by other threads due to a previous retrieval. This means your usage is unsafe because you can close the connection while in use, as you are observing. For these cases, you would use some form of reference counting to close the connection when there are no active usages.

One way to do this is through [reference types](https://www.kdgregory.com/index.php), such as a phantom reference for finalization. The weakness of this approach is that it relies on a GC cycle to discard the entry, which is non-deterministic (e.g. Epsilon GC is for performance tests and never collects). Therefore manual reference counting is likely a more robust approach for an object pool.

Most likely a cache is not a great fit for this. A connection pool should provide exclusive access whereas a cache is offering concurrent access. There are dedicated libraries like [stormpot](https://github.com/chrisvest/stormpot) and [vibur](http://www.vibur.org/vibur-object-pool/). A popular dedicated jdbc connection pool is [Hikari](https://github.com/brettwooldridge/HikariCP).

**Comment by mdhsl** [comment]
Thank you very much for your quick response. That's what I thought. I made an implementation using the close() in the @finalize() first and another with the phantomReference. 

But I don't like these approaches, I wanted to be sure to use the cache correctly first.

Thanks and nice work on Caffeine, it is greatly appreciated :)

**Comment by mdhsl** [comment]
I'm reopening this thread because after modifying Caffeine a bit, I can solve my problem.

Is it possible (wise?) to add a RemovalCause 'PRE' allowing to 'prevent' the eviction of a data before it is removed from the cache again?

Indeed, in my case, and I think it must concern other cases, we need to synchronize the whole cache before each get() to be sure that during the removalListener(), other threads have not acquired the object.

I made a simple test using a ReentrantReadWriteLock which allows to synchronize the cache only when it is 'pre-evicted'. This greatly reduces the cache contention.

This is a simple piece of code:

```java
 @Override
  public void notifyRemoval(@Nullable K key, @Nullable V value, RemovalCause cause) {
    if (!hasRemovalListener()) {
      return;
    }
    Runnable task = () -> {
      try {
+++     removalListener().onRemoval(key, value, RemovalCause.PRE);
        removalListener().onRemoval(key, value, cause);
      } catch (Throwable t) {
        logger.log(Level.WARNING, "Exception thrown by removal listener", t);
      }
    };
    try {
      executor.execute(task);
    } catch (Throwable t) {
      logger.log(Level.ERROR, "Exception thrown when submitting removal listener", t);
      task.run();
    }
  }
```

Here is an effective way to solve my problem:

```java
...
    static ReentrantReadWriteLock lock = new ReentrantReadWriteLock();

    static final LoadingCache<String, SQLiteManager> cache = Caffeine.newBuilder()
            .expireAfterWrite(10, TimeUnit.MILLISECONDS)
            .weakValues()
            .removalListener((String filePath, SQLiteManager manager, RemovalCause cause) -> {
                if(cause == RemovalCause.PRE) {
                    lock.writeLock().lock();
                } else {
                    if (manager != null) {
                        manager.close();
                    }
                    lock.writeLock().unlock();
                }
            })
            .build(key -> new SQLiteManager(new File(FILE)));

....
      lock.readLock().lock();
      data = cache.get(FILE).get(x, y, z);
      lock.readLock().unlock();

**Comment by mdhsl** [comment]
In fact it's not a problem related only to JDBC connections, it's more generic. In my case, I have this problem with something else where I have to 'destroy' JNI objects to make sure the memory is freed efficiently.

I use the JDBC close() as an example here. But the idea is to be sure that the cache object that has to be evicted is not taken by other threads and that we can do its close() in the removal()

My implementation is not correct, it was just to underline the idea. I agree with you; it doesn't make sense in the same thread. You should launch an event just before the actual eviction

Translated with www.DeepL.com/Translator (free version)

**Comment by ben-manes** [comment]
Oh I see, you have the SQLiteManager call within the read lock. That is how the fix works.

An equivalent approach would be,
```java
// consumer
for (;;) {
  var manager = cache.get(FILE);
  synchronized (manager) {
    if (manager.isClosed()) {
      continue;
    }
    return manager.get(x, y, z);
  }
}

// removalListener
synchronized (manager) {
  manager.close();
}
```

This would use a per-manager lock to reduce blocking queries on different managers. It would retry on the client if it had a stale read.

**Comment by mdhsl** [comment]
Your solution works fine! it seems a little be hacky but works fine.

**Comment by ben-manes** [comment]
I can see why you are going to all of this trouble because you have to maintain multiple databases, rather than a pool of connections to a single one. There are keyed object pools, but most are not very performant. I wrote a [prototype](https://github.com/ben-manes/multiway-pool) that worked okay, but trashed it in the last commit. It's more complex than you need, though.

Ideally you could delegate the locking to `ConcurrentHashMap` so that the manager is only ever accessed exclusively. That gets worse though, since you have to handle everything with a `compute` block (create if absent, query, close on error) and stash the query result into an external instance. This would require using `Caffeine.evictionListener` instead so that the removal notification code is run within the atomic operation. Stubbing out the code was a lot more hacky so I don't think you'll get much better than that retry loop.

**Comment by mdhsl** [comment]
> I can see why you are going to all of this trouble because you have to maintain multiple databases, rather than a pool of connections to a single one. There are keyed object pools, but most are not very performant. I wrote a [prototype](https://github.com/ben-manes/multiway-pool) that worked okay, but trashed it in the last commit. It's more complex than you need, though.
> 
> Ideally you could delegate the locking to `ConcurrentHashMap` so that the manager is only ever accessed exclusively. That gets worse though, since you have to handle everything with a `compute` block (create if absent, query, close on error) and stash the query result into an external instance. This would require using `Caffeine.evictionListener` instead so that the removal notification code is run within the atomic operation. Stubbing out the code was a lot more hacky so I don't think you'll get much better than that retry loop.

That's pretty cool, it is exactly what I need. I'll checkout that and try to modify if needed. Thank you very much

**Comment by ben-manes** [comment]
yeah, just revert the last commit where I broke everything, because Guava was slow. You can in Caffeine as the interfaces are almost identical. If you find it useful we could resurrect that code and get it into a usable state.
