### ISSUE TITLE
RFC: Does it make sense for Caffeine to be a JCache provider?

### ISSUE THREAD

**Issue by gitblit** [ben-manes/caffeine#6]
I've been wishing that Guava could be used as a light-weight JCache provider.  Does it make sense for Caffeine to be a JCache provider?  Or is it too early for consideration?

https://github.com/jsr107

**Comment by ben-manes** [comment]
I haven't followed jsr307 since its reboot, when I had to decline Greg Luck's invitation to join the JSR due to the Oracle/Google lawsuit. At the time it was simply an extraction of Ehcache's APIs, though they appear to have resolved a lot of my original concerns since. 

Surprisingly it seems that they entirely ignored Java 8, neither adopting j.u.c, lambdas, nor new JDK naming conventions in favor of their own versions (e.g. [CompletionListenerFuture](https://github.com/jsr107/jsr107spec/blob/master/src/main/java/javax/cache/integration/CompletionListenerFuture.java) vs [CompletableFuture](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/CompletableFuture.html)). They're API seems to be more focused on distributed caching than in-memory cache performance, so some of the design decisions are a little quirky to promote the vender implementations users are expected to adopt.

My understanding is that this JSR is implemented at the container level, not the library. [Spring's implementation](http://docs.spring.io/spring/docs/4.1.0.BUILD-SNAPSHOT/spring-framework-reference/html/cache.html) supports a Guava backend. I imagine that there's CDI and Guice extensions somewhere too.

If there's a base substrate that the library should provide to make it easier to integrate with JCache, then I'd add that as an optional extension. I'd need to learn more about the whole situation and look into existing integrations.

If you have a better understanding if what I can/should do to aid JCache usage, that would be helpful in getting support added. Otherwise it will probably be backlogged for the time being.

**Comment by gitblit** [comment]
Clearly you have a better handle on caching than I do.

My understanding of JCache is that it is an abstraction layer like SLF4J.  The distributed caching providers (Ehcache, Infinispan, Hazelcast, etc) are all JCache providers.  The frameworks that have spent effort to define and abstract their own cache interface (Spring, Play, etc) may not care about JCache.  The Spring abstraction you cite supports the JCache annotations, but that is not to say it is a JCache provider.

There are Guice extensions provided by the reference implementation.  That's how I am using it.  It's mucho bueno.

Like any abstraction, it's lowest common denominator functionality.  Interacting with the provider in this way allows the provider to be runtime-pluggable.  My app may not need the distributed power of Hazelcast so a lighter-weight caching solution would be more attractive but as my needs change I can swap it out.  Or possibly I want to swap providers based on production vs. development - similar to how many shops use H2 or SQLite.

If I do want vendor-specific power then I can choose to configure my provider through a vendor-specific config file (ehcache.xml, infinispan.xml, etc) that can be specified with the JCache abstraction layer.  I'm not suggesting that this part of the spec be supported.

However, being able to define Caffeine caches with JCache's builder and reference caches using Guice+JCache annotations would be huge. To be transparent, my end goal would really be to see the official Guava Cache become a JCache provider since I regularly use Guava as a standard library in my projects.

It's not clear to me what your long-term plans are for Caffeine.  I am assuming that your design will be used to inform a Guava Cache rebirth.  Either way, I think that any new Java cache implementation should not ignore the JCache spec.

**Comment by ben-manes** [comment]
Thanks for the clarification. Looking into the other providers I see that you're right. They implement adapters and annotation extensions leverage the `ServiceLocator` to load the implementation.

I'm not a fan of the JCache spec to use in my work, but I understand the motivation to allow others to use it if they prefer. It won't be my top priority since there's a lot to do before I'm happy with the implementation. I agree that it should be an optional dependency just like the Guava adapters and may be in the first release or shortly after. I'll probably work on it when I'm done with the core and am iterating on feedback from anyone I can convince to give a review.

The relationship with Guava is unknown. While some of my former colleagues are supportive, the core team has been quiet. This may be because they have not communicated what Guava will look like in a Java 8 world, so there are many open questions. While I'd love to get this back under the Google brand and their involvement, it may simply be an alternative to promote as the Guava cache languishes.

**Comment by gitblit** [comment]
Fair enough.​

I'll keep an eye on your project & thanks for the consideration.

**Comment by ben-manes** [comment]
I started flushing out the basics.

I plan on using [Typesafe Config](https://github.com/typesafehub/config) for the configuration file unless there is a reasonable concern.

One difficulty that may delay this feature is figuring out how to run the TCK as part of the build. It is intended to be used manually by updating its configuration files and running at the command-line or in IntelliJ. It appears to be a suite of JUnit tests, some using the JVM and others calling to a local cache server of its own design. It doesn't appear designed for easy integration, except for the foresight of being published on Maven Central. Hazelcast manually extends every test class so that their build picks it up with their customizations. I think with some proper Gradle magic this can be integrated in a cleaner fashion, but that will take some time to work out.

If I can get the TCK integrated, that should make it implementing the adapters much easier since development will be driven by tests.

**Comment by ben-manes** [comment]
I spoke too soon. The TCK is now integrated into the build.

**Comment by ben-manes** [comment]
Okay, so after spending the weekend on this roughly 80% (381) tests pass. The failures are due to not yet implementing adapters for all of the JCache features (listeners, expiration, writer, and statistics). I suspect that these are probably very easy to add, but I haven't investigated yet. We also need to flush out configuration through an external file, which is just scaffolding at the moment.

When the module is complete, you're welcome to port it over to Guava. There isn't a lot of Caffeine-specific code, though it will be a little more work if you want to backport from Java 8. The only challenge might be `Cache.invoke` where I use `asMap's compute` method to provide the per-entry atomicity expected by `EntryProcessor`. If you implement it racy instead, that may be spec-compatible due to the JavaDoc saying that consistency is defined by the cache (even though it contradicts itself by saying the entry is operated on atomicly). None of the TCK tests actually test any concurrency expectations.

**Comment by gitblit** [comment]
That's great news!  Your choice of TypeSafe Config works for me - I use it
too.

**Comment by ben-manes** [comment]
Listeners are now working. Their design requires in-order event processing and listeners may be configured to force the caller to block. This differs from Guava where events are asynchronous and unordered. I resolved this conflict by treating JCache listeners as actors using `CompletableFuture` chaining to construct a dispatch queue and `CHM.compute` for scheduling. The RI, Ehcache, and Hazelcache versions all appear buggy and wrong if going by the JavaDoc. The TCK, as a whole, is a pitiful test suite that doesn't actually enforce most of the spec.

Expiration appears messy because they continue to redefine terms commonly accepted in the JDK. `LinkedHashMap`'s access-order means read or write, whereas JCache does not consider a write as accessing an entry. There are further redefinitions in creation and update expiration policies that are inconsistent. So expiration needs to be implemented from scratch.

As listeners cannot accept null key or values, JCache does not support reference collection (weak, soft). This would probably not be available anyways because I'll have to add expiration wrappers.

The spec authors originally designed everything to match Ehcache, as they drove it. Instead of understanding algorithmic choices, all implementations are expected to mirror it. Now that the lead is at Hazelcache they've migrated that implementation to be JCache compatible by converting algorithms. He's made the recent v1.1 API **incompatible** with v1.0 by adding non-default methods to the interfaces that match Hazelcache's extensions.

Hopefully when JEE8 is released the JCP will provide adult supervision. Until then the JCache spec is not reliable and grossly under tested.

**Comment by ben-manes** [comment]
Expiration is the remaining feature left to implement, followed by external configuration. However I need your guidance on what you expect from expiration support.

All of the implementation available use lazy expiration, due to Ehcache being implemented that way and dictating the spec. The Ehcache documentation says,

> If an entry expires but is not accessed, and no resource constraints force eviction,
> then the expired entry remains in place.

This approach is trivial to implement and fast, but error prone. Its an excellent choice for large caches with a size bound like memcached, but poor as a standalone policy due to a memory leak if uncapped. The common active approach is a O(lg n) priority queue, which has numerous drawbacks. Instead by modeling expiration as doubly linked lists, we adapted CLHM's O(1) concurrent approach to be time bound instead of size bounded. We use share an access-order list (read or write) for maximum size and time-to-idle policies. A write-order list (insert / update) is shared by a time-to-live policy and the refresh-after-write feature.

Unfortunately JCache's expiration policies do not match 1-to-1 with Caffeine / Guava's. I do not want to add their variants into Caffeine's core as each requires their own list structure that cannot be reused, thereby being wasteful memory-wise. I would also not want to expose it in a public API, so that would need some reflection hacks to configure. Simply not worth doing.

1. Do you want lazy expiration evaluated on entry access? (matches all others)
2. Do you want periodic expiration? If so, which are acceptable?
  1. O(1) periodic cleanup on user thread
  2. O(n) background sweep by evaluating a watermark (`ForkJoinPool.commonPool()` thread)
  3. O(lg n) per call on user-thread (hint, not acceptable to me)
  4. Lazy with per-thread ops counter to perform a random sampling to discover expired entries
 5. Other ideas?

My ideal is (2.1), but I don't want to invest into re-implementing Caffeine's core in the JCache module. So I'd lean towards (2.2) as the simplest as the cost is not user-facing. If (1) is acceptable, then (2.4) is a simple addition that help alleviate fears unbounded growth though does not prevent it.

P.S. Sorry for these excessively long ramblings =)

**Comment by gitblit** [comment]
Like I wrote before you *clearly* are more expert at caching than I.  I have simple needs and I'm not doing anything elaborate which is why the JCache spec attracted me.  Your review of the JCache spec is not very flattering, but I'm pretty sure it's scheduled to be part of JEE8. :|

Either 2.2 or 1+2.4 is acceptable.  This is your baby and I'm ok with either solution.

Thank you so much for really digging into this!

**Comment by ben-manes** [comment]
Now passes TCK with lazy expiration support. There's probably a lot of clean-up work and so on, which can be resolved in future iterations.

**Comment by gitblit** [comment]
Awesome!
