### ISSUE TITLE
cache.get from mappingFunction hangs

### ISSUE THREAD

**Issue by nau** [ben-manes/caffeine#60]
The last line never terminates. Tested on Caffeine 2.2.1 and 2.2.2. Java 8u60 on Mac, El Capitan.
```java
        Cache<String, String> cache = Caffeine.newBuilder().build();
        Function<String, String> loader2 = (String t) -> "3";
        Function<String, String> loader1 = (String t) -> cache.get("2", loader2);
        System.out.println(cache.get("1", loader1));
```

**Comment by ben-manes** [comment]
Recursive computations are not supported. This is [not supported](http://stackoverflow.com/a/28845674/19450) by `ConcurrentHashMap` which livelocks in Java 8 and should throw an exception in most cases in Java 9.

The JavaDoc for the cache loader and get methods include warnings (see below). This is understandably surprising at first, but I think a reasonable limitation. I agree that hanging is a poor experience, which is why I worked with Doug to find ways to fail fast.
```
the computation... must not attempt to update any other mappings of this cache.
```

**Comment by ben-manes** [comment]
The only practical step I could take is embed a copy of Doug's fixed ConcurrentHashMap. I'd prefer not to do that. Its unfortunate that this has been fixed for over a year and yet never made it into a JDK8 release. Closing as I don't have any good resolution until JDK9.
