### ISSUE TITLE
Potential scaling issue with eviction activity?

### ISSUE THREAD

**Issue by cruftex** [ben-manes/caffeine#619]
I recently started benchmarking again, especially on multi core systems. Here is a result running on a 24 core system:

![ZipfianSequenceLoadingBenchmark-byThread-1Mx500-notitle](https://user-images.githubusercontent.com/2668191/139669059-b82cdf7c-6a5c-459e-8bde-e87d5f5a6ce6.png)

This operates the cache with 1M entry capacity in read through mode with a Zipfian distribution of keys between 0 and 5M. This results in a hit rate of around 88%. More details, see the [cache2k bechmarks](https://cache2k.org/benchmarks.html).

From my gut feeling I would have expected that Caffeine would scale better and cache2k worse. This is not the case. Maybe you like to double check that my benchmark is not flawed?

**Comment by ben-manes** [comment]
This is because you are enabling `boostConcurrency` in cache2k, which turns on segmentation to increase the write throughput at the cost to the hit rate. For your workload that increases to 32 segments from its default of 2. If you did not have this enabled then your original assumption of worse throughput would probably be correct.

Caffeine does not segment its eviction policy and this is a [known](https://arxiv.org/abs/2109.03021) scaling limit. While it could similarly have an option to do so, this eviction throughput has not been a user reported problem. It is an unnatural workload where the cache is evicting constantly, the application is doing no real work, and system performance is limited by this activity. Therefore for now I am closing this because real-world usage has not shown it to be a problem to resolve. If users do find it to be one then I'll tackle it and likely using a similar approach to your configuration option.

**Comment by cruftex** [comment]
> It is an unnatural workload where the cache is evicting constantly, the application is doing no real work, and system performance is limited by this activity.

A agree, that is the nature of micro benchmarks.

Thanks for the remarks. I will do some experimentation around the `boostConcurrency` option and segmentation. Maybe I can drop it by finding another compromise with the standard segmentation.
