### ISSUE TITLE
ComposeResult in LocalAsyncCache will result in a failed future if one of the keys yields a completion exception

### ISSUE THREAD

**Issue by martinbomio** [ben-manes/caffeine#627]
Hello!
First of all, I want to thank you for the great lib, it performs considerably better to Guava's cache, but offers a compatible interface which makes it very easy to switch implementations, kudos!

I was taking a look at the `AsyncCache` api, in particular the `getAll`, and was wondering if it would be possible to have a variation of a get all that instead of returning `CompletableFuture<Map<K,V>>`, it can return a `Map<K, CompletableFuture<V>>`.

The main reason for this request is that with the current `getAll`, if the `mappingFunction` does an async call, and one of those calls for one of the keys fails, then it will lead to the resulting future to fail, because of the [composeResult](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncCache.java#L156).

Please let me know if you need more info!

**Comment by ben-manes** [comment]
My concern is that the expected behavior would change depending on the loader that was used. A per-key loader could provide partial results, whereas a bulk loader is a single shot. If we exposed a different API then users might assume they can reliably get partial results and filter out failures, and all failing might imply the wrong error handling. That all might nudge developers towards per-key loaders, whereas they should prefer opting into a bulk loader for better performance.

An alternative approach could be to implement a bulk loader which filters out failed futures from being returned. The `getAll` map does not have to contain all keys, only those that were found. That has the negative impact of making your call site not know why the key was absent so there is some information lost in between.

P.S. Thanks!

**Comment by ben-manes** [comment]
Actually a better workaround for per-key loads is just to call `get(key)` and compose the results yourself. 🙂

**Comment by martinbomio** [comment]
@ben-manes thanks for the quick reply.

The thing about using the `get(..)` is that we cannot leverage batching on the external source (i.e. backend service, redis, memcache call) if those sources support it

**Comment by ben-manes** [comment]
yeah, I think getAll with a map of futures doesn't make a ton of sense given the interactions of single vs batch and usage patterns.

Another approach is to make single calls and perform the batching by the external call abstraction to coalesce individual calls into batches. That way it is cross-cutting and not the responsibility of the caller to optimize. This is attractive but also beyond the scope of this library in the same way retrials with backoff are better suited by a dedicated library like [failsafe](https://failsafe.dev/). There is an contrib [example](https://github.com/ben-manes/caffeine/tree/master/examples/coalescing-bulkloader), but I think a proper coalescing request library would be neat (time, size, etc). That might be more work for your specific case compared to your special case handling if only a one-off problem.

**Comment by martinbomio** [comment]
I agree. Closing the issue. Thanks for the help!
