### ISSUE TITLE
WildFly Could not read provided index: /content/xyz.war/WEB-INF/lib/caffeine-2.9.1.jar/META-INF/jandex.idx

### ISSUE THREAD

**Issue by htr3n** [ben-manes/caffeine#628]
I used Caffeine as the cache for my configuration and deployed it to WidFly 11 wrapped in a singleton bean inside a WAR. From time to time, I saw this message

```
 2021-11-23 11:37:41,546 1052 ERROR [MSC service thread 1-2] server.deployment - WFLYSRV0002: Could not read provided index: /content/xyz.war/WEB-INF/lib/caffeine-2.9.1.jar/META-INF/jandex.idx
```

What does that message imply? Does it affect any functionality? 

Caffeine: 2.9.1
WildFly 11.0.0.Final
JDK: 1.8

**Comment by ben-manes** [comment]
Quarkus asked us to include a jandex file, which is a precomputed metadata file of the class information. That was added in 2.8.6 for quarkusio/quarkus#10420 (Graal AOT). They then decided that it wasn't helpful, so it was removed in the 3.0 release (as by semver it became a breaking change). The file has no meaning for Caffeine and can be ignored. I don't know how Wildfly might care except that jandex is a JBoss thing they use, but I think you should be able to suppress the error without a problem. Otherwise you could talk with the Quarkus team who collaborate on all of those other JBoss/Redhat projects.

**Comment by htr3n** [comment]
@ben-manes thanks for the info, it's interesting. Nonetheless, you said this is removed in v3.0+. Unfortunately, we get stuck with 2.x due to using JDK 1.8, as Caffeine 3.0+ asks for JDK 11. Any change to back port this to 2.x?

**Comment by ben-manes** [comment]
I'm not very familiar with jandex, but if it is meant to be consumed by clients then it becomes an API? That's why it seemed safe to remove in a major version, but inappropriate from a semantic versioning versioning perspective to do so in a minor version. I doubt anyone else was using it, but you'd need to get insight from the Redhat/JBoss team on what the right thing to do here is. My lack of knowledge leaves me to favor leaving it alone.

**Comment by htr3n** [comment]
@ben-manes fair enough. I'm surprised to see the warning/error message and then learned about the relationship between Caffeine and Quarkus in this case.

**Comment by ben-manes** [comment]
The simplest is probably just to [exclude the file](https://stackoverflow.com/a/20539586/19450) from the dependency when building your war. Otherwise you could just ignore it since there is zero expected functionality.
