### ISSUE TITLE
AsyncCache should allow partial results within a timeout

### ISSUE THREAD

**Issue by Dirk-c-Walter** [ben-manes/caffeine#63]
There is a common usage pattern for AsyncCaches that is currently not well supported, namely returning incomplete results if the computation can't finish for all keys in some timeout. Getting 100% of the data in 100ms is best, but it is often better to get 90% of the data in 100ms than wait 1 second for 100% of the data, but as the computation is expensive you want to finish it and cache it for future accesses.

Currently I solve that with uglyness like this in the loader;

`
public CompletableFuture[] asyncLoadAll(final Iterable[? extends String] keys, final Executor executor) {

    return CompletableFuture.supplyAsync(() -> {

        final CompletableFuture[] future = bulkGet(keys);

        try {

            return future.get(timeout, MILLISECONDS);

        } catch (InterruptedException | ExecutionException | TimeoutException e) {

            LOG.error("Error while fetching data for the cache", e);

            future.whenComplete((map, ex) -> {

                if(map != null) {

                    localCache.synchronous().putAll(map);

                }

            });

            return Collections.EMPTY_MAP;

        }

    }, executor);

}
`

but I can't help but feel like there should be a better solution.

**Comment by ben-manes** [comment]
JDK9 is adding timeout support ([orTimeout](http://download.java.net/jdk9/docs/api/java/util/concurrent/CompletableFuture.html#orTimeout-long-java.util.concurrent.TimeUnit-) and [completeOnTimeout](http://download.java.net/jdk9/docs/api/java/util/concurrent/CompletableFuture.html#completeOnTimeout-T-long-java.util.concurrent.TimeUnit-) to the future chain.

In the case you're showing the original request is times out and the cache is populated with the partial results. Other users may want the cache to eventually populate with the entire results, but have the user request have a timeout to obtain the completed subset.

My hope is that with the JDK9 helper methods then either use-case could be trivially handled in the client code. There are probably some external utilities providing those features in JDK8, since its annoying gap in CF. Then I'm not sure whether direct support in the API is a significant benefit, and exactly what we'd want that to look like.

**Comment by ben-manes** [comment]
Re-reading your code and my response it looks like I error'd.

The case of partial results might make sense as N calls to the cache (e.g. `get(key)`) and then letting the consumer take the results that materialized within the timeout. The other case is a single bulk call where the a timeout is again on the consumer side and retrieves only the entries that were in the cache already. Most async clients (like spymemcached) return a `Future<Map>`, not a `Map<K, Future>` so partial results can't be obtained.

I think all of this could then be handled at the consumer side as follows
```java
AsyncLoadingCache<Integer, Integer> cache = Caffeine.newBuilder().buildAsync(k -> k);
List<Integer> keys = ImmutableList.of(1, 2, 3);
return CompletableFuture.supplyAsync(() -> {
  try {
    return cache.getAll(keys).get(1, TimeUnit.SECONDS);
  } catch (TimeoutException | InterruptedException | ExecutionException e) {
    throw new RuntimeException(e);
  }
}).exceptionally(e ->  cache.synchronous().getAllPresent(keys));
```

In JDK9 that would be simplified as
```java
AsyncLoadingCache<Integer, Integer> cache = Caffeine.newBuilder().buildAsync(k -> k);
List<Integer> keys = ImmutableList.of(1, 2, 3);
return cache.getAll(keys).orTimeout(1, TimeUnit.SECONDS)
    .exceptionally(e -> cache.synchronous().getAllPresent(keys));
```

Does that work for you?

**Comment by Dirk-c-Walter** [comment]
Yes, and your code snipets give me some ideas for improvements, thanks.

Admitedly I am mostly working with an odd duck data source, the overhead for a single item is huge, but it's constant as batch sizes go up, and it returns an async stream of results. So the effect is much like a list futures, one where I don;t know the key until I get the actual item. I think instead of the loader I will just have to populate the cache myself to get it working well with that.

there are plans to move to more async friendly systems at some point in the future, but that is likely after Java9.

**Comment by ben-manes** [comment]
Let me know if you think an `AsyncCache` (non-loading) would be useful. This can be emulated using `buildAsync(key -> null)`.

I didn't see the use-case so I've been hesitant to add it prematurely and add more API to learn. Instead I added all the expected methods needed for a non-loading version (e.g. `get(key, func)` so that extracting the API later would be seamless.

**Comment by Dirk-c-Walter** [comment]
That would be usefull for a few scenarios. I'm currently emulating such a thing by avoiding calls to get and just using getIfPresent, since I do want the loader for reloads. My usecase is  probably a pretty rare one though.

While we are wishlisting anyway; One other option that would be usefull is an integrated blacklist for known bad keys, currently that is handled by a second cache and just testing keys against that but something more integrated might be usefull.

the final thing on my wishlist would be for the AsyncLoadingChace to be able to return the estimated size directly instead of having to hop over the synchronous view.

**Comment by ben-manes** [comment]
My rule of thumb for an API is to find a balance so as to not throw in the kitchen sink and nudges towards the "best practices", while not restricting you from getting your task done. I'm sure Bloch has stated that much better, and his [tips](http://www.infoq.com/articles/API-Design-Joshua-Bloch) are pretty [great](http://landawn.com/How%20to%20Design%20a%20Good%20API%20and%20Why%20it%20Matters.pdf). By being a library it should be easy to adapt for building more targeted solutions, including other caches with APIs for solving a specific use-case.

The blacklist is a kitchen sink feature, which you solve as well as I could. A whitelist could be implemented more cheaply as a filter (bloom or cuckoo). A "bad key" might also be viewed as "negative caching" (caching a miss), which can be implemented using a sentinel value (often an optional). The use of smaller weights on the negative could be used as either unbounded (0 weight is never size evicted) or at a ratio (1 for negative, 10 for positive).

I wanted to keep the conceptual weight low, so I try to be compositional instead of bubbling everything up. Most usages of `put` are best replaced with loading through the cache, so valid but a red flag to justify each use. I thought of `estimatedSize` similarly, as usually you're only interested in them for statistics as the cache should manage the bounding. A nice benefit at Google was the ability to see lots of usages to understand how an API was consumed, and then adapt based on data instead of theory. So without seeing more code I'm still of the belief that most users shouldn't need it.

That might be a weak argument given `invalidate` is more likely to be needed, and its a hop away. Had there not be subtle differences then one would expect the api to be `AsyncLoadingCache<K, V> extends LoadingCache<K, CompletableFuture<V>>`. But since it doesn't restrict users while keeping the API small and easily understandable, it seemed like a good trade-off.

If I did introduce `AsyncCache` then I might bubble up some of those methods from the view for convenience. The argument would be symmetry, each interface remains small, and ease of use. Since `AsyncLoadingCache` is a bit of a one-off, adding a bunch more methods might make it feel too complex and wouldn't add to the power-to-weight ratio.

Sorry for the verbosity. I am very interested in discussions to improve the API while doing so carefully.
