### ISSUE TITLE
To understand the internal locking mechanism/ thread safety in Caffeine Cache

### ISSUE THREAD

**Issue by NancyGandhi** [ben-manes/caffeine#630]
- We need to understand the internal locking/syncing/thread safety mechanism implemented by Caffeine Cache to safeguard the get, put, evict and clear operations.

- We are curious to understand how caffeine cache internally takes care of the atomicity of the multiple put ,get, evict, clear operations in a multi-threaded environment.

- A pictorial representation of the working would be helpful.

- Is there any detailed documentation available around the same?

- Also, could you please let us know the internal data structure that caffeine uses.

**Comment by ben-manes** [comment]
Hi Nancy,

It might be helpful to read these short overviews of the internal data structures ([part 1](http://highscalability.com/blog/2016/1/25/design-of-a-modern-cache.html), [part 2](http://highscalability.com/blog/2019/2/25/design-of-a-modern-cachepart-deux.html), [slides](https://docs.google.com/presentation/d/1NlDxyXsUG1qlVHMl4vsUUBQfAJ2c2NsFPNPr2qymIBs), [design](https://github.com/ben-manes/caffeine/wiki/Design)).

At a high level, the cache is backed by a `ConcurrentHashMap` and tries to maintain similar semantics. It stores its policy metadata in as the entry's value in a `Node` class. An instance may reside on multiple doubly-linked lists. As those policies are not thread-safe, we use a pub/sub mechanism to record events into ring buffers and replay them under an exclusive lock with minimal blocking. When performing writes these are typically done via Map computations where the `Node` instance is synchronized on. The extra synchronization is because not all instance mutations require going through the map's locks.

> atomicity of the multiple put ,get, evict, clear operations in a multi-threaded environment.

- `Cache.getIfPresent` == `Map.get`: lock-free operation. It reads volatile fields and uses CAS to record into a ring buffer.
- `Cache.get` == `Map.computeIfAbsent`: lock-free optimistic read, but if absent or pending eviction then falls back to a `Map.compute` to load the value.
- `Cache.put`: This performed the map's `putIfAbsent`, which locks internally on a hashbin. If present then the node is synchronized on to update it outside of the map. This is equivalent to doing everything inside of a `compute` but was benchmarked to be faster.
- `evict`: This is performed under a single exclusive lock to only allow one thread to perform the eviction routine. The map is modified using `computeIfPresent`.
- `Cache.invalidateAll` == `Map.clear`: This acquires the eviction lock, iterates over all entries, and discards them. That was more efficient than iterating and the outer per-key remove method.

For most operations we get the same linearizability behavior as `ConcurrentHashMap` provides. That means that a remove will block on an in-flight compute until it finishes and work with its results. This is true except for `Map.clear`, where `ConcurrentHashMap` will block the `clear()` operation to wait for an in-flight `computeIfAbsent` call to finish and discard the new mapping. That occurs because their internal iterator can observe `ReservationNode` entries which are established to block other writes for that entry, but are not visible externally. Since the map's iterators do not expose the in-flight entry, Caffeine's does not discover it for removal. Therefore while `Cache.invalidateAll(keys)` is linearizable, we cannot make the same guarantee for `Cache.invalidateAll()`.

**Comment by ben-manes** [comment]
Another important aspect to highlight is `Cache.asMap()` provides richer user functionality, such as performing `Map.compute` atomic operations. The cache interfaces try to provide a narrow, opinionated view while `cache.asMap()` and `cache.policy()` offer escape hatches for additional functionality.

`AsyncCache` will have different linearization characteristics because it is a bounded `Map<K, CompletableFuture<V>>` where the future may be in-flight. Any assumptions you'd make writing such a map yourself should hold with Caffeine. In general you can think of this library as a bounded `ConcurrentHashMap` and, other than that detail on `clear()`, it should match your expected behavior.
