### ISSUE TITLE
Caffeine Cache vs AsyncCache nature

### ISSUE THREAD

**Issue by abhisheksurve45** [ben-manes/caffeine#632]
Hi @ben-manes , this is not an issue, just wanted to understand the working of both Cache and AsyncCache

Cache :

1. How does this handle thundering herd (afaik it does not)
2. Is cache.put(key, value) synchronous, does it obtain lock on entire cache or that specific key.

AsyncCache : 

1. What is the difference between cache.put(key, CompletableFuture.completedFuture(value)) and cache.synchronous().put(key, value)
2. cache.synchronous().put obtains lock on entire cache or just the key

**Comment by ben-manes** [comment]
I think the [faq](https://github.com/ben-manes/caffeine/wiki/Faq) might be helpful as going into more details regarding your questions.

> Cache: How does this handle thundering herd (afaik it does not)

It is built on top of `ConcurrentHashMap` which performs (roughly) per-entry locking.

> Cache: Is cache.put(key, value) synchronous, does it obtain lock on entire cache or that specific key.

The specific key, or more precisely the hashbin. That is fine-grained locking so typically there is no practical distinction.

> AsyncCache: What is the difference between cache.put(key, CompletableFuture.completedFuture(value)) and cache.synchronous().put(key, value)

They are identical. The view's implementation is exactly that,

https://github.com/ben-manes/caffeine/blob/1405bd0dee3fa55a6fb1b2b8fe5832c16f9ecb9b/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncCache.java#L545-L549

> AsyncCache: cache.synchronous().put obtains lock on entire cache or just the key

The hashbin (~per key).

**Comment by abhisheksurve45** [comment]
Hi @ben-manes 

So since Cache<K, V> uses a concurrent hashmap internally,  and since computeIfAbsent is an atomic operation, which means it can handle cache stampede if I understand it correctly. (https://stackoverflow.com/a/67452181)

So from the https://github.com/ben-manes/caffeine/wiki/Faq#bulk-loads section, I did not get why exactly AsyncCache<K, V> is preferable in terms of cache stampede.

Please let me know. Thanks.

**Comment by ben-manes** [comment]
Most usages are individual key lookups, `cache.get(key)`, so either is perfectly fine. A bulk load, `cache.getAll(keys)`, can offer a performance benefit by performing one query instead of multiple. In that case a synchronous cache cannot protect against a cache stampede due to using the hash table's locking. Instead placeholder entries must be inserted and the load performed outside of the hash table's locks, which is exactly how `AsyncCache` works.

> we can also leverage thread interrupt by giving timeout in Future.get?

You might prefer using `CompletableFuture.orTimeout(duration, unit)` instead of interrupts.

> Basically I want to mitigate the cache stampede issue, so not sure which one to use, Cache<K, V> or AsyncCache<K, V>.

Both work fine, with the caveat if using `getAll`. An async cache can be nicer for very long running computations because there is no possibility of collisions on the hashbin. It also allows for composing futures if the surrounding logic is reactive. The synchronous cache is nicer when just you want a bounded `ConcurrentHashMap`, which implies single key operations. As most Java code is written in a synchronous fashion, typically that style of cache is preferred for readability reasons.

**Comment by abhisheksurve45** [comment]
Got it. Thanks @ben-manes
