### ISSUE TITLE
All thread was blocked

### ISSUE THREAD

**Issue by RockyLOMO** [ben-manes/caffeine#634]
os: ubuntu-18.04.6-live-server-amd64   2core  4G 
jdk: 11.0.11+9-Ubuntu-0ubuntu2.18.04 
caffeine version: 2.9.3
`        return Caffeine.newBuilder()
                .scheduler(Scheduler.forScheduledExecutorService(Tasks.scheduler()));
` 
server qps: 5500+

5 client threads access cache that everything is ok, but when 10 client threads access cache that everything seems frozen.

![block](https://user-images.githubusercontent.com/1748083/146637231-556ecea6-35c6-4eb6-93a9-df9639a97b96.png)

Plz help, thx.

**Comment by ben-manes** [comment]
If you captured a thread dump (jstack) then we might be able to find the cause. We would need to know which thread holds the lock and why. You can email that privately.

The usual suspects are,
 - A custom eviction listener / cache writer performs some work on eviction and is stuck
 - A load / compute is stuck, causing the eviction to block on the same hash table lock
 - A Linux futex bug where the signal to unlock was lost, leaving the Java lock in a bad state

I am not aware of any library bug at this time, so my initial guess leans towards application or Linux issues as we've encountered them as the causes in the past. But we need more details to determine the root cause regardless.

**Comment by ben-manes** [comment]
Another case is recursion causing a stack overflow that failed to release the lock. See https://github.com/ben-manes/caffeine/issues/203#issuecomment-826264751. [JEP-270](https://openjdk.java.net/jeps/270) tried to handle this but it may not be full proof.

**Comment by ben-manes** [comment]
Closing due to lack of response. Please reopen if I can be of help.
