### ISSUE TITLE
 How do I know the remaining expiration time of the key

### ISSUE THREAD

**Issue by bootstrap2025** [ben-manes/caffeine#635]
Hi~
I can only judge whether the key exists according to the getIfPresent method, but how do I know the remaining expiration time of this key? If there is no such method, is there any plan to add this method?

**Comment by ben-manes** [comment]
To see if a key exists it is better to use `cache.asMap().containsKey(key)` since that won't be recorded as an access by eviction, expiration, or statistics.

See `cache.policy()` for [Policy.FixedExpiration](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/com.github.benmanes.caffeine/com/github/benmanes/caffeine/cache/Policy.FixedExpiration.html) and [Policy.VarExpiration](https://www.javadoc.io/doc/com.github.ben-manes.caffeine/caffeine/latest/com.github.benmanes.caffeine/com/github/benmanes/caffeine/cache/Policy.VarExpiration.html). They have per-key lookup methods for their remaining durations. They are not on the `Cache` interface because these types of methods are configuration dependent.

**Comment by bootstrap2025** [comment]
thanks
