### ISSUE TITLE
Trigger eviction / when does eviction happen?

### ISSUE THREAD

**Issue by cruftex** [ben-manes/caffeine#64]
As part of a benchmark I'd like to test the efficiency of the eviction algorithm. However, it seems Caffeine isn't strictly adhering to the `maximumSize` setting. E.g. one test runs with a random pattern of 1000 keys and a maximum cache size of 500 and yields a phenomenal hitrate of 97%. The benchmark is `CaffeineBenchmark.benchmarkTotalRandom1000_500` at https://github.com/cache2k/cache2k-benchmark

I tried with `cleanUp` but it seems not to trigger the eviction. Is there a way to force eviction? Any other ideas to do a reasonable efficiency comparison?

**Comment by ben-manes** [comment]
This is delegated to the executor to reduce response latencies by not penalizing the caller. As described further in [Testing](https://github.com/ben-manes/caffeine/wiki/Testing), you should use a same thread executor for unit tests (or simulations). It will then provide predictable synchronous behavior.

Note that Caffeine lazily begins tracking accesses when the cache first reaches 50%+ full. This was based on observing that many usages set a bounding as a safety net, but otherwise never reach it due to expiration and the low logical count. This can skew small traces but has negligible impact for large ones, the latter being more like a long-running server.

In latest `SNAPSHOT`, but not released, has the `initialCapacity` setting pre-allocates the sketch. This is in order to avoid the lazy resizing for weighted caches (e.g. byte sized) where the entry could cannot be easily inferred. That has the side effect of removing this skew from small traces.

**Comment by gruberjuliannama** [comment]
50%+ full. This was based on observing that many usages set a bounding as a safety net, but otherwise never reach it due to expiration and the low logical count. This can skew small traces but has negligible impact for large ones, the latter being more like a long-running server.

In latest SNAPSHOT, but not released, has the initialCapacity setting pre-allocates the sketch. This is ,, caches (e.g. byte sized) where the entry could cannot benthneme...?

**Comment by gruberjuliannama** [comment]
the benchmarks to measure cache efficiency on real world access patterns.

For each trace a Java class is available to read the trace into memory and to calculate basic metrics on it. The traces are represented as compressed file with 4-byte integers.

The original source of the trace Cpp, Glimpse, Multi2 and Sprite is from the authors of these papers:

J. Kim, J. Choi, J. Kim, S. Noh, S. Min, Y. Cho, and C. Kim, "A Low-Overhead, High-Performance Unified Buffer Management Scheme that Exploits Sequential and Looping References", 4th Symposium on Operating System Design & Implementation, October 2000.
D. Lee, J. Choi, J. Kim, S. Noh, S. Min, Y. Cho and C. Kim, "On the Existence of a Spectrum of Policies that Subsumes the Least Recently Used (LRU) and Least Frequently Used (LFU) Policies",?

**Comment by ben-manes** [comment]
Hi @gruberjuliannama,
I assume that you're replies were premature while you draft a comment. The [simulator](https://github.com/ben-manes/caffeine/wiki/Simulator) in this project includes support for both short and long traces, from a variety of academic sources.

**Comment by gruberjuliannama** [comment]
settings) {
    int events = settings.synthetic().events();
    switch (settings.synthetic().distribution().toLowerCase()) {
      case "counter":
        return counter(settings.synthetic().counter().start(), events);
      case "exponential":
        return exponential(settings.synthetic().exponential().mean(), events);
      case "hotspot":
        HotspotSettings hotspot = settings.synthetic().hotspot();
        return Synthetic.hotspot(hotspot.lowerBound(), hotspot.upperBound(),
            hotspot.hotOpnFraction(), hotspot.hotsetFraction(), events);
      case "zipfian":
        return zipfian(settings.synthetic().zipfian().items(), events);
      case "scrambled-zipfian":
        return scrambledZipfian(settings.synthetic().zipfian().items(), events);
      case "skewed-zipfian-latest":
        return skewedZipfianLatest(settings.synthetic().zipfian().items(), events);
      case "uniform":
        UniformSettings uniform = settings.synthetic().uniform();
        return uniform(uniform.lowerBound(), uniform.upperBound(), events);
      default:
        throw new IllegalStateException("Unknown distribution: "
            + settings.synthetic().distribution());    ?

**Comment by gruberjuliannama** [comment]
settings) {
int events = settings.synthetic().events();
switch (settings.synthetic().distribution().toLowerCase()) {
case "counter":
return counter(settings.synthetic().counter().start(), events);
case "exponential":
return exponential(settings.synthetic().exponential().mean(), events);
case "hotspot":
HotspotSettings hotspot = settings.synthetic().hotspot();
return Synthetic.hotspot(hotspot.lowerBound(), hotspot.upperBound(),
hotspot.hotOpnFraction(), hotspot.hotsetFraction(), events);
case "zipfian":
return zipfian(settings.synthetic().zipfian().items(), events);
case "scrambled-zipfian":
return scrambledZipfian(settings.synthetic().zipfian().items(), events);
case "skewed-zipfian-latest":
return skewedZipfianLatest(settings.synthetic().zipfian().items(), events);
case "uniform":
UniformSettings uniform = settings.synthetic().uniform();
return uniform(uniform.lowerBound(), uniform.upperBound(), events);
default:
throw new IllegalStateException("Unknown distribution: "
+ settings.synthetic().distribution());,,

2016-04-09 20:14 GMT+02:00 Ben Manes <notifications@github.com>:

**Comment by ben-manes** [comment]
Those are synthetic distributions. The trace files are available in the links on the before mentioned wiki page.

**Comment by gruberjuliannama** [comment]
Thanks, but I do not know how many of you are you, and you do not do a very
kycccen not known at verytassze and ate,, not really? thanks.

2016-04-09 21:13 GMT+02:00 Ben Manes <notifications@github.com>:

**Comment by ben-manes** [comment]
Okay, closing as this is going nowhere.

**Comment by gruberjuliannama** [comment]
so I can not and do not know you? That's it !!

2016-04-09 21:19 GMT+02:00 Ben Manes <notifications@github.com>:

**Comment by cruftex** [comment]
Ben, albeit the interference, your message came through.

> In latest SNAPSHOT, but not released, has the initialCapacity setting pre-allocates the sketch. This is in order to avoid the lazy resizing for weighted caches (e.g. byte sized) where the entry count cannot be easily inferred. That has the side effect of removing this skew from small traces.

So you mean that `initialCapacity(0)` will start eviction right away?

**Comment by ben-manes** [comment]
Please review my original reply. You want to specify a same thread executor. The rest was regarding the hit rate of small traces.

**Comment by cruftex** [comment]
Yes, I got that. Sorry my question was confusing. Corrected it:

So you mean that `initialCapacity(0)` will make the eviction algorithm to record & analyze the accesses from the beginning of usage?

**Comment by ben-manes** [comment]
You'd want to use `initialCapacity(maximumSize)`, as otherwise you are still forcing the sketch to resize to ensure its accuracy. When resized the sketch is empty (the frequency information is lost). As noted, this only applies to `SNAPSHOT` where the intent was for a different use-case that also serves to help in this scenario.

See [CaffeinePolicy](https://github.com/ben-manes/caffeine/blob/master/simulator/src/main/java/com/github/benmanes/caffeine/cache/simulator/policy/product/CaffeinePolicy.java) for a complete example.

**Comment by ben-manes** [comment]
Released 2.2.7 which includes the `initialCapacity` change, which will help your small trace simulations.

**Comment by cruftex** [comment]
Perfect timing. Thanks!
