### ISSUE TITLE
variable expiration causes periodic spike of cache miss.

### ISSUE THREAD

**Issue by takaaki7** [ben-manes/caffeine#642]
We configure caffeine with ttl in 7.5min ~ 12.5min (using `Expiry` to add jitter), but there are spike of cache miss in every minute.
Because the operation at cache miss is heavy, this causes unstable cpu load.

Is this expected behaviour? How to resolve?

Following metrics shows total gets count / hit count / miss count. Miss count is high at 30 sec every minutes.
<img width="1289" alt="スクリーンショット 2022-01-05 16 24 09" src="https://user-images.githubusercontent.com/8406540/148176959-c2046c04-6bc7-4a08-af95-0e585904f7f7.png">

Code
```java
  private final static Random rand = new Random();

  public MyStore() {
    CaffeineStatsCounter caffeineStatsCounter = new CaffeineStatsCounter(Metrics.globalRegistry, "group_cache");
    LoadingCache<Key, Group> cache =
        ((Function<Caffeine<Object, Object>, LoadingCache<Key, Group>>) builder ->
          builder
            .initialCapacity(1000)
            .softValues()
            .expireAfter(
              new Expiry<>() {
                @Override
                public long expireAfterCreate(
                  @NonNull Object key, @NonNull Object value, long currentTime) {
                  long expireAfterCreationNanoSec = 600 * 1000_000_000l; //10min
                  // should expire 7.5min ~ 12.5min
                  return (long) (expireAfterCreationNanoSec + expireAfterCreationNanoSec * 0.25 * (2 * rand.nextDouble() - 1));
                }

                @Override
                public long expireAfterUpdate(
                  @NonNull Object key,
                  @NonNull Object value,
                  long currentTime,
                  @NonNegative long currentDuration) {
                  return currentDuration;
                }

                @Override
                public long expireAfterRead(
                  @NonNull Object key,
                  @NonNull Object value,
                  long currentTime,
                  @NonNegative long currentDuration) {
                  return currentDuration;
                }
              })
            .maximumSize(160_000)
            .build(
              new CacheLoader<>() {
                @Nullable
                @Override
                public Group load(Key key) throws Exception {
                  logger.debug("reload cache for {} from source.", key);
                  return delegate.get(key);
                }
              })).apply(Caffeine.newBuilder().recordStats(() -> caffeineStatsCounter));
    caffeineStatsCounter.registerSizeMetric(cache);
    this.statsMemCache = cache;
  }
```

Cache size metrics
<img width="1434" alt="スクリーンショット 2022-01-05 16 40 00" src="https://user-images.githubusercontent.com/8406540/148180015-69328829-7aa4-457b-b488-99232708475b.png">

Cache eviction metrics. The only cause is `expired`.
<img width="1435" alt="スクリーンショット 2022-01-05 16 40 13" src="https://user-images.githubusercontent.com/8406540/148180056-71dd233d-7cd3-4734-a510-771247e0fd39.png">

**Comment by ben-manes** [comment]
I can't give an exact answer, only hints to look into.

You might want to use `refreshAfterWrite` to reload an active entry when stale but before it is expired (unusable). This hides latency spikes from cache misses as the stale value will be returned during the async reload, thereby avoiding a miss for a hot entry from blocking all the threads trying to load a fresh value. The cold entries would still fade away due to expiration due to not being accessed (one hit wonders). Currently this does not have a variable refresh option, but as only a subset of entries are hot it's typically okay despite that feature gap.

The cache batches work so possibly a spike is due to processing those events when the batch is handled. The entries are maintained in a [timing wheel](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/main/java/com/github/benmanes/caffeine/cache/TimerWheel.java) for an amortized O(1) priority queue, implemented with the resolutions of [1.07s x 64, 1.14m x 64, 1.22h x 32, 1.63d x 4, 6.5d x 1]. This should cause ~1s spikes if evenly distributed due to cascading causing the entries to be rehashed from the 1m bucket to 1s buckets, assuming there are no bugs. You are welcome to write more tests if you think that could be causing excessive batching and delaying the entry's eviction. The timestamps are validated during lookup so it does not impact misses and only when the cache's maintenance cycle turns the wheels, which causes it to evicts expired entries and updates the stats.

By default the cache triggers maintenance based on calling activity (reads and writes) and then schedules this cleanup on an executor (FJP's common pool). If the application has periodic behavior that causes spiked cache activity or if the FJP's threads are fully utilized then that can sometimes explain similar behavior. You could see is using `Caffeine.scheduler(Scheduler.systemScheduler())` and `Caffeine.executor(Runnable::run)` changes things at all.

**Comment by takaaki7** [comment]
Thanks, I'll try refreshAfterWrite.
But I'm concerned about expiration without jitter. We cache a lof of entries(about 40,000), and when we start up a new application process, tha cache is full instantly.
There is possibility that spike of async reload.

> The timestamps are validated during lookup so it does not impact misses

Yes if it is true, there is no problem. And as I read code and debug, it seems true, but there are miss spikes in fact...
The method I read carefully is `BoundedLocalCache.computeIfAbsent`. It seems asynchronous maintenance have nothing to do with spike of miss.

**Comment by ben-manes** [comment]
The variable refresh support requires finding the time and energy to generalize the implementation. You can workaround it though by simply returning a future that has a delayed start time, e.g. using delayedExecutor. This can provide the jitter but could skew load time stats. Similarly you can coalesce refreshes to batch the loads to make it more efficient. The cache just needs the future but you can control its execution.

The miss spikes seems odd since that is recorded on the caller, so a burst of activity would be needed. When the cache evicts shouldn’t impact that stat as it would take a miss, so it feels like an application behavior since you add that jitter which we don’t manipulate…

**Comment by takaaki7** [comment]
Using CacheLoader.asyncReload and adding jitter, coalesce refreshes sounds great! We'll try it.

> The miss spikes seems odd since that is recorded on the caller, so a burst of activity would be needed. When the cache evicts shouldn’t impact that stat as it would take a miss, so it feels like an application behavior since you add that jitter which we don’t manipulate…

I see. Actually I don't have any idea of what application implementation is the cause...
But refreshAfterWrite and asyncReload may be better alternative, I think this problem will be resolved.

Thank you for your comment!

**Comment by takaaki7** [comment]
Just for information, I detected the cause is application implementation bug. Incoming `Key`'s `equals()`,`hashcode()` varys in every minutes.

**Comment by ben-manes** [comment]
haha, that old chestnut! Good job figuring it out. 🙂
