### ISSUE TITLE
OpenHFT ChronicleMap

### ISSUE THREAD

**Issue by dlmarion** [ben-manes/caffeine#65]
Have you considered adding ChronicleMap to the benchmark?

**Comment by ben-manes** [comment]
It would be misleading because ChronicleMap does not evict (unbounded) and has the additional overhead of persisting off-heap. The unbounded ConcurrentHashMap listings are to show a baseline for comparing the overhead and scaling effects relative to the optimal. It uses a Zipf distribution (per Pareto principle) and 100% hits to demonstrate contention. However real-world may be different, e.g. higher penalties in some policies due to O(n) eviction. To keep the benchmark intellectually honest its important to limit the variables, test what can be done accurately and fairly, have an even playing field, and document my design trade-offs for transparency.

A benchmark of serializing off-heap data structures would minimize the serialization penalty to show the overhead of the implementation. That would be a fair comparison, but obviously the serialization is the dominant cost and could make the differences negligible in practice. A benchmark would need to show both small and large serializations in order to determine the effects, e.g. locking and fragmentation. So I can't imagine doing this fairly if my focus is on-heap.

I think serialization is a brute-force strategy and is not the right approach for off-heap. I'm a fan of instead of native bindings to the unmanaged data, which provides similar performance as on-heap data. For now that would require JNI overhead, but [JEP 191](http://openjdk.java.net/jeps/191) (Foreign Function Interface) would inline the calls to have minimal overhead. That compiled library vs serialization seems like a good trade-off given the few platforms and use-case of offheap. [Apache Mnemonic](https://github.com/apache/incubator-mnemonic) is spearheading this strategy and Accumulo might want to collaborate with them to help mature it. I've talked to their lead about some improvement ideas, but haven't had the bandwidth to dig in myself.

**Comment by dlmarion** [comment]
Fair enough, thanks for the quick response. I was thinking it might fit well into the 100% read use case. I have a use-case for a large static map that is loaded at application start up and read concurrently by many threads. Thanks also for the pointer to Apache Mnemonic, I had not heard of it.
