### ISSUE TITLE
make CompletableFutures first class cacheable items

### ISSUE THREAD

**Issue by overheadhunter** [ben-manes/caffeine#653]
Hi,

you [recently made us aware of this lib](https://github.com/cryptomator/cloud-access-java/pull/5#discussion_r775097066) for its atomic capabilities when dealing with long-running computations. In most cases they work great, but for CompletableFutures they can be improved.

## Context

Let's take a look at `AsyncCache#get(key, mappingFunction)`:

https://github.com/ben-manes/caffeine/blob/5e834f8fdcf3819a242da7a44d7e62c7fde0ab2a/caffeine/src/main/java/com/github/benmanes/caffeine/cache/AsyncCache.java#L74

https://github.com/ben-manes/caffeine/blob/5e834f8fdcf3819a242da7a44d7e62c7fde0ab2a/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncCache.java#L72-L77

As said before, this works great for any mapping function that returns `V`. So far, so good.

Now we're dealing with a provider that returns a `CompletableFuture<V>` itself. In other words, if we don't want to end up with a `CompletableFuture<CompletableFuture<V>>`, our mapping function would need to look something like this: `k -> provider.provideSomeFuture(k).join()`.

Instead of _chaining_ futures, we'd be _wrapping_ them in yet another future, which is kind of ugly. But luckily, there is an easy workaround:

## Current Solution

For this purpose, we can use this BiFunction mapper that is supposed to return a CompletableFuture:

https://github.com/ben-manes/caffeine/blob/5e834f8fdcf3819a242da7a44d7e62c7fde0ab2a/caffeine/src/main/java/com/github/benmanes/caffeine/cache/AsyncCache.java#L97-L98

We can just ignore the executor and yield the original future `asyncCache.get(key, (k, executor) -> provider.provideSomeFuture(k));`.

## Proposal

While this does work, it feels like second class support for CompletableFutures. Given that CompletableFutures are Java's primary API for async workloads (if not using 3rd party libraries), I believe it might be nice to have some `get` method that supports a single-argument mapping function `Function<K, CompletableFuture<V>>` (skipping the executor) with `flatmap`-like behaviour.

Furthermore, and this is important, since the original future is returned from the Cache, a failed future does **not** imply an unhandled exception is thrown by some `Function<K, V>`. Therefore logging a warning is misleading and may even lead to logging cascades when multiple of these AsyncCaches are chained.

## Alternatives

Instead of adding a completely new `flatGet` (sorry didn't come up with a less stupid name right now) method, I thought one could let the current implementation branch when encountering CompletableFutures, but that's a bad idea. In order to check its type, we'd have to wait for the result of the mappingFunction, which is what we wanted to avoid in the first place.

**Comment by ben-manes** [comment]
`get(k, bifunction)` isn't meant to feel second-class and ignoring the executor is perfectly fine. If someone does customize the Caffeine executor it does hint that they might want to pass that through, as they might be trying to avoid the default `ForkJoinPool.commonPool()` used by both. And as you noted, we'd need a new name due to type erasures causing a conflict.

An equivalent single-arg alternative is `asMap().computeIfAbsent(k, func)`. I don't recall why that implementation doesn't merely delegate to `get(k, bifunction)` as it should be identical (and the code is very similar), so I might dig into that over the weekend to see if it can be simplified.

I'd be hesitant to add a differently named method that was a very minor stylistic change, e.g. just to ignore this optional argument. That adds to the api surface, which as a different name would increase the conceptual weight. As users already have to think about difficult topics like concurrency, we try introduce minimal concepts, be very precise, and lean heavily on the familiar collections & concurrency apis. For every public method and class we run it through Josh Bloch's api design maxims ([list](https://www.infoq.com/articles/API-Design-Joshua-Bloch/), [video](https://www.youtube.com/watch?v=heh4OeB9A-c)). In your case my gut feeling is that it wouldn't carry its weight as such a minor difference.

The logging can be disabled by your logging library. Unfortunately a common mistake with futures is to only handle the success case, especially in fire-and-forget calls. As an exception is swallowed by the future instead of bubbling up to the thread's exception handler, often times those errors would go unnoticed until debugging the side effect of broken application behavior. It then makes sense for us to provide some friendly, minimal logging to help surface this for developers less familiar with concurrent programming, as experts can easily disable this as unnecessary noise. In logback that simply adding `logger('com.github.benmanes.caffeine.cache', ERROR)`.

I'm not sure if I followed the "with flatmap-like behaviour", as that sounded like an additional feature you might want that wasn't explained? Please let me know if I missed something and thank you for the api suggestions.

**Comment by ben-manes** [comment]
> I don't recall why that implementation doesn't merely delegate to `get(k, bifunction)` as it should be identical (and the code is very similar), so I might dig into that over the weekend to see if it can be simplified.

I reviewed the code and tests, and the difference is a subtle detail around the Map contract where it made more sense to copy-paste a few lines than parametrize a shared method (25 LOC). `Map.computeIfAbsent` allows a null value from the `mappingFunction`, but it really doesn't make sense for a future (which instead could resolve to holding a null value). The `get` method treats a null mapping as a likely programming bug and throws an `NullPointerException`. The null handling is also the reason why `AsyncCache<K, V>` does is not declared as `extends Cache<K, CompletableFuture<V>>` as an almost correct but just slightly different contract. Another minor impact is that it also alters the miss statistics: a future resolving to null is a miss, but is returning a null future one? From a pragmatic end-user perspective though the two are equivalent.

**Comment by overheadhunter** [comment]
> `get(k, bifunction)` isn't meant to feel second-class and ignoring the executor is perfectly fine.

All right, this works for us. In this case, please consider this merely as a request for improving the JavaDoc. Currently, it neither states that the executor can be ignored, nor is there any guarantee that the returned CompletableFuture isn't rewrapped. Knowing the implementation isn't enough. We need to rely on a contract. 🙂 

One possibility to improve documentation for this mapper is to make it an explicit type, e.g.

```java
/**
 * ...
 * <p>
 * The instance returned from the {@code mappingFunction} will be stored in this cache unless {@code null}. If the asynchronous
 * computation fails (i.e. the future completes exceptionally), the entry will be automatically removed from this cache.
 * <p>
 * ...
 *
 * @param mappingFunction the function to asynchronously compute a value
 */
<K, V> CompletableFuture<V> get(K key, AsyncMappingFunction<K, V> mappingFunction);

/**
 * A mapping function invoked atomically during cache misses.
 *
 * @param <K> Key type
 * @param <V> Value type
 */
@FunctionalInterface
interface AsyncMappingFunction<K, V> extends BiFunction<K, Executor, CompletableFuture<V>> {

	/**
	 * Maps the given key to a future value. While the async computation of the value may take some time, the future
	 * will be returned instantaneously.
	 * <p>
	 * <b>Warning:</b> as with {@link CacheLoader#load}, this method <b>must not</b> attempt to update any other mappings of this cache.
	 *
	 * @param key      The key
	 * @param executor An executor that may be used to run the computation
	 * @return The future value
	 */
	@Override
	CompletableFuture<V> apply(K key, Executor executor);
}
```

(Note that the wildcards are missing to narrow down the use of "correct" mapping functions. I.e. passing `(Number k, Object executor) -> CompletableFuture.completedFuture(Integer.valueOf(k))` to `AsyncCache<Integer, String>.get(...)` doesn't make any sense. But I may not understand the intend here, so feel free to ignore this suggestion.)

> I'd be hesitant to add a differently named method that was a very minor stylistic change, e.g. just to ignore this optional argument. That adds to the api surface, which as a different name would increase the conceptual weight.

That's perfectly understandable and I won't argue it. 👍

**Comment by ben-manes** [comment]
Unfortunately the new type suggestion is backwards incompatible as we’d either replace the method or the lambda could not infer the target as multiple matches.

I will review and clarify the JavaDoc, thanks!
