### ISSUE TITLE
[2.9.3] Ticker interface does not extend/implement the Ticker class hierarchy used by the Guava Test Lib - rendering no ability to "advance time" in unit testing

### ISSUE THREAD

**Issue by dlepe** [ben-manes/caffeine#658]
I'm currently using version 2.9.3 of the library. According to the wiki, I can use the FakeTicker implementation provided by the Guava Test Lib.

Unfortunately, I'm not able to cast the Guava `FakeTicker` instance into the Ticker class expected by the .ticker(...) method on the `Caffeine.newBuilder()`. Are there plans to integrate the Guava Test Lib into this library to allow the use of FakeTicker for testing time advancement?

`java.lang.ClassCastException: com.google.common.testing.FakeTicker cannot be cast to com.github.benmanes.caffeine.cache.Ticker`

**Comment by ben-manes** [comment]
I think what you missed is the method reference to adapt, as both are functional interfaces. The [Testing](https://github.com/ben-manes/caffeine/wiki/Testing) page has `.ticker(ticker::read)`. This is used by our unit tests as well.

(I'll update `Ticker` since its actually missing `@FunctionalInterface` for a compile enforced check)
