### ISSUE TITLE
Stats for the put operations are not computed.

### ISSUE THREAD

**Issue by mangatmodi** [ben-manes/caffeine#660]
We initialize the cache as following(kotlin)
```Kotlin
Caffeine.newBuilder()
        .scheduler(Scheduler.systemScheduler())
        .expireAfterAccess(config.ttl(), HOURS)
        .maximumSize(config.cacheSize())
        .recordStats()
        .build<FilterStoreKey, String>().also {
            CaffeineCacheMetrics.monitor(meterRegistry, it, "caffeine-cache")
        }
```

In the metrics we can see stats for `GET` but the `PUT` stats are always 0. I went through the implementation and I found that in the implementations of both `BoundedLocalCache` and `UnBoundedLocalCache`, we never update the `CacheStats` in the `put(...)` function. However we do so for the `get(...)`.

Is it intentional? If not, then I would happy to create a PR for fixing it.

**Comment by mangatmodi** [comment]
Hey @ben-manes 

Thanks for the reply. Maybe we should put this information in the wiki for the time being. I thought that our code had a bug when I saw `0` number for the `PUT`. I am also creating a ticket in the Micrometer project. It should be documented there too.

It sounds off that we have metrics on the `GET` and not on the `PUT`. If I am right cache stampede could still occur if we have cache miss, this will lead to more requests to the backing resource. I think caffeine has a genuine case where people  simply `PUT` data rather than bulk loading. 

In any case, I have already added `PUT` metric at our application.

**Comment by ben-manes** [comment]
> It sounds off that we have metrics on the GET and not on the PUT

Our CacheStats track the hit rate, load count, and evictions (via StatsCounter). We don't track individual methods like get, put, or explicit removal. This mirrors Guava's Cache, where we decided on more abstract intents rather than individual operations where it gets messy and a long list if exhaustive. I think that the higher level metrics make sense as our baseline and others are welcome to enrich them with more details.
