### ISSUE TITLE
Feature: LoadingCache with per-call-overridable CacheLoader, or version of load method with "extra" parameters for CacheLoader

### ISSUE THREAD

**Issue by tsutsu** [ben-manes/caffeine#661]
We have a cache where _some_ callers want the cache to attempt on cache miss to load from Redis, and then fall back to fetching/scraping from a web source. Other callers, however, want the cache to limit its cache misses to only attempting to loading from Redis; if the key is not found in Redis, then an exception should be raised. This is the same data, with both sets of callers expecting to their entries to warm the cache for the other. It's just that the callers have different limits for how much work they're willing to allow the cache to do.

Making this distinction requires passing parameters into the `CacheLoader` somehow. AFAICT, there is currently no part of the interface of a `LoadingCache` that allows transport of parameters through into the `CacheLoader`, without making those parameters part of the key. Naively, making the parameters part of the key means that the cache entries loaded by one load strategy, and the cache entries loaded by the other, will be segregated in keyspace, which defeats the point. (I say naively, because we might be able to slip data in by making our key class have fields that are ignored in computation of the key-object's `equals` and `hashCode` methods. If this is "the idiomatic way to do it", please let us know.)

We've tried using a regular manual `Cache` rather than a `LoadingCache`, and passing one or the other load strategy as a second mapping `Function` param to `cache.get` — but in doing so, we seemingly lose statistics collection. (We're currently relying on `io.prometheus.simpleclient_caffeine` to feed into Grafana dashboards; doing this loses us stats like `caffeine_cache_load_duration_seconds_sum`, `caffeine_cache_loads_total`, and `caffeine_cache_eviction_total`.) These metrics are critical for us, so we need to figure out a solution that keeps them.

**Comment by ben-manes** [comment]
> Making this distinction requires passing parameters into the CacheLoader somehow.

An traditional approach to this is a `javax.inject.Provider` which resolves at runtime the per-request instance. For example a servlet request might be tied to an authenticated user, but as the servlet handler is a singleton it cannot be injected the user directly. By using a dynamic lookup it can resolve and operate on the value. In dependency injection frameworks this would usually by done internally via a thread local scope. This technique would let you pass parameters into the `CacheLoader`, but only makes sense if that pattern fits your use-case and doesn't appear like a blatant hack.

`LoadingCache.get(key)`, `Cache.get(key, mappingFunction)`, and `Cache.asMap().computeIfAbsent(key, mappingFunction)` all dispatch to the cache's `computeIfAbsent` implementation. This should record statistics for the load. When glancing at the implementations I don't know why you would lose statistics since it seems identical and shouldn't differ in functionality or statistics handling. Can you confirm and provide a minimal test case?

**Comment by ben-manes** [comment]
The issue is your metrics binder. There is no reason for them to conditionalize these stats.

```
if(c.getValue() instanceof LoadingCache) {
    cacheLoadFailure.addMetric(cacheName, stats.loadFailureCount());
    cacheLoadTotal.addMetric(cacheName, stats.loadCount());
    cacheLoadSummary.addMetric(cacheName, stats.loadCount(), stats.totalLoadTime() / Collector.NANOSECONDS_PER_SECOND);
}
```

https://github.com/prometheus/client_java/blob/3568b2477c60dcde4d9380b666ad60a33d0f4208/simpleclient_caffeine/src/main/java/io/prometheus/client/cache/caffeine/CacheMetricsCollector.java#L156-L161
