### ISSUE TITLE
Can a caffeine cache or multiple caches cause an OutOfMemoryError when the application runs out of allocated RAM memory? 

### ISSUE THREAD

**Issue by maurice85** [ben-manes/caffeine#668]
I have a couple of questions about Caffeine caches.

 I can set the maximum number of entries a cache can contain using `setMaximumSize()`. I use different CaffeineManagers for different object types. The objects of each type can be stored in different languages. So next to that I make a cache for each available language. For each new cache i create i set the `maximumSize` to `10000`.

Because i have a lot of caches it could occur that the RAM memory that was allocated for the application that uses the caffeine caches is used up before all the caches have reached their maximum size of 10000. 

My first question is: What happens when the application has run out of memory and the application tries to add a new entry to any of the existing caches? Will this cause an `OutOfMemoryError` which crashes the application or will the cacheManager simply throw a `RuntimeException` instead?

My second question is about the following part in the description of the methode `maximumSize()`:

**As the cache size grows close to the maximum, the cache evicts entries that are less likely to be used again. For example, the cache may evict an entry because it hasn't been used recently or very often.**

Does that mean that it will actively look for entries that are about the expire? For instance, if the cache is almost full and two entries are about to expire. The first expires in 3 minutes, while the second will expire in one minute. In such a case, will the cacheManager decide to evict the second one because that one is the closest to its expiry time?

Thank you

**Comment by ben-manes** [comment]
> My first question is: What happens when the application has run out of memory and the application tries to add a new entry to any of the existing caches? Will this cause an OutOfMemoryError which crashes the application or will the cacheManager simply throw a RuntimeException instead?

It will throw an `OutOfMemoryError` and not attempt to do anything implicitly. To some extent you can safeguard against this by using soft references, but they are a well known performance gotcha due to adding GC pressure that while supported they are not recommended. Instead sizing your caches is better, perhaps using a second layer if helpful (e.g. memcached). Usually caches are tied to specific business logic that makes sizing straightforward. If you have the same domain but segmented, e.g. translations per language, then a composite key might let you share a single cache, e.g. (storyId, language) => translated story.

> Does that mean that it will actively look for entries that are about the expire?

No, but it will remove expired and reference collected entries prior to size eviction. This refers to using an eviction policy that  incorporates frequency and recency, as shown in our [hit rate analysis](https://github.com/ben-manes/caffeine/wiki/Efficiency). This will adapt in to favor LRU, LFU, or MRU based on the observed workload. The entry's remaining expiration time is not a consideration.

**Comment by asad-awadia** [comment]
@maurice85 you should keep the sum of all the max sizes such that they can all fit in ram. So User cache gets 1000, billing gets 50, api key cache gets 500 etc instead of one size for everyone
