### ISSUE TITLE
Kotlin Native Suspend Coroutine Support for Async

### ISSUE THREAD

**Issue by mhmtszr** [ben-manes/caffeine#673]
We love using **caffeine** as a local cache provider, but it can't support native Kotlin coroutines if it supports it would be great.

In the Kotlin we need to do like that:
```
Caffeine.newBuilder()
      .maximumSize(10000)
      .expireAfterWrite(3, TimeUnit.HOURS)
      .buildAsync { _, executor: Executor ->
          CoroutineScope(executor.asCoroutineDispatcher()).future {
              ....some suspend method calls...
          }
      }
```

@ben-manes

**Comment by ben-manes** [comment]
I think this is best done by the community, similar to Scala's [library](https://github.com/blemale/scaffeine) for adapting to their language idioms (`Option`, `scala.concurrent.Future`) and the Clojure [library](https://github.com/AppsFlyer/cloffeine) for theirs. These offer thin wrappers on top of the Java apis to avoid the noise of doing it manually, like your example using the coroutine converters has to do in each use-case. Since I am not as familiar with those languages, I think it is best for an expert in that language to write adapters and maintain them. The APIs are small and stable so this isn't much work.

For Kotlin, I recall Netflix musing about doing this in a PR thread on one of their projects (but of course not getting to it). I think it just comes down to someone knowledgeable enough to spend a few days to build it out.

**Comment by ben-manes** [comment]
Closing as out of scope for me, but I would encourage someone else to give it a try.

**Comment by sksamuel** [comment]
@mhmtszr see https://github.com/sksamuel/aedile as one possible approach
