### ISSUE TITLE
[Feature Request] Add weight eviction as first-class stat

### ISSUE THREAD

**Issue by drcrallen** [ben-manes/caffeine#68]
Instead of just having a count of entries, this ask is that the weight of evicted entries be added as an available stat.

**Comment by ben-manes** [comment]
Can you explain why this metric would be useful to you? Is it to gauge the average weighted size of an entry?

**Comment by drcrallen** [comment]
Tuning purposes. My intended use case is to look at the eviction velocity by weight to help tune cache sizes.

Typically a user sits down during a session and does some quantity of requests. The cache allows requests which they (or similar users) repeat avoid performing more expensive operations. (for my use case this actually functions in three tiers: a small local cache on heap, and a larger cluster-wide cache in memcached, and a "no cache found, recalculate it" layer). 

A key question is: "How much cache do I churn through per hour during peak usage?"

If I know how long is typical for a group of requests that I would hope would be cached (ex: one browsing session), then I can make sure the cache has the proper maximum weight to accommodate that quantity.

So lets say I know that normal eviction churn during peak is about 1GB / hr, and I know 90% of my users have a session length of 1 hr. To make sure my weight maximum can accommodate 90% of the browsing sessions (approximately), I'll need at least 1GB headroom in the cache. If I only give the cache 100MB, then I would expect it to only hold about 6 minutes of data, and therefore is probably way under-provisioned. If I give it 10GB of weight then I can expect to waste heap space keeping cache around that will probably never be used.

Mostly I'm interested in getting some sort of metric that can track "Is my weight upper bound right-sized?"

**Comment by ben-manes** [comment]
I think that's a very reasonable request.

It will look a little hacky interface-wise since by semver I can't change the API in a backwards incompatible manner. I'd like to wait until JDK9 var-handles before pushing the major version. So I'd have some hack on `StatsCounter` to include a no-op default method and add a new constructor to `CacheStats`. Then in v3 I'd make them required as an API break that would effect almost no one.

If you have other metrics you'd like to see added let me know. I think `putCount` was a common request.

If you're able to gather more insight into #67 as well, I'd appreciate it. I can't reproduce an issue in a realistic scenario, only when the system is dedicated towards inserts with an intent of destroying the cache. I'm not convinced its the queue, which has mostly been used as fodder, but its a known backlog item.

I probably won't have the bandwidth to work on a new queue for a little while. I'd want it to be array-based with a small initial footprint (e.g. 16e) and a cap (e.g. 1024), and probably spin wait trying to reschedule. That would probably be done using some link chunking to let the consumer follow on a resize. I'm a little fearful of a spin wait by assuming that the consumer is prioritized quickly. In JDK9 the `onSpinWait()` hint to generate an x86 `pause` instruction would help alleviate some of my fears.

**Comment by drcrallen** [comment]
Sounds good, thanks.

Note that my current best method for right-sizing the cache is to spin-up/reboot a node and monitor `cache.policy().eviction().weightedSize()` over time until it hits its limit. This does *not* give good live monitoring of cache, but it does give me some ballpark for expected cache performance.

**Comment by ben-manes** [comment]
yep, monitoring is critical.

`evictionCount` is defined as not including manual removal. A weighted version would naturally parallel that. Would you expect to see a `removeCount` and weighted version added?

```java
/**
 * Returns the number of times an entry has been evicted. This count does not include manual
 * {@linkplain Cache#invalidate invalidations}.
 *
 * @return the number of times an entry has been evicted
 */
```

**Comment by drcrallen** [comment]
```java
  /**
   * Returns the sum of weights of evicted entries. This total does not include manual
   * {@linkplain Cache#invalidate invalidations}.
   *
   * @return the sum of weights of evicted entities
   */
  @Nonnegative
  public long evictionWeight() {
    return evictionWeight;
  }
```

Something similar to the above would fit the use case. Since weights can be up to `Integer.MAX_VALUE`, I'm not sure what the best way to account for `long` overflow in a long-running service would be.

**Comment by ben-manes** [comment]
okay, great. I just wanted to make sure about manual removals in case that would cause a surprise. I can add or keep ignoring that, based on preferences.

Since `Long.MAX_VALUE / Integer.MAX_VALUE = 4,294,967,298` I suspect that it is not much of an issue.

**Comment by ben-manes** [comment]
While your asking, any other stats you think would be useful?

I've seen requests on Guava for `putCount`. The intent is to nudge users to load through the cache, but arguably good monitoring trumps API hints.

If added, then I'd expect to probably add `removeCount` and `removeWeight` as the parallel for the automatic load / eviction stats.
