### ISSUE TITLE
Cache stats on asMap().compute / Caffeine 2.9.3

### ISSUE THREAD

**Issue by stevekradel-okta** [ben-manes/caffeine#689]
Hello!  I have a "primary cache" of type `Cache<String, SomeMetadataHolder>` that wraps a secondary cache of type `LoadingCache<String, String>` ; the intent here is to take advantage of asynchronous `LoadingCache` refresh operations to detect if content is slightly stale, despite the entry in the "primary cache" entry not necessarily nearing expiration; and the primary cache is grossly polymorphic and cannot itself be a `LoadingCache`.  The primary cache is invoked in this form:

```java
return primaryCache.asMap().compute(key, (k, value) -> {
  if (value != null && value.etag.equals(loadingCache.get(k)) {
    return value;
  }

  return slowComputation(otherStuffInClosure);
}
```

While the Caffeine javadocs imply that stats will be updated for the `compute` flavors of map methods, I've observed that everything counts as a cache miss.  The objects in this cache are immutable and don't override `equals`, which is to say that identity comparison is expected and okay.  So, there arise a couple questions, I guess:
- Will Caffeine's cache admission algorithms still work in this case, or will every `compute` result count as a new cache entry?
- Should I front-end this operation with `getIfPresent` (at possible risk of doubling the hit count on each present key)?
- Am I missing some way to record a `compute` operation that returns the second parameter of its function as a hit?

**Comment by ben-manes** [comment]
Stats can get confusing, so you should treat ours as best effort. When you want different behavior then you can augment them with your own metrics.

A `compute` is always a write into the cache, even if the same value. Currently the wrapper to the function assumes that if it is called then it must be a cache miss and records the load success/failure times. That makes sense for a computeIfAbsent. For a `compute` and `computeIfPresent` I am not sure what one would expect, so this was a reasonable default. I wouldn't be opposed to something more nuanced, but (only thinking about this briefly) all variants seem confusing. The entry is modified and loaded, but is that a hit? Or should that only record the load and not impact the hit/miss metrics? The non-loading Map methods like `replace` have no effect on the stats.

https://github.com/ben-manes/caffeine/blob/e1119b96a3167404fc8904ab6f7f9fdc85993ab1/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalCache.java#L155-L181

Since this only impacts how we record external metrics and not how the eviction algorithms view the cache, I don't think you have to worry regarding your questions. It is a singular entry and the policy will consider it as a hit for frequency and recency. I think the only issue is whether we can make the stats better here, or if you need to maintain your own metrics instead.

**Comment by stevekradel-okta** [comment]
Thank you Ben for your thoughtful reply.  I'm happy to incorporate a manually-updated `ConcurrentStatsCounter` into this pattern, and now only wish for a way to configure the cache with a way to return stats to interested parties (e.g. `CaffeineCacheMetrics` which collects both stats and other cache properties) while suppressing the cache's standard recordkeeping.

It's great to know that the frequency/recency statistics for the requested keys will still be effective with the `asMap` style; my "least surprise" state would have been that non-null, identity-equal return values from `compute` would count as a hit, so this set off concerns that treating the cache as a map might be the wrong direction in general.  I'll close this comment and may later open another for separating whether there are (somewhere) stats associated with a Cache from whether or not the Cache itself records them.

**Comment by ben-manes** [comment]
I’ll look into improving this behavior. There are various usages like async to consider, but I agree your proposal is a more reasonable expectation.

Treating the cache as a map is fine and correct. I spent less time thinking through stats compared to everything else.

The eviction policy only cares about recency and frequency of a key, and how many read events occurred over a sample period. The latter is a pseudo hit rate over a period for a hill climber optimization. An update might be treated as a read event as the entry was accessed, even if modifying may not always be a true hit.

**Comment by ben-manes** [comment]
@stevekradel-okta What do you think is reasonable for `merge(key, value, (v1, v2) -> v3)`?

**Comment by ben-manes** [comment]
Thanks @stevekradel-okta. I started to sketch out the [table](https://docs.google.com/spreadsheets/d/1L_4rC5_aaVNi5Wdbb1jaebYEBOFtFJ3yl4zacllLVk8/edit#gid=0) of Map operation to stats. You are welcome to help me on that and edit, if interested.

In some cases computes are used for removals. A case like `Map.remove(key)` or `Map.replace(k, v)` are not tracked, so a compute to remove an entry might not make sense for hit/miss rates (and maybe even load success/failure). See for example the [Coherence integration](https://github.com/oracle/coherence/pull/60/) which uses computes for their synchronous listeners.

Since use-cases vary so much for Map operations, this is why I refer to our stats as best effort. I think we can make the defaults better, but probably not fit all scenarios.
