### ISSUE TITLE
Make REPLACED eviction cause stats available without registering a removal listener

### ISSUE THREAD

**Issue by leonard84** [ben-manes/caffeine#700]
Hi, we recently added a cache, and use the `StatsCounter` interface to monitor it's metrics. However, we noticed that it doesn't show the expected `REPLACED` stats, they were in fact 0. 

Looking at the code, it seems that `RemovalCause.REPLACED`/`RemovalCause.EXPLICIT` is never passed to the `StatsCounter#recordEviction(int, RemovalCause)` method. I would assume, so as to not change the old methods behavior.

```java
  default void recordEviction(@NonNegative int weight, RemovalCause cause) {
    // This method will be abstract in version 3.0.0
    recordEviction(weight);
  }
```

could be changed to
```java
  default void recordEviction(@NonNegative int weight, RemovalCause cause) {
    // This method will be abstract in version 3.0.0
    if (cause.wasEvicted()) {
        recordEviction(weight);
    }
  }
```
to keep the old behavior.

**Comment by ben-manes** [comment]
In the wiki I tried to [clarify](https://github.com/ben-manes/caffeine/wiki/Removal) the terminology, 
> * **eviction** means removal due to the policy
> * **invalidation** means manual removal by the caller
> * **removal** occurs as a consequence of invalidation or eviction

Guava's [StatsCounter](https://github.com/google/guava/blob/e7b86f4767ad1cfa58c5bcad1f7ca9358d52ee45/guava/src/com/google/common/cache/AbstractCache.java#L183-L188) merely has `recordEviction()` and that was extended (during 2.x) based on user feedback to include the weight and cause. However it is still an eviction and not a more generic `recordRemoval` call, and if decided to broaden it then the more generic method would be appropriate for consistency and compatibility.

However, the philosophy for statistics is not to capture everything (some want explicit puts, for example). Instead it is to capture the most common cases and metrics that only the cache knows like hit rate and the miss penalty. We then encourage adding your own metrics for anything additional which you might find useful, like those explicit removals. If there are metrics that only the cache can provide an does not then it should be considered, but otherwise for simplicity deferring to the user's best judgement for what else they need keeps the API from exploding into many (seemingly reasonable) use-cases.

**Comment by leonard84** [comment]
Ok makes sense.
