### ISSUE TITLE
BoundedLocalCache can not StatsCounter

### ISSUE THREAD

**Issue by ycy1991** [ben-manes/caffeine#701]
Why can't cache information when the cache is bounded
![image](https://user-images.githubusercontent.com/16506338/164971153-b1a8d8d1-22bd-488c-a0cb-825b0529cab5.png)
Are there any design considerations

**Comment by ben-manes** [comment]
`BoundedLocalCache` is abstract and code generated subclasses add fields and override (e.g. see `SSS` in the jar). As there are many possible feature configurations that each need different data structures, this was an attempt to reduce the memory overhead to only what is used by the application. That is particularly useful for cache entries since there may be millions of them so the overhead adds up. We try to be conscientious about these things if low effort to manage.

**Comment by ycy1991** [comment]
Thank you. Later, combined with the source code, it is inferred that colleagues configured multiple caches
