### ISSUE TITLE
how Caffeine work

### ISSUE THREAD

**Issue by fizz12344321** [ben-manes/caffeine#705]
Hi Ben, i know you are one of tje contributor on the Caffeine cache, i try using it instead of ehcache in cache layer 2 of hibernate. So i read in github, that it used ConcurrentLinkedHashMap. i don't know why do you choose it, and it may be handle thread safe problems when a lot of requests, Caffeine has three strategies for value eviction — size-based, time-based, and reference-based :D is it right ? thank you

**Comment by ben-manes** [comment]
Caffeine's differentiators are its high concurrency, high hit rate, and async apis. Older caching libraries use classic algorithms that were designed before multi-core machines were commonplace. They generally focus on ease of use and features. For example hotels.com ([article](https://medium.com/expedia-group-tech/latency-improvement-with-in-memory-caching-using-caffeine-34713ec77446)) improved their latency with an added benefit of significantly reduced costs. Similarly for doordash ([article](https://doordash.engineering/2022/05/03/how-we-applied-client-side-caching/)) where they needed to maintain performance and wanted to reduce their operational costs. Others have similar stories ([LinkedIn](https://engineering.linkedin.com/blog/2017/07/building-the-activity-graph--part-2), [Atlassian](https://www.atlassian.com/blog/technology/aws-scaling-multi-region-low-latency-service), [Allegro](https://blog.allegro.tech/2017/01/estimating-the-cache-efficiency-using-big-data.html), [Outbrain](https://medium.com/outbrain-engineering/oh-my-guava-we-are-moving-to-caffeine-99387819fdbb)). If an alternative library is serving you well then that's great and otherwise I hope Caffeine serves you well. Hope that answers your question.

**Comment by fizz12344321** [comment]
thank you
