### ISSUE TITLE
Is there a way to conditionally put() if present without a race condition?

### ISSUE THREAD

**Issue by MrCreosote** [ben-manes/caffeine#706]
Firstly, thanks for the great work on Caffeine.

Essentially I want to do something like this, where `cache` is a `Cache<String, String>`, `newval` is a `String`, and `predicate` is a `Predicate<String>` (which may have access to `newval`):

```
final String val = cache.getIfPresent(key);
if (val != null && predicate.test(val) {
     cache.put(key, newval);
}
```

IOW, an API like
```
cache.putIfPresent(K key, V value, Predicate<V> predicate)
```
or
```
cache.putIfPresent(K key, V value, BiPredicate<K, V> predicate)
```

Where the V value to the predicate is the current value in the cache.

I don't think there's any way to do this other than the first block above which is subject to race conditions, but I thought I'd ask.

Thanks!

**Comment by ben-manes** [comment]
The `Cache.asMap()` view is really nice here,

```java
cache.asMap().computeIfPresent(key, (k, oldValue) -> {
  return predicate.test(oldValue) ? newValue : oldValue;
});
```

Does that help?

**Comment by MrCreosote** [comment]
My experience is with the [Guava cache](https://github.com/google/guava/wiki/CachesExplained#inserted-directly) where they say some sort of scary things about using the `asMap` view (especially in my case where I'm also using the `get(key, fn())` cache method to populate the cache), but it sounds like that's groovy with Caffeine, so I'll give that a go. Thanks!

**Comment by ben-manes** [comment]
Guava's cache was written before the Java 8 compute methods. The main warning was that in Java 5 style `Map` there was loading, so we wanted to highlight that `Map.get` == `Cache.getIfAbsent`, not `LoadingCache.get`. Then it's all the other bits about avoiding racy logic as most developers don't think about atomicity like you did. Unfortunately the attempt to add Java 8 compute methods to their cache is very problematic (buggy, slow), so given the lack of maintenance it wasn't recommended. Doubly so since some use old versions of Guava and would inherit the non-atomic default in `Map`, so just lots of issues.

Caffeine is Java 8-based and those computes are first class. The `Cache.get(key, fn())` case is just a delegate to `asMap().computeIfAbsent`. If you run into any issues or have further questions, please feel welcome to reopen.

**Comment by MrCreosote** [comment]
Awesome, thanks for the detailed answer. And thanks for not stackoverflowing my nooby question.

**Comment by ben-manes** [comment]
Oh, one reason for Guava's wording was that CacheBuilder was a replacement for MapMaker. We inherited that class and tried to overhaul it to incorporate CLHM's policy approach. I would have preferred starting from scratch and Caffeine reflects my original proposal, but it was a 20% activity so a redo was too high risk for the Guava team. Anyway, in that class the `Map.get` had a quiet side effect of loading the entry on a miss which was very useful but too implicit. The documentation was written with an eye towards migrations and we described our changes in this [slide deck](https://github.com/ben-manes/concurrentlinkedhashmap/blob/wiki/ConcurrentCachingAtGoogle.pdf). The video may still be somewhere, I had a conflict and Charles presented it for both of us at StrangeLoop (2011 I think).
