### ISSUE TITLE
Value validation before return

### ISSUE THREAD

**Issue by ejwinter** [ben-manes/caffeine#707]
I was looking for a way to run a `validate` predicate on a cached item before the cache returned it.  The quintessential example would be a check if the item has expired through some business logic.  Hopefully, a lightweight check.

If the predicate returns false then that key/value would be invalidated.

I expect this may have been considered but was reject with good reason but I couldn't find anything readily in closed items.

```java
  cache = Caffeine.newBuilder()
                .expireAfterWrite(30, TimeUnit.MINUTES)
                .validate(cachedInstance -> !cachedInstance.isExpired())
                .build(key -> {
                        return client.getSecret(key);
                 });
```

Thanks for the great library!

**Comment by ben-manes** [comment]
In the particular case of expiration, you could use our `expireAfter(Expiry)` to allow entries to have different durations. The cache does validate that the entry is usage before returning (not expired, not GC'd weak/soft value). In those cases proactively trigger internal maintenance for the eviction policy to perform its cleanup, where additional data structures let this be O(1). We don't callback to invalidate it directly, though, since there are race conditions like a race causing the entry to be resurrected by another write.

Since the API tries to feel like an extension to Java Collections, a cache is intended to be an implementation detail of a class. Like a `ConcurrentHashMap` if not directly supported then your code should have good, atomic options to handle this customization without much effort. It is a little more code, but also very explicit and your implementation probably only has 1-3 lookups so easy to have private helper methods and encapsulate the complexity. In this particular case that might then be,

```java
public Secret get(Key key) {
  var secret = cache.get(key);
  if (isValid(secret)) {
    return secret;
  }
  // invalidate this stale instance, not if replaced since
  cache.asMap().remove(key, secret);
  // compute, must be okay if cachable
  return cache.get(key);
}
```

**Comment by ben-manes** [comment]
Closing, but reopen if you have further comments
