### ISSUE TITLE
about Caffeine use concurrency

### ISSUE THREAD

**Issue by HelloTo4x** [ben-manes/caffeine#710]
Hi, i have a question, when Caffeine use Concurrency for multi thread, does it need lock to avoid Race condition

**Comment by ben-manes** [comment]
Caffeine is built on top of `ConcurrentHashMap`, which offers lock-free reads and fine-grained locking on writes. The eviction policies maintain their own state such as recency order (LRU list), which traditional approaches require a lock on read (e.g. a synchronized `LinkedHashMap`). Instead of blocking the thread to perform a tiny amount of work, we schedule the work in lock-free ring buffers and have defer to another thread to drain the buffers and process that work under a lock.

An overview of the design is is written up in,
   * [Design of a Modern Cache: part #1][modern-cache-1], [part #2][modern-cache-2] ([slides][modern-cache-slides])
   * [Design wiki page](https://github.com/ben-manes/caffeine/wiki/Design)
   * [Internal JavaDoc](https://github.com/ben-manes/caffeine/blob/143efe110e8d8dedc40f6a44b5264f817e3ff41b/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L106-L192)

[modern-cache-1]: http://highscalability.com/blog/2016/1/25/design-of-a-modern-cache.html
[modern-cache-2]: http://highscalability.com/blog/2019/2/25/design-of-a-modern-cachepart-deux.html
[modern-cache-slides]: https://docs.google.com/presentation/d/1NlDxyXsUG1qlVHMl4vsUUBQfAJ2c2NsFPNPr2qymIBs

**Comment by HelloTo4x** [comment]
thank you so much
