### ISSUE TITLE
BoundedLocalCache::computeIfAbsent nested call may cause deadlock

### ISSUE THREAD

**Issue by MrLiuzy** [ben-manes/caffeine#712]
Hi, ben-manes @ben-manes 
**I find a flaw of  call BoundedLocalCache::computeIfAbsent nested when the task queue full may cause deadlock.** 
**PerformCleanupTask hold the evictionLock then acquire the ConcurrentHashMap$Node monitor**
**BoundedLocalCache::computeIfAbsent nested call hold the ConcurrentHashMap$Node monitor, when task queue full, it acquire evictionLock**
**if the ConcurrentHashMap$Node is same then deadlock arise**

![image](https://user-images.githubusercontent.com/17588331/169268835-630933e2-455b-449a-a676-8cd72845339e.png)

**I write a demo to reproduce this problem**
```java
public class CaffeineDeadLockTest implements Expiry<Object, CacheObj> {
	private Cache<Object, CacheObj> cache = Caffeine.newBuilder().maximumSize(1).expireAfter(this).recordStats().build();
	@Override
	public long expireAfterCreate(Object key, CacheObj value, long currentTime) {
		return TimeUnit.MILLISECONDS.toNanos(value.seconds);
	}
	@Override
	public long expireAfterUpdate(@NonNull Object key, @NonNull CacheObj value, long currentTime, @NonNegative long currentDuration) {
		return currentDuration;
	}
	@Override
	public long expireAfterRead(@NonNull Object key, @NonNull CacheObj value, long currentTime, @NonNegative long currentDuration) {
		return currentDuration;
	};
	public Object iocs() {
		return cache.get(new Key("iocs"), (k)->{
			//模拟嵌套调用
			//Simulate nested calls
			rpcs();
			return new CacheObj("iocs", 2, "", "", 1, "");
		});
	}
	public Object rpcs() {
		return cache.get(new Key("rpcs"), (k)->{
			return new CacheObj("rpcs", 2, "", "", 1, "");
		});
	}
	static class Key {
		private String key;
		public Key(String key) {
			this.key = key;
		}
		@Override
		public boolean equals(Object obj) {
			return this.key.equals(((Key)obj).key);
		}
		@Override
		public int hashCode() {
			//让key在ConcurrentHashMap中计算出来的数组下标相同
			//Make the array index computed by the key in ConcurrentHashMap the same 
			return 1;
		}
		@Override
		public String toString() {
			return key;
		}
	}
	
	public static void main(String[] args) throws IOException {
		/* caffeine-2.8.8
		 * reproduce deadlock of nested call Cache.get(key,Function) by the following steps
		 * 
		 * nested call:
		 * Cache.get(key,()->{
		 * 		Cache.get(key2,Function);
		 * 		return xxx;
		 * })
		 * 
		 * Step 1. add a breakpoint at BoundedLocalCache line 904(data.computeIfPresent)
		 * hang the Thread wait until Step 2 is complete, then going on
		 */
		CaffeineDeadLockTest test = new CaffeineDeadLockTest();
		test.rpcs();
		test.iocs();
		ThreadUtil.sleep(4);
		new Thread(()->{
			test.iocs();//Step 2. add a breakpoint at this line, wait for 10s, then going on 
		}).start();
		new Thread(()->{
			//fill the task queue
			int maxSize = 128 * Runtime.getRuntime().availableProcessors();
			for(int i=0;i<maxSize;i++) {
				test.rpcs();
				ThreadUtil.sleep(4);
			}
		}).start();
		System.out.println("end");
		System.in.read();
	}
}

**Comment by ben-manes** [comment]
Caffeine is built on top of `ConcurrentHashMap` and this is a subtle but important design restriction `compute` methods. I identified this flaw in the [2011 preview](https://markmail.org/message/bn2nmbslyzoibfmy) and the regression in [2014 JDK8](https://markmail.org/message/dixewqcvbbs5gzi2). In jdk9 the implementation of `computeIfAbsent` now throws an `IllegalStateException` when it can detect a recursive write, instead of the livelock failure that you experienced.

In Caffeine's javadoc we state,
> Warning: as with [CacheLoader.load(K)](https://www.javadoc.io/static/com.github.ben-manes.caffeine/caffeine/2.8.8/com/github/benmanes/caffeine/cache/CacheLoader.html#load-K-), mappingFunction must not attempt to update any other mappings of this cache.

The FAQ describes a [workaround](https://github.com/ben-manes/caffeine/wiki/Faq#recursive-computations) by decoupling the computation from the map so that locking is performed outside of the map operation.

The 2011 discussion did lead to the `ConcurrentHashMap#computeIfAbsent` to include an implementation warning, which was not part of the interface's contract.
```java
* @throws IllegalStateException if the computation detectably
*         attempts a recursive update to this map that would
*         otherwise never complete
```

Interestingly when adding the method to `HashMap` they originally thought it was safe and that the restriction was needed only for concurrent data structures. It was quickly discovered that recursive writes would corrupt the hash table when it triggered a resizing, so in jdk9 that too detects and fails fast.

I hope that helps. Let me know if you have any questions.

**Comment by ben-manes** [comment]
Rereading and I see that your code is recursive, but the description is regarding a blocked eviction. That happens when the eviction’s victim entry resides in the same hashbin locked by a long running computation. The collision causes the write buffer to fill and blocks writes until this is cleared up. It is a violation of the javadoc (Caffeine, CHM) that warns against that. A log warning was added in the recent releases if detected (https://github.com/ben-manes/caffeine/commit/0620efd8bebda44f54b84a3020cf6a9fcca30930). The simplest solution is the same - decouple the computation from the map’s lock. AsyncCache makes this easy.

**Comment by MrLiuzy** [comment]
@ben-manes Thanks for your reply. I think it‘s a good idea to print a warning log. 
In my case, the code ran correctly for more than 2 years before the deadlock issue occurred this month. Therefore, it's a flaw that is difficult to found and reproduced
So, what do you think if we could provide a configuration method that sets whether to throw an exception when a recursive call is detected. This is a strong reminder to prevent developers from ignoring the warning log.
Like this:
`Caffeine.newBuilder().exceptionWhenRecursive(boolean)`
