### ISSUE TITLE
A lot of unreachable cache object found when using caffeine 2.9.3 (expireafterwrite)

### ISSUE THREAD

**Issue by renyingxin** [ben-manes/caffeine#719]
caffeine Version: 2.9.3
JAVA version: 8

Hi, we are new to caffeine and encounter a memory problem, we are using expireafterwrite, with Weigher to controll the total memory usage
1、we find we can hold about 9000 live cache object, but we found much more unreachable cache object than expected(80,000)
2、from the dump file, we check that the live cache objects are hold by com.github.benmanes.caffeine.cache.BoundedLocalCache$UpdateTask (also found 850+ unreachable UpdateTask )

can you provide any idea to check about this problem, thanks~

**Comment by ben-manes** [comment]
An unreachable object is eligible for garbage collection, so you might encounter a `GC Overhead Limit Reached` error. In my experience that means that you are generating churn at too high a rate, creating very large objects, spending excessive time spent on finalizers, or exhausting the heap due to soft references. In a generational collector, objects living in the young gen are very quick to evacuate but behavior forcing rapid promotion to the old gen can cause excessive GC'ing and failures. This differs from a typical memory leak where objects are mistakenly held (strong references), fill the heap, and starve the system of available resources. Instead here you have somehow overwhelmed the GC, indicating some pathological behavior has blocked it from running correctly. The instance counts are a side effect of that, not the root cause, since they are ready to be swept up.

**Comment by renyingxin** [comment]
Sorry delay to reply... we found cacheObject may be triggered by too many concurrent load, we will try to find the root cause and fix it , really appreciate for your reply~
