### ISSUE TITLE
Question about benchmark table:

### ISSUE THREAD

**Issue by guidomedina** [ben-manes/caffeine#72]
Hi @ben-manes 

At your benchmark table, can I assume that the "Compute" performance is referring to the following operations?

- `ConcurrentHashMap<K, V>.computeIfAbsent(key, loadingFunction)`
- `LoadingCache<K, V>.get(key)` with a predefined loader function.

I'm using it to update a price concurrent map represented as the following:

```
  final LoadingCache<Integer, ConcurrentMap<Integer, Queue<PriceEntry>>>
    bidPricePools = newBuilder().build(priceId -> newConcurrentMap());

  final LoadingCache<Integer, ConcurrentMap<Integer, Queue<PriceEntry>>>
    offerPricePools = newBuilder().build(priceId -> newConcurrentMap());
```

The `LoadingCache` integer key is the price source ID and the `ConcurrentMap` integer key is the instrument ID (i.e.: EURUSD, EURGBP, USDGBP, etc) I have several price sources and each can stream thousands per second so I'm forced to get the newly created or existing `ConcurrentMap` atomically.

The `ConcurrentMap` is of no concern as I only put/get on it, assume there is neither expiration nor size bounded.

**Comment by guidomedina** [comment]
Assume there is neither expiration nor size bounded.

**Comment by ben-manes** [comment]
Yes. The benchmark page links to the code so that everything is transparent.

Caffeine performs a `get then computeIfAbsent` by optimistically assuming that the entry is present. Otherwise the performance will be limited by `computeIfAbsent` locking pessimistically (just like `putIfAbsent`). This is a simple trick, but people are often surprised its not built-in.

**Comment by guidomedina** [comment]
oh sorry I didn't notice the benchmark link, thanks again for the nice work you have done with Caffeine.

I have another huge project which I worked before which I recommended them to migrate from Guava to Caffeine.

**Comment by guidomedina** [comment]
The trick is simple indeed, but you have to make sure you call the loading function once, hence falling back to a pessimistic locking but for a cache that's perfectly OK.

**Comment by ben-manes** [comment]
Thanks. Its nice to hear feedback :-)

Yep, definitely only a single load is performed or else you could have resource leaks. For a cache we have to validate that the entry has not expired or that its key/value were not GC'd, which adds some complexity during the computation. The older trick of using a `Future` and `putIfAbsent` to memoize tended to use a `get` prescreen too in practice, due to the locking. One would expect that `computeIfAbsent` would prescreen, but at 32+ cores the pessimistic approach is surprisingly better.

**Comment by guidomedina** [comment]
Nothing to worry about then as the projects I work for they won't get hands on 32+ cores for at least 1 more year AFAIK, is there any performance difference between:

`Cache<K, V>.get(key, mappingFunction)` vs `LoadingCache.get(key)` with a predefined mapping function? i.e.: `newBuilder().build(mapping)`

Assume the same, neither expiration time nor size bounded.

**Comment by ben-manes** [comment]
Nope, no difference. That's all that the implementation does. It stashes a predefined function from the cache loader and delegates.

**Comment by guidomedina** [comment]
Then it is more convenient to use as people will tend to go crazy with lambdas believing Java will just use the same function without realizing they are using a dozen of different functions even if syntactically and semantically they are the same function.

I know I know, JIT might help, but who knows.

**Comment by ben-manes** [comment]
I believe later versions of JDK8 started doing a lot better at caching lambdas. But I'm not sure if that is only for non-capturing lambdas, which are the rarer case. The `LoadingCache` is also a nudge that users really should delegate the computation to the cache instead of a racy get-compute-put which is way too common.

**Comment by guidomedina** [comment]
Yeah, the huge project I mentioned I introduced Guava long time ago and `LoadingCache` is heavily in use but they are still in Java 7, I have loading caches for things like `Pattern` to keep compiled patterns in-memory forever.

I will start a new contract next month with them and my first task will be to migrate to Java 8 and while at it migrate to Caffeine.

Thanks a lot again for your help.

**Comment by ben-manes** [comment]
Cool, thanks for reaching out. Closing until next time :-)
