### ISSUE TITLE
Exclude certain entries from LoadingCache?

### ISSUE THREAD

**Issue by halfninja** [ben-manes/caffeine#726]
Hi, 

I'm looking at whether it's possible to use `LoadingCache` such that certain items aren't cached at all (but still return the value from the loader). Essentially I want a caching layer in front of a binary loader, but only cache small items.

I've experimented with writing a `Weigher` where undesirable items are given a weight of `Integer.MAX_VALUE` to effectively make them too heavy to cache. Would this do the job, or would they still end up being cached for a while until evicted, possibly pushing out older small items?

**Comment by ben-manes** [comment]
That weigher trick should work, as the cache will try to eject an item that is too large rather than flush everything out. Another approach is to use variable expiration, `expireAfter(Expiry)`, to indicate immediate eviction. You would simply need to be aware of your trick for a removal listener, if that has any differing logic based on the cause.

Ideally the cache should be smart about if an entry is worth caching based on actual usage, as sometimes our own intuitions are wrong or the application's changes invalidate our original assumptions. We did the [research work](https://dl.acm.org/doi/10.1145/3507920?cid=99659224047) on taking an entry's weight into account when making an eviction decision, but this has not been integrated yet. The current approach is still competitive and outperforms most size-aware policies, so our ideas added a small boost and kept it low priority on implementation work. I'd be curious as to if your workaround is actually needed and, if so, what could be done to avoid that work.

**Comment by halfninja** [comment]
Thanks for the comprehensive response, and good to know a weigher or a variable expiry could do the trick.

In most cases I expect the cache can indeed handle this with its default behaviour. In my case the blobs are web assets, and the smaller ones are likely to be files that a page is waiting to load, so prioritising those might provide better perceived performance even if average performance is not as good with perhaps more frequently accessed larger files. Perceived speed a bit too domain-specific to expect a generic cache to handle. 

Maybe I'm imagining the need to optimise this before I've even done any benchmarking. Or perhaps I should push all this off to our memcached and leave Caffeine to just cache our HTML as it does now.

Anyway thanks again - if I do manage to do any comparative benchmarks I'll post them here as I'm also curious, but I'll close for now as I've got plenty to go on.
