### ISSUE TITLE
what does disadvantage of Caffeine

### ISSUE THREAD

**Issue by HelloTo4x** [ben-manes/caffeine#727]
Hi, what does disadvantage of Caffeine, because Caffeine use Ring buffer, which need full slot to process, is it right ? I mean all request must block while Ring buffer has empty slot, is it right ?

**Comment by ben-manes** [comment]
Caffeine uses ring buffers for reads and writes. The read buffers are lossy, which means that they skip recording the access event into the buffer if it is full. This allows the cache to sample access events for maintaining a good recency / frequency policy, but in a manner that has low impact on the request latency / throughput.

The write buffer is bounded since those events can't be lost (e.g. adding a new entry). This buffer offers enough slack to handle a burst of writes, but under stress would incur backpressure to ensure that maintaining the cache policy can keep up. This typically isn't a problem except if some action blocks the drain from occurring, which is more often a bug or misuse than the application's expected behavior.

Any design has tradeoffs, so it depends on what you mean by disadvantage. For our design targets I think it strikes a good balance, but it is easy to nitpick any choice (even if all the known alternatives are worse). It would be trivial to find complaints about things that are unrealistic or make little sense in practice, and therefore deoptimized in favor for actual use cases. Tradeoffs are for a net win, rather than being ideal in every possible category regardless of its practicality.

Certainly if you have different goals in mind, e.g. memcached style remote nodes, then different tradeoffs would make sense. In that case avoiding a GC'd language and minimizing the footprint to maximizing memory availability are two major goals, as can be tiered storage and high performance network layer. In that use-case, workload traces tend to show LRU as more optimal. It is a different beast than an application's local cache.

If you have anything specific then I can offer more depth, but I am afraid that otherwise this is too general of a question for me to answer.

**Comment by HelloTo4x** [comment]
For example, my ring buffer has 2048 slots, so it needs to 2048 requests(each request = 1 slot in the ring buffer), so when my application has litter request, it needs to wait for more requests to full of the slot on the ring buffer, i mean this issue.

**Comment by ben-manes** [comment]
That is true for reads, and what is the impact of that? The same data is held in the cache (read only, so no evictions) and the priority order is an internal algorithmic detail. As the ring buffer is allocated, there is no extra space penalty. Having it slowly fill up doesn't cause have any external visibility. If a write occurs then it is flushed asap.

**Comment by HelloTo4x** [comment]
sure, so it doesn't affect to "write", thank you so much
