### ISSUE TITLE
Special cache for long keys

### ISSUE THREAD

**Issue by guidomedina** [ben-manes/caffeine#73]
Hi @ben-manes

Have you consider a cache for long keys similar to https://github.com/JCTools/JCTools/blob/master/jctools-experimental/src/main/java/org/jctools/maps/NonBlockingHashMapLong.java

It got me curious to the point of believing that it may make sense due to boxing/unboxing, but by Java 10 we won't need to worry about it anymore?

I think it would be worth having it only if it really makes a difference, say; low latency applications with pauseless GC requirements.

WDTY?

**Comment by guidomedina** [comment]
I also wonder why there is only a long version of NBHM, why not for int also.

**Comment by ben-manes** [comment]
This is way too messy to tackle and support long-term. At best it would reside as a fork that receives much less attention, so more of a one-off.

I think we're all eagerly awaiting ValueTypes and wish they'd land sooner. This would require forking ConcurrentHashMap, updating the interfaces, reworking anywhere using `null`, and code generating the primitive types. To avoid boxing via `OptionalX` the interfaces would probably be more like Guava (exception on cache miss). I think the ripple effect is large.

When value types arrive it will be interesting to see how the cache is effected. The changes to `Map` would be the model emulate. If the changes could be shoe-horned in but APIs are much better with clean slate, I might do both (by transitioning to a new package namespace).

I suspect many low-latency systems use thread-per-core as much as possible, where a non-concurrent cache is preferred. If someone wants to give it a try then I'd help, but otherwise waiting for Java 10 seems to be more practical.

**Comment by guidomedina** [comment]
I believe now that it is more of a specialized case for NBHM as there it can be just copied & pasted, for non-concurrent cases Agrona provides these `int` versions which I started using.

In the long term there will be some nightmares to tackle first with `ValueTypes` make entrance.
Closing it, thanks for the ideas.

**Comment by ben-manes** [comment]
I think a non-concurrent TinyLFU cache would be nice. Last I looked Agrona provided an n-way associative cache and an n^2 lru cache. A TinyLFU cache would be simple, very compact, and have much higher hit rates.
