### ISSUE TITLE
difference between Ehcache and Caffeine

### ISSUE THREAD

**Issue by HelloTo4x** [ben-manes/caffeine#730]
Hi, i read : https://blog.katastros.com/a?ID=01050-1fe779ce-9f71-481e-a7ba-21405ca18f6c. and https://gosunaina.medium.com/cache-redis-ehcache-or-caffeine-45b383ae85ee, except for talking about high performance, and concurrency, and Caffeine has some different strategies when caching, so do you know about other differences between them, thank you

**Comment by ben-manes** [comment]
Ehcache covers heap, offheap, disk, and distributed caching. This breadth leads to a more limited api as it tries to unify all concepts under common interfaces. It also results in poor performance due to a lack of focus because those are each hard problems.

Caffeine only targets heap caching and offers a more flexible api. Instead we encourage others to build on top for their solutions, often replacing homegrown caches. For example see Coherence and Infinispan for distributed caches using Caffeine under the covers.

It’s a philosophical difference of jack of all trades or best in class in one area. I prefer the latter and to allow others to contribute their expertise. They offer a commercial solution so feature creep is incentivized.

Ehcache v3 was a rewrite that didn’t get much traction and they don’t appear to be investing much into it. I don’t think it gets much serious consideration anymore, but is a natural upgrade path for older applications using v1/v2 (which was popular 10-15 years ago). I think most usages are out of habit and it’s kind of a legacy project.

**Comment by HelloTo4x** [comment]
thank you for your enthusiasm <3

**Comment by HelloTo4x** [comment]
but why don't you design Caffeine with "distributed caching" and "offheap" like Ehcache :(. with distributed caching, we can call it from other instance via tcp or http or something else

**Comment by HelloTo4x** [comment]
and do you provide any tool for transferring data from Ehcache to Caffeine ?

**Comment by ben-manes** [comment]
There are multiple projects that give you that and use Caffeine under the covers. Instead of doing everything, building a community seemed to have more impact. See Infinispan, Coherence, and Redisson.

Ehcache designed jsr107 JCache which we support as an extension. That makes it easy to switch. I have not heard of any major projects using Ehcache 3 so I don’t think it’s very important for our potential users from an adoption angle.

**Comment by HelloTo4x** [comment]
thank u so much
