### ISSUE TITLE
why don't u use Offheap

### ISSUE THREAD

**Issue by fizz12344321** [ben-manes/caffeine#737]
Hi, why don't you use Offheap in cache like Ehcache ?

**Comment by ben-manes** [comment]
In short, we can either do one thing really well or do a lot of things poorly. That choice to focus on a heap cache lets someone else do offheap really well and then those two projects can be combined into great. There are other projects that offer a combine Caffeine with their off-heap store (e.g. Infinispan, Coherence, HBase, Cassandra) and we've helped them make their off-heap caches better (e.g. [OHC](https://github.com/snazy/ohc), [Oak](https://github.com/yahoo/Oak)). I enjoy working and learning from other people, so I don't feel the need to try to do everything myself.

On a technical level, off-heap has a lot of negative tradeoffs. The typical approach is to serialize the data which can be a really high tax for an application. The systems that benefit the most are data store which already treats the value as opaque bytes, so for them it is simply optimizing the data placement. The main performance tax is somewhere else, like the network layer for memcached / redis, for the application to access that data. However an embedded off-heap cache for a business application, like Ehcache offers, is impacted much more negatively because it has less cache reuse and pays that tax more often.

An alternative is to use Caffeine as-is and store the value offheap. This is done by an upcoming paper, Robusta, that moves the data onto persistent memory. A possibly elegant approach might be to use [Apache Mnemonic](https://github.com/apache/mnemonic) to generate offheap stubs and avoid serialization entirely. This keeps the cache management on-heap so you get all the benefits of Caffeine and the heavyweight value is off-heap so you avoid the GC penalty. For most cases one might use Ehcache's solution, this approach is likely faster and more flexible.
