### ISSUE TITLE
why do you choose ConcurrencyHashMap

### ISSUE THREAD

**Issue by fizz12344321** [ben-manes/caffeine#738]
Hi Ben, i am a newbie with Caffeine. My buddies suggest that I use Caffeine for high concurrency. But i don't know how to deal with concurrency when caching invalidates for high-traffic sites, can you recommend to me how to do it with Caffeine, is it the reason that you use ConcurrencyHashMap ?

**Comment by ben-manes** [comment]
I’m sorry, but I don’t understand the question.

we use ConcurrentHashMap because it’s robust, fast, and highly concurrent. Caffeine is best thought of as a bounded map, which we offer via the asMap view.

we offer a local cache, so invalidation across servers is out of scope. That’s often done using expiration or a pubsub topic to broadcast the key to discard. It’s also common to layer on top of a remote cache like memcached or redis to get more scale.

Most usages are very simple and [tutorials](https://www.baeldung.com/java-caching-caffeine) hopefully make it more approachable. The api tries to nudge best practices and be clear about what to expect.

Hope that helps

**Comment by ben-manes** [comment]
The cache will scale with your workload and does not require any special tuning. Internally it adapts its data structures to handle more concurrency and improve the hit rate (adjusting the recency / frequency bias). Your responsibility is to decide on the policy configuration (expiration, max size, etc) and business logic using the cache. We'll take care of performance and there are no knobs to play with (like write concurrency level).

The [concurrency benchmarks](https://github.com/ben-manes/caffeine/wiki/Benchmarks#server-class) and [hit rate efficiency](https://github.com/ben-manes/caffeine/wiki/Efficiency) tries to convey the above. Caffeine is robustly a top performer in more scenarios than other caches and we want users to focus on their problems instead of trying to figure out why the cache is too or ineffective.
