### ISSUE TITLE
remove @NonNull from com.github.benmanes.caffeine.cache#get()

### ISSUE THREAD

**Issue by weyseley** [ben-manes/caffeine#746]
I take issue with this method below, my situation is that Function return null, but it reported NullPointerException that could have been avoided
@Nullable
V get(@NonNull K var1, @NonNull Function<? super K, ? extends V> var2);

and i saw the issue about @NonNull, and found it has fixed after 3.X，but i still use jdk 8
so I would like to remove the annotation(@NonNull) and release a new version(2.9.4)

**Comment by ben-manes** [comment]
In 3.x this is defined similarly as,
https://github.com/ben-manes/caffeine/blob/2128448d841adadd4646b12abe0d9b19a55f5f2f/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Cache.java#L81-L82

The `@PolyNull` makes the analysis conditional so that a null check on `V` is only required if the function returned `null`. In both the caller may receive a null value and should consider that case. If "my situation is that Function return null" is true, then a potential NPE is a valid warning.

I am hoping to softly deprecate 2.x as jdk 8 is it has reached end of life (Mar 2022) and will stop receiving critical security fixes in 2025. That means there is a higher burden on companies who chose to stay on Java 8 and an expectation of diminishing industry support. Therefore I am hesitant to put the time/energy into backporting for small quality-of-life issues like this one.
