### ISSUE TITLE
Cannot consume in Android build that uses R8

### ISSUE THREAD

**Issue by nrobi144** [ben-manes/caffeine#750]
Using https://github.com/aPureBase/KGraphQL (`:0.17.14-fork-7`), that has a dependency on `com.github.ben-manes.caffeine:caffeine:3.0.2` in an Android project results in 

```
com.android.tools.r8.internal.ez0: MethodHandle.invoke and MethodHandle.invokeExact are only supported starting with Android O (--min-api 26)
```

**Comment by nrobi144** [comment]
This error can be fixed by upgrading Android `minSdkVersion to 26`.

However
```
com.android.tools.r8.internal.ez0: Call to polymorphic signature of VarHandle are only supported starting with Android P (--min-api 28)
``` 

occurs on `minSdk < 28`

**Comment by ben-manes** [comment]
This project does not support Android. The design goals for a server-side cache is very different from mobile, e.g. concurrency, dependency size, and memory assumptions. After we wrote Guava's cache, the Android team wrote LruCache as its counterpart because Google recognized that the ecosystems were different. For example, [Store](https://github.com/dropbox/Store) is an Android cache that is tailored for those users. This was true pre-Android too, with Java ME being only a subset of Java SE to avoid performance pitfalls.

A library may be lucky to work in both ecosystems without any changes, but this is simply good fortune. As the two continue to diverge more then library authors who want to support both will need to offer that via adapters.

**Comment by ben-manes** [comment]
fwiw, the twitch4j project ran into this and created a common api, [Xanthic/cache-api](https://github.com/Xanthic/cache-api).
