### ISSUE TITLE
[2.2.6] Caffeine might be retaining strong references

### ISSUE THREAD

**Issue by drcrallen** [ben-manes/caffeine#76]
It takes a couple of days to run into this error case, but Caffeine seems to be retaining strong references somewhere. 

<img width="1399" alt="screen shot 2016-05-05 at 8 25 46 am" src="https://cloud.githubusercontent.com/assets/8213081/15047895/d088bf4c-129b-11e6-802e-23879644a503.png">

We have weighted eviction based on entry size, and the cache is reporting `com.github.benmanes.caffeine.cache.Policy.Eviction#weightedSize` pretty consistently:

<img width="630" alt="screen shot 2016-05-05 at 8 32 43 am" src="https://cloud.githubusercontent.com/assets/8213081/15047981/39a09856-129c-11e6-9c9a-12f696d267de.png">

Once the update to 2.3.0 rolls out I can get the eviction throughput as well, but I don't have that statistic yet.

For general eviction stats, here's the count of evicitons per hour:

<img width="622" alt="screen shot 2016-05-05 at 8 39 40 am" src="https://cloud.githubusercontent.com/assets/8213081/15048142/003e7582-129d-11e6-868b-658c025e5303.png">

Here's what G1GC old gen looks like:

<img width="623" alt="screen shot 2016-05-05 at 8 38 29 am" src="https://cloud.githubusercontent.com/assets/8213081/15048097/cefc6ed4-129c-11e6-92de-3edeb66597d5.png">

This is on a canary node under production workloads.

Using https://github.com/metamx/druid-cache-caffeine/tree/druid-caffeine-cache-0.8.3.4 

It is worth noting there are 10 nodes under test, and only one of them is exhibiting this issue so far (I do not have a great check for the others)

Here's a graph showing the other canary nodes' old gen which seem to be ok. The original node used to test before the others were brought on board (orange) is still chugging strong.
<img width="630" alt="screen shot 2016-05-05 at 8 53 23 am" src="https://cloud.githubusercontent.com/assets/8213081/15048551/f2be6bcc-129e-11e6-9905-78bc71d4c3f5.png">

**Comment by ben-manes** [comment]
A strong reference would be expected in the hash table, a queue (SLRU, expiration), or a buffer (read/write).

For the queues the culprit we'd expect is a dangling reference. I'm inclined to trust the tests which so far disprove that, due to the queues being operated on in single-threaded behavior. That lets the tests be exhaustive as we don't have to worry about races. If the cache is evicting from the SLRU queues then I'd rule that out.

The read buffer is bounded and lossy, so activity should cause it to flush eventually. Even if it holds a stale reference, there's only so many it can retain (16 * (4 * NCPUs)).

That leaves the write buffer, which until 2.3.0 was SingleConsumerQueue. That should be drained immediately and be very small, so 2.8M retained nodes indicates a problem. That could be either due to [GC nepotism](http://psy-lob-saw.blogspot.com/2016/03/gc-nepotism-and-linked-queues.html), a write rate that starves the async drain, or that the async task failed to run. In 2.2.6 a fix was made to avoid nepotism and in 2.3.0 a bounded (array-based) buffer applies back pressure to avoid starvation. After an upgrade we'd expect neither of those to be possible.

If this occurs on the latest release, that only  for the async drain to be stuck and not applied. That would halt any eviction from occurring since the maintenance task handles that. We'd expect that a race, unhandled failure, or executor malfunction to cause the scheduling state machine to be invalid. Since you still see evictions occurring that doesn't seem to be the cause either.

I'm optimistic that 2.3.0 will fix this. It shouldn't suffer the nepotism or starvation that could explain the excessively large queue.

**Comment by ben-manes** [comment]
For sanity purposes I added Guava [tests](https://github.com/ben-manes/caffeine/commit/e08c87d4f178d7738b6a3643400f55345d2e3ba6) for the queues. All pass, with minor changes to support iterator removal for test compatibility.

**Comment by drcrallen** [comment]
@ben-manes validation halted due to https://github.com/ben-manes/caffeine/issues/77

**Comment by ben-manes** [comment]
For anyone else reading, please see #77 where we found it is [JDK-8078490](https://bugs.openjdk.java.net/browse/JDK-8078490) which affects 8u40-8u60 (fixed in 8u65). Leaving open until @drcrallen has results to confirm our analysis.

**Comment by johnou** [comment]
@ben-manes the fix isn't included in 8u60? https://bugs.openjdk.java.net/browse/JDK-8079701

**Comment by ben-manes** [comment]
oh you're right. Thanks for the correction.

**Comment by johnou** [comment]
Wasn't trying to break balls, but had to confirm since our application relies heavily on FJP.

**Comment by ben-manes** [comment]
oh no worries. I misread the bug which had an integration into 8u65. Good to know it was resolved sooner.

**Comment by drcrallen** [comment]
This seems to be resolved through a combination of updating to 2.3.0 and using a single threaded executor for maintenance tasks.
