### ISSUE TITLE
Does method put thread safe?

### ISSUE THREAD

**Issue by dcy652701** [ben-manes/caffeine#760]
I looked into source code of put, I didn't see synchronize or lock. So I think put is unsafe for multi thread

**Comment by ben-manes** [comment]
The bounded cache uses `synchronized` on put, whereas the unbounded is a simply proxy to ConcurrentHashMap so it doesn't have to do much itself. The caches are threadsafe.

**Comment by ben-manes** [comment]
Sorry for the short reply earlier, as I was in a meeting and didn't know when I'd get back to this. Here are more details to satisfy your curiosity.

The `put` method below is complex for performance reasons, as a simpler version using a `Map.compute` had 50% throughput in a microbenchmark. The put method does an optimistic read and synchronizes on the entry (an lru list node) to update it, or else adds the entry by a `putIfAbsent`. This is performed within a retry loop since the operation could race with other writes and the cache avoids using coarse locks.

https://github.com/ben-manes/caffeine/blob/80791a03f2a737189969df8afd27b94b3a4f915e/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L2173-L2292

The unbounded cache is a simple delegate to a `ConcurrentHashMap` so nothing fancy is needed. It merely calls `Map.put` and notifies a removal listener asynchronously, if configured. Obviously this cache type isn't used very often, so it is not very interesting logic. All of the concurrency handling is done by the underlying Map and our adapter is for convenience, e.g. if unbounded for a unit test.

https://github.com/ben-manes/caffeine/blob/80791a03f2a737189969df8afd27b94b3a4f915e/caffeine/src/main/java/com/github/benmanes/caffeine/cache/UnboundedLocalCache.java#L422-L429

In addition to our own test suite, we use [Lincheck](https://github.com/Kotlin/kotlinx-lincheck) to [assert](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/test/java/com/github/benmanes/caffeine/lincheck/AbstractLincheckCacheTest.java) linearizability.

**Comment by dcy652701** [comment]
> Sorry for the short reply earlier, as I was in a meeting and didn't know when I'd get back to this. Here are more details to satisfy your curiosity.
> 
> The `put` method below is complex for performance reasons, as a simpler version using a `Map.compute` had 50% throughput in a microbenchmark. The put method does an optimistic read and synchronizes on the entry (an lru list node) to update it, or else adds the entry by a `putIfAbsent`. This is performed within a retry loop since the operation could race with other writes and the cache avoids using coarse locks.
> 
> https://github.com/ben-manes/caffeine/blob/80791a03f2a737189969df8afd27b94b3a4f915e/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L2173-L2292
> 
> The unbounded cache is a simple delegate to a `ConcurrentHashMap` so nothing fancy is needed. It merely calls `Map.put` and notifies a removal listener asynchronously, if configured. Obviously this cache type isn't used very often, so it is not very interesting logic. All of the concurrency handling is done by the underlying Map and our adapter is for convenience, e.g. if unbounded for a unit test.
> 
> https://github.com/ben-manes/caffeine/blob/80791a03f2a737189969df8afd27b94b3a4f915e/caffeine/src/main/java/com/github/benmanes/caffeine/cache/UnboundedLocalCache.java#L422-L429
> 
> In addition to our own test suite, we use [Lincheck](https://github.com/Kotlin/kotlinx-lincheck) to [assert](https://github.com/ben-manes/caffeine/blob/master/caffeine/src/test/java/com/github/benmanes/caffeine/lincheck/AbstractLincheckCacheTest.java) linearizability.

Thanks
