### ISSUE TITLE
java.lang.System.getLogger is incompatible with Android

### ISSUE THREAD

**Issue by vitorpamplona** [ben-manes/caffeine#763]
Issue #456 described the decision to use [JEP-264: Platform Logging API](https://openjdk.java.net/jeps/264) to redirect logs to slf4j. Unfortunately, Android has not provided a `System.getLogger` interface yet (I know, it sucks). This means that every use of 3.0+ on Android will simply crash on runtime. 

A solution would use the `org.slf4j:slf4j-api` to abstract the desired logging frameworks without having a dependency on Java9.

**Comment by ben-manes** [comment]
We don't support Android. If you only target that then using something like [Store](https://github.com/MobileNativeFoundation/Store) (NYTimes / Dropbox) or a facade like [cache-api](https://github.com/Xanthic/cache-api) (Twitch) to swap to a more appropriate implementation. The needs of server and mobile requirements favor different design decisions to optimize for, such as Android's lower concurrency needs but byte/method count limits. For example during the development of Guava's Cache those discussions led the Android team to write [LruCache](https://developer.android.com/reference/androidx/collection/LruCache) because they did not think using Guava on mobile would make sense (which later popularity of proguard seemed to alleviate some of those concerns).

**Comment by vitorpamplona** [comment]
It's too bad. 2.9 works great on Android. We have been using for quite some time without any issues.

**Comment by ben-manes** [comment]
You are welcome to continue using 2.x, as that remains supported. It just has never been the focus of this library. More recently it seems that the Android community has pushing Kotlin and its multi-platform support as a reason to rewrite away from Java (as that is not transcoded). That would push pressure to have Caffeine rewritten, e.g. Dropbox translated Guava's Cache to Kotlin for their usage in Store. The communities are diverging and I think best served by experts in their respective areas.

**Comment by vitorpamplona** [comment]
Communities try to diverge but, in the end, they always come back together (or just don't block each other). It has been the story of the past 23 years in Java. They need each other way more than they realize. 

As for us, we might just fork it, run a regex replace all in all files, and republish automatically. It should be easy enough.
