### ISSUE TITLE
Throws an exception sporadically when cache loader uses the same cache

### ISSUE THREAD

**Issue by RokLenarcic** [ben-manes/caffeine#764]
I am using caffeine in a library that wraps functions to cache function calls, but I will present here code that produces an exception in a minimal example. I don't know if this is considered a bug or not, but worth noting that the same scenario with Guava works perfectly. Affected version is 3.1.1. 

```
package org.example;

import com.github.benmanes.caffeine.cache.Cache;
import com.github.benmanes.caffeine.cache.Caffeine;

/**
 * Hello world!
 *
 */
public class App 
{
    private static Cache<Long, Long> cache = Caffeine.newBuilder().initialCapacity(4).build();

    private static Long fib(Long n) {
        if (n <= 1) {
            return 1L;
        } else {
            return cache.get(n - 1, App::fib) + cache.get(n - 2, App::fib);
        }
    }

    public static void main( String[] args )
    {
        System.out.println(fib(10L));
    }
}

```

So to explain, this is basically how a function caching framework would cache a recursive fibonacci function. This serves as an example.

The exception thrown is:
```
Exception in thread "main" java.lang.IllegalStateException: Recursive update
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1763)
	at com.github.benmanes.caffeine.cache.UnboundedLocalCache.computeIfAbsent(UnboundedLocalCache.java:294)
	at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:110)
	at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
```

So this happens when computeIfAbsent in ConcurrentHashMap tries to computeIfAbsent on the same bucket. 

When ConcurrentHashMap is created, there is a number of buckets = concurrencyLevel or if not given it's equal to initial capacity.

So when number of buckets is 16 (say by removing that `initialCapacity(4)`), and we have 10 cache entries (calling `fib(10)`), they don't hit the same buckets while loading recursively. But when there are only 4 buckets you get an error.

Guava works when used like this.

**Comment by ben-manes** [comment]
This is a known surprise and not a bug. We do try to warn in the JavaDoc for `Cache.get` that a recursive computation is not supported,

```java
   * <b>Warning:</b> as with {@link CacheLoader#load}, {@code mappingFunction} <b>must not</b>
   * attempt to update any other mappings of this cache.
```

ConcurrentHashMap does not support this and I worked with Doug Lea on failing fast, whereas before it would get stuck in a silent livelock. You can read about this in [2011](https://markmail.org/thread/kbqxdfapp5n6u7j3) and [2014](https://markmail.org/message/dixewqcvbbs5gzi2).

The JavaDoc of ConcurrentHashMap's `computeIfAbsent` states,
```java
   * <p>The mapping function must not modify this map during computation.
```

Originally HashMap thought it was safe, but they realized it corrupted the hash table and disallow it
```java
    * <p>This method will, on a best-effort basis, throw a
    * {@link ConcurrentModificationException} if it is detected that the
    * mapping function modifies this map during computation.
    *
    * @throws ConcurrentModificationException if it is detected that the
    * mapping function modified this map
```

In Guava the computation is decoupled from the map operation, so it is similar to storing a future as the value. This allows it to work in some cases, except it can deadlock if ordering is not deterministic. Many years ago I fixed Guava's cache to error early when it recursively computed the same key instead of deadlocking (by checking if `Thread.holdsLock(entry)` before waiting on the future value). This means that if you are careful then it will work in Guava as a disfavored but supported behavior.

You can simulate Guava's behavior by computing outside of the map. The [FAQ](https://github.com/ben-manes/caffeine/wiki/Faq#recursive-computations) has an example using a factorial operation, where the thread inserts and completes a CompletableFuture. This requires a little more work and you have to handle errors safely, but it is explicit and a general purpose solution.

```java
AsyncCache<Integer, Integer> cache = Caffeine.newBuilder().buildAsync();

int factorial(int x) {
  var future = new CompletableFuture<Integer>();
  var prior = cache.asMap().putIfAbsent(x, future);
  if (prior != null) {
    return prior.join();
  }
  int result = (x == 1) ? 1 : (x * factorial(x - 1));
  future.complete(result);
  return result;
}
```

**Comment by RokLenarcic** [comment]
Thank you, your final code piece is very helpful. 
Is the AsyncCache type necessary, wouldn't normal `Cache<Integer, CompletableFuture<Integer>>` also work? I am trying to stay away from executors as those complicate stacktraces immensely.

**Comment by ben-manes** [comment]
yes, that is actually equivalent as AsyncCache is a convenience for that signature. It adds a little intelligence that makes it nicer to work with. If I recall correctly that would be to not evict an in-flight future (by size, expiration), unwrapping for a removal listener, proper refreshAfterWrite behavior, removing automatically if failed or null result, and fixing up the stats. It also disallows using weak/soft value reference caching as very unlikely to make sense.

The example code doesn't use an executor, performs the computation on the calling thread, and sets the future directly. As a sample it did not handle exceptions which would leave the future in-flight and not evictable, whereas you would catch and set `future.completeExceptionally(e)` in real code.
