### ISSUE TITLE
memory safe cache

### ISSUE THREAD

**Issue by dragon-zhang** [ben-manes/caffeine#776]
Hi, @ben-manes

Setting the cache size has always been a difficult problem, because the setting is too small to make full use of resources; Large settings will cause OOM. This problem also exists in blocking queues.

The features I implemented in Apache Shenyu effectively solves this problem:
1. [MemoryLimitedLinkedBlockingQueue](https://github.com/apache/shenyu/blob/master/shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/MemoryLimitedLinkedBlockingQueue.java)
2. [MemorySafeLinkedBlockingQueue](https://github.com/apache/shenyu/blob/master/shenyu-common/src/main/java/org/apache/shenyu/common/concurrent/MemorySafeLinkedBlockingQueue.java)

In these classes, two solutions are proposed:
1. Set `memoryLimit`, calculate the object size through `java.lang.instrument.Instrumentation#getObjectSize`, and ensure that the total does not exceed `memoryLimit`.
2. Set `maxFreeMemory`, and obtain the maximum available memory of the current JVM through `java.lang.Runtime#freeMemory`. As long as the maximum available memory of the current JVM is greater than `maxFreeMemory`, it is allowed to add to queue or cache, otherwise it is rejected. Here I use reverse thinking. You can find some interesting discussions in [apache/dubbo#10021](https://github.com/apache/dubbo/pull/10021) .

Personally, I prefer the second solution.

Following this idea, also in order to fix a bug in Apache Shenyu, I created [MemorySafeWindowTinyLFUMap](https://github.com/apache/shenyu/blob/master/shenyu-common/src/main/java/org/apache/shenyu/common/cache/MemorySafeWindowTinyLFUMap.java) based on `caffeine`, perhaps this implementation is not elegant enough. 

Could you please provide some implementations in `caffeine` based on the ideas mentioned above? 
I would appreciate it if you would.

**Comment by ben-manes** [comment]
I believe your approach is good and thank you for the example, but I don't think it is appropriate for us to offer this functionality directly. Unfortunately this is a messy, error-prone topic. Instead we trust that you know best and try to give you all of the capabilities that you need, while avoiding being responsible for potential JVM minefields.

Calculating an object's size is quirky and may be wrong; see the draft JEP [Low-level Object layout introspection methods](https://openjdk.org/jeps/8249196). We sidestep this through a `Weigher` interface and `maximumWeight` to let users opt into this estimators.

Since the JVM doesn't have a callback like Android's [onTrimMemory](https://developer.android.com/reference/android/content/ComponentCallbacks2#onTrimMemory(int)), your scheduling thread is a best-effort. Unfortunately an intermediate spike of activity could cause an out-of-memory error because the cache cannot react quickly enough to free memory. As a safer approach than calling unknown user code, the JVM introduced soft references so that the GC could reclaim this transient memory if needed.

In both your approach (2) and (typically) unbounded soft reference usages, this leads to using as much of the "free" memory as possible for caches. That violates the GC's generational hypothesis where it expects large pools of free memory (saw tooth), and causes GC thrashing as each collection only recovers enough memory to handle a few requests. That results in a death spiral and excessive stop-the-world old collections, which increases latencies. Therefore soft references are generally discouraged as they promote poor behaviors, lower performance, and the GC is unaware of what data is most valuable to keep. Similar things happen for native memory, where Linux will itself leverage free memory for the buffer cache, but is very unfriendly to applications that try to use all available resources. 

A partial solution to this is to combine a maximum size / weight with soft references. This way you can achieve high hit rates and avoid filling the heap in healthy runs, while also being responsive if the JVM gets overloaded. The operator still has to decide on a good cache size, but this way the application might be more tolerant to unexpected usage spikes.

A flaw in your `MemorySafeWindowTinyLFUMap` is that is sets an unreachable maximum size, 1 billion entries. The cache policy has to use some memory to track access history for making smarter decisions and by default we lazily allocate that once the cache reaches 50% of the threshold. This way an unrealistic value might be set (e.g. to quickly disable a cache) or a safety threshold, and avoids wasting memory / time. In our case a `long[maximumSize]` is allocated, an 8gb allocation if done upfront. Because of this the policy may be giving you LRU or FIFO order due to minimal tracking. That's likely fine for the desire of being memory bounded and concurrent, but it is not acting as intelligent as you may have expected.

P.S. Congrats on graduating to a top-level Apache project!

**Comment by dragon-zhang** [comment]
Thanks for sharing your patience and valuable knowledge, I didn't know much about cache policy before. 

After checking Shenyu's code, although the `maximumSize` is set to `1<<30`, the `initialCapacity` is `1<<16`. And `MemorySafeWindowTinyLFUMap` will allow the user to set the `maximumSize` of Caffeine.

In `com.github.benmanes.caffeine.cache.Expiry`, I want a new method as follows:
```java
/**
     * Specifies that the entry should be automatically removed from the cache once
     * the condition matched. To indicate no expiration, {@code false} should be returned.
     * <p>
     * <b>Note:</b> The {@code currentTime} is supplied by the configured
     * {@link com.github.benmanes.caffeine.cache.Ticker} and by default does not
     * relate to system or wall-clock time. When calculating the duration based on
     * a time stamp, the current time should be obtained independently.
     *
     * @param key         the key represented by this entry
     * @param value       the value represented by this entry
     * @param currentTime the current time, in nanoseconds
     * @return true if the entry should be automatically removed
     */
    boolean expireOnCondition(@NonNull K key, @NonNull V value, long currentTime);
```
It is up to you to decide whether to add this method.

**Comment by ben-manes** [comment]
Unfortunately we would not be able to do anything more intelligent than you can in your code if we supported that expiration method. The convenience of our support would be of negative value to maintainability, so similarly to max memory it is best left to your own code where you know the boundary conditions much better than we do.

Caffeine uses strictly amortized O(1) algorithms, e.g. expiration uses a hierarchical timing wheel which is a hash-based priority queue. This makes it very fast to add, reorder, remove, and evict entries based on a known order, and avoids the cache size from significantly degrading performance. The `expireOnCondition` is unordered, causing evaluation to occur at some unknown time. One approach would be to periodically scan all entries, O(n), to determine if the criteria is met. Another is to evaluate on access, e.g. `Cache.get`, and pollute the cache with dead entries. This approach is what memcached and redis used, but they require a size eviction to be set to for eviction whereas Caffeine does not. Because cache pollution significantly increased the operating cost of those deployments, more recent versions use background sweeper threads to continuously scan the cache for dead entries.

Another quirk with your API is that an entry transition from being expired to unexpired without interacting with the cache. For example, what is the expectation of `LoadingCache.get(key)` if the existing value expired, a new value loaded, and in between that old value is no longer expired? If replaced and the removal listener notified, would the consumer be surprised to receive an entry that violates the `expireOnCondition` with an expired removal cause? Probably not, so then should the newly loaded value be dropped instead? Unfortunately that does not solve the problem because even if removed due to expiration, a direct update to the value could change its state before the listener is notified. If the user relied on changing the evaluation without going through the cache then the behavior would be non-deterministic.

Given these realities, this library tried to solve the general problems that would be difficult for users to do themselves. It then tries to expose enough control so that you can intelligently conform it to your use-case. This allows you to solve your problems, while we avoid implementing non-generalizable features that may be error prone. If the only benefit is code reuse, then others are welcome to open-source their extension libraries with those niceties.

Thanks for the thoughtful suggestions! 🙂

**Comment by dragon-zhang** [comment]
I learned a lot from you :)
