### ISSUE TITLE
No async variant of removal/eviction listeners

### ISSUE THREAD

**Issue by smaug-fm** [ben-manes/caffeine#778]
I am using `Async` variant of the cache and just noticed that only a synchronous removal/eviction listener can be added.
I must call some cleanup actions in the removal listener and they are asynchronous which means I cannot call them properly, without blocking. Is there any way this can be solved? 
How asynchronicity is supposed to be achieved in such a case? Thanks!

**Comment by ben-manes** [comment]
An entry is only eligible for eviction when the future has completed successfully, at which point the policy metadata is calculated (weight, expiration). A `Caffeine.evictionListener` is atomic with the map operation (`computeIfPresent`) so it makes sense for cleanup that needs to be done sequentially with the key. You wouldn't want to perform expensive blocking operations within this if possible since it can block other writes until complete (per docs in `ConcurrentHashMap`).

A `Caffeine.removalListener` is always invoked asynchronously on the `Caffeine.executor` after the map operation has completed (explicit invalidation or eviction). Since this is asynchronous (no guarantee _when_ it will run), we can chain it to on the future to run after it completes successfully `thenAcceptAsync`.

If you need to explicitly remove an incomplete future prior and perform additional steps atomically within that map operation, then you can use a `AsyncCache.asMap().compute`. Since that is under the map's lock you should try to avoid blocking on the future (if you needed it to complete) as that could halt other map operations (per docs in `ConcurrentHashMap`).

I am not sure why you would need to block within the removal listener on other async calls. You could have the listener merely call those async operations and chain more steps logic against those other futures (e.g. `thenRun`).

Does any of that help?

**Comment by smaug-fm** [comment]
Yes, it makes sense now. I thought they both (removal and eviction listeners) execute synchronously with the map operation, but as `removalListener` is invoked asynchronously by design, I think I can just fire-and-forget my async action.
Thanks for the quick reply!
