### ISSUE TITLE
Sometimes cache fails to call mapping function after it returns null

### ISSUE THREAD

**Issue by baltiyskiy** [ben-manes/caffeine#787]
`Caffeine.buildAsync()` documentation states:

> If the asynchronous computation fails or computes a null value then the entry will be automatically removed. 

This means that a subsequent `get()` must invoke the computation again. However, this is not always the case.

Unit test:

```java
package test;

import com.github.benmanes.caffeine.cache.AsyncLoadingCache;
import com.github.benmanes.caffeine.cache.Caffeine;
import org.hamcrest.CoreMatchers;
import org.junit.Test;

import java.time.Duration;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.atomic.AtomicBoolean;

import static org.hamcrest.MatcherAssert.assertThat;

public class CaffeineTest {
  @Test
  public void shouldCallComputationAfterItReturnedNull() throws ExecutionException, InterruptedException {
    AtomicBoolean shouldReturnValue = new AtomicBoolean(false);
    AsyncLoadingCache<String, String> cache = Caffeine.newBuilder()
      .buildAsync((key, executor) -> {
        CompletableFuture<String> future = new CompletableFuture<>();
        executor.execute(() -> {
          future.complete(
            shouldReturnValue.compareAndSet(false, true) ? null : "value"
          );
        });
        return future;
      });
    int nRuns = 2000;
    for (int run = 0; run < nRuns; run++) {
      System.out.print("\r" + run + "/" + nRuns);
      String v1 = cache.get("key").get();
      String v2 = cache.get("key").get();
      assertThat(v1, CoreMatchers.nullValue());
      assertThat(v2, CoreMatchers.equalTo("value"));
      cache.synchronous().invalidate("key");
      shouldReturnValue.set(false);
    }
  }
}
```

The result:
```
3/2000
java.lang.AssertionError: 
Expected: "value"
     but: was null
Expected :"value"
Actual   :null
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:18)
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:6)
	at test.CaffeineTest.shouldCallComputationAfterItReturnedNull(CaffeineTest.java:35)
```

**Comment by ben-manes** [comment]
The issue is a bit subtle, but in short "automatically" does not mean instantaneously. By using an asynchronous cache you lose making some linearizability assumptions.

The cache removes the entry using a `whenComplete` callback, but returns the future produced by `buildAsync`. This is because a dependent action produces a new future and operations like `future.cancel` is not communicated upstream. For example, you might have `buildAsync` return a http client's future and canceling it on a timeout to close the connection. This won't work if we return the `whenComplete` instance where canceling instead stops the entry from being removed and not the http request. The cache therefore returns the produced future, where `get()` does not block waiting for the dependent actions to also complete. This leads to a race where the call to `v2` happens before the callback runs.

An easy solution to this specific case is to ensure that the entry was removed by the calling thread. Then the caller knows that the next `get` will be a different future instance. Using the following passes your test.

```java
var future = cache.get("key")
assertThat(future.get(), CoreMatchers.nullValue());

cache.asMap().remove("key", future);
String v2 = cache.get("key").get();
assertThat(v2, CoreMatchers.equalTo("value"));

cache.synchronous().invalidate("key");
shouldReturnValue.set(false);
```

**Comment by baltiyskiy** [comment]
Thank you, it helps. However, I'm concerned about this statement:

>  By using an asynchronous cache you lose making some linearizability assumptions.

I would expect the cache to be linearizable on individual entries. If it's not the case, I might be in for more surprises. Is there any document which states the consistency model that Caffeine follows?

**Comment by baltiyskiy** [comment]
Also, it looks like it's not impossible to make `get()` return the future that waits for dependent operations; the only problem is to create a future that will propagate cancellation upstream.

**Comment by ben-manes** [comment]
Linearization and asynchronous actions do not blend together very well as a general rule. While the hash table entry is managed in a linearizable fashion, its value is a future and the computation is decoupled from this atomic scope. If you work from the perspective that an `AsyncCache` is a bounded `Map<K, CompletableFuture<V>>` then your assumptions should hold.

**Comment by baltiyskiy** [comment]
Sorry, I don't follow the `Map<K, CompletableFuture<V>>` analogy, because the map simply doesn't have the API that Caffeine has.
Taking the reported scenario as an example: the closest is `computeIfAbsent()`, but it won't remove the entry from the map when the resulting future completes to `null`.

**Comment by ben-manes** [comment]
The compute methods will remove an entry when the result is null and not establish a mapping if an exception is thrown. We extend that for an async value so that likewise a future that failed or resolved to null needs to be removed. This is then equivalent to,

```java
Map<K, CompletableFuture<V>> map;
var future = map.computeIfAbsent(key, this::loader);
future.exceptionally(error -> {
  map.remove(key, future);
  return null;
});
return future;
```

The dependent action is added after the mapping is established as it may otherwise run within it, e.g. if immediately completed, which would cause a recursive write as it tries to modify the map within the computation (an `IllegalStateException`). Since the dependent action is performed after the mapping is established, the loader's future could be read before the exception handler has run.

**Comment by baltiyskiy** [comment]
Thanks! So the model is `Map<K, CompletableFuture<V>>`, extended the way you described. However, one could also extend `Map` in a way that would expose not the original `future` (the mapping stored in the map), but the future-with-dependent-actions, with cancellation propagated. E.g., something like:

```
    var future = map.computeIfAbsent(key, this::loader);
    var publicFuture = new CompletableFuture<V>() {
      @Override
      public boolean cancel(boolean mayInterruptIfRunning) {
        super.cancel(mayInterruptIfRunning);
        return future.cancel(mayInterruptIfRunning);
      }
    };
    future.whenComplete((value, ex) -> {
      if (ex != null) {
        map.remove(key, future);
        publicFuture.completeExceptionally(ex);
      } else {
        publicFuture.complete(value);
      }
    });
    return publicFuture;
```

Since Caffeine prefers the former over the latter, it looks like there is some guiding principle in choosing one way (with one consistency guarantees) over another. The question is, is it made explicit somewhere? I'm asking because my assumptions about how Caffeine behaves were wrong, so I will need to replace them with something.

**Comment by ben-manes** [comment]
While that version makes sense for internal code where you know the narrow usages, it's a different challenge when providing a library for others. If `CompletableFuture` added methods in later versions then the propagation might not work as expected on a later JDK without a dependency upgrade and possibly us needing a multi-release jar for version compatibilities. If the user extended CompletableFuture to retain additional context then that would be lost as not downcastable. If the loader stored the future in a mapping before returning it, then the associations could not be matched as  `CompletableFuture` uses reference identity for equality. That also means that our `asMap` view which offers methods like `replace` would operate on incompatible different instances, making those atomic methods unusable. I suppose there are likely more quirky cases.

Certainly both choices have different surprising behavior and by returning exactly the future produced by the loading function, we can at least explain the problem so that users could implement the `publicFuture` approach in their code. The alternative is harder to work around and it seemed more error prone if we tried to patch over this issue.

**Comment by baltiyskiy** [comment]
I agree that wrapping futures doesn't work well for Caffeine. 

Looking further at the "map of futures" model: the fact that in Caffeine, `get(key)` will return the same future while the computation is in progress, is translated to `map.compute()` that checks if the mapping is present and if it's complete --- correct?

**Comment by ben-manes** [comment]
I am not sure if Iunderstand your question.

For creating the hashmap entry we do a get to lookup and validate if present, else fallback to a compute. If multiple threads see it’s missing then only one does the work, all wait, and the others no op. An async cache just computes a new in-flight future, so the waiting on its result is then handled externally to the map computation.
