### ISSUE TITLE
Best way to force CacheWriter.write after stored object variable change?

### ISSUE THREAD

**Issue by oobles** [ben-manes/caffeine#79]
When using the cache as a writeThrough/writeBack cache.  The first  cache.put(x,y) will cause the CacheWriter.write() method to be called.  If y.setVariable(z) is called to update the cached object, the only way I can see to force the value to be written through is to call cache.invalidate(x); cache.put(x,y).
Is it possible to force CacheWriter.write to be called even if the object is the same as previously put?

Currently, I've tried leaving the objects in the cache and updated some of their set methods.  At some point I've called cache.invalidateAll() with the intention of flushing the cache.  However, now I'm overriding the CacheWriter.delete (Cause.EXPLICIT) to have two meanings.  One is invalidate(x) with the intention of deleting from underlying store, while invalidateAll() should require saving any changes.
It would be useful to have a flushAll() with a different cause going to the CacheWriter.delete to allow for this situation.

**Comment by ben-manes** [comment]
One problem is that you are mutating the value outside of the cache. That's usually problematic in general because of the shared, mutable state. A put of the same value (x == x) wouldn't trigger the writer because the state didn't really change from the cache's perspective. The CacheWriter is a hook into the atomic operations that otherwise might be done silently (e.g. put or replace). For other operations like compute you have a direct hook into the action.

Trying to optimize for your scenario would be a negative for others because it forms many opinions and exposes a lot of knobs (like flush). That would make sense if this was a framework which you had to integrate into for batching, rate limiting, retrials, etc. But this is a library and you should think of the cache as a data structure which means you're in control and its okay to go around it. If you want to flush the write back queue, well that's in your code so why not call that directly?

You might view that as a little ugly, but if you think of the cache as a fancy Map instead of a framework then its okay. The framework is the abstraction for you build on top of with your other data structures, which encapsulates everything. If CacheWriter doesn't help then ignore it. If its easier to use Map computations instead, do that. The writer is a synchronous hook into a lifecycle activity that you would otherwise not have access to, which means it could be useful for some cases (or not).

I hope that helps and doesn't come out wrong. My sense is that you're trying too hard to work within the cache as the abstraction, rather than a data structure you mold however best suites your needs.

**Comment by oobles** [comment]
Thanks for the fast response! It took me a bit of time to digest what you were saying, but I've been able to do as you suggest.  I'd prefer if the Cache library provided a difference between invalidated (just remove from cache) versus removed/deleted (with intention to delete from underlying store) .  However, I understand why you wouldn't want to.

I've been able to get the desired outcome by using the write back to store on expiration (so mutated state is captured).  Also wrote a custom flush command which removes required elements from the cache and writes mutated state back to underlying store.  In effect as you suggested going past the cache when required.  Other than expired items from cache (which are written to store) all other items explicitly removed from the cache are ignored.

**Comment by ben-manes** [comment]
I'm glad you got it working.

It is a very fair request and a slipper slope. The cache provides the context of manual or eviction based removal, but why it was manually performed is part of your domain. Trying to convey that through the cache leads to a full fledged framework. That could mean a lot more complex, opinionated, and messier API. The worst case is not that something isn't built in, but that I block you from getting your job done because the API is too limiting by not conceiving a use-case. I'd rather limit the scope to let others build richer frameworks, e.g. [imcache](https://github.com/Cetsoft/imcache), than go overboard and make too many mistakes.
