### ISSUE TITLE
Prevent eviction of young objects

### ISSUE THREAD

**Issue by stemill** [ben-manes/caffeine#793]
Is it possible to have a policy whereby objects are not allowed to be evicted from the cache until they have had a minimum amount of time in there (to avoid newly added objects being evicted as underused before they have had a chance to accrue a few hits).

**Comment by ben-manes** [comment]
This is very workload dependent. In the case of databases / search / analytics, those typically scan many rows that would pollute the cache and only want highly frequent data to be retained. In others like buffering execution data for being picked up by a worker listening to a job queue, the workload is strongly recency-biased. This means that there is no best practice assumption here, as shown below.

![image](https://user-images.githubusercontent.com/378614/196255922-5f21fbe2-f180-451a-b8bd-b619a0286a9a.png)

Caffeine tries to resolve this by monitoring the hit rate adaptively determining how long until an item is eligible for eviction (the admission window). In our traces this adjusts quickly and correctly, so that the cache matches the optimal policy configuration. The stress test below shifts from LRU to MRU to LRU and compares against the optimal offline policy.

![image](https://user-images.githubusercontent.com/378614/196256529-0ae3a6ed-57c0-4533-a068-f28db4727cf4.png)

**Comment by stemill** [comment]
Thanks for the reply. I think the instance I was looking at was a real edge case so I think this is probably not a problem for my use case after all.
