### ISSUE TITLE
Strange eviction behavior of bounded cache

### ISSUE THREAD

**Issue by oakad** [ben-manes/caffeine#80]
We are using caffeine 2.2.5 caches, bound both by item count and expiration after access. The caches are loading ~500 new entries per sec, whereupon each entry should be fairly sort lived (order of seconds total lifetime).

Depending on a run (same code, same machine), the cache may behave nicely for a time (eviction rate roughly equals to the load rate, cache stays bounded), but eventually it starts accumulating items beyond its bounds and eviction rate drops rather sharply and stays very low, whereupon number of items in cache grows uncontrollably.

Periodically running "cleanUp()" helps to reduce the item count to a reasonable value, but results in problems elsewhere (probably because cache is locked for too long or some other unclear reason).

Desired behavior: bounded cache should never grow above its bounds; eviction rate should keep up with load rate in aggressively loading caches.

**Comment by ben-manes** [comment]
Can you upgrade to `2.3.0` and ensure that your JVM is 8u60 or above? There are a few issues that may be at play,
 - 2.2.6 fixed the scheduling of the fork join task which may not have been prompt enough after the changes in `2.2.4` which was a bad release. I was racing to resolve issues which you might be exposed to.
 - `2.3.0` adds back pressure to writes so that even in synthetic workloads writes cannot overwhelm the eviction.
 - JDK 8u60 fixed a bug in ForkJoinPool causes it to discard (not run) execution tasks. That can cause severe mayhem.

**Comment by oakad** [comment]
Thank you for a swift reply.

We are running openjdk 1.8.0_71-b15 here, so we should be fine (?) on this account.
I will get v 2.3.0 and try it out.

**Comment by oakad** [comment]
After doing a quick run I can confirm that with 2.3 a problem would not manifest itself, at least for a time being.

Thank you for your help.

**Comment by ben-manes** [comment]
Thanks for the update and sorry for the inconvenience.
