### ISSUE TITLE
Option to keep victims softly or weakly reachable

### ISSUE THREAD

**Issue by Pr0methean** [ben-manes/caffeine#829]
For a memory-constrained image-processing app, I implemented https://github.com/Pr0methean/OcHd-KotlinBuild/blob/main/src/main/kotlin/io/github/pr0methean/ochd/tasks/caching/SemiStrongTaskCache.kt in order that victimCache could hold a weak or soft reference to the value, so that it would still be available for as long as possible when the size limit of primaryCache (which is shared between all instances in the same tile-size category) was exceeded but there was enough memory free elsewhere on the heap. It'd be handy if the same thing could be done without needing to implement a separate class to wrap soft/weak references: a fixed maximum number of strongly-reachable values, and an unlimited number of softly or weakly reachable ones that had been evicted from strong reachability. This would make it possible to make use of the entire heap, even when the size of the strongly-reachable live set varied unpredictably and there was nothing to gain by shrinking the heap.

**Comment by ben-manes** [comment]
While a great example, I think this is best left to as external to this library. A lot of projects have used this cache as part of their own framework, so adding more high-level concepts is perfect. Thanks for sharing, if someone asks we can dig up this issue for a reference.

As you know, "an unlimited number of soft... would make it possible to make use of the entire heap" is a reasonable goal but also does not play well with the GC's assumptions. Unfortunately that is unpredictable and, at least historically, could cause frequent and long stop-the-world pauses. It isn't a wrong approach, just easily misused due to a lack of understanding. Since it is a footgun we try to emphasize size eviction and other layering approaches (e.g. local + remote caches), and leave the orchestration to developers who will better understand those tradeoffs vs simply enabling a builder configuration flag.

**Comment by ben-manes** [comment]
What are you confused by, @Pr0methean?

**Comment by Pr0methean** [comment]
Not so much confused as disappointed, that https://github.com/Pr0methean/OcHd-KotlinBuild/actions/runs/3589013254 probably won't benefit from any Caffeine upgrades in the foreseeable future.

**Comment by ben-manes** [comment]
I'm unsure what benefits you might expect to see? There wouldn't be any performance difference if layering was built-in rather than user implemented. The only change is who is responsible for that bridge code, which unfortunately is more complex for this library to provide because it has to be more general purpose. A little scaffolding code is normal for integrations, and yours looks easy to maintain. I would be concerned if there were features missing that made it hard or impossible to implement this feature.

**Comment by Pr0methean** [comment]
Having it implemented in a library like Caffeine would also increase my confidence that my solution was correct, in much more general cases than I'd be able to cover with unit tests of my own.

**Comment by ben-manes** [comment]
The more general approach has to be consider more advanced expectations. For example if one iterates over the cache is it at a given layer or combined? Does one have different policies between layers, e.g. by expiration, and can those reconfigured at runtime? Is an entry promoted when modified? Are these concepts unavailable to maintain the current API, can they be retrofitted on, or is a new one required due to too many ripple effects?

There have been requests for non-heap layers such as persistent memory, off-heap, file, and distributed. That runs into many other complications, such as atomicity expectations. There are many frameworks that use Caffeine to do this already, such as Coherence and Infinispan. A framework can be opinionated and richer, whereas Caffeine is more of a library like `HashMap` to be a tool to compose with.

I think there is ample room for nice abstractions like what you want, but writing and maintaining them can fall onto the broader community rather than this project. I'd rather restrict the scope to what I can manage and support, and reference / learn from the great work that others decide to contribute.
