### ISSUE TITLE
What about iteration order?

### ISSUE THREAD

**Issue by cowwoc** [ben-manes/caffeine#86]
I can across this library looking for a concurrent `Map` that retains iteration order similar to `LinkedHashMap`. Is this the right place to look? Where else should I look?

**Comment by ben-manes** [comment]
The cache provides ordered snapshots, but that is O(n) to construct. Its primarily for warm restarts (e.g. Cassandra). This means you could get an order determined by the eviction policy, but that's not what you really want.

Implementing FIFO views of a `ConcurrentHashMap` wouldn't be too difficult if you synchronize all writes but leave reads lock-free. Then you could have a linked list cross cutting the map with volatile prev/next fields. A removal would unlink the entry but not update the removed entry's pointers so that a concurrent traversal could iterate through it.

**Comment by cowwoc** [comment]
Are you aware of an existing implementation? I'm trying to fix a bug in my own library. I'm not really interested in implementing this myself (it's out of scope of what I'm trying to do).

**Comment by ben-manes** [comment]
I've seen StackOverflow discussions where answers used `ConcurrentLinkedQueue` using O(n) removals or `ConcurrentSkipListMap` with timestamped keys (seems error prone).

There are caches like Apache Ignite and Infinispan that interleaved a `ConcurrentLinkedDeque` by exposing its nodes so that they could LRU move the entry safely. It looks like Ignite wrote a standalone [FIFO version](https://github.com/apache/ignite/blob/master/modules/core/src/main/java/org/jsr166/ConcurrentLinkedHashMap.java) as a fork for `ConcurrentHashMap`, which seems much more complicated then I'd have thought necessary.

I always found simpler alternatives whenever the need came up, which is probably why there is nothing popular floating around Github. For example if iteration is rare you can lock on writes to insert into a `LinkedHashMap`, provide a synchronized `forEach(BiConsumer<K, V>)` or snapshot, and get lock-free random reads. Probably most use-cases don't need high iteration concurrency so quick workarounds are good enough.

**Comment by cowwoc** [comment]
@ben-manes My use-case is as follows: https://bitbucket.org/cowwoc/guava-jdk8/issues/1/toimmutablemap-does-not-keep-iteration

A user wants me to convert `Stream` entries into an `ImmutableMap` where the iteration order of the resulting map is equal to the insertion order of the input elements. Somewhere down the line, I decided that I wanted this to be thread-safe but thinking about it now: does it really make sense to talk about iteration order in this context of multiple writers? I mean, how could someone guarantee a meaningful insertion order on the input-end without using locks themselves?

Some people on Stackoverflow are even writing that the problem is technically unsolvable: that you must use locks in order to provide insertion iteration order.

Anyway, I think I will end up doing the following:
* If the `Stream` is sequential, retain insertion order without providing thread-safety.
* If the `Stream` is parallel, provide thread-safety without guaranteeing the iteration order.

**Comment by ben-manes** [comment]
I agree insertion order with multiple writers quickly becomes meaningless and depending on it is very error prone. The idea only makes sense to me with a single writer, but not wanting to penalize reads by keeping them lock-free. That could be a priority queue with O(1) lookups. All cases I can think of either have better solutions or simpler workarounds.

Shouldn't it be the stream's responsibility to ensure ordering? The terminal action should receive the entries in order if the source was ordered and the StreamOps were constructed to retain it. I'd expect all you should do is set the collector's characteristics to preserve the original order. It looks like your fix is to remove `UNORDERED` characteristic from the `toImmutableMap` collector.

**Comment by cowwoc** [comment]
Fortunately, I just noticed that https://docs.oracle.com/javase/tutorial/collections/streams/parallelism.html states that:

> The Java runtime performs a concurrent reduction if **all** of the the following are true for a particular pipeline that contains the collect operation:
> 
> * The stream is parallel.
> * The parameter of the collect operation, the collector, has the characteristic Collector.Characteristics.CONCURRENT. To determine the characteristics of a collector, invoke the Collector.characteristics method.
> * Either the stream is unordered, or the collector has the characteristic Collector.Characteristics.UNORDERED. To ensure that the stream is unordered, invoke the BaseStream.unordered operation

Notice: there is no such thing as concurrent ordered collectors. If the collector is CONCURRENT then it must also be UNORDERED. Yay for me :) I guess that solves that problem.
