### ISSUE TITLE
Add @CheckReturnValue to package-info.java (and @CanIgnoreReturnValue as appropriate)

### ISSUE THREAD

**Issue by kluever** [ben-manes/caffeine#863]
Hey Ben,

In our quest to stomp out accidentally ignored return value bugs, I was hoping you'd be able to add ErrorProne's `@CheckReturnValue` to a `package-info.java` (in each package that caffeine owns), as well as `@CanIgnoreReturnValue` to methods that are "ignorable".

Specifically, we noticed that `refresh()` went from being `void` to returning a `Future` --- and that change is going to cause problems with errorprone's `FutureReturnValueIgnored` check.

Does this sound reasonable?

**Comment by kluever** [comment]
Awesome, thanks for handling this! A bit more background: internally, we've made "CRV the default", so previously-safe API changes like `void` to non-`void` are a bit more problematic for us.

Thanks again --- hope all is well.

**Comment by ben-manes** [comment]
How lenient would you like me to be regarding `@CanIgnoreReturnValue`? I see cases like [Cache.getIfPresent(key)](https://github.com/google/guava/blob/ef779cb2fe5306de1aad25e6c2bf69d82cfa711f/guava/src/com/google/common/cache/Cache.java#L104-L105) annotated with remarks to remove in the internal bug `b/27479612`. However, other cases like [Cache.getAllPresent(keys)](https://github.com/google/guava/blob/ef779cb2fe5306de1aad25e6c2bf69d82cfa711f/guava/src/com/google/common/cache/Cache.java#L117) are not annotated so the result must be handled. There isn't a consistent rule, as [LoadingCache.getAll(keys)](https://github.com/google/guava/blob/ef779cb2fe5306de1aad25e6c2bf69d82cfa711f/guava/src/com/google/common/cache/LoadingCache.java#L125-L126) is annotated to be unchecked.

I would guess that you want it to be strict but, due to the enormous code base, deferred some refactorings until later. Do you want Caffeine's apis to be lenient or strict? I think that I'd need some more assistance to make sure that I did not foobar this and cause headaches.

**Comment by ben-manes** [comment]
Released in 3.1.3
