### ISSUE TITLE
Cache nodes won't be update until 220 years later

### ISSUE THREAD

**Issue by karlchan-cn** [ben-manes/caffeine#865]
Hello,
 I got a problem that some cache nodes won't been updated even the refresh & write expire period exceeded.
 After checking the cache configuration and read the Caffeine source code,I finally tackle this problem.
### Conclusion:
I suggest that upgrade the caffeine source code,which is about to offer user a refresh lock expire configuration,not just the default 220 years expiration.
![image](https://user-images.githubusercontent.com/3454327/216532711-384bdcaf-b48f-4f9d-b5ab-e6dc671d7534.png)
![image](https://user-images.githubusercontent.com/3454327/216532718-739019d2-2f0f-4719-818c-b6bfa43aa6b3.png)

### The root causes are 
1. cusomized RejectedExecutionHandler without throw and exception
2. the refreshIfNeeded-action in the BoundedLocalCache.java sets a refresh-lock in 220 years later
3. the reload command rejected by the executor when its workers count reaches max core size and the work queue is full,without throw any exception
4. at last then when complete unlock action won't be executed and no exception will be thrown

Here are the source code explanations
1. cusomized RejectedExecutionHandler 
```
TraceThreadPoolExecutor threadPoolExecutor = new TraceThreadPoolExecutor(config.getLocalCacheThreadPoolSize(),
                config.getLocalCacheThreadPoolSize(), 0, TimeUnit.MILLISECONDS, new ArrayBlockingQueue<>(100),
                new NamedThreadFactory("ad-detail-local-cache"), new RejectedExecutionHandler() {
            @Override
            public void rejectedExecution(Runnable r, ThreadPoolExecutor executor) {
               // no exception throw
                log.info("detail threadPoolExecutor reject!");
            }
        });
```
2. refresh-lock
```
  @SuppressWarnings("FutureReturnValueIgnored")
  void refreshIfNeeded(Node<K, V> node, long now) {
    if (!refreshAfterWrite()) {
      return;
    }
    K key;
    V oldValue;
    long oldWriteTime = node.getWriteTime();
    long refreshWriteTime = (now + ASYNC_EXPIRY);
    if (((now - oldWriteTime) > refreshAfterWriteNanos())
        && ((key = node.getKey()) != null) && ((oldValue = node.getValue()) != null)
        // CAS lock
        && node.casWriteTime(oldWriteTime, refreshWriteTime)) {
```
3. command rejected by executor
![image](https://user-images.githubusercontent.com/3454327/216530379-7d24f1fc-3f32-4a76-ae21-ec6c88777238.png)

4. two missed unlock points (quot from BoundedLocalCache.refreshIfNeeded)
4.1 
![image](https://user-images.githubusercontent.com/3454327/216530686-6ab1bb00-4737-440b-9c65-909e3b9087a8.png)
4.2 
![image](https://user-images.githubusercontent.com/3454327/216531164-52ad4589-6e61-4a96-b845-e144660df207.png)

**Comment by ben-manes** [comment]
As you note, the problem is that your `RejectedExecutionHandler` discards tasks when the pool exhausts its capacity (akin to `ThreadPoolExecutor.DiscardPolicy`). That means that anything submitted to it may simply never run and can cause surprising behavior if the logic that might depend on the execution. In this case the future never completes and whether that is acceptable depends on the api contract.

`Caffeine.executor` warns against this configuration,
>  Beware that configuring a cache with an executor that discards tasks or never runs them may experience non-deterministic behavior.

Ideally you might use a caller-runs policy to avoid any surprises, but if you do want this load shedding then consider overriding `CacheLoader.asyncReload` to return your own `CompletableFuture`. That might use `orTimeout` to allow it to fail similar, mirroring your configurable lock idea, so that it recovers naturally.

I think this executor behavior would be problematic for most libraries so I would only use it where either I wrote all of the related logic or unless the documentation explicitly allowed it. Otherwise you are likely to run into these surprises, as the discard policy was meant as a strawman api example (e.g. as was `LinkedList`) where the authors didn't think it would actually be used in practice.

**Comment by ben-manes** [comment]
I believe v3 is also more forgiving in this situation where refreshing logic was rewritten. It no longer disables expiration for that entry and instead maintains a secondary map. It should therefore expire and discard the in flight future, thereby recovering. This was an invasive change so it was not done in v2. If you upgrade then that might recover satisfactorily.

**Comment by ben-manes** [comment]
I looked into adding unit tests for this case, but I believe it is already covered by `LoadingCacheTest.refresh_expired`. In that variant the entry expires before the reload completes, which results in it being evicted and the refresh discarded. That's an explicit refresh, but an automatic one behaves equivalently. I may look into adding more explicit tests just to avoid any regressions by clarifying the scenarios. So I believe you simply need to upgrade to resolve the issue.

**Comment by karlchan-cn** [comment]
Thanks for your solutions.
As for my case,upgrade to V3x, may add one more uncertanty to an online system.
Here are my soluctions so far
1. throw an exception in RejectedExecutionHandler
2. expand the queue size and core size of the executor

**Comment by karlchan-cn** [comment]
> I believe v3 is also more forgiving in this situation where refreshing logic was rewritten. It no longer disables expiration for that entry and instead maintains a secondary map. It should therefore expire and discard the in flight future, thereby recovering. This was an invasive change so it was not done in v2. If you upgrade then that might recover satisfactorily.
> 
> https://github.com/ben-manes/caffeine/blob/c29a257aad55a15ed5ad6f75c36c1cdc99387b35/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L1286-L1300

In my view,a lock should be used to refresh/update to ensure that,there is only one refresh/update action in one time window.
So,design an re-entrant mechanism for update/refresh in an predictable interval / period,that may act more like KISS principle.

Simple is the best.

**Comment by ben-manes** [comment]
v3 uses a lock flag by reserving the least significant bit of the write timestamp. This way the entry can still expire instead of being disabled, no extra per entry state is needed, and we do not block via a map compute. I don’t recall the details, but iirc v1 or so used the map compute and suffered performance and stability issues. It’s a surprising complex feature due to all of the desired characteristics
