### ISSUE TITLE
AsyncLoadingCache should not propagate future cancellation

### ISSUE THREAD

**Issue by paulferaud** [ben-manes/caffeine#870]
Title I guess.

We are using an `AsyncLoadingCache` in our app, and there are cases where a request fails for reasons unrelated to the cache. This causes the request to cancel any running future it is currently waiting on, which includes futures returned by the `AsyncLoadingCache`.

The issue is that if we have a concurrent request waiting on the same cache value, then that request will be caught in the cancellation blast-radius, as the value it was waiting for will now fail with a `CancellationException`, even though the current request was perfectly fine.

I believe that the safe behavior is that by default, cancellation of a future returned by the cache should not actually cancel the loading of said cache key. It feels like by default, if you've already started loading a key, you might as well let it run to completion for future reads.

For context, we are using different async frameworks, all of which cancel on failure. So it's not like we are explicitly cancelling anything either. Opting out of this behavior for each and every read sounds untenable.

If you really wanted to cancel a cache load, potentially hurting any concurrent operations waiting on said key to load, that should be a cache-level operation, IMO. Potentially, at the `cache.asMap().get(key).cancel(true)` level. But not by the future returned by `get`

**Comment by ben-manes** [comment]
In this case you can use [CompletableFuture#copy()](https://docs.oracle.com/en/java/javase/12/docs/api/java.base/java/util/concurrent/CompletableFuture.html#copy()) on the cached future. This will decouple it so that the copy receives the original's result or can be completed independently, and the original is not modifiable through it.

The cache takes pains in order to always return the same future instance that it was populated with. There are quirks due to how dependent actions behave and instance equality which affects atomic operations like `asMap.remove`. For example if you did want to cancel the upstream operation, by the cache returning a different instance this would not be possible. Unfortunately anything we do is not intuitive, so being more transparent to allow user code to easily adapt to make explicit expectations has been the lesser of bad implement choices.

**Comment by paulferaud** [comment]
Hum... I was not aware of `.copy()`. Yeah, I think that sounds acceptable. Thanks!

I'm still not a huge fan of that being the default, but I think it could be easy enough to accept it as a lesser evil.
