### ISSUE TITLE
Jcache and hibernate: Config file uri

### ISSUE THREAD

**Issue by eiden** [ben-manes/caffeine#88]
It seems that the jcache integration expects that the config file is hardcoded to `application.conf`. Is this intentional? 

The hibernate jcache integration allows for a "config uri" that is used to supply a config file to the jcache implementation:
http://docs.jboss.org/hibernate/orm/5.2/userguide/html_single/Hibernate_User_Guide.html#caching-provider-jcache-cache-manager

This uri is passed in the call to `javax.cache.spi.CachingProvider#getCacheManager`:
https://github.com/hibernate/hibernate-orm/blob/master/hibernate-jcache/src/main/java/org/hibernate/cache/jcache/JCacheRegionFactory.java#L78

**Comment by ben-manes** [comment]
You're right that we don't do anything intelligent with the URI and followed the pattern from the specification's reference implementation. If desired perhaps we could let you specify a different resource base name, but I'm not sure how useful that is.

The configuration library allows you to [specify the configuration source](https://github.com/typesafehub/config#standard-behavior) as a system property to the file, classpath resource, or a URL. That has always worked very well for me in practice and with the trend away from monolithic applications I'd question the need for a multiple root configuration files.

**Comment by eiden** [comment]
Thanks for the system properties tip. I'm not so familiar with the typesafe config library. For now I have just added an `application.conf` to my resources directory.

I agree that the need to have multiple root config files is probably small. I don't have the need for multiple config files myself. 

But it would be convenient if I could use the hibernate config `hibernate.javax.cache.uri` to point to the config file. And that would make caffeine behave the same way as the ehcache-jcache implementation. 

I guess that most users trying to integrate hibernate and caffeine via jcache would be a bit surprised that they cannot configure the cache as described in the hibernate docs..

Thanks for the prompt feedback, looking forward to some more caffeine testing. Feel free to close this issue.

**Comment by ben-manes** [comment]
I'm closing, but will reconsider if reopened.

The most likely case for this feature is if the configuration files were not mergable and there were conflicts. The Typesafe library has a merging model so this isn't a problem.

Another case might be due to templates ("default") configuration. For simple cases this removes redundancy, but in complex applications the default shouldn't include policy information (e.g. max-size). If a library specified the defaults in its `reference.conf` then it might become an issue across all cases. I think the solution to that reuse problem is to allow a definition to specify a template to prototype from. Then libraries could use their own templates and the `default` could be merely the configuration like JMX. If you'd like that enhancement then please create another issue for us to discuss on.

**Comment by ben-manes** [comment]
> I guess that most users trying to integrate hibernate and caffeine via jcache would be a bit surprised that they cannot configure the cache as described in the hibernate docs..

I reviewed the [specification](https://docs.google.com/document/d/1MZQstO9GJo_MUMy5iD5sxCrstunnQ1f85ekCng8LcqM/edit#heading=h.8qbrgipw8go) and other implementations, and users should be surprised because the documentation is misleading. The specification only requires that the URI provides a unique identity within a classloader. In regards to configuration it merely states,

> For example an implementation may permit a URI to be used as the location of a configuration file, say for pre-configured caches.

While this is permitted it does not allow implementations to restrict only use it for that case and reject a URI if the resource is not found. In this way Ehcache 3 may not conform to the specification by adding an additional restriction.

When reviewing other open-source implementations it seems that only Ehcache uses this configuration option. I believe they do this because only one `ehcache.xml` is supposed to exist on the classpath and is not merged, so this approach provides isolation for different modules to define their own caches. Since the Typesafe Config format is more flexible this problem doesn't arise in the same manner.

@sebersole
I think the Hibernate's documentation should be reworded to not imply that others will configure similarly.

**Comment by sebersole** [comment]
Well to be fair, I have reached out to you a number of times for you input on the configurability and just never heard anything back ;)

TBH such a JCache-specific  discussion is beyond my scope of knowledge wrt to JCache.  If there is some specific changes you'd like to see in the Hibernate documentation it would be better to propose some the specific changes you'd like to see.

**Comment by ben-manes** [comment]
Sorry, I didn't mean to sound critical of Hibernate. I had to investigate to confirm that I wasn't violating the specification and its an easy misunderstanding to make. I think it was fine for Ehcache to highlight that ability given that they contributed support, so the fact that others don't is a detail Hibernate shouldn't have been expected to realize.

I don't have much of a complaint against the current documentation because it is correct. Those two properties are used for configuration (with the URI as an optional namespace rarely used). The example of an Ehcache configuration is again valid, as they use the URI to support multiple configuration files. The fact that it confused a user is an unfortunate consequence of the example.

I didn't have much feedback on configurability because it is messy in JCache. The standard's configuration object is very limited and only supports unbounded caches. It was enough to show demos and imply vendor-free configuration, but can't be used that way in practice. I think a unified configuration is the wrong approach and would only add unnecessary complexity for Hibernate. I am quite happy with the current state of Hibernate's support, so my only feedback would have been negative towards the proposal.
