### ISSUE TITLE
Add support for action when cache expires

### ISSUE THREAD

**Issue by DachuanZhao** [ben-manes/caffeine#880]
It would be useful to be able to have a custom action when cache expires.

For my use case I use caffeine cache as a counter . So I want set the value to zero rather than remove the key ( It causes lots of gc ) . 

e.g.
```java
        Cache<Integer, Integer> caffeineCache = Caffeine.newBuilder()
                .initialCapacity(110000000)
                .maximumSize(110000000)
                .expireAfterWrite(30, TimeUnit.MINUTES).
                .expireAction( (key , value) -> (this.put(key,0)) ) // I don't know how to make it 
                .build();
```

**Comment by ben-manes** [comment]
The actions we support are by a removal / eviction listener. That's intended to cover cleaning up resources when the entry was removed. Caffeine also supports `refreshAfterWrite` so that a stale entry can be reloaded, which allows avoids hot items from being evicted and causing a latency spike. An expired entry is considered too old to be usable, will be evicted, and a concurrent read that observes it will mimic a cache miss.

Typically due to the high hit rate of a cache, GC due to eviction is a low penalty. If you haven't already, a good first step is to profile before trying to optimize as most often our intuitions are wrong. JFR is really handy for this.

It looks like using refresh instead of expiration and an immediate reload would mostly solve your problem. A reload is typically asynchronous and either the cache would need to be configured with a direct executor or return a completed future. That could look something like,

```java
Cache<Integer, Integer> caffeineCache = Caffeine.newBuilder()
    .initialCapacity(110000000)
    .maximumSize(110000000)
    .expireAfterWrite(30, TimeUnit.MINUTES).
    .build(new CacheLoader<Integer, Integer>() {
      @Overload public Integer load(Integer key) {
        return 0;
      }
      @Overload public CompletableFuture<Integer> reloadAsync(Integer key, Executor executor) {
        return CompletableFuture.completed(load(key));
      }
    });
```

This has a slight caveat that while being reloaded the old value is returned, so technically there is a tiny race. If that's not acceptable, then a simple workaround is to wrap the value and manage the timestamp yourself. Then your caller can synchronize when being reset to avoid the chance of a stale read.

In regards to adding a new feature, the bar is if that cannot be done easily in user code. In your case it seems that it could be done as a custom refresh mechanism without a large lift. Since we're not trying to have every possible feature, but rather be a ConcurrentMap with bounding rules that is flexible to adapt to solve most problems, this doesn't yet seem like a strong candidate to bring into the core.

**Comment by ben-manes** [comment]
Actually, for the manual case then Guava's `Suppliers.memoizeWithExpiration(supplier, duration, unit)` is a perfect fit.

```java
LoadingCache<Integer, Supplier<Integer>> caffeineCache = Caffeine.newBuilder()
    .initialCapacity(110000000)
    .maximumSize(110000000)
    .build(key -> Suppliers.memoizeWithExpiration(() -> 0, 30, TimeUnit.MINUTES));
var supplier = cache.get(key);
return supplier.get();
```

That sounds like it would do exactly what you want very succinctly.

**Comment by DachuanZhao** [comment]
> 
 '```load``` after ```delete```' means ```caffeineCache``` deletes the key first , then add a new same key and set the value 0 , which costs losts of gc when there are many keys expires. 
In my sitution , hit rate of the cache is very slow .

**Comment by ben-manes** [comment]
The cache is designed to throw data away, where expiration implies it is not usable anymore. Your case is interesting but outside of a traditional cache, so a novel reuse but maybe there is a better approach? For example you have a counter but `Integer` is immutable so an increment is a cache write which is more costly.

 I'd recommend instead of having the cache manage the TTL you remove that feature and have your own class, .e.g `Counter`, which is holds an `AtomicInteger` and has TTL logic. Then on access you can reset it to zero if expired and the cache would only manage by maximum size. This would avoid GC churn and have the semantics you want.
