### ISSUE TITLE
Question: Refreshing on eviction entries

### ISSUE THREAD

**Issue by technical-debt-collector** [ben-manes/caffeine#882]
We're implementing Caffeine to cache the results of a lookup API which is
1. slow - one request might take multiple secs
2. unreliable - it occasionally responds with wrong information, forcing the callers to retry until it eventually responds correctly
3. not maintained by us, but required in our business.

To minimize customer impact, we'd like to optimize for cache hits at the expense of a larger and more persistent cache.
We have a few strategies defined, one of which relies on intercepting eviction events and using this to call the lookup service so that the entry is refreshed. 
This way it sounds like we can refresh the entry without requiring customer interaction, although it's not immediately clear to me if this will end up refreshing the entry the way we hope for (without it ever being removed from the cache) and guaranteeing an existent entry in the cache so long as the lookup source still contains the entry.

What are your thoughts on this? Does this seem like an appropriate use case of the evictionListener feature?

**Comment by ben-manes** [comment]
Most often `refreshAfterWrite` is appropriate, where the entry will be asynchronously reloaded if accessed after this threshold but has not yet expired or otherwise evicted. This keeps hot data fresh in the cache, rather than suffering latency spikes due to periodically expiring. It also allows inactive entries to fade away, making room for more useful content. This approach serves stale but usable data while the reload is in process, which only is triggered by an access to that entry (so not a periodic task). The sync/async reload methods in `CacheLoader` can be overridden, e.g. to use `Failsafe` to leverage retry/fallback policies.

If you are using eviction as a trigger to a reload, but never actually want mappings to be removed, then that doesn't sound like a bounded cache. Instead a `ConcurrentMap` with a `ScheduledExecutorService` would be simple and more obvious, where your periodic task would refresh the contents.

Does any of that help?

**Comment by technical-debt-collector** [comment]
Yep, we were also thinking of using refreshAfterWrite to accomplish this in a fairly easy manner. I suppose it all boils down to reasonable expiry configurations for us in this case.

Keeping complexity down is also a bit of a focus, ideally we wouldn't really want to schedule something to periodically refresh entries we deem as stale. I guess making the cache unbounded is not really favourable either :D 

With this in mind, I think we'll be better off with sticking to refreshAfterWrite in this case. Not treating a cache as bounded also sounds like a bit of a risky play on our end. 
Thanks for the quick and informative response!
