### ISSUE TITLE
Why choose to use '|'?

### ISSUE THREAD

**Issue by chunxinhou** [ben-manes/caffeine#883]
https://github.com/ben-manes/caffeine/blob/df1596be6096178e525ba77be233e840d361bef4/caffeine/src/main/java/com/github/benmanes/caffeine/cache/BoundedLocalCache.java#L993

**Comment by ben-manes** [comment]
It a nitpick optimization as it allows the cpu to schedule the branches to be evaluated in parallel instead of sequentially. Joshua Bloch's old talk, [Performance Anxiety](https://dzone.com/articles/joshua-bloch-performance), recommended it and it is inconsequential so mostly for fun. It would not appear in a profile or benchmark or change behavior if we used a conditional or.
