### ISSUE TITLE
Excessive logging in LocalAsyncCache

### ISSUE THREAD

**Issue by paulferaud** [ben-manes/caffeine#885]
Could we get rid of the log in `LocalAsyncCache`? Specifically, the one that says `"Exception thrown during asynchronous load"`?

The issue is that a future failing could be a perfectly normal part of the workflow, and having caffeine log these is mostly the same as the "catch log rethrow" pattern, which is mostly considered anti-pattern. For context, our use case is polling a system for resources, which 404's when said resource is not there. Which is a normal event in our process, but we don't want to wrap in a `Optional`, as we don't want to cache that the value is missing.

All the other logs are fine, since the exception is caught by caffeine itself, and never propagated.

But that one log is particularly noisy, and is arguably a client issue. If the client doesn't want to consume the future, or wants to catch the exception, there isn't really a reason to log it.

I realize we can filter the log, but that kind of feels like a patch over something that shouldn't really happen to begin with. Other issues include that it has no granularity (it's either on for all caches, or off for all caches). It is also an binary-level option, and it makes it hard for my library code to not spam my client just because I moved from Guava to Caffeine.

**Comment by ben-manes** [comment]
The recommendation is to disable the logger, which is typically a one line configuration change. Alternatively, use a CancellationException or TimeoutException as they are not logged.

The logging was introduced because it was not uncommon for developers to forget to handle errors and have the exception silently swallowed. That led to quiet breaks in their logic, only visible as the entry disappearing from the cache. Async programming is less common and more error prone than the synchronous style, so mistakes are fairly common and frustrating. A log message is a benign hint to assist that is easily disabled.
