### ISSUE TITLE
How to implement soft TTL and hard TTL?

### ISSUE THREAD

**Issue by Bennett-Lynch** [ben-manes/caffeine#886]
Hi,

I'd like to create a time-based cache with a soft TTL and hard TTL with the following requirements:

1. Queries for keys that result in an entry that has elapsed the hard TTL will perform a blocking/synchronous load for a new value.
2. Queries for keys that result in an entry that has elapsed the soft TTL will return the current value and then perform an asynchronous load for a new value.
    1. Successful loads will update the cache.
    2. Failed loads will be logged as a warning.
3. There should be at most one concurrent load attempt per key.

The motivation is two-fold:
1. Improve availability by allowing most transient failures to be absorbed by the asynchronous best-effort loads.
2. Improve latency by reducing the likelihood of performing a synchronous load on the request path.

Does Caffeine support this natively? My search yielded a few similar requests but no concrete solutions.

Optionally, it would also be helpful if the cache supported an option to proactively refresh values that have reached the soft TTL, rather than only on-demand. Presumably this could be somewhat hackily accomplished by manually scheduling a background thread that attempts to repeatedly iterate and read the entire cache.

Thanks for the great library!

**Comment by ben-manes** [comment]
See [refreshAfterWrite](https://github.com/ben-manes/caffeine/wiki/Refresh) for the soft ttl, where a hard ttl is an expiration option. See `CacheLoader.reload` or `asyncReload` if you want to use the old value as part of the calculation.

A proactive reload is best left to your code as you can use a ScheduledExecutorService to traverse and reload as needed. That can be done by using the `Cache.asMap()` view to iterate on, `FixedRefresh` to query the metadata for the entry, and `LoadingCache.refresh(k)` to trigger a reload. See`Cache.policy()` for the policy-specific extensions where we can add more convenience methods as needed.

**Comment by Bennett-Lynch** [comment]
This is great, thank you @ben-manes. I think proactive refresh might be frequent enough of a desired use case that it would be nice if Caffeine at least offered this as an option (especially since it is already using a default `Executor`).

**Comment by ben-manes** [comment]
Proactive refresh means that we might never evict anything, since you are reloading the entire working set. It comes up frequently, but seems error prone where it is unclear if the user has thought through the implications. There is also nothing smarter for the cache to do that cannot be done in user code, were it is a dozen or less lines to implement. At least then the behavior is explicit and customizable, whereas a config option might be easily missed or misunderstood.

We can add more convenience method to the `Policy` to assist, if it could allow for simplifications. We're not trying to offer every possible feature, but solve the hard ones and expose hooks to unblock developers in solving their problems. If you run into annoyances then please open an issue and we can discuss if it can be made better.

**Comment by Bennett-Lynch** [comment]
Understood. In my current use case the key space is predictably small and confined, so I have no concern for cache size and want proactive refresh as a cheap optimization. Thanks again.
