### ISSUE TITLE
Usage of primitive longs as keys

### ISSUE THREAD

**Issue by andrii0lomakin** [ben-manes/caffeine#888]
Hi.
I am considering using Caffeine as a caching solution for the database, which uses primitive values, namely longs, as the keys.
We need to squeeze every performance during access to the cached data.

 So I am curious whether you considered extending Caffeine implementation to use primitive longs as keys. If so, would you accept pool requests?

**Comment by ben-manes** [comment]
For the time being, this wouldn't be a supported feature. When value types land then we'll try to make it compatible.

To this today would require that we fork `ConcurrentHashMap` to support primitives, write primitive interfaces for everything (Cache, Weigher, etc), and rework some internal logic. Right now we use the key field as a state machine for (alive, retired, dead), so that would have to go elsewhere. That is all very invasive, a lot of work, and outdated when / if value types arrive.

One alternative is off-heap caches like Cassandra's [ohc](https://github.com/snazy/ohc). They may be more footprint and friendly to large caches, depending on the use-case.

Another approach is to write a specialized cache that serves the scenarios and apis that you need. For example maybe starting from `NonBlockingHashMapLong`, layering on top atomic computes by striped locking, and then adding the eviction policies. Those don't have to be as fancy as ours, though you are welcome to borrow any code. The easiest would be to use a Clock-based policy, e.g. ClockPro from the simulator, since those policies are designed for concurrent reads at the cost of potentially more expensive evictions. The W-TinyLFU policy is quite good and ring buffer code easy to copy over, just more to maintain yourself.

hope that helps!

**Comment by laa** [comment]
Hi @ben-manes .
It definitely helps.  I am a big fan of the W-TinyLFU policy and have already ported it for OrientDB once. So we will go using the second direction. I am interested in a concurrent hash table optimized for the usage of small keys. If value types are released, I hope we will help you in the adaptation of this change into the main repository. 
I appreciate your quite generous position about borrowing project code.

May I ask you in the context of this issue in the light of the development of ZGC do you still find the usage of off-heap caches useful with modern JVMs?

**Comment by ben-manes** [comment]
Oh that's right, I had forgotten you have W-TinyLFU and related infrastructure at your fingertips already. That's really great.

In general I don't really like off-heap, at least not when it was hyped a decade ago for normal business app usages. Those cases are better served using something like memcached. Often the cost of off-heap was higher, e.g. by using worse locking and serialization schemes.

I think it may still make sense for a database if it only needs a pool of raw memory to serve byte arrays, etc. Typically a GC is not optimized for humongous objects and G1 iterated on that multiple times to cope a bit better. Also, since it traces over the liveset and ZGC is not yet generational, there might be a loss of throughput. If the data layout is well known and does not need to be treated as a Java object but rather a bag of bytes then bypassing it by [JEP-434](https://openjdk.org/jeps/434) may still be preferable. I know some have tried to mix using Caffeine on-heap for cache management and using off-heap values (e.g. pmem / nvm storage).

If you can avoid it then that's really wonderful. I am simply unsure if it is still better in very extreme cases like a database for the best performance and memory usage.

`NonBlockingHashMapLong` (currently maintained by jctools) is probably your best starting point for a primitive concurrent map. It does have it's quirks with tombstones and C style code, but is a well tested and respected implementation.

good luck!
