### ISSUE TITLE
Value handling before expiring action  

### ISSUE THREAD

**Issue by bhdrk** [ben-manes/caffeine#91]
Is there anyway to make a decision regarding to the state of the cached entity before removing it? I imagine somethings like that.

```java
final Cache<String, MyEntity> CACHE = Caffeine.newBuilder()
            .expireAfterAccess(10, TimeUnit.MINUTES, new RemovalStrategy<String, MyEntity>() {
                public boolean beforeRemove(String key, MyEntity value) {
                    /**
                     * if it returns true remove the entity, but false continue to keep it in the cache
                     */
                    return makeDecision(value); 
                }
            })
            .build();
```

**Comment by ben-manes** [comment]
No, but there are workarounds. If improperly designed it could lead to an O(n) scan to evaluate all entries when attempting to evict. Likely a different configuration is more suitable to your problem, so can you explain what you are trying to achieve?

`expireAfterAccess` turns out to be rarely useful in practice. Rather than being about data freshness, it is a time-based LRU to give a maximum lifetime of an inactive entry. This could make sense if using a reference-based cache to more eagerly evict prior to GC, but a maximum size is the preferred strategy.

`expireAfterWrite` handles data freshness and can be combined with `refreshAfterWrite` to retain the active entries. This is commonly useful for local caches which are allowed to be eventually consistent across a cluster.

`maximumSize` takes into account frequency and recency. It will usually outperform a custom policy, e.g. prioritizing certain customer's data over others due to business concerns. In those cases it makes more sense to evaluate ways to reduce the miss penalty, e.g. a memcached tier, to achieve good performance for all users.

`maximumWeight` will exclude zero-weight entries from size-based eviction. This can be useful in cases where an entry should be pinned, e.g. an incomplete `Future` should not be evicted. This can be useful in  some cases, like Hydra's [mediated eviction](https://www.addthis.com/blog/2014/03/20/hydra-internals-efficient-storage-of-nested-hierarchical-data/) for transaction leases (uses a fork of our prior project).

Per-entry expiration is a sometimes useful feature not provided. That's most common implementation is left to user code where expired entries are lazily size-based evicted and emulates a miss when accessed. The other strategy like O(lg n) reordering and a dedicated thread can become too expensive. There is a high possibility that this feature could be implemented efficiently using a hashed wheel timer, but I have not yet experimented with that idea yet.

A hacky workaround to achieve what you want could be to have a `CacheWriter` evict to a temporary map and schedule an asynchronous task to repopulate the cache. To avoid races, a `CacheLoader` could first check this map prior to fetching the data from a remote source. This would recycle the entry.

**Comment by ben-manes** [comment]
Closing. If your case is to resurrect an expired entry by checking if it is still valid first, then I think the best solution is to use `refreshAfterWrite` and implement that intelligence in `reload`.
