### ISSUE TITLE
Caffeine currenthashmap crash

### ISSUE THREAD

**Issue by Lipe17CPS** [ben-manes/caffeine#962]
```java

public class Main {
    private static final ExecutorService EXECUTOR_SERVICE = Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors());

    private static final LoadingCache<String, ExampleClass> CACHE = Caffeine.newBuilder().build(key -> {
        CompletableFuture<ExampleClass> future = new CompletableFuture<>();

        EXECUTOR_SERVICE.execute(() -> {
            try {
                // Select in database
                Thread.sleep(1000);

                // Completed select
                future.complete(new ExampleClass(key));
            } catch (InterruptedException e) {
                e.printStackTrace();
            }
        });

        return future.join();
    });

    public static void main(String[] args) {
        System.out.println("aaa\n");

        ExampleClass exampleClass = CACHE.get("test");
        // Thread is breaking

        System.out.println("bbb\n");
    }

    public static class ExampleClass {
        public ExampleClass(String aa) {
            // Others elements

            // Put in cache
            CACHE.put(aa, this);
        }
    }
}

```

This method is crashing on execute CACHE.get("**")

Caffeine version 3.1.4

**Comment by ben-manes** [comment]
This will deadlock as well if you switch this to using `ConcurrentHashMap` and `computeIfAbsent`, as shown below. This is because you are performing an atomic computation (meaning it holds the entry's lock), blocks on a thread trying to write to that mapping, and that async writer is blocked waiting for the entry's lock. This would succeed for a non-atomic compute, like `ConcurrentSkipListMap`, at the risk of doing the work multiple times and silently throwing away the results on a race.

A simple solution would be to perform the computation outside of the map, e.g. `Map<K, CompletableFuture<V>>`, so that the mapping is established with an in-flight future and the caller waits on that outside of the map's lock. A bounded cache of that map type is `AsyncCache`, which also offers a convenient `synchronous` view. Of course your actual application logic might not mirror your test case.

Please also note that `ConcurrentHashMap` does not allow for writes within a computation, even for distinct keys, and if detected this will throw an exception. Your attempt to workaround that by blocking on another thread doing that write does not satisfy that restriction, only hide it from being detected early and deadlocking. The map will internally use locks that may cover multiple entries, or readjust due to expanding the table, so collisions on distinct keys is possible. As you noticed, this results in a deadlock and is a violation of the api contract.

Hope that helps.

<details>
<summary>Map based cache</summary>

```java
import java.util.Map;
import java.util.concurrent.CompletableFuture;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;


public class Main {
  private static final ExecutorService EXECUTOR_SERVICE =
      Executors.newFixedThreadPool(Runtime.getRuntime().availableProcessors());

  private static final Map<String, ExampleClass> CACHE = new ConcurrentHashMap<>();

  private static Main.ExampleClass load(String key) {
    CompletableFuture<ExampleClass> future = new CompletableFuture<>();

    EXECUTOR_SERVICE.execute(() -> {
      try {
        // Select in database
        Thread.sleep(1000);

        // Completed select
        future.complete(new ExampleClass(key));
      } catch (InterruptedException e) {
        e.printStackTrace();
      }
    });

    return future.join();
  }

  public static void main(String[] args) {
    System.out.println("aaa\n");

    ExampleClass exampleClass = CACHE.computeIfAbsent("test", Main::load);
    // Thread is breaking

    System.out.println("bbb\n");
  }

  public static class ExampleClass {
    public ExampleClass(String aa) {
      // Others elements

      // Put in cache
      CACHE.put(aa, this);
    }
  }
}
```
</details>

**Comment by Lipe17CPS** [comment]
Perfect, I can already fix the error in my code I just created this issue to check if this is not exactly an error, but apparently it is not but thank you very much for your attention
