### ISSUE TITLE
Cache.get(key, mappingFunction) should not be @CheckReturnValue

### ISSUE THREAD

**Issue by syskin345** [ben-manes/caffeine#965]
`Cache.get(key, k->value) ` is essentially `Cache.putIfAbsent(key, value)`. As such, the return value can be safely ignored. Current annotations don't allow such usage.

**Comment by ben-manes** [comment]
It matches Map.computeIfAbsent. You can use the asMap() view for putIfAbsent. We tend to follow guava’s usage of the annotations so you could ask them for clarification and we’ll mirror it if applicable.

**Comment by ben-manes** [comment]
In guava it’s [marked](https://github.com/google/guava/blob/4aaebca4e1f05891ec8e5ff0183cdde9894815f3/guava/src/com/google/common/cache/Cache.java#L104) as ignored, but with a note as enforcing later. I guess it seemed worth following that upfront rather than dealing with restricting later. @kluever, @cpovirk can you give us insights here on the plan?

**Comment by ben-manes** [comment]
I'm going to close this because I think the current behavior is correct and not limiting.

The core `Cache` interface is opinionated and nudges users to what we consider best practices. For example `put` does not return the old value because ideally that state is irrelevant (think cpu/disk cache), or that we strongly prefer atomically loading through the cache versus a racy get-load-put. The `asMap()` view and `Cache.policy()` provide escape hatches as pragmatically many times those details do matter, just less commonly. Your usage of `Cache.get`  could use the asMap() view's `computeIfAbsent` or `putIfAbsent` without a warning and be almost as succinct, so there is little cost in the Cache interface's opinion that most usages should check the return value.
