### ISSUE TITLE
question about "WARNING: Exception thrown during asynchronous load"

### ISSUE THREAD

**Issue by jkvargas** [ben-manes/caffeine#978]
Hey guys,
I am getting some exceptions coming from asyncLoads :)
Is there a way to get more info on those?
I tried to find the info but was not clear to me.
Thanks

**Comment by ben-manes** [comment]
We log all that we know, I think. The exception would hopefully make it clear what the cause was?

https://github.com/ben-manes/caffeine/blob/4f2a68d8151554c2594776adbdc174bcf33526a1/caffeine/src/main/java/com/github/benmanes/caffeine/cache/LocalAsyncCache.java#L209

Some users don't want us to log this, so they disable the logger in their configuration. We try to log what we observe since often unhandled and swallowed, so we try to make your debugging easier. But all we know is the exception thrown which should have the stack trace of all the relevant bits. If you stacktrace is absent then likely the JVM optimized it away due to defaulting to enabling `OmitStackTraceInFastThrow`.

**Comment by Stephan202** [comment]
> If you stacktrace is absent then likely the JVM optimized it away due to defaulting to enabling `OmitStackTraceInFastThrow`.

Besides simply disabling that feature (using `-XX:-OmitStackTraceInFastThrow`), if you suspect that this may be the case, it can help to find the earliest occurrences of the exception in the logs (starting from the moment that the JVM was started); those first occurrences generally do come with a stack trace. :)
