### ISSUE TITLE
Extend the writer API to be able to signal that an entry cannot be evicted from the cache at the moment

### ISSUE THREAD

**Issue by nikolavp** [ben-manes/caffeine#99]
We are currently using caffeine in a non traditional cache scenario. It works out really well for us with the following exception:

We have values which are changed from different threads and they reference count the value to signal that a thread is doing some work on it. We want to prevent the cache from dropping values which have a reference count greater than 0 but there is no way to do that with the current Writer implementation, or is there?

A possible workaround is to give a weight of 0 to those values but there are two problems with that:
* we want to limit the amount of values in the cache which are not currently referenced
* the weight method is only applied when the value enters the cache and the reference counting happens after that most of the time

Can we extend the writer API to have a method which is called *tryDelete* or something which returns a boolean to indicate if the value should be "resurrected"(I saw that there is such flag in BoundLocalCache). It can be a default method which calls delete by default and returns true to indicate that it has deleted the value successfully.

I know that this is a strange usecase but I would rather not fork the project just to add that functionality.

**Comment by ben-manes** [comment]
I know its a rare but valid request. [Hydra](http://www.addthis.com/blog/2014/03/20/hydra-internals-efficient-storage-of-nested-hierarchical-data/#.VIu3-IrF88Y) forked CLHM to add that selectivity to manage transaction leases. Its definitely a complex scenario and I'm not sure if there are any satisfactory solutions.

My concern with that type of API is that it feels fragile. An O(1) eviction could degrade to O(n) and possibly not be able to evict. Or it could "advise" not to evict but fallback to do so anyways (e.g. Ehcache's `EvictionAdvisor`) which could give a false sense of correctness in unit tests.

As you said, using a weight of zero is a possible option. The weight is also calculated on an update, so a reference count could be managed by an `asMap().computeXXX` block with an intelligent weigher. A quirk here is that weighing occurs outside of the atomic operation to avoid unnecessary lock hold times (e.g. a sizeOf weigher). In that case you'd need to be careful to avoid a race condition of the reference count changing from concurrent calls, causing the entry to be incorrectly weighed.

A perhaps cleaner option is to use a victim cache. If the entry was removed prematurely then it could be put into a secondary, unbounded map. The cache loader could query this map to resurrect the entry, and fallback to computing it otherwise. I suspect that would be the simpler and more obvious code than trying to manipulate the weight, and avoids the addition of a fragile API.

**Comment by nikolavp** [comment]
A secondary victim cache worked. What bothers me a little is that it is unbounded and the system can run out of memory. Thankfully the special case isn't hit that often so it should be OK.

Probably this is for closing.

NB: I learned a lot by just opening and looking into closing issues, this no how should probably be ported to the wiki some how ;)

**Comment by ben-manes** [comment]
Oh, and you could also reinsert asynchronously when improperly evicted. Then the victim is almost always empty and you retain a stricter bound.
